In [1]:
%load_ext autoreload
%autoreload 2

# core

> Fill in a module description here

In [2]:
#| default_exp core

In [3]:
#| hide
from nbdev.showdoc import *

In [4]:
#| export
import pandas as pd
from tqdm import tqdm
import re
import numpy as np
import os
from collections import  defaultdict
import re
from random import choice
from itertools import groupby, chain
from operator import itemgetter
from randseq.utils import revcomp, calculate_log2fc, get_lib_seq_context, get_patterns, find_broad_in_specific, _get_filter_for_motif
from typing import List, Tuple, Set, Callable

In [5]:
#| hide
from randseq.example_data import get_example_data_dir

In [6]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['counts_long.csv',
 '__pycache__',
 '__init__.py',
 'countsTable.csv',
 'counts_long_clean.csv']

### 1. Computing the log2fc of the sequences from counts data

In [7]:
counts_file="countsTable.csv"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df

,K12_T0,HS_T0,E1114_T0,E1167_T0,H120_T0,TA054_T0,TA447_T0,E101_T0,41-1Ti9_T0,TA280_T0,M114_T0,TA249_T0,ROAR8_T0,JJ1886_T0,CFT073_T0,APECO1_T0,UTI89_T0,S88_T0,MG1655_T0
CGGAGGTACTGGGTACATTT,0.043818,0.049551,0.187868,-0.302314,0.238304,0.051836,0.186450,0.093344,0.029484,0.106924,-0.329062,-0.102645,0.144280,0.084854,0.212674,0.229591,-0.457070,0.213624,0.090458
TGGCGATAATGCCGGCTATC,0.045463,0.137127,0.437387,0.113014,0.137767,0.060845,0.063668,-0.014449,-0.008977,-0.025606,0.003605,0.084441,-0.167417,0.018354,0.041919,0.016410,-0.207488,0.092292,0.101627
TTCCAGTTCACTGGTCTTCG,-0.049694,0.049903,-0.105148,-0.061620,-0.081886,-0.072083,0.402207,0.087885,0.207649,0.127306,0.204781,-0.106153,-0.012804,0.285761,-0.167107,0.269887,0.182096,0.458076,0.128330
AATTTCAGTGCCGTTCAGAT,-0.251957,-0.422224,-0.224591,-0.058728,-0.204575,-0.192908,-0.220676,-0.143054,-0.277042,-0.205084,0.058866,-0.064442,-0.029019,-0.042375,-0.095307,-0.254714,0.460256,-0.183890,-0.180938
CTGCGGTAATAATTCCCGCC,-0.178427,-0.154025,0.581087,0.401967,0.047002,-0.309751,-0.200689,-0.292042,-0.473919,-0.298991,-0.221896,-0.060500,0.085888,-0.279165,-0.206676,-0.097563,-0.347949,-0.188758,-0.186226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GCTTGATGTAGCCTTCGAAC,-0.100518,-0.079966,0.027302,-0.268222,-0.337706,-0.047079,-0.072379,-0.246364,-0.250380,-0.142468,-0.091826,-0.004635,0.260965,-0.174715,0.278843,-0.206298,-0.319604,-0.055837,-0.133185
TAATGGCAAATTGACACTCC,0.258205,0.103683,0.428049,-0.106268,0.247864,0.050536,0.240706,0.133009,0.195027,0.096144,0.482377,-0.168566,-0.008969,0.224936,0.009979,0.217354,0.453491,0.201961,0.387054
GCTGCGCGCGGAGTTGTTCC,-0.629856,-0.381054,-0.431536,-0.328063,-0.461695,-0.258496,-0.442414,-0.358037,-0.372732,-0.359784,-0.581490,0.174623,-0.984388,-0.273490,-0.490203,-0.122278,-0.562652,-0.497605,-0.959646
GCAACACGCCAGTAAGGTGT,0.693416,0.487153,0.744586,-0.054785,0.474863,0.585146,0.162493,0.388078,0.733043,0.280496,0.167936,0.605561,0.400524,0.051808,0.422091,0.098976,0.294288,0.064457,0.376418
GATAGCCGGATAGCTTAAGG,-0.245685,-0.131631,-0.429244,-0.213968,-0.271218,-0.171113,-0.015624,-0.355447,-0.236553,-0.093049,-0.299090,-0.282985,-0.134136,-0.079377,-0.211507,-0.151722,-0.154721,-0.400835,0.140210

### Listing all the sequence motifs found in our library that follow a specific pattern 

The pattern is a list of 3 numbers:
1. The number of defined bases in the first part of the site  
2. The number of undefined bases in the middle  
3. The number of defined bases in the second part of the site

In [8]:
#| export
# Helper function to create regex group strings for the main function
def _make_regex_group_str(length: int, content_char_class: str = "[ATGC]") -> str:
    """
    Creates a regex capturing group string.
    If length is 0, creates an empty capturing group "()".
    Otherwise, creates a group like "([ATGC]{length})".
    """
    if length > 0:
        return f"({content_char_class}{{{length}}})"
    else: # length == 0
        return "()" # Captures an empty string

def get_sites_in_seq(
    sequence_library: List[str],
    pattern: Tuple[int, int, int] = (3, 6, 4),
    no_ori: bool = True,
    custom_revcomp: Callable[[str], str] = revcomp
) -> List[Set[str]]:
    """
    Computes the list of unique sites matching a defined pattern within each sequence
    of a given library.

    The pattern specifies a motif structure: (defined_bases_part1, spacer_length, defined_bases_part2).
    For example, a pattern (3, 6, 4) looks for sites like XXXNNNNNNXXXX, where X
    represents a defined base (A, T, G, C) and N represents an undefined base in the motif.

    Args:
        sequence_library: A list of DNA sequence strings. All sequences are expected
                          to be of the same length.
        pattern: A tuple of three non-negative integers:
            1. The number of defined bases in the first part of the site.
            2. The length of the spacer (undefined bases) in the middle.
            3. The number of defined bases in the second part of the site.
        no_ori: If True (default), the search for sites is performed on both the
                provided sequence and its reverse complement. If False, only the
                provided sequence strand is searched.
        custom_revcomp: A function to compute the reverse complement. Defaults to
                        a basic internal `revcomp` function.

    Returns:
        A list of sets. Each set contains unique site strings found in the
        corresponding input sequence. Sites are represented with 'N' for the
        spacer region (e.g., "ATCNNNNGGC").

    Raises:
        ValueError: If the sequence library is empty.
        ValueError: If sequences in the library are not all of the same length.
        ValueError: If the pattern is not a tuple of three non-negative integers.
        ValueError: If the total length of the site defined by the pattern is zero.
        ValueError: If the total length of the site pattern exceeds the length of the
                    sequences in the library.
    """
    # --- Input Validation ---
    if not sequence_library:
        raise ValueError("Sequence library cannot be empty.")

    try:
        first_seq_len = len(sequence_library[0])
    except IndexError: # Should be caught by the above, but for safety
        raise ValueError("Sequence library cannot be empty.")

    if not (
        isinstance(pattern, tuple) and
        len(pattern) == 3 and
        all(isinstance(p_num, int) and p_num >= 0 for p_num in pattern)
    ):
        raise ValueError(
            "Pattern must be a tuple of three non-negative integers: "
            "(defined_bases_part1, spacer_length, defined_bases_part2)."
        )

    defined_len1, spacer_len, defined_len2 = pattern
    pattern_total_length = defined_len1 + spacer_len + defined_len2

    if pattern_total_length == 0:
        # Finding motifs of total length 0 (e.g., pattern (0,0,0)) is problematic
        # as it would match everywhere. It's better to disallow it.
        raise ValueError("The total length of the site pattern (sum of its parts) cannot be zero.")

    shorter_seq = min([len(s) for s in sequence_library])
    if pattern_total_length > shorter_seq:
        raise ValueError(
            f"Site pattern's total length ({pattern_total_length}) is longer than "
            f"the shorter sequence length ({shorter_seq})."
        )

    # --- Regex Preparation ---
    # Uses the helper _make_regex_group_str to create "()" for zero-length parts.
    # This ensures three capturing groups are always present for consistent unpacking later.
    group1_str = _make_regex_group_str(defined_len1)
    # The spacer part in the original regex also used [ATGC] for the characters
    # it matched in the sequence, even though these are replaced by 'N's in the motif.
    group2_str = _make_regex_group_str(spacer_len) 
    group3_str = _make_regex_group_str(defined_len2)
    
    # The lookahead `(?=...)` is crucial for finding all overlapping sites.
    regex_pattern_str = f"(?={group1_str}{group2_str}{group3_str})"
    
    # Using re.IGNORECASE for robustness, assuming 'atgc' is equivalent to 'ATGC'.
    compiled_regex = re.compile(regex_pattern_str, re.IGNORECASE)

    # --- Site Finding ---
    all_sequence_results: List[Set[str]] = []
    
    for seq_original_case in sequence_library:
        current_sequence_sites: Set[str] = set()
        
        # Standardize sequence to uppercase for consistent processing and regex matching
        processed_seq = seq_original_case.upper()

        sequences_to_scan = [processed_seq]
        if no_ori:
            # Ensure the revcomp function also standardizes or expects uppercase
            reverse_complement_seq = custom_revcomp(processed_seq)
            sequences_to_scan.append(reverse_complement_seq)

        for target_sequence in sequences_to_scan:
            # Find all matches in the current target sequence (forward or reverse complement)
            # matches will be a list of 3-tuples due to the three capturing groups.
            matches = compiled_regex.findall(target_sequence)
            for part1, actual_spacer_bases, part2 in matches: # Unpack the 3 captured groups
                # Construct the site motif string using 'N's for the spacer region.
                # The `actual_spacer_bases` captured by the regex are intentionally
                # ignored here for the motif string, which uses a generic 'N' spacer.
                # If spacer_len is 0, 'N' * 0 is an empty string.
                site_motif = f"{part1}{'N' * spacer_len}{part2}"
                current_sequence_sites.add(site_motif)
        
        all_sequence_results.append(current_sequence_sites)

    return all_sequence_results

In [9]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib=get_lib_seq_context(log2fc_df.index,left,right)
sites_in_seq=get_sites_in_seq(lib,pattern=(3,6,4),no_ori=True)
assert len(sites_in_seq) == len(lib)
print(f"First 5 pattern matching sequences found in the first sequence of the library:")
list(sites_in_seq[0])[:5]

First 5 pattern matching sequences found in the first sequence of the library:

['CGGNNNNNNTGGG',
 'AGCNNNNNNTAGC',
 'TTGNNNNNNAGCT',
 'TTTNNNNNNAGAA',
 'ATANNNNNNGTCG']

In [10]:
#| export
def score(FCs, thr=-1):
    """
    Returns the fraction of sequences depleted below the thr value.
    Handles empty lists of FCs by returning 0.
    """
    if len(FCs)==0:  # Check if the list is empty
        return 0.0
    return sum([x < thr for x in FCs]) / len(FCs)

In [11]:
assert score([-2,-0.5,-0.1,-5],thr=-1) == 0.5

In [12]:
#| export
def identify_depleted_motifs_scanning_ends(log2fc_series, 
                                           scan_depth_k=7, 
                                           max_motif_length=6, 
                                           depletion_threshold=-1, 
                                           score_thr=0.85, 
                                           min_sequence_support=5):
    """
    Identifies DNA motifs associated with sequence depletion by scanning k positions
    from both the left and right ends of sequences, using a pandas Series of log2FC values.

    Args:
        log2fc_series (pd.Series): pandas Series with sequences (DNA strings) as index
                                   and log2FC values as data.
        scan_depth_k (int): The number of positions to scan from each end (0 to k inclusive).
        max_motif_length (int): The maximum length of the motif to consider.
        depletion_threshold (float): The log2FC threshold for considering a sequence depleted.
        min_sequence_support (int): The minimum number of sequences (strictly greater than this value)
                                    a motif must be found in to be included in the results.

    Returns:
        pd.DataFrame: A DataFrame with identified motifs, their length, actual 0-indexed position,
                      number of occurrences, average log2FC, and depletion score (fraction_depleted).
                      Sorted by primary depletion metrics.
    """
    if not isinstance(log2fc_series, pd.Series):
        print(f"Error: Input must be a pandas Series.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    if log2fc_series.empty:
        print(f"Error: Input Series is empty.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    current_log2fc_series = pd.to_numeric(log2fc_series.copy(), errors='coerce')
    series_name = current_log2fc_series.name if current_log2fc_series.name else "input Series"
    print(f"Analyzing motifs of length 1 to {max_motif_length}, scanning positions 0 to {scan_depth_k} from each end, for {series_name}.")
    print(f"Minimum sequence support for a motif: > {min_sequence_support} (i.e., {min_sequence_support +1} or more)")


    motif_stats_accumulator = {}

    # Iterate over (sequence_string, log2fc_value) pairs
    for seq_str, log2fc_val in current_log2fc_series.items(): 
        if pd.isna(log2fc_val) or not isinstance(seq_str, str):
            continue

        processed_positions_for_this_seq = set() 
        for motif_len in range(1, max_motif_length + 1):
            if len(seq_str) < motif_len:
                continue

            # Left scans
            for j_offset in range(scan_depth_k + 1):
                actual_pos_left = j_offset
                if actual_pos_left + motif_len <= len(seq_str):
                    if (actual_pos_left, motif_len) not in processed_positions_for_this_seq:
                        motif = seq_str[actual_pos_left : actual_pos_left + motif_len]
                        key = (motif, actual_pos_left, motif_len) 
                        if key not in motif_stats_accumulator:
                            motif_stats_accumulator[key] = []
                        motif_stats_accumulator[key].append(log2fc_val)
                        processed_positions_for_this_seq.add((actual_pos_left, motif_len))

            # Right scans
            for j_offset in range(scan_depth_k + 1):
                actual_pos_right = len(seq_str) - motif_len - j_offset
                if actual_pos_right >= 0 and actual_pos_right + motif_len <= len(seq_str):
                    if (actual_pos_right, motif_len) not in processed_positions_for_this_seq:
                        motif = seq_str[actual_pos_right : actual_pos_right + motif_len]
                        key = (motif, actual_pos_right, motif_len) 
                        if key not in motif_stats_accumulator:
                            motif_stats_accumulator[key] = []
                        motif_stats_accumulator[key].append(log2fc_val)
                        processed_positions_for_this_seq.add((actual_pos_right, motif_len))
    
    if not motif_stats_accumulator:
        print("No motifs found or no valid data to process based on scan parameters.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    # Use a list comprehension for conciseness
    results = [
        {
            'motif': key[0],             # motif_str
            'length': key[2],            # motif_len
            'position': key[1],          # actual_pos
            'num_sequences': len(fc_values_list), 
            'avg_log2fc': np.mean(fc_values_list),
            'fraction_depleted': score(fc_values_list, depletion_threshold)
        }
        for key, fc_values_list in motif_stats_accumulator.items()
        if len(fc_values_list) > min_sequence_support # Apply min_sequence_support filter
    ]
    
    if not results:
        print(f"No motifs found meeting the minimum sequence support of > {min_sequence_support}.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values(
        by=['fraction_depleted', 'avg_log2fc', 'num_sequences'],
        ascending=[False, True, False]
    )
    results_df = results_df.loc[results_df['fraction_depleted'] > score_thr]
    return results_df

In [13]:
depleted_motifs_df=identify_depleted_motifs_scanning_ends(log2fc_df["JJ1886_T0"])
depleted_motifs_df.head(10)

Analyzing motifs of length 1 to 6, scanning positions 0 to 7 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)

        motif  length  position  num_sequences  avg_log2fc  fraction_depleted
9827    AAAAG       5        11             10   -5.662158                1.0
24677  GTGCGG       6         0              6   -5.490821                1.0
14175   AAAGT       5        12             13   -5.262390                1.0
14176   CAAAG       5        11             16   -5.201596                1.0
19651   GTGCG       5         0             10   -5.107176                1.0
2921     AAAG       4        12             42   -5.076919                1.0
2931    AAAGC       5        12              9   -5.029139                1.0
19268   AAAGA       5        12             13   -4.996286                1.0
11517   GTGTC       5         0              6   -4.959089                1.0
26164   AAAGG       5        12              7   -4.943650                1.0

In [14]:
#| export
def filter_to_core_motifs(depleted_motifs_df, 
                          score_improvement_margin=0.05):
    """
    Filters a DataFrame of depleted motifs to identify underlying "core" motifs.
    A longer motif is kept only if it's significantly better than a shorter core motif it contains.

    Args:
        depleted_motifs_df (pd.DataFrame): DataFrame from identify_depleted_motifs_scanning_ends.
        score_improvement_margin (float): A longer motif's 'fraction_depleted' must be
                                          greater than the core motif's score by this margin.
        fc_improvement_margin (float): A longer motif's 'avg_log2fc' must be lower
                                       than the core motif's avg_log2fc by this margin.

    Returns:
        pd.DataFrame: A filtered DataFrame containing potentially core motifs.
    """
    if depleted_motifs_df.empty:
        return pd.DataFrame(columns=depleted_motifs_df.columns)

    sorted_df = depleted_motifs_df.sort_values(
        by=['length','fraction_depleted'],
        ascending=[True, False]
    ).reset_index(drop=True)

    core_motifs_list = []
    
    for idx, candidate_row in sorted_df.iterrows():
        candidate_motif = candidate_row['motif']
        candidate_pos = candidate_row['position']
        candidate_len = candidate_row['length']
        candidate_score = candidate_row['fraction_depleted']
        
        is_subsumed = False
        for core_dict in core_motifs_list: 
            core_motif = core_dict['motif']
            core_pos = core_dict['position']
            core_len = core_dict['length']
            core_score = core_dict['fraction_depleted']
            
            if core_len < candidate_len and core_motif in candidate_motif:    
                relative_start = candidate_motif.find(core_motif)
                if candidate_pos + relative_start == core_pos:
                    significantly_better_score = candidate_score >= core_score - score_improvement_margin
                        
                    if significantly_better_score:
                        is_subsumed = True
                        break 
        
        if not is_subsumed:
            core_motifs_list.append(candidate_row.to_dict())
            
    if not core_motifs_list:
         return pd.DataFrame(columns=depleted_motifs_df.columns)
    return pd.DataFrame(core_motifs_list)

In [15]:
depleted_motifs_df=filter_to_core_motifs(depleted_motifs_df)
depleted_motifs_df.head(10)

  motif  length  position  num_sequences  avg_log2fc  fraction_depleted
0   GTG       3         0            187   -4.764500                1.0
1  AAAG       4        12             42   -5.076919                1.0

In [16]:
def get_fold_change_values_per_site_old(site_sets_list, fold_changes_list):
    """
    Computes a dictionary mapping each unique site to a list of its associated
    log2 Fold Change (FC) values.

    Args:
        site_sets_list (list): A list of sets, where each set contains the sequence motifs found in a member of the library.
        fold_changes_list (list): A list of log2FC values, corresponding to each
                                  sequence in the library.

    Returns:
        dict: A dictionary where keys are sequence motifs and values are numpy arrays
              containing the log2FC values associated with that site.
    """

    # Step 1: Create a flat list of (site, FC_value) pairs
    # Each site within a set is associated with that set's FC value.
    site_fc_pairs_nested = [
     [(site, fc_value) for site in site_set]
     for site_set, fc_value in zip(site_sets_list, fold_changes_list)
     ]
    site_fc_pairs = list(chain.from_iterable(site_fc_pairs_nested)) # Standard way to flatten

    # Step 2: Sort the pairs by site to prepare for grouping
    # Sorting is essential for groupby to work correctly.
    site_fc_pairs.sort(key=itemgetter(0)) # Sorts by the first element (site)

    # Step 3: Group by site and collect FC values
    site_to_fcs_map = {}
    for site, group in groupby(site_fc_pairs, key=itemgetter(0)):
        # group is an iterator of (site, fc_value) tuples for the current site
        # Extract the FC value (the second element) from each pair in the group
        fcs_for_site = np.array([fc_value for current_site, fc_value in group])
        site_to_fcs_map[site] = fcs_for_site

    return site_to_fcs_map

In [17]:
pattern=(3,6,4)
set_list=get_sites_in_seq(lib,pattern=pattern,no_ori=True)
site_FCs=get_fold_change_values_per_site_old(set_list,log2fc_df["JJ1886_T0"].values)
site_FCs["AGCNNNNNNGGGA"]

array([ 0.02025893, -0.15083807,  0.19052559,  0.04266223,  0.22493562,
       -0.13188093,  0.0203179 ,  0.10373391, -0.18265707,  0.24137364,
       -0.10160173,  0.5539999 ,  0.19568499,  0.29179059, -0.02109236,
       -0.46896125,  0.00812423])

In [18]:
#| export
def get_fold_change_values_per_site(site_sets_list, fold_changes_list):
    """
    Computes a dictionary mapping each unique site to a list of its associated
    log2 Fold Change (FC) values using collections.defaultdict for optimization.

    Args:
        site_sets_list (list): A list of sets, where each set contains the 
                               sequence motifs found in a member of the library.
        fold_changes_list (list): A list of log2FC values, corresponding to each
                                  sequence in the library.

    Returns:
        dict: A dictionary where keys are sequence motifs and values are numpy arrays
              containing the log2FC values associated with that site.
    """
    # Step 1: Initialize a defaultdict to store lists of FC values for each site.
    # defaultdict(list) will automatically create a new list for a site
    # the first time it's encountered.
    site_to_fcs_map_intermediate = defaultdict(list)

    # Step 2: Iterate through the site sets and their corresponding fold changes.
    # zip() pairs each site_set with its fc_value.
    for site_set, fc_value in zip(site_sets_list, fold_changes_list):
        # For each site in the current set, append the fc_value
        # to the list associated with that site in the dictionary.
        for site in site_set:
            site_to_fcs_map_intermediate[site].append(fc_value)

    # Step 3: Convert the lists of FC values to NumPy arrays.
    # This is done after all values are collected to efficiently create the arrays.
    site_to_fcs_map_final = {
        site: np.array(fcs_list)
        for site, fcs_list in site_to_fcs_map_intermediate.items()
    }

    return site_to_fcs_map_final

In [19]:
pattern=(3,6,4)
set_list=get_sites_in_seq(lib,pattern=pattern,no_ori=True)
site_FCs=get_fold_change_values_per_site(set_list,log2fc_df["JJ1886_T0"].values)
site_FCs["AGCNNNNNNGGGA"]

array([ 0.02025893, -0.15083807,  0.19052559,  0.04266223,  0.22493562,
       -0.13188093,  0.0203179 ,  0.10373391, -0.18265707,  0.24137364,
       -0.10160173,  0.5539999 ,  0.19568499,  0.29179059, -0.02109236,
       -0.46896125,  0.00812423])

In [20]:
#| export
def filter_sequences_without_core_motifs(log2fc_series, core_motifs_df):
    """
    Filters an original log2fc Series to remove sequences that contain 
    any of the specified core motifs.

    Args:
        log2fc_series (pd.Series): Series with sequences as its index and log2FC values.
        core_motifs_df (pd.DataFrame): DataFrame of core motifs, must include
                                       'motif', 'position', and 'length' columns.

    Returns:
        pd.Series: A new Series containing only sequences (and their log2FC values)
                   from log2fc_series that do not carry any of the core motifs.
    """
    if not isinstance(log2fc_series, pd.Series) or log2fc_series.empty:
        # print("Info: log2fc_series is empty or not a Series. Returning a copy.")
        return log2fc_series.copy() 
    
    expected_core_motif_cols = ['motif', 'position', 'length']
    if not isinstance(core_motifs_df, pd.DataFrame) or core_motifs_df.empty or \
       not all(col in core_motifs_df.columns for col in expected_core_motif_cols):
        print("Info: core_motifs_df is empty or invalid for filtering. Returning original log2fc_series.")
        return log2fc_series.copy()

    # Create a boolean mask, True for sequences to keep
    sequences_to_keep_mask = pd.Series(True, index=log2fc_series.index)

    # Iterate through each unique sequence string in the original Series' index
    # Using .loc for assignment to the mask handles duplicate indices in the original Series correctly
    for seq_str_to_check in log2fc_series.index.unique(): 
        if not isinstance(seq_str_to_check, str): 
            continue # Skip if index label is not a string
        
        # Check this sequence against all core motifs
        for _, motif_row in core_motifs_df.iterrows():
            motif_str = motif_row['motif']
            try:
                position = int(motif_row['position'])
                motif_len = int(motif_row['length'])
            except (ValueError, TypeError):
                # print(f"Warning: Invalid position/length for motif {motif_str} in core_motifs_df. Skipping this motif.")
                continue 

            if not isinstance(motif_str, str) or not motif_str: 
                continue

            if len(seq_str_to_check) >= position + motif_len:
                if seq_str_to_check[position : position + motif_len] == motif_str:
                    # If a motif is found, mark all occurrences of this sequence string for removal
                    sequences_to_keep_mask.loc[log2fc_series.index == seq_str_to_check] = False 
                    break # Move to the next unique sequence_str_to_check

    return log2fc_series[sequences_to_keep_mask]

In [21]:
filted_log2fc_df = filter_sequences_without_core_motifs(log2fc_df, depleted_motifs_df)

In [22]:
#| export
def get_sites_scores(site_FCs, pattern, log2FC_thr=-1):
    """ 
    Scores sites based on depletion and occurrence.
    Returns a pandas DataFrame with 'site', 'fraction_depleted', 'num_sequences', 'avg_log2fc'.
    """
    site_scores_list = []
    
    for site_key, fc_values in site_FCs.items():
        if not isinstance(fc_values, (list, np.ndarray)) or len(fc_values) == 0:
            continue # Skip if fc_values is not a list/array or is empty
            
        current_score = score(fc_values, log2FC_thr)
        num_occurrences = len(fc_values)
        avg_fc = np.mean(fc_values) if num_occurrences > 0 else np.nan
        
        site_scores_list.append({
            'motif': site_key,
            'fraction_depleted': current_score,
            'num_sequences': num_occurrences,
            'avg_log2fc': avg_fc
        })
            
    if not site_scores_list:
        return pd.DataFrame(columns=['motif', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
    return pd.DataFrame(site_scores_list)

In [23]:
site_scores = get_sites_scores(site_FCs,pattern)
site_scores.sort_values(by=['fraction_depleted', 'num_sequences'], ascending=[False, False]).head(10)

               motif  fraction_depleted  num_sequences  avg_log2fc
16368  AGGNNNNNNCCTC           1.000000              1   -4.601867
16373  GAGNNNNNNCCCC           1.000000              1   -1.406262
3410   CACNNNNNNATTA           0.958974            195   -4.569183
3411   AATNNNNNNGTGC           0.826923             52   -3.962960
9121   AATNNNNNNGTGG           0.815385             65   -3.883041
3152   TAANNNNNNTGTG           0.785714            238   -3.746732
1091   AATNNNNNNGTGA           0.771429             70   -3.628320
15086  GAGNNNNNNGTCT           0.750000              4   -4.012801
9576   AATNNNNNNGTGT           0.740741             54   -3.485249
16126  GGTNNNNNNAGGA           0.666667              3   -2.235343

In [24]:
#| export
def filter_redundant_patterns(df, score_margin=0.05):
    """
    Filters a DataFrame of  patterns, removing redundant motifs based on
    specificity and a score condition.

    A motif 'p1' is considered redundant and removed if there is another
    motif 'p2' in the DataFrame such that:
    1. p1 is a specific version of p2 
    2. The score condition is met: p2.score > p1.score - score_margin.
    3. For equivalent motifs, the one with the lower score is dropped. If
       scores are equal, the one with the higher original index is dropped.

    Args:
        df (pd.DataFrame): DataFrame with 'motif' and 'score' columns.
        score_margin (float): A margin to relax the score comparison.

    Returns:
        pd.DataFrame: A filtered DataFrame with redundant rows removed.
    """
    indices_to_drop = set()
    # Use a reset index to simplify looping, but keep original for final drop
    df_reset = df.reset_index()

    for i, p1 in df_reset.iterrows():
        if i in indices_to_drop:
            continue
            
        for j, p2 in df_reset.iterrows():
            if i == j:
                continue

            motif1, score1 = p1['motif'], p1['fraction_depleted']
            motif2, score2 = p2['motif'], p2['fraction_depleted']

            is_subset = find_broad_in_specific(motif1, motif2)

            if not is_subset:
                continue

            # motif1 is a subset of motif2. Now check if it should be dropped.
            is_superset = find_broad_in_specific(motif2, motif1)

            if not is_superset:
                # motif1 is a STRICT subset of motif2.
                # Drop motif1 if the score condition is met.
                if score2 > score1 - score_margin:
                    indices_to_drop.add(i)
                    break 
            else:
                # They are equivalent. Tie-break:
                # 1. Drop the one with the lower score.
                # 2. If scores are equal, drop the one with the higher index.
                if score1 < score2:
                    indices_to_drop.add(i)
                    break
                elif score1 == score2 and i > j:
                    indices_to_drop.add(i)
                    break
    
    # Get original indices of rows to drop
    original_indices_to_drop = df_reset.loc[list(indices_to_drop)]['index']
    return df.drop(original_indices_to_drop)

In [25]:
#| export
def update_motif_scores_from_unique_hits(
    flexible_motifs_df,
    log2fc_series,
    left_context,
    right_context,
    flexible_motif_log2fc_thr=-1,
    flexible_motif_min_support=3,
    flexible_motif_score_thr=0.85
):
    """
    Updates a DataFrame of motifs with new scores based on unique sequence hits
    and filters the result based on the provided thresholds.

    Args:
        flexible_motifs_df (pd.DataFrame): DataFrame with a 'motif' column.
        log2fc_series (pd.Series): Series with DNA sequences as index and values.
        left_context (str): DNA string to prepend for matching.
        right_context (str): DNA string to append for matching.
        flexible_motif_log2fc_thr (float): The log2fc threshold for the score function.
        flexible_motif_min_support (int): The minimum number of unique sequences required.
        flexible_motif_score_thr (float): The minimum fraction_depleted score required.

    Returns:
        pd.DataFrame: A new, filtered DataFrame with updated scores.
    """
    new_metrics = []
    all_motifs = flexible_motifs_df['motif'].tolist()

    for current_motif in all_motifs:
        other_motifs = [m for m in all_motifs if m != current_motif]

        matches_current_filter = _get_filter_for_motif(log2fc_series, current_motif, left_context, right_context)

        matches_other_filter = pd.Series(False, index=log2fc_series.index)
        for other_motif in other_motifs:
            matches_other_filter |= _get_filter_for_motif(log2fc_series, other_motif, left_context, right_context)
            
        final_filter = matches_current_filter & ~matches_other_filter
        
        filtered_series = log2fc_series[final_filter]
    

        log2fc_values = filtered_series.values
        
        num_sequences = len(log2fc_values)
        # Use the passed threshold for scoring
        fraction_depleted = score(log2fc_values, thr=flexible_motif_log2fc_thr)
        avg_log2fc = np.mean(log2fc_values) if num_sequences > 0 else 0.0
        
        new_metrics.append({
            'fraction_depleted': fraction_depleted,
            'num_sequences': num_sequences,
            'avg_log2fc': avg_log2fc
        })

    df_updated = flexible_motifs_df.copy()
    metrics_df = pd.DataFrame(new_metrics, index=df_updated.index)
    
    df_updated['fraction_depleted'] = metrics_df['fraction_depleted']
    df_updated['num_sequences'] = metrics_df['num_sequences']
    df_updated['avg_log2fc'] = metrics_df['avg_log2fc']

    # Apply final thresholds to filter the updated DataFrame
    # The condition for avg_log2fc should be less than or equal to the threshold
    final_df = df_updated[
        (df_updated['avg_log2fc'] <= flexible_motif_log2fc_thr) &
        (df_updated['num_sequences'] >= flexible_motif_min_support) &
        (df_updated['fraction_depleted'] >= flexible_motif_score_thr)
    ]
    
    return final_df

In [26]:
#| export
def find_restricted_motifs(log2fc_series, 
                           left_context_str, 
                           right_context_str, 
                           fixed_motif_scan_depth_k=6,
                           fixed_motif_max_length=4,
                           fixed_motif_depletion_thr=-1,
                           fixed_motif_score_thr=0.85,
                           fixed_motif_min_support=5,
                           core_motif_score_margin=0.05, # For fixed motifs
                           flexible_motif_patterns=[(6,0,0),(3,4,4)], 
                           flexible_motif_log2fc_thr=-1,
                           flexible_motif_min_support=3,
                           flexible_motif_score_thr=0.7,
                           core_flexible_motif_score_margin=0.2 # For flexible motifs
                           ):
    """
    Full pipeline to identify fixed-position core motifs and then position-independent motifs
    (from a list of patterns) in the remaining sequences (with context for flexible search).
    """
    print("--- Starting Fixed-Position Motif Analysis (on original short sequences) ---")
    depleted_fixed_motifs_df = identify_depleted_motifs_scanning_ends(
        log2fc_series, 
        scan_depth_k=fixed_motif_scan_depth_k,
        max_motif_length=fixed_motif_max_length,
        depletion_threshold=fixed_motif_depletion_thr,
        score_thr=fixed_motif_score_thr,
        min_sequence_support=fixed_motif_min_support
    )
    core_fixed_motifs_df = filter_to_core_motifs( 
        depleted_fixed_motifs_df,
        score_improvement_margin=core_motif_score_margin
    )
    del depleted_fixed_motifs_df

    if core_fixed_motifs_df.empty:
        print("No core motifs found at fixed positions.")
    else:
        print(f"Found {len(core_fixed_motifs_df)} core motifs at fixed positions:")
        for _, row in core_fixed_motifs_df.iterrows():
            print(f"  - Fixed Motif: {row['motif']}, Pos: {row['position']}, Len: {row['length']}, FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    print("\n--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---")
    log2fc_series_for_flexible_analysis = filter_sequences_without_core_motifs(
        log2fc_series, 
        core_fixed_motifs_df 
    )
    if len(log2fc_series_for_flexible_analysis) == len(log2fc_series):
        print("No sequences were filtered out based on fixed-position core motifs (or no core motifs found).")
    else:
        print(f"Filtered log2fc_series for flexible analysis: {len(log2fc_series_for_flexible_analysis)} sequences remaining.")

    if log2fc_series_for_flexible_analysis.empty:
        print("No sequences remaining for flexible motif analysis after filtering.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc']) 
        return core_fixed_motifs_df, flexible_motifs_results_df

    short_sequences_for_flex_analysis = log2fc_series_for_flexible_analysis.index.tolist()
    sequences_with_context_for_flex = get_lib_seq_context(
        short_sequences_for_flex_analysis, 
        left_context_str, 
        right_context_str
    )
    fc_values_for_flexible_analysis = log2fc_series_for_flexible_analysis.tolist()
    del log2fc_series_for_flexible_analysis
    
    cumulative_flexible_motifs_df = pd.DataFrame()

    if not isinstance(flexible_motif_patterns, list):
        print("Warning: flexible_motif_patterns should be a list. Wrapping it in a list.")
        flexible_motif_patterns = [flexible_motif_patterns]

    flexible_motif_patterns = sorted(flexible_motif_patterns, key=lambda x: (x[0]+x[2], x[1]))  #sorting the patterns by complexity (defined positions and spacer length)
    
    for current_flex_pattern in tqdm(flexible_motif_patterns):
        
        site_sets_flexible = get_sites_in_seq(
            sequences_with_context_for_flex, 
            pattern=current_flex_pattern, 
            no_ori=True 
        )
        if len(site_sets_flexible) != len(fc_values_for_flexible_analysis):
            print(f"    Error: Mismatch in length between site sets ({len(site_sets_flexible)}) and FC values ({len(fc_values_for_flexible_analysis)}) for pattern {current_flex_pattern}. Skipping this pattern.")
            continue

        site_fcs_flexible = get_fold_change_values_per_site(
            site_sets_flexible,
            fc_values_for_flexible_analysis 
        )
        del site_sets_flexible # Free memory

        current_pattern_scores_df = get_sites_scores( 
            site_fcs_flexible,
            pattern=current_flex_pattern, 
            log2FC_thr=flexible_motif_log2fc_thr
        )
        
        if not current_pattern_scores_df.empty:
            current_pattern_scores_df.rename(columns={'site': 'motif'}, inplace=True) 
            current_pattern_scores_df['pattern'] = str(current_flex_pattern) 
            filtered_for_this_pattern = current_pattern_scores_df[
                (current_pattern_scores_df['fraction_depleted'] > flexible_motif_score_thr) &
                (current_pattern_scores_df['num_sequences'] > flexible_motif_min_support)
            ]
            if len(filtered_for_this_pattern)>0: 
                print(f"Found hits with pattern: {current_flex_pattern}")
                print(filtered_for_this_pattern)
            
            if not filtered_for_this_pattern.empty:
                print(f"Found {len(filtered_for_this_pattern)} candidate(s) for pattern {current_flex_pattern}. Filtering against previous results...")
                
                # Combine with previous results and filter iteratively
                combined_before_filtering = pd.concat([cumulative_flexible_motifs_df, filtered_for_this_pattern], ignore_index=True)
                
                cumulative_flexible_motifs_df = filter_redundant_patterns(
                    combined_before_filtering,
                    score_margin=core_flexible_motif_score_margin,
                )
                print(f"  -> {len(cumulative_flexible_motifs_df)} core motifs remain after filtering.")
                print(cumulative_flexible_motifs_df)


    if cumulative_flexible_motifs_df.empty:
        print(f"\nNo flexible motifs found meeting initial support > {flexible_motif_min_support} and score > {flexible_motif_score_thr} for any provided pattern.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc']) 
    else:
        print(f"\nIdentified {len(cumulative_flexible_motifs_df)} raw flexible motifs. Now filtering to core flexible motifs...")
        print("\nNow flitering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds")
            
        flexible_motifs_results_df = update_motif_scores_from_unique_hits(cumulative_flexible_motifs_df, 
                                                                        log2fc_series, 
                                                                        left_context_str, 
                                                                        right_context_str, 
                                                                        flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
                                                                        flexible_motif_min_support=flexible_motif_min_support,
                                                                        flexible_motif_score_thr=flexible_motif_score_thr)
        
        print(f"\n{len(flexible_motifs_results_df)} motifs remaining:")
        if flexible_motifs_results_df.empty:
            print("No core flexible motifs remained after filtering.")
        else:                                                                                                                             
            for _, row in flexible_motifs_results_df.iterrows():
                print(f"{row['motif']} (from pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    return core_fixed_motifs_df, flexible_motifs_results_df

In [ ]:
#| export
def find_restricted_motifs(log2fc_series, 
                           left_context_str, 
                           right_context_str, 
                           fixed_motif_scan_depth_k=6,
                           fixed_motif_max_length=4,
                           fixed_motif_depletion_thr=-1,
                           fixed_motif_score_thr=0.85,
                           fixed_motif_min_support=5,
                           core_motif_score_margin=0.05, # For fixed motifs
                           flexible_motif_patterns=[(6,0,0)], 
                           flexible_motif_log2fc_thr=-1,
                           flexible_motif_min_support=3,
                           flexible_motif_score_thr=0.7,
                           core_flexible_motif_score_margin=0.2 # For flexible motifs
                           ):
    """
    Full pipeline to identify fixed-position core motifs and then position-independent motifs
    (from a list of patterns) in the remaining sequences (with context for flexible search).
    """
    print("--- Starting Fixed-Position Motif Analysis (on original short sequences) ---")
    depleted_fixed_motifs_df = identify_depleted_motifs_scanning_ends(
        log2fc_series, 
        scan_depth_k=fixed_motif_scan_depth_k,
        max_motif_length=fixed_motif_max_length,
        depletion_threshold=fixed_motif_depletion_thr,
        score_thr=fixed_motif_score_thr,
        min_sequence_support=fixed_motif_min_support
    )
    core_fixed_motifs_df = filter_to_core_motifs( 
        depleted_fixed_motifs_df,
        score_improvement_margin=core_motif_score_margin
    )
    del depleted_fixed_motifs_df

    if core_fixed_motifs_df.empty:
        print("No core motifs found at fixed positions.")
    else:
        print(f"Found {len(core_fixed_motifs_df)} core motifs at fixed positions:")
        for _, row in core_fixed_motifs_df.iterrows():
            print(f"  - Fixed Motif: {row['motif']}, Pos: {row['position']}, Len: {row['length']}, FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    print("\n--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---")
    log2fc_series_for_flexible_analysis = filter_sequences_without_core_motifs(
        log2fc_series, 
        core_fixed_motifs_df 
    )
    if len(log2fc_series_for_flexible_analysis) == len(log2fc_series):
        print("No sequences were filtered out based on fixed-position core motifs (or no core motifs found).")
    else:
        print(f"Filtered log2fc_series for flexible analysis: {len(log2fc_series_for_flexible_analysis)} sequences remaining.")

    if log2fc_series_for_flexible_analysis.empty:
        print("No sequences remaining for flexible motif analysis after filtering.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc']) 
        return core_fixed_motifs_df, flexible_motifs_results_df

    short_sequences_for_flex_analysis = log2fc_series_for_flexible_analysis.index.tolist()
    sequences_with_context_for_flex = get_lib_seq_context(
        short_sequences_for_flex_analysis, 
        left_context_str, 
        right_context_str
    )
    fc_values_for_flexible_analysis = log2fc_series_for_flexible_analysis.tolist()
    del log2fc_series_for_flexible_analysis
    
    cumulative_flexible_motifs_df = pd.DataFrame()

    if not isinstance(flexible_motif_patterns, list):
        print("Warning: flexible_motif_patterns should be a list. Wrapping it in a list.")
        flexible_motif_patterns = [flexible_motif_patterns]

    flexible_motif_patterns = sorted(flexible_motif_patterns, key=lambda x: (x[0]+x[2], x[1]))  #sorting the patterns by complexity (defined positions and spacer length)
    
    for current_flex_pattern in tqdm(flexible_motif_patterns):
        
        site_sets_flexible = get_sites_in_seq(
            sequences_with_context_for_flex, 
            pattern=current_flex_pattern, 
            no_ori=True 
        )
        if len(site_sets_flexible) != len(fc_values_for_flexible_analysis):
            print(f"    Error: Mismatch in length between site sets ({len(site_sets_flexible)}) and FC values ({len(fc_values_for_flexible_analysis)}) for pattern {current_flex_pattern}. Skipping this pattern.")
            continue

        site_fcs_flexible = get_fold_change_values_per_site(
            site_sets_flexible,
            fc_values_for_flexible_analysis 
        )
        del site_sets_flexible # Free memory

        current_pattern_scores_df = get_sites_scores( 
            site_fcs_flexible,
            pattern=current_flex_pattern, 
            log2FC_thr=flexible_motif_log2fc_thr
        )
        
        if not current_pattern_scores_df.empty:
            current_pattern_scores_df.rename(columns={'site': 'motif'}, inplace=True) 
            current_pattern_scores_df['pattern'] = str(current_flex_pattern) 
            filtered_for_this_pattern = current_pattern_scores_df[
                (current_pattern_scores_df['fraction_depleted'] > flexible_motif_score_thr) &
                (current_pattern_scores_df['num_sequences'] > flexible_motif_min_support)
            ]
            if len(filtered_for_this_pattern)>0: 
                print(f"Found hits with pattern: {current_flex_pattern}")
                print(filtered_for_this_pattern)
            
            if not filtered_for_this_pattern.empty:
                print(f"Found {len(filtered_for_this_pattern)} candidate(s) for pattern {current_flex_pattern}. Filtering against previous results...")
                
                # Combine with previous results and filter iteratively
                combined_before_filtering = pd.concat([cumulative_flexible_motifs_df, filtered_for_this_pattern], ignore_index=True)
                
                cumulative_flexible_motifs_df = filter_redundant_patterns(
                    combined_before_filtering,
                    score_margin=core_flexible_motif_score_margin,
                )
                print(f"  -> {len(cumulative_flexible_motifs_df)} core motifs remain after filtering.")
                print(cumulative_flexible_motifs_df)


    if cumulative_flexible_motifs_df.empty:
        print(f"\nNo flexible motifs found meeting initial support > {flexible_motif_min_support} and score > {flexible_motif_score_thr} for any provided pattern.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc']) 
    else:
        print(f"\nIdentified {len(cumulative_flexible_motifs_df)} raw flexible motifs. Now filtering to core flexible motifs...")
        print("\nNow flitering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds")
            
        flexible_motifs_results_df = update_motif_scores_from_unique_hits(cumulative_flexible_motifs_df, 
                                                                        log2fc_series, 
                                                                        left_context_str, 
                                                                        right_context_str, 
                                                                        flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
                                                                        flexible_motif_min_support=flexible_motif_min_support,
                                                                        flexible_motif_score_thr=flexible_motif_score_thr)
        
        print(f"\n{len(flexible_motifs_results_df)} motifs remaining:")
        if flexible_motifs_results_df.empty:
            print("No core flexible motifs remained after filtering.")
        else:                                                                                                                             
            for _, row in flexible_motifs_results_df.iterrows():
                print(f"{row['motif']} (from pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    return core_fixed_motifs_df, flexible_motifs_results_df

In [27]:
counts_file="countsTable.csv"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)

patterns = get_patterns()
core_fixed_motifs_df, flexible_motifs_df = find_restricted_motifs(log2fc_df["JJ1886_T0"], 
                        left,
                        right, 
                        fixed_motif_scan_depth_k=6,
                        fixed_motif_max_length=4,
                        fixed_motif_depletion_thr=-1,
                        fixed_motif_score_thr=0.85,
                        fixed_motif_min_support=5,
                        core_motif_score_margin=0.05,
                        flexible_motif_patterns=[(6,0,0),(7,0,0),(4,2,4),(4,4,3),(4,3,4),(4,4,4)],
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_min_support=3,
                        flexible_motif_score_thr=0.7
                        )

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Analyzing motifs of length 1 to 4, scanning positions 0 to 6 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 2 core motifs at fixed positions:
  - Fixed Motif: GTG, Pos: 0, Len: 3, FracDep: 1.00, AvgFC: -4.76, N: 187
  - Fixed Motif: AAAG, Pos: 12, Len: 4, FracDep: 1.00, AvgFC: -5.08, N: 42

--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---
Filtered log2fc_series for flexible analysis: 11275 sequences remaining.

 17%|█▋        | 1/6 [00:02<00:13,  2.75s/it]

Found hits with pattern: (6, 0, 0)
       motif  fraction_depleted  num_sequences  avg_log2fc    pattern
4091  GAGACC                1.0              9   -4.313837  (6, 0, 0)
4092  GGTCTC                1.0              9   -4.313837  (6, 0, 0)
Found 2 candidate(s) for pattern (6, 0, 0). Filtering against previous results...
  -> 1 core motifs remain after filtering.
    motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0  GAGACC                1.0              9   -4.313837  (6, 0, 0)

 33%|███▎      | 2/6 [00:06<00:12,  3.12s/it]

Found hits with pattern: (7, 0, 0)
         motif  fraction_depleted  num_sequences  avg_log2fc    pattern
15993  AGGTCTC               1.00              5   -4.255940  (7, 0, 0)
15994  GAGACCT               1.00              5   -4.255940  (7, 0, 0)
16062  CCTGAGA               0.75              4   -3.030459  (7, 0, 0)
16063  TCTCAGG               0.75              4   -3.030459  (7, 0, 0)
16074  TGAGACC               1.00              4   -5.344022  (7, 0, 0)
16075  GGTCTCA               1.00              4   -5.344022  (7, 0, 0)
Found 6 candidate(s) for pattern (7, 0, 0). Filtering against previous results...
  -> 2 core motifs remain after filtering.
     motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0   GAGACC               1.00              9   -4.313837  (6, 0, 0)
3  CCTGAGA               0.75              4   -3.030459  (7, 0, 0)

 50%|█████     | 3/6 [00:09<00:09,  3.31s/it]

Found hits with pattern: (4, 4, 3)
             motif  fraction_depleted  num_sequences  avg_log2fc    pattern
7327   GTACNNNNGTG                1.0             20   -5.237623  (4, 4, 3)
14360  ATACNNNNGTG                1.0              5   -4.428066  (4, 4, 3)
14361  GCACNNNNGTA                0.8              5   -3.848971  (4, 4, 3)
15147  AAAGNNNNGTT                1.0             21   -5.325198  (4, 4, 3)
Found 4 candidate(s) for pattern (4, 4, 3). Filtering against previous results...
  -> 6 core motifs remain after filtering.
         motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0       GAGACC               1.00              9   -4.313837  (6, 0, 0)
1      CCTGAGA               0.75              4   -3.030459  (7, 0, 0)
2  GTACNNNNGTG               1.00             20   -5.237623  (4, 4, 3)
3  ATACNNNNGTG               1.00              5   -4.428066  (4, 4, 3)
4  GCACNNNNGTA               0.80              5   -3.848971  (4, 4, 3)
5  AAAGNNNNGTT               1.00             21   -5.325198  (4, 4, 3)

 67%|██████▋   | 4/6 [00:14<00:07,  3.94s/it]

Found hits with pattern: (4, 2, 4)
            motif  fraction_depleted  num_sequences  avg_log2fc    pattern
9881   TACGNNGGTG              0.875              8   -4.538017  (4, 2, 4)
9894   CACCNNCGTA              0.875              8   -4.538017  (4, 2, 4)
26354  CCTCNNCCTC              0.750              4   -4.109363  (4, 2, 4)
26361  GAGGNNGAGG              0.750              4   -4.109363  (4, 2, 4)
42265  CTGANNCCTC              0.750              4   -4.053409  (4, 2, 4)
42271  GAGGNNTCAG              0.750              4   -4.053409  (4, 2, 4)
47666  TCGTNNGTAC              0.750              4   -2.511846  (4, 2, 4)
47667  GTACNNACGA              0.750              4   -2.511846  (4, 2, 4)
Found 8 candidate(s) for pattern (4, 2, 4). Filtering against previous results...
  -> 10 core motifs remain after filtering.
          motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0        GAGACC              1.000              9   -4.313837  (6, 0, 0)
1       CCTGAGA              0.750              4   -3.030459  (7, 0, 0)
2   GTACNNNNGTG              1.000             20   -5.237623  (4, 4, 3)
3   ATACNNNNGTG              1.000              5   -4.428066  (4, 4, 3)
4   GCACNNNNGTA              0.800              5   -3.848971  (4, 4, 3)
5   AAAGNNNNGTT              1.000             21   -5.325198  (4, 4, 3)
6    TACGNNGGTG              0.875              8   -4.538017  (4, 2, 4)
8    CCTCNNCCTC              0.750              4   -4.109363  (4, 2, 4)
10   CTGANNCCTC              0.750              4   -4.053409  (4, 2, 4)
12   TCGTNNGTAC              0.750              4   -2.511846  (4, 2, 4)

 83%|████████▎ | 5/6 [00:19<00:04,  4.39s/it]

Found hits with pattern: (4, 3, 4)
             motif  fraction_depleted  num_sequences  avg_log2fc    pattern
10007  GTACNNNGGTG           1.000000              9   -5.092974  (4, 3, 4)
10024  CACCNNNGTAC           1.000000              9   -5.092974  (4, 3, 4)
17958  TCACNNNCGTA           0.714286              7   -3.547885  (4, 3, 4)
17959  TACGNNNGTGA           0.714286              7   -3.547885  (4, 3, 4)
31272  TGAGNNNTCTG           0.750000              4   -4.077213  (4, 3, 4)
31274  CAGANNNCTCA           0.750000              4   -4.077213  (4, 3, 4)
36068  AAAGNNNCGTT           1.000000              5   -6.057519  (4, 3, 4)
36069  TAACNNNACTT           0.833333              6   -4.729768  (4, 3, 4)
36070  AAGTNNNGTTA           0.833333              6   -4.729768  (4, 3, 4)
36071  AACGNNNCTTT           1.000000              5   -6.057519  (4, 3, 4)
37398  TACGNNNGTGT           0.800000              5   -4.230048  (4, 3, 4)
37410  ACACNNNCGTA           0.800000              5   -4.230048  (4, 3, 4)
40732  AAAGNNNGGTT           1.000000              6   -5.306290  (4, 3, 4)
40738  AACCNNNCTTT           1.000000              6   -5.306290  (4, 3, 4)
43244  AAAGNNNAGTT           1.000000              4   -5.328530  (4, 3, 4)
43250  AACTNNNCTTT           1.000000              4   -5.328530  (4, 3, 4)
45966  GTACNNNTGTG           1.000000              4   -6.086366  (4, 3, 4)
45968  CACANNNGTAC           1.000000              4   -6.086366  (4, 3, 4)
46665  GAACNNNCCTT           0.750000              4   -3.221192  (4, 3, 4)
46666  AAGGNNNGTTC           0.750000              4   -3.221192  (4, 3, 4)
48259  AACANNNCTTT           1.000000              6   -4.731617  (4, 3, 4)
48263  AAAGNNNTGTT           1.000000              6   -4.731617  (4, 3, 4)
54507  GAGGNNNCAGG           0.750000              4   -3.945381  (4, 3, 4)
54508  CCTGNNNCCTC           0.750000              4   -3.945381  (4, 3, 4)
58947  GTACNNNCGTG           1.000000              4   -5.025342  (4, 3, 4)
58948  CACGNNNGTAC           1.000000              4   -5.025342  (4, 3, 4)
Found 26 candidate(s) for pattern (4, 3, 4). Filtering against previous results...
  -> 16 core motifs remain after filtering.
          motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0        GAGACC           1.000000              9   -4.313837  (6, 0, 0)
1       CCTGAGA           0.750000              4   -3.030459  (7, 0, 0)
2   GTACNNNNGTG           1.000000             20   -5.237623  (4, 4, 3)
3   ATACNNNNGTG           1.000000              5   -4.428066  (4, 4, 3)
4   GCACNNNNGTA           0.800000              5   -3.848971  (4, 4, 3)
5   AAAGNNNNGTT           1.000000             21   -5.325198  (4, 4, 3)
6    TACGNNGGTG           0.875000              8   -4.538017  (4, 2, 4)
7    CCTCNNCCTC           0.750000              4   -4.109363  (4, 2, 4)
8    CTGANNCCTC           0.750000              4   -4.053409  (4, 2, 4)
9    TCGTNNGTAC           0.750000              4   -2.511846  (4, 2, 4)
12  TCACNNNCGTA           0.714286              7   -3.547885  (4, 3, 4)
14  TGAGNNNTCTG           0.750000              4   -4.077213  (4, 3, 4)
17  TAACNNNACTT           0.833333              6   -4.729768  (4, 3, 4)
20  TACGNNNGTGT           0.800000              5   -4.230048  (4, 3, 4)
28  GAACNNNCCTT           0.750000              4   -3.221192  (4, 3, 4)
32  GAGGNNNCAGG           0.750000              4   -3.945381  (4, 3, 4)

100%|██████████| 6/6 [00:24<00:00,  4.11s/it]

Found hits with pattern: (4, 4, 4)
              motif  fraction_depleted  num_sequences  avg_log2fc    pattern
784    GGTANNNNCGTG               0.75              4   -1.775300  (4, 4, 4)
817    CACGNNNNTACC               0.75              4   -1.775300  (4, 4, 4)
10146  CCACNNNNGTAC               1.00              5   -5.723264  (4, 4, 4)
10147  GTACNNNNGTGG               1.00              5   -5.723264  (4, 4, 4)
14944  GTACNNNNGTGT               1.00              5   -5.237645  (4, 4, 4)
14952  ACACNNNNGTAC               1.00              5   -5.237645  (4, 4, 4)
18490  GTACNNNNGTGA               1.00              8   -4.964453  (4, 4, 4)
18501  TCACNNNNGTAC               1.00              8   -4.964453  (4, 4, 4)
28520  AAGTNNNNTTAA               0.80              5   -3.338426  (4, 4, 4)
28532  TTAANNNNACTT               0.80              5   -3.338426  (4, 4, 4)
35135  GAGGNNNNGGTC               1.00              4   -4.357958  (4, 4, 4)
35143  GACCNNNNCCTC               1.00              4   -4.357958  (4, 4, 4)
35383  AAAGNNNNGTTA               1.00              7   -5.664336  (4, 4, 4)
35385  TAACNNNNCTTT               1.00              7   -5.664336  (4, 4, 4)
42547  AAAGNNNNGTTT               1.00              4   -4.816791  (4, 4, 4)
42548  AAACNNNNCTTT               1.00              4   -4.816791  (4, 4, 4)
45380  AAAGNNNNGTTG               1.00              4   -5.112519  (4, 4, 4)
45382  CAACNNNNCTTT               1.00              4   -5.112519  (4, 4, 4)
47580  GAACNNNNCTTT               1.00              6   -5.410260  (4, 4, 4)
47581  AAAGNNNNGTTC               1.00              6   -5.410260  (4, 4, 4)
Found 20 candidate(s) for pattern (4, 4, 4). Filtering against previous results...
  -> 19 core motifs remain after filtering.
           motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0         GAGACC           1.000000              9   -4.313837  (6, 0, 0)
1        CCTGAGA           0.750000              4   -3.030459  (7, 0, 0)
2    GTACNNNNGTG           1.000000             20   -5.237623  (4, 4, 3)
3    ATACNNNNGTG           1.000000              5   -4.428066  (4, 4, 3)
4    GCACNNNNGTA           0.800000              5   -3.848971  (4, 4, 3)
5    AAAGNNNNGTT           1.000000             21   -5.325198  (4, 4, 3)
6     TACGNNGGTG           0.875000              8   -4.538017  (4, 2, 4)
7     CCTCNNCCTC           0.750000              4   -4.109363  (4, 2, 4)
8     CTGANNCCTC           0.750000              4   -4.053409  (4, 2, 4)
9     TCGTNNGTAC           0.750000              4   -2.511846  (4, 2, 4)
10   TCACNNNCGTA           0.714286              7   -3.547885  (4, 3, 4)
11   TGAGNNNTCTG           0.750000              4   -4.077213  (4, 3, 4)
12   TAACNNNACTT           0.833333              6   -4.729768  (4, 3, 4)
13   TACGNNNGTGT           0.800000              5   -4.230048  (4, 3, 4)
14   GAACNNNCCTT           0.750000              4   -3.221192  (4, 3, 4)
15   GAGGNNNCAGG           0.750000              4   -3.945381  (4, 3, 4)
16  GGTANNNNCGTG           0.750000              4   -1.775300  (4, 4, 4)
24  AAGTNNNNTTAA           0.800000              5   -3.338426  (4, 4, 4)
26  GAGGNNNNGGTC           1.000000              4   -4.357958  (4, 4, 4)

Identified 19 raw flexible motifs. Now filtering to core flexible motifs...

Now flitering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds

4 motifs remaining:
GAGACC (from pattern (6, 0, 0)), FracDep: 1.00, AvgFC: -3.75, N: 6
GTACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.92, N: 6
ATACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.74, N: 146
AAAGNNNNGTT (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -5.02, N: 54

In [28]:
core_fixed_motifs_df

  motif  length  position  num_sequences  avg_log2fc  fraction_depleted
0   GTG       3         0            187   -4.764500                1.0
1  AAAG       4        12             42   -5.076919                1.0

In [29]:
flexible_motifs_df

         motif  fraction_depleted  num_sequences  avg_log2fc    pattern
0       GAGACC                1.0              6   -3.750094  (6, 0, 0)
2  GTACNNNNGTG                1.0              6   -4.922717  (4, 4, 3)
3  ATACNNNNGTG                1.0            146   -4.744952  (4, 4, 3)
5  AAAGNNNNGTT                1.0             54   -5.018200  (4, 4, 3)

In [30]:
#| hide
#| eval: false
counts_file="counts_long.csv"
file_path=os.path.join(data_path,counts_file)
df = pd.read_csv(file_path)

# Check if the DataFrame is empty or has no columns
if not df.empty and df.shape[1] > 0:
    # Identify rows where the first column string does NOT end with "GGGGGGGG"
    # The '~' operator negates the boolean condition
    filtered_df = df[~df.iloc[:, 0].astype(str).str.endswith('GGGGGGGG')]

    # Save the filtered DataFrame to a new CSV file without the pandas index
    filtered_df.to_csv(os.path.join(data_path,"counts_long_clean.csv"), index=False)

In [ ]:
#| hide
#| eval: false
counts_file="counts_long_clean.csv"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts.replace(np.nan,0)
log2fc_df = calculate_log2fc(counts, reference_column='Control', count_threshold=20, pseudocount=1)
left, right = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
patterns = get_patterns() #[(6, 0, 0), (7, 0, 0), (3, 4, 4), (4, 1, 4), (4, 2, 4), (4, 3, 4), (4, 4, 4), (4, 5, 4), (4,6,4), (4,7,4), (4,8,4)]
core_fixed_motifs_df, flexible_motifs_df = find_restricted_motifs(log2fc_df["16226_R1"], 
                        left,
                        right, 
                        fixed_motif_scan_depth_k=6,
                        fixed_motif_max_length=4,
                        fixed_motif_depletion_thr=-1,
                        fixed_motif_score_thr=0.85,
                        fixed_motif_min_support=5,
                        core_motif_score_margin=0.05,
                        flexible_motif_patterns=patterns,
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_min_support=3,
                        flexible_motif_score_thr=0.7
                        )

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Analyzing motifs of length 1 to 4, scanning positions 0 to 6 from each end, for 16226_R1.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 1 core motifs at fixed positions:
  - Fixed Motif: CTTT, Pos: 4, Len: 4, FracDep: 0.98, AvgFC: -3.02, N: 245

--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---
Filtered log2fc_series for flexible analysis: 30834 sequences remaining.

  2%|▏         | 1/43 [00:32<22:29, 32.14s/it]

KeyboardInterrupt:

In [40]:
#| export

from multiprocessing import Pool, cpu_count
import functools # To pass fixed arguments to the parallel function


def process_single_flexible_pattern(
    current_flex_pattern,
    sequences_with_context_for_flex,
    fc_values_for_flexible_analysis,
    flexible_motif_log2fc_thr,
    flexible_motif_score_thr,
    flexible_motif_min_support
):
    """
    Helper function to process a single flexible motif pattern.
    This function will be called in parallel.
    """
    # print(f"  Processing pattern: {current_flex_pattern}") # Can uncomment for debugging parallel runs

    site_sets_flexible = get_sites_in_seq(
        sequences_with_context_for_flex,
        pattern=current_flex_pattern,
        no_ori=True
    )
    if len(site_sets_flexible) != len(fc_values_for_flexible_analysis):
        print(f"    Error: Mismatch in length between site sets ({len(site_sets_flexible)}) and FC values ({len(fc_values_for_flexible_analysis)}) for pattern {current_flex_pattern}. Skipping this pattern.")
        return pd.DataFrame() # Return empty DataFrame if error

    site_fcs_flexible = get_fold_change_values_per_site(
        site_sets_flexible,
        fc_values_for_flexible_analysis
    )
    # del site_sets_flexible # Cannot del in a parallel function as it's not a copy

    current_pattern_scores_df = get_sites_scores(
        site_fcs_flexible,
        pattern=current_flex_pattern,
        log2FC_thr=flexible_motif_log2fc_thr
    )

    if not current_pattern_scores_df.empty:
        current_pattern_scores_df.rename(columns={'site': 'motif'}, inplace=True)
        current_pattern_scores_df['pattern'] = str(current_flex_pattern)
        filtered_for_this_pattern = current_pattern_scores_df[
            (current_pattern_scores_df['fraction_depleted'] > flexible_motif_score_thr) &
            (current_pattern_scores_df['num_sequences'] > flexible_motif_min_support)
        ]
        # print(f"    Found {len(filtered_for_this_pattern)} hits for pattern {current_flex_pattern}") # Can uncomment for debugging
        return filtered_for_this_pattern
    return pd.DataFrame()


def find_restricted_motifs_mp(log2fc_series,
                           left_context_str,
                           right_context_str,
                           fixed_motif_scan_depth_k=6,
                           fixed_motif_max_length=4,
                           fixed_motif_depletion_thr=-1,
                           fixed_motif_score_thr=0.85,
                           fixed_motif_min_support=5,
                           core_motif_score_margin=0.05,  # For fixed motifs
                           flexible_motif_patterns=[(6, 0, 0), (3, 4, 4)],
                           flexible_motif_log2fc_thr=-1,
                           flexible_motif_min_support=3,
                           flexible_motif_score_thr=0.7,
                           core_flexible_motif_score_margin=0.2,  # For flexible motifs
                           cpu_count=1):
    """
    Full pipeline to identify fixed-position core motifs and then position-independent motifs
    (from a list of patterns) in the remaining sequences (with context for flexible search).
    """
    print("--- Starting Fixed-Position Motif Analysis (on original short sequences) ---")
    depleted_fixed_motifs_df = identify_depleted_motifs_scanning_ends(
        log2fc_series,
        scan_depth_k=fixed_motif_scan_depth_k,
        max_motif_length=fixed_motif_max_length,
        depletion_threshold=fixed_motif_depletion_thr,
        score_thr=fixed_motif_score_thr,
        min_sequence_support=fixed_motif_min_support
    )
    core_fixed_motifs_df = filter_to_core_motifs(
        depleted_fixed_motifs_df,
        score_improvement_margin=core_motif_score_margin
    )
    del depleted_fixed_motifs_df

    if core_fixed_motifs_df.empty:
        print("No core motifs found at fixed positions.")
    else:
        print(f"Found {len(core_fixed_motifs_df)} core motifs at fixed positions:")
        for _, row in core_fixed_motifs_df.iterrows():
            print(f"  - Fixed Motif: {row['motif']}, Pos: {row['position']}, Len: {row['length']}, FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    print("\n--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---")
    log2fc_series_for_flexible_analysis = filter_sequences_without_core_motifs(
        log2fc_series,
        core_fixed_motifs_df
    )
    if len(log2fc_series_for_flexible_analysis) == len(log2fc_series):
        print("No sequences were filtered out based on fixed-position core motifs (or no core motifs found).")
    else:
        print(f"Filtered log2fc_series for flexible analysis: {len(log2fc_series_for_flexible_analysis)} sequences remaining.")

    if log2fc_series_for_flexible_analysis.empty:
        print("No sequences remaining for flexible motif analysis after filtering.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
        return core_fixed_motifs_df, flexible_motifs_results_df

    short_sequences_for_flex_analysis = log2fc_series_for_flexible_analysis.index.tolist()
    sequences_with_context_for_flex = get_lib_seq_context(
        short_sequences_for_flex_analysis,
        left_context_str,
        right_context_str
    )
    fc_values_for_flexible_analysis = log2fc_series_for_flexible_analysis.tolist()
    del log2fc_series_for_flexible_analysis # Free memory

    # Ensure flexible_motif_patterns is a list
    if not isinstance(flexible_motif_patterns, list):
        print("Warning: flexible_motif_patterns should be a list. Wrapping it in a list.")
        flexible_motif_patterns = [flexible_motif_patterns]

    # Sorting the patterns by complexity (defined positions and spacer length)
    flexible_motif_patterns = sorted(flexible_motif_patterns, key=lambda x: (x[0] + x[2], x[1]))

    # --- Parallelization starts here ---
    print(f"Parallelizing flexible motif analysis across {len(flexible_motif_patterns)} patterns...")

    # Determine number of processes to use
    # It's often good practice to leave one core free for system processes
    num_processes = cpu_count
    print(f"Using {num_processes} processes for parallel analysis.")

    # Create a partial function to fix common arguments for _process_single_flexible_pattern
    # This makes it compatible with Pool.map or passing a single tuple to starmap
    partial_process_pattern = functools.partial(
        process_single_flexible_pattern,
        sequences_with_context_for_flex=sequences_with_context_for_flex,
        fc_values_for_flexible_analysis=fc_values_for_flexible_analysis,
        flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
        flexible_motif_score_thr=flexible_motif_score_thr,
        flexible_motif_min_support=flexible_motif_min_support
    )

    all_pattern_results = []
    # Use tqdm for a progress bar with multiprocessing
    with Pool(processes=num_processes) as pool:
        # Use imap_unordered for results to come in as they are ready,
        # which is useful with tqdm and when order doesn't strictly matter for intermediate steps
        for result_df in tqdm(pool.imap_unordered(partial_process_pattern, flexible_motif_patterns),
                              total=len(flexible_motif_patterns),
                              desc="Processing flexible patterns"):
            if not result_df.empty:
                all_pattern_results.append(result_df)

    # Combine all results from parallel processing
    cumulative_flexible_motifs_df = pd.concat(all_pattern_results, ignore_index=True) if all_pattern_results else pd.DataFrame()

    # --- Continue with the rest of your original logic for filtering and final results ---
    if not cumulative_flexible_motifs_df.empty:
        print(f"Found {len(cumulative_flexible_motifs_df)} candidate(s) from all patterns. Filtering against redundancies...")
        cumulative_flexible_motifs_df = filter_redundant_patterns(
            cumulative_flexible_motifs_df,
            score_margin=core_flexible_motif_score_margin,
        )
        print(f"  -> {len(cumulative_flexible_motifs_df)} core motifs remain after filtering.")
        # print(cumulative_flexible_motifs_df) # Uncomment to see intermediate results

    if cumulative_flexible_motifs_df.empty:
        print(f"\nNo flexible motifs found meeting initial support > {flexible_motif_min_support} and score > {flexible_motif_score_thr} for any provided pattern.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
    else:
        print(f"\nIdentified {len(cumulative_flexible_motifs_df)} raw flexible motifs. Now filtering to core flexible motifs...")
        print("\nNow filtering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds")

        flexible_motifs_results_df = update_motif_scores_from_unique_hits(cumulative_flexible_motifs_df,
                                                                          log2fc_series,
                                                                          left_context_str,
                                                                          right_context_str,
                                                                          flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
                                                                          flexible_motif_min_support=flexible_motif_min_support,
                                                                          flexible_motif_score_thr=flexible_motif_score_thr)

        print(f"\n{len(flexible_motifs_results_df)} motifs remaining:")
        if flexible_motifs_results_df.empty:
            print("No core flexible motifs remained after filtering.")
        else:
            for _, row in flexible_motifs_results_df.iterrows():
                print(f"{row['motif']} (from pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    return core_fixed_motifs_df, flexible_motifs_results_df

In [ ]:
#| hide
#| eval: false
counts_file="countsTable.csv"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)

patterns = get_patterns()
core_fixed_motifs_df, flexible_motifs_df = find_restricted_motifs_mp(log2fc_df["JJ1886_T0"], 
                        left,
                        right, 
                        fixed_motif_scan_depth_k=6,
                        fixed_motif_max_length=4,
                        fixed_motif_depletion_thr=-1,
                        fixed_motif_score_thr=0.85,
                        fixed_motif_min_support=5,
                        core_motif_score_margin=0.05,
                        flexible_motif_patterns=[(6,0,0),(7,0,0),(4,2,4),(4,4,3),(4,3,4),(4,4,4)],
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_min_support=3,
                        flexible_motif_score_thr=0.7, cpu_count=5)

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Analyzing motifs of length 1 to 4, scanning positions 0 to 6 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 2 core motifs at fixed positions:
  - Fixed Motif: GTG, Pos: 0, Len: 3, FracDep: 1.00, AvgFC: -4.76, N: 187
  - Fixed Motif: AAAG, Pos: 12, Len: 4, FracDep: 1.00, AvgFC: -5.08, N: 42

--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---
Filtered log2fc_series for flexible analysis: 11275 sequences remaining.
Parallelizing flexible motif analysis across 6 patterns...
Using 5 processes for parallel analysis.

Processing flexible patterns: 100%|██████████| 6/6 [00:11<00:00,  1.96s/it]

Found 66 candidate(s) from all patterns. Filtering against redundancies...
  -> 19 core motifs remain after filtering.

Identified 19 raw flexible motifs. Now filtering to core flexible motifs...

Now filtering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds

4 motifs remaining:
GAGACC (from pattern (6, 0, 0)), FracDep: 1.00, AvgFC: -3.75, N: 6
GTACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.92, N: 6
ATACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.74, N: 146
AAAGNNNNGTT (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -5.02, N: 54

In [32]:
#| hide
import nbdev; nbdev.nbdev_export()