In [ ]:
%load_ext autoreload
%autoreload 2

# core

> Finding the DNA motifs a strain restricts, from a table of plasmid counts before and after delivery.

In [ ]:
#| default_exp core

In [ ]:
#| hide
from nbdev.showdoc import *
from fastcore.test import test_close, test_eq, test_fail

In [ ]:
#| export
import ast
import pandas as pd
from tqdm import tqdm
import numpy as np
from scipy.stats import beta, kurtosis, skew
import os
import functools
from multiprocessing import Pool
import re
from itertools import product
from randseq.coding import (encode_library, _pattern_window_codes, decode_motif_codes,
                            encode_motif, motif_presence_matrix,
                            pattern_is_self_rc, rc_code_table)
from randseq import fast as _fast
from randseq.utils import (IUPAC_COLLAPSE, IUPAC_EXPAND, score, revcomp, calculate_log2fc, get_lib_seq_context, get_patterns,
                           canonical_pattern,
                           find_broad_in_specific, _get_filter_for_motif, canonical_motif,
                           plasmid_background, motif_pvalues, benjamini_hochberg)

In [ ]:
#| hide
from randseq.example_data import get_example_data_dir

In [ ]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['__init__.py',
 '__pycache__',
 'countsTable.csv.gz',
 'counts_panel.csv.gz',
 'counts_panel_key.csv',
 'pMin_backbone.fasta']

## What RandSeq measures

A library of plasmids carrying random inserts is conjugated into a recipient strain. A plasmid
whose insert contains a recognition site for an active restriction system is destroyed on entry,
so it is **depleted** relative to the input library. Sequencing the library before and after
gives, for each insert, a log2 fold change. This module works backwards from those fold changes
to the sequence motifs responsible.

### The method in four sentences

Every plasmid gets a **log2FC**: how much rarer it became after delivery. Every motif gets the
plasmids that contain it, and so a set of log2FC values. A motif's **score** is the fraction of
those values below a threshold — what fraction of the plasmids carrying this motif were
destroyed. Everything after that is deciding **which of the many motifs that score well is the
actual site**.

That last sentence is the bulk of the work. As four steps, then reporting:

1. counts → log2FC per plasmid
2. score every motif of every requested pattern — **the scan**
3. keep one description per site, discarding the same site written more or less specifically
4. drop a candidate whose score was borrowed from a stronger one
5. report, with each motif's depletion weighed against what plasmids of the same GC content do
   in this sample

Steps 3 and 4 are two halves of one problem: **one real site makes many motifs score well.**
Step 3 works on motif *strings*, and settles descriptions that differ by a defined position.
Step 4 works on *plasmids*, and settles descriptions in shapes too different for any string rule
to relate.

Which motifs an experiment could have found at all depends on the vector and the library, not on
this code; `03_design` works that out, and a negative result needs it.

### The example data

Two count tables ship with the package.

- `countsTable.csv.gz` — 19 recipient strains, with the donor `MFDpir` as the input library;
  11,629 inserts of 20 nt
- `counts_panel.csv.gz` — 8 recipient strains and two donor replicates (`Control_R1`,
  `Control_R2`), each strain picked to exercise one behaviour of the pipeline;
  `example_data/counts_panel_key.csv` says which. 34,217 inserts, mostly 150 nt and ragged at
  the short end

They differ in insert length, in library size and in their vector flanks. *E. coli* JJ1886
appears in both, so two measurements of one strain must agree on which motifs they call and on
which strand they name them.

## Step 1: counts → log2FC per plasmid

The input is a table of read counts: **one row per insert sequence, one column per sample**. One
column holds the input library — the donor, before delivery — and every other column is a
recipient strain.

`calculate_log2fc` turns that into a fold change per insert, against the input column:

- **`count_threshold`** drops inserts too rare in the input to measure, keeping those seen
  *more than* this many times (so `20` keeps 21 and above). An insert read three times gives a
  fold change that is mostly sampling noise.
- **`pseudocount`** is added to every count first, so an insert driven to zero yields a finite
  number instead of `-inf`.
- counts are then converted to **relative abundance** — each column divided by its own sum — so
  that samples sequenced to different depths are comparable, and the reference column is dropped
  from the result.

Everything downstream works on a single column of this table: a Series indexed by insert
sequence, valued by log2 fold change.

**One more adjustment happens inside `find_restricted_motifs`: each series is centred on its
median.** A plasmid that no system touches should have a log2FC of 0, but the typical plasmid
usually does not. Normalising both samples to their totals makes the reference-weighted average
*fold change* equal to 1, and the log of an average is larger than the average of the logs: the
more fold changes vary from plasmid to plasmid — an uneven or bottlenecked transconjugant pool —
the further the typical log2FC falls below 0. Across the BB2 libraries the median runs from +0.07
to −1.05, lower the wider the distribution (Spearman −0.62 with the interquartile range), and
strains that call nothing are shifted as much as those that do (−0.07 to −0.73), so the shift is
not caused by sites. A fixed threshold on uncentred values would then mean a different stringency
in every strain: in 381A (median −0.62) 55% of plasmids fall below −0.5 before any site is
involved. Centring measures every plasmid against the sample's typical one. Without centring, a permissive
threshold floods the shifted strains with candidates (7084, median −0.40, brings 22,669 to step 4
instead of 4); with it, the threshold means the same thing everywhere. `center=False` turns it
off.

In [ ]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df

                        K12_T0     HS_T0  ...    S88_T0  MG1655_T0
seq                                       ...
CGGAGGTACTGGGTACATTT  0.043818  0.049551  ...  0.213624   0.090458
TGGCGATAATGCCGGCTATC  0.045463  0.137127  ...  0.092292   0.101627
TTCCAGTTCACTGGTCTTCG -0.049694  0.049903  ...  0.458076   0.128330
AATTTCAGTGCCGTTCAGAT -0.251957 -0.422224  ... -0.183890  -0.180938
CTGCGGTAATAATTCCCGCC -0.178427 -0.154025  ... -0.188758  -0.186226
...                        ...       ...  ...       ...        ...
GCTTGATGTAGCCTTCGAAC -0.100518 -0.079966  ... -0.055837  -0.133185
TAATGGCAAATTGACACTCC  0.258205  0.103683  ...  0.201961   0.387054
GCTGCGCGCGGAGTTGTTCC -0.629856 -0.381054  ... -0.497605  -0.959646
GCAACACGCCAGTAAGGTGT  0.693416  0.487153  ...  0.064457   0.376418
GATAGCCGGATAGCTTAAGG -0.245685 -0.131631  ... -0.400835   0.140210

[11503 rows x 19 columns]

## Step 2: the position-independent scan

Every motif of every **pattern** is scored over `left_flank + insert + right_flank`, on both
strands. A pattern is the shape of a site, written as three numbers — defined bases in the first
half, undefined bases between, defined bases in the second. `(6, 0, 0)` is a contiguous 6 bp site
like `GGTCTC`; `(3, 4, 4)` is a bipartite site like `CACNNNNGTAT`. `get_patterns()` in
`randseq.utils` returns the shapes REBASE records for Type I, II and III systems.

The flanks are scanned because a site can **straddle the junction** between insert and vector.
In the panel library the left flank ends in `AAAC`, so every insert that starts `NNNNGTC`
completes B156's site `AAACNNNNGTC`. Those plasmids are cut like any other carrier, and the scan
counts them like any other carrier: 382 of the 894 plasmids that carry the site in B156 carry it
across the junction.

Two rules define what "the plasmids containing a motif" means, and both matter for reading the
output:

- a motif is counted **once per plasmid**, however many times it occurs in that plasmid
- a motif and its **reverse complement are the same motif** — the library is scanned on both
  strands and the two are collapsed before counting

The search space is the caller's: `flexible_motif_patterns` lists the shapes to enumerate, and a
site whose shape is not in that list cannot be found.

The rest of this section is what the scan computes and how it is kept fast and exact.

### What the scan computes, on three sequences

Before any machinery, the whole of step 2 for a single motif, by hand. `GAGACC` is present in the
first two sequences — in the second it is read on the other strand, as `GGTCTC`, and the two are
one motif. Collect the log2FC of the plasmids that carry it, and the score is the fraction of
those below the threshold. Thresholds keep one convention throughout the package: a **log2FC**
threshold is strict (`log2FC < thr`), a **score or support** threshold inclusive (`>= thr`, so
`min_support=3` means three supporting sequences, not four).

In [ ]:
_seqs = ["GAGACCTT", "AAGAGACC", "TTTTTTTT"]
_fc = [-2.0, 0.5, -3.0]

carries = [("GAGACC" in s) or ("GGTCTC" in s) for s in _seqs]   # either strand, one motif
vals = [f for f, c in zip(_fc, carries) if c]
print(f"plasmids carrying GAGACC : {[s for s, c in zip(_seqs, carries) if c]}")
print(f"their log2FC             : {vals}")
print(f"score, fraction below -1 : {score(vals, thr=-1)}")

plasmids carrying GAGACC : ['GAGACCTT', 'AAGAGACC']
their log2FC             : [-2.0, 0.5]
score, fraction below -1 : 0.5

That is step 2 for one motif. The scan does it for **every** motif of every requested
architecture at once, which is the only reason any machinery is needed.

### How the scan is made fast

Scoring every motif of every pattern is where the runtime goes, so the scan does not work on
strings. Each library sequence is encoded once as 2-bit base codes, and a motif of pattern
`(d1, spacer, d2)` becomes an **integer** — its `d1 + d2` defined bases read as a base-4
numeral — so every per-motif statistic is an `np.bincount` over those integers. The alternative,
building a Python set of motif strings per sequence, costs roughly 10 s and 2 GB of RAM per
pattern on a 30k-sequence library against well under a second here.

`randseq.coding` holds that machinery — `encode_library`, `_pattern_window_codes`,
`decode_motif_codes`, `encode_motif`, `motif_presence_matrix` — together with the proofs that it
is exact. What matters in this notebook is only the contract:

- a window containing **any** non-ACGT base is rejected, padding included
- a motif is counted **once per sequence** that contains it, on either strand
- decoding is the exact inverse of encoding, so a reported motif string is the motif that was
  counted

A readable implementation of the same scan lives outside the package as
`tests/reference_scan.py`, and `tests/test_reference_scan.py` requires the two to produce
identical tables — so the fast path cannot quietly drift from the obvious one.

When numba is installed (`randseq[fast]`), `get_pattern_scores` runs steps A and B below as a
single compiled pass from `randseq.fast` instead, about thirteen times faster on eight cores.
What follows is still what it computes: the kernel is tested to return the same totals as these
numpy steps, on every shipped pattern.

### The scan in three steps

Scoring a pattern is one function, but it is three operations, and each has an output worth
seeing. The library below is twelve inserts of twelve bases with a site planted in four of
them — `GAGACC`, which reads `GGTCTC` on the other strand — and those four are the depleted
ones. Everything is small enough to check by eye.

In [ ]:
demo_lib = ["GAGACCTTAACG", "TTGAGACCGCAT", "ACGGTCTCAATG", "CCAAGAGACCTT",
            "ACGTTGCAATGC", "TTACGCATTGCA", "GCATTACGGTTA", "ATGCCATTGCAA",
            "CATGCAATTGCG", "TTGCAATGCCAT", "GCAATTGCATGC", "ATTGCCATGCAA"]
demo_fc = np.array([-2.5, -3.0, -3.5, -3.0, 0.2, -0.1, 0.0, 0.3, -0.2, 0.1, 0.0, -0.3])

pd.DataFrame({"insert": demo_lib, "log2FC": demo_fc,
              "carries the site": [("GAGACC" in s) or ("GGTCTC" in s) for s in demo_lib],
              "depleted (< -1)": demo_fc < -1})

          insert  log2FC  carries the site  depleted (< -1)
0   GAGACCTTAACG    -2.5              True             True
1   TTGAGACCGCAT    -3.0              True             True
2   ACGGTCTCAATG    -3.5              True             True
3   CCAAGAGACCTT    -3.0              True             True
4   ACGTTGCAATGC     0.2             False            False
5   TTACGCATTGCA    -0.1             False            False
6   GCATTACGGTTA     0.0             False            False
7   ATGCCATTGCAA     0.3             False            False
8   CATGCAATTGCG    -0.2             False            False
9   TTGCAATGCCAT     0.1             False            False
10  GCAATTGCATGC     0.0             False            False
11  ATTGCCATGCAA    -0.3             False            False

The four carriers are exactly the four depleted plasmids, so a correct scan must report
`GAGACC` with a depletion fraction of 1.0 on a support of 4. Nothing else in the library should
come close.

**The library, encoded.** Before any scanning, `encode_library` turns the strings into 2-bit
base codes — `A=0 C=1 G=2 T=3`, anything else `4` — and returns the reverse complement
alongside, so both strands are available without re-encoding anything.

In [ ]:
demo_fwd, demo_rc = encode_library(demo_lib)
print(f"fwd {demo_fwd.shape} {demo_fwd.dtype}, rc {demo_rc.shape}\n")
pd.DataFrame(demo_fwd[:4], index=demo_lib[:4])

fwd (12, 12) uint8, rc (12, 12)

              0   1   2   3   4   5   6   7   8   9   10  11
GAGACCTTAACG   2   0   2   0   1   1   3   3   0   0   1   2
TTGAGACCGCAT   3   3   2   0   2   0   1   1   2   1   0   3
ACGGTCTCAATG   0   1   2   2   3   1   3   1   0   0   3   2
CCAAGAGACCTT   1   1   0   0   2   0   2   0   1   1   3   3

Row `i` of `rc` is the reverse complement of sequence `i`, left-aligned in the same way — not a
reversal of the padded row. For the first insert:

In [ ]:
print(f"      {demo_lib[0]}   {demo_fwd[0].tolist()}")
print(f"  rc  {revcomp(demo_lib[0])}   {demo_rc[0].tolist()}")

      GAGACCTTAACG   [2, 0, 2, 0, 1, 1, 3, 3, 0, 0, 1, 2]
  rc  CGTTAAGGTCTC   [1, 2, 3, 3, 0, 0, 2, 2, 3, 1, 3, 1]

**Step A — which motifs does each sequence contain?** Scan every window of both strands, then
reduce to one entry per *sequence and motif*: a motif occurring several times in one insert, or
once on each strand, is still one plasmid carrying it.

A site is double-stranded, so `GAGACC` and `GGTCTC` are one motif and must not be counted twice.
Whether both spellings even reach this point is decided by the pattern — a motif of
`(d1, spacer, d2)` reverse-complements into one of `(d2, spacer, d1)`. When that is the same
shape, as it is for `(6, 0, 0)`, the scan finds the site once per strand and the two codes are
**folded onto one** here. When it is not, the rc spelling belongs to another pattern's code space
and never appears, so there is nothing to fold. `randseq.coding` carries that rule and its proof;
the effect is that every pattern emits exactly one row per plasmid per site.

In [ ]:
#| export
def motif_occurrences(encoded_library, pattern):
    """Which motifs each sequence contains, as parallel `(sequence index, motif code)` arrays.

    Both strands are scanned and the result is reduced to one entry per sequence per motif, so
    a motif occurring several times in one sequence -- or once on each strand -- is counted
    once. Where a pattern is self-reverse-complementary the two spellings of a site are folded
    onto one code first, so `GAGACC` and `GGTCTC` come back as a single motif rather than two
    rows carrying identical statistics. Windows containing a non-ACGT base, or running off the
    end of a short sequence, are dropped: both carry the out-of-range code that
    `_pattern_window_codes` assigns.

    Returns:
        (seq_idx, motif_codes): equal-length int arrays. `seq_idx` is non-decreasing, so the
        pairs come out grouped by sequence.
    """
    fwd, rc = encoded_library
    n_codes = 4 ** (pattern[0] + pattern[2])
    codes = np.concatenate([_pattern_window_codes(fwd, pattern),
                            _pattern_window_codes(rc, pattern)], axis=1)
    if pattern_is_self_rc(pattern):
        # One site, two spellings, both in this code space -- fold each onto the smaller of the
        # pair. Rejected windows keep their out-of-range code: they are not in the table, so
        # they are held out of the lookup and passed through untouched.
        table = rc_code_table(pattern)
        inside = codes < n_codes
        codes = np.where(inside, np.minimum(codes, table[np.where(inside, codes, 0)]), codes)
    codes.sort(axis=1)                                  # repeats become adjacent
    keep = codes < n_codes                              # drop rejected windows
    keep[:, 1:] &= codes[:, 1:] != codes[:, :-1]        # drop repeats within a sequence
    return np.nonzero(keep)[0], codes[keep]

In [ ]:
seq_idx, motif_codes = motif_occurrences(encode_library(demo_lib), (6, 0, 0))
occurrences = pd.DataFrame({
    "sequence": [demo_lib[i] for i in seq_idx],
    "motif": decode_motif_codes(motif_codes, (6, 0, 0)),
    # the code IS the motif: A=0 C=1 G=2 T=3, read as a base-4 numeral
    "code (base 4)": [np.base_repr(c, 4).zfill(6) for c in motif_codes],
    "code": motif_codes})
print(f"{len(occurrences)} (sequence, motif) pairs from {len(demo_lib)} sequences")
occurrences.head(8)

82 (sequence, motif) pairs from 12 sequences

       sequence   motif code (base 4)  code
0  GAGACCTTAACG  AAGGTC        002231   173
1  GAGACCTTAACG  ACCTTA        011330   380
2  GAGACCTTAACG  AGACCT        020113   535
3  GAGACCTTAACG  CCTTAA        113300  1520
4  GAGACCTTAACG  CGTTAA        123300  1776
5  GAGACCTTAACG  CTTAAC        133001  1985
6  GAGACCTTAACG  GAGACC        202011  2181
7  TTGAGACCGCAT  ACCGCA        011210   356

Each row is one plasmid carrying one motif, and the base-4 column shows that a code is not an
arbitrary label — it **is** the motif. `GAGACC` is `202011` because `A=0 C=1 G=2 T=3`. The
integer is just that numeral in decimal, which is what makes every per-motif statistic an
`np.bincount`.

A 12 bp insert holds seven 6-mers per strand. Folding the strands together means those fourteen
windows collapse to at most seven distinct motifs — fewer still when a motif occurs twice in one
insert, or is its own reverse complement.

Pulling out just the planted site shows what the scan is going to score:

In [ ]:
occurrences[occurrences.motif.isin(["GAGACC", "GGTCTC"])]

        sequence   motif code (base 4)  code
6   GAGACCTTAACG  GAGACC        202011  2181
11  TTGAGACCGCAT  GAGACC        202011  2181
18  ACGGTCTCAATG  GAGACC        202011  2181
27  CCAAGAGACCTT  GAGACC        202011  2181

Four sequences, one row each. `GGTCTC` is **not** a separate entry: it is the same site read on
the other strand, and Step A folded the pair onto the single code shown. Which of the two
spellings survives is decided by the code, not by biology — the smaller numeral wins, here
`GAGACC`. *Reporting* is where that is re-spelled to the name the literature uses, which for this
site is `GGTCTC`.

None of the twelve inserts above contains anything but `ACGT`, and all are the same length, so
neither rejection rule has shown itself yet. Both are about windows: a window containing a base
other than `ACGT` is dropped, and so is one that runs past the end of a short sequence (the
encoding pads short sequences with the same code an `N` gets). Three inserts show both:

In [ ]:
edge = ["GAGACCTT",           # clean
        "GAGACCTTNAAAAAA",    # an N at position 8, then six more bases
        "GAGAC"]              # shorter than the 6-base pattern
_s, _c = motif_occurrences(encode_library(edge), (6, 0, 0))
pd.DataFrame({"sequence": [edge[i] for i in _s], "motif": decode_motif_codes(_c, (6, 0, 0))})

          sequence   motif
0         GAGACCTT  AAGGTC
1         GAGACCTT  AGACCT
2         GAGACCTT  GAGACC
3  GAGACCTTNAAAAAA  AAAAAA
4  GAGACCTTNAAAAAA  AAGGTC
5  GAGACCTTNAAAAAA  AGACCT
6  GAGACCTTNAAAAAA  GAGACC

The second insert keeps everything the first has — those windows end before the `N` — loses the
six windows that cover position 8, and picks up `AAAAAA` from the clean stretch after it (`TTTTTT`
on the other strand, folded). The third is padded to the library's width, every window runs into
the padding, and it contributes nothing.

In [ ]:
#| hide
_by = {e: sorted(m for i, m in zip(_s.tolist(), decode_motif_codes(_c, (6, 0, 0))) if edge[i] == e)
       for e in edge}
test_eq(_by["GAGACCTT"], ["AAGGTC", "AGACCT", "GAGACC"])
test_eq(_by["GAGACCTTNAAAAAA"], ["AAAAAA", "AAGGTC", "AGACCT", "GAGACC"])   # N windows dropped
test_eq(_by["GAGAC"], [])                                                   # too short: none
test_eq(len(motif_occurrences(encode_library(["GAGNCC"]), (6, 0, 0))[0]), 0)  # N anywhere kills it

**Step B — group those pairs by motif.** Every statistic the scan reports is a sum over the
sequences carrying a motif, so each is one `np.bincount`. One of them sums each carrier's
**background**: the rate at which a plasmid like it depletes in this sample with no site involved,
which the p-value needs. On a real library `plasmid_background` (`01_utils`) estimates it from the
plasmids of similar GC content; on these twelve inserts one rate does for all, the third of them
that are depleted. `first_seq` is kept so the output can be ordered by where a motif first
appears, which makes the table a function of the library rather than of hash order.

In [ ]:
#| export
def _motif_totals(seq_idx, motif_codes, fc_values, background, log2FC_thr, n_codes):
    """Per motif code: sequences carrying it, how many of those are depleted, the sum of their
    log2FC, the sum of their background, and the index of the first sequence that carries it.

    Sums rather than means, because `np.bincount` adds; the means are taken once at the end.
    """
    seq_fc = fc_values[seq_idx]
    n_seqs = np.bincount(motif_codes, minlength=n_codes)
    n_depleted = np.bincount(motif_codes, weights=seq_fc < log2FC_thr, minlength=n_codes)
    fc_sum = np.bincount(motif_codes, weights=seq_fc, minlength=n_codes)
    bg_sum = np.bincount(motif_codes, weights=background[seq_idx], minlength=n_codes)
    first_seq = np.full(n_codes, len(fc_values))
    np.minimum.at(first_seq, motif_codes, seq_idx)
    return n_seqs, n_depleted, fc_sum, bg_sum, first_seq

In [ ]:
demo_bg = np.full(len(demo_lib), (demo_fc < -1).mean())      # one rate for all: 4 of 12
n_seqs, n_depleted, fc_sum, bg_sum, first_seq = _motif_totals(
    seq_idx, motif_codes, demo_fc, demo_bg, -1, 4 ** 6)

present = np.flatnonzero(n_seqs)                 # the motifs this library actually contains
totals = pd.DataFrame({"motif": decode_motif_codes(present, (6, 0, 0)),
                       "n_seqs": n_seqs[present], "n_depleted": n_depleted[present],
                       "sum_log2fc": fc_sum[present], "sum_background": bg_sum[present],
                       "first_seq": first_seq[present]})
print(f"{len(totals)} motifs present out of {4 ** 6} possible")
totals.sort_values(["n_depleted", "n_seqs"], ascending=False).head(6)

53 motifs present out of 4096 possible

     motif  n_seqs  n_depleted  sum_log2fc  sum_background  first_seq
43  GAGACC       4         4.0       -12.0        1.333333          0
2   AAGGTC       2         2.0        -5.5        0.666667          0
13  AGACCG       2         2.0        -6.5        0.666667          1
14  AGACCT       2         2.0        -5.5        0.666667          0
47  GTCTCA       2         2.0        -6.5        0.666667          1
50  TCTCAA       2         2.0        -6.5        0.666667          1

`GAGACC` tops the table with four sequences, all four depleted — one row for the site, since
Step A folded `GGTCTC` into it. Only the motifs actually present get a row; the other codes
have a count of zero and are dropped.

**Step C — turn the totals into the reported numbers.** `fraction_depleted` is
`n_depleted / n_seqs`, `avg_log2fc` is `fc_sum / n_seqs`, and the p-value compares the depleted
count with the carriers' mean background, `bg_sum / n_seqs`. That is all that is left to do:

In [ ]:
#| export
def scan_pattern(encoded_library, pattern, fc_values, background, log2FC_thr=-1, parallel=True):
    """Steps A and B for one pattern: per motif code, how many sequences carry it, how many of
    those are depleted, the sum of their log2FC, the sum of their background, and the first
    sequence that carries it.

    The compiled kernel from `randseq.fast` when numba is installed, `motif_occurrences` and
    `_motif_totals` otherwise -- the same five arrays either way. Every count the pipeline makes
    of "the plasmids carrying a motif" comes from here, so no two steps can disagree on it.
    `background` is each plasmid's expected depletion rate, from `plasmid_background`.
    """
    fc_values = np.asarray(fc_values, dtype=float)
    background = np.asarray(background, dtype=float)
    if _fast.HAVE_NUMBA:
        return _fast.pattern_totals(encoded_library, pattern, fc_values, background, log2FC_thr,
                                    parallel=parallel)
    seq_idx, motif_codes = motif_occurrences(encoded_library, pattern)
    return _motif_totals(seq_idx, motif_codes, fc_values, background, log2FC_thr,
                         4 ** (pattern[0] + pattern[2]))


def _scores_from_totals(totals, pattern, codes):
    """Step C for the given motif codes: the reported statistics, ordered by first sequence."""
    n_seqs, n_depleted, fc_sum, bg_sum, first_seq = totals
    codes = codes[np.argsort(first_seq[codes], kind="stable")]
    n = n_seqs[codes]
    frac = n_depleted[codes] / n
    return pd.DataFrame({
        'motif': decode_motif_codes(codes, pattern),
        'fraction_depleted': frac,
        'num_sequences': n,
        'avg_log2fc': fc_sum[codes] / n,
        # P(at least this many of n depleted | null), the null being the carriers' mean
        # background -- see `plasmid_background` in `01_utils`.
        'p_value': motif_pvalues(n, frac, bg_sum[codes] / n),
    })


def get_pattern_scores(encoded_library, fc_values, pattern, log2FC_thr=-1,
                       background=None, parallel=True):
    """
    Scores every motif of `pattern` found in the library, on both strands.

    Steps A, B and C above: find the (sequence, motif) pairs, total them per motif, and turn
    the totals into the reported statistics. A motif is counted once per sequence that contains
    it on either strand. `tests/reference_scan.py` holds a readable implementation of the same
    scan, and `tests/test_reference_scan.py` requires the two to give identical tables.

    When numba is installed, steps A and B run as one compiled pass instead (`randseq.fast`),
    which returns the same totals; `tests/test_fast_scan.py` requires the two paths to agree.

    Args:
        encoded_library (tuple): (fwd, rc) arrays from `encode_library`.
        fc_values (list or np.ndarray): log2FC of each sequence, in library order.
        pattern (tuple): (d1, spacer, d2) motif pattern.
        log2FC_thr (float): a sequence is depleted when its log2FC is below this value.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`; a motif's p-value is taken against its carriers' mean. Defaults
            to one rate for all, the fraction of this library that is depleted: the encoded
            library holds the sequences with their flanks, not the inserts GC is counted on.
        parallel (bool): let the compiled path use numba's threads. Ignored on the numpy path.

    Returns:
        pd.DataFrame: one row per motif with 'motif', 'fraction_depleted',
            'num_sequences', 'avg_log2fc' and 'p_value', ordered by the first sequence that
            contains the motif.
    """
    fc_values = np.asarray(fc_values, dtype=float)
    if background is None:
        background = np.full(len(fc_values), np.mean(fc_values < log2FC_thr))
    totals = scan_pattern(encoded_library, pattern, fc_values, background, log2FC_thr,
                          parallel)                                                   # A + B
    return _scores_from_totals(totals, pattern, np.flatnonzero(totals[0]))            # C

In [ ]:
scores = get_pattern_scores(encode_library(demo_lib), demo_fc, (6, 0, 0))
scores.sort_values(["fraction_depleted", "num_sequences"], ascending=False).head(6)

     motif  fraction_depleted  num_sequences  avg_log2fc   p_value
6   GAGACC                1.0              4       -3.00  0.012346
0   AAGGTC                1.0              2       -2.75  0.111111
2   AGACCT                1.0              2       -2.75  0.111111
8   AGACCG                1.0              2       -3.25  0.111111
11  GTCTCA                1.0              2       -3.25  0.111111
12  TCTCAA                1.0              2       -3.25  0.111111

The planted site comes out at `fraction_depleted` 1.0 on four plasmids with a mean log2FC of
−3.0. The motifs below it are fragments of the same depleted inserts — 6-mers overlapping the
planted site — on two plasmids each: too few to judge, which is what
`flexible_motif_min_support` exists to discard.

In [ ]:
#| hide
cols = ['fraction_depleted', 'num_sequences', 'avg_log2fc']
_t = scores.set_index('motif')
test_eq(_t.loc['GAGACC', cols].tolist(), [1.0, 4, -3.0])
assert 'GGTCTC' not in _t.index        # folded onto GAGACC: one site, one row, not two

# Step A: one entry per sequence per motif, however often it occurs or on whichever strand.
_e = encode_library(["GAGACCGAGACC", "TTTTTTTT"])          # GAGACC occurs TWICE in the first
_s, _c = motif_occurrences(_e, (6, 0, 0))
_pairs = list(zip(_s.tolist(), decode_motif_codes(_c, (6, 0, 0))))
test_eq(len(_pairs), len(set(_pairs)))                     # no (sequence, motif) pair repeats
test_eq(sum(1 for s, m in _pairs if s == 0 and m == "GAGACC"), 1)   # twice, both strands -> one
test_eq(sum(1 for s, m in _pairs if s == 0 and m == "GGTCTC"), 0)   # the rc spelling is folded
test_eq(sorted(m for s, m in _pairs if s == 1), ["AAAAAA"])         # TTTTTT folds onto AAAAAA
test_eq(len(motif_occurrences(encode_library(["NNNNNNNN"]), (6, 0, 0))[0]), 0)

# An asymmetric pattern has nothing to fold, and is left exactly as it was: the rc of a
# (4, 4, 3) motif is a (3, 4, 4) motif, which is not in this code space at all.
_sa, _ca = motif_occurrences(encode_library(["AAATACCCCCGTGAAA"]), (4, 4, 3))
test_eq(sum(1 for m in decode_motif_codes(_ca, (4, 4, 3)) if m == "ATACNNNNGTG"), 1)

# Step B: the totals are sums over exactly those pairs, each sequence's background included.
_n, _d, _f, _b, _first = _motif_totals(_s, _c, np.array([-5.0, 0.0]), np.array([0.25, 0.5]), -1, 4 ** 6)
_g = encode_motif("GAGACC", (6, 0, 0))
test_eq((int(_n[_g]), int(_d[_g]), float(_f[_g]), float(_b[_g]), int(_first[_g])), (1, 1, -5.0, 0.25, 0))
_ta = encode_motif("AAAAAA", (6, 0, 0))                    # the folded home of TTTTTT
test_eq((int(_n[_ta]), int(_d[_ta]), float(_b[_ta]), int(_first[_ta])), (1, 0, 0.5, 1))
test_eq(int(_n[encode_motif("CCCCCC", (6, 0, 0))]), 0)     # absent -> no sequences

### The real library

So far the scan has run on twelve inserts made up by hand. From here on the notebook works on the
example library instead: the inserts with their vector flanks added, and the matching log2FC
values. `get_lib_seq_context` builds the scanned strings, `plasmid_background` gives each
plasmid its GC-matched background, which every test from here on is taken against, and
`process_single_flexible_pattern` below wraps the scan with the support and score thresholds that
turn scores into candidates.

In [ ]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib = get_lib_seq_context(log2fc_df.index, left, right)
fcs = log2fc_df["JJ1886_T0"].values
bg = plasmid_background(log2fc_df.index, fcs, -1)
print(f"{len(lib)} sequences, each {len(lib[0])} nt with the flanks added")
lib[0][:60]

11503 sequences, each 60 nt with the flanks added

'GTCCTAGGTATAATACTAGTCGGAGGTACTGGGTACATTTGTTTTAGAGCTAGAAATAGC'

In [ ]:
#| export
def process_single_flexible_pattern(
    current_flex_pattern,
    encoded_library,
    fc_values_for_flexible_analysis,
    background,
    flexible_motif_log2fc_thr,
    flexible_motif_score_thr,
    flexible_motif_min_support,
    parallel=True,
):
    """
    Scores all motifs of one flexible pattern and keeps the candidates with
    fraction_depleted >= flexible_motif_score_thr and num_sequences >= flexible_motif_min_support.

    Args:
        current_flex_pattern (tuple): (d1, spacer, d2) motif pattern.
        encoded_library (tuple): (fwd, rc) arrays from `encode_library` (sequences with context).
        fc_values_for_flexible_analysis (list): log2FC of each sequence, in library order.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`.
        flexible_motif_log2fc_thr (float): log2FC below which a sequence counts as depleted.
        flexible_motif_score_thr (float): minimum fraction_depleted (inclusive, `>=`).
        flexible_motif_min_support (int): minimum number of sequences (inclusive, `>=`).
        parallel (bool): passed to `scan_pattern`; False inside a pool worker.

    Returns:
        (pd.DataFrame, np.ndarray, tuple): the surviving candidates -- 'motif',
            'fraction_depleted', 'num_sequences', 'avg_log2fc', 'p_value' and 'pattern' (the
            pattern as a string) -- the p-value of *every* motif that had enough support to be a
            test, survivor or not, and the pattern's totals from `scan_pattern`, so that later
            steps can look motifs of this pattern up rather than scan it again.

    Both are returned because the Benjamini-Hochberg correction needs the full set of tests, and
    only this function ever sees it: the candidates that fail the score threshold are discarded
    here, but they were still tested, and a correction that ignored them would be wrong.
    """
    fc = np.asarray(fc_values_for_flexible_analysis, dtype=float)
    totals = scan_pattern(encoded_library, current_flex_pattern, fc, background,
                          flexible_motif_log2fc_thr, parallel)
    n_seqs, n_depleted, bg_sum = totals[0], totals[1], totals[3]
    # Only the candidates are turned into strings; the tests stay arrays. A pattern has up to
    # 4**8 motifs present, and decoding every one of them was most of this step's time.
    tested = np.flatnonzero(n_seqs >= max(flexible_motif_min_support, 1))
    frac = n_depleted[tested] / n_seqs[tested]
    kept = _scores_from_totals(totals, current_flex_pattern,
                               tested[frac >= flexible_motif_score_thr])
    kept['pattern'] = str(current_flex_pattern)
    return kept, motif_pvalues(n_seqs[tested], frac, bg_sum[tested] / n_seqs[tested]), totals

In [ ]:
candidates, tested, _ = process_single_flexible_pattern((3, 4, 4), encode_library(lib), fcs, bg, -1, 0.7, 3)
# far more motifs were tested than survived -- the correction has to account for all of them
print(f"{len(candidates)} candidates kept out of {len(tested)} tested")
candidates.sort_values('num_sequences', ascending=False).head()

8 candidates kept out of 16296 tested

         motif  fraction_depleted  ...        p_value    pattern
1  ATANNNNTGTG           0.964467  ...  1.250984e-246  (3, 4, 4)
2  CACNNNNGTAT           1.000000  ...  6.893502e-261  (3, 4, 4)
4  TACNNNNGTGA           0.849315  ...   7.008886e-73  (3, 4, 4)
6  TACNNNNGTGG           0.907692  ...   2.267976e-73  (3, 4, 4)
0  AACNNNNCTTT           1.000000  ...   1.893283e-87  (3, 4, 4)

[5 rows x 6 columns]

In [ ]:
#| hide
# The scan reports whichever strand it read; these are the same two sites as ATACNNNNGTG and
# AAAGNNNNGTT, which is how they are spelled once canonicalised for reporting.
assert {"CACNNNNGTAT", "AACNNNNCTTT"} <= set(candidates.motif)

## Step 3: one description per site

One site comes back from the scan described several ways, each differing from the next by a single
position. In this library the Type I site `CACNNNNGTAT` also comes back as `CACNNNNGTA`, one base
shorter, and the site `CACNNNNGTAC` comes back once for each base pinned at the first position of
its spacer — `CACANNNGTAC`, `CACCNNNGTAC`, `CACGNNNGTAC`, `CACTNNNGTAC`. Step 3 keeps one
description per site, with one tool and three rules applied in a fixed order:

- **the variant profile**: pin one position next to a motif to each of A, C, G and T, and score
  the four motifs on the plasmids that carry each
- **rule 1, a mixture is not a site**: drop a motif when some position next to it splits its four
  variants into depleting and not
- **rule 2, a one-base extension of a site is redundant**: drop a motif that is a rule-1 survivor
  plus one defined base
- **rule 3, a motif with an uninformative base is not the site**: drop a motif when putting N back
  at one of its defined bases gives four bases that all behave like the site

Rule 1 comes first because rule 2 rests on it: an extension adds nothing *because* the motif it
extends is a site, and only rule 1 establishes that. The end of this section shows what goes wrong
the other way round.

### The tool: scoring the four bases at one position

Rules 1 and 3 both ask one question: *given a motif and a position next to it, what does each of the four
bases score there?* `variant_profile` answers it — four motifs in, their support, depletion
score and background out. It reads the counts step 2 made (`scan_pattern`), so a variant is scored exactly as the
scan would have scored it, and a pattern is scanned at most once however many motifs need it.

In [ ]:
#| export
def variant_profile(motifs, pattern, encoded, fc, background, log2fc_thr, totals=None):
    """Support, depletion score and background for each of a set of related motifs.

    Read off the pattern's totals from `scan_pattern` -- the counts step 2 makes -- so a
    variant is scored exactly as it would have been had its pattern been scanned there.

    Args:
        motifs (list): motif strings, all of the same `pattern`.
        pattern (tuple): the `(d1, spacer, d2)` shape they share.
        encoded (tuple): `(fwd, rc)` from `encode_library`.
        fc (np.ndarray): log2 fold change per library sequence, in the same order.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`.
        log2fc_thr (float): a plasmid is depleted below this.
        totals (dict): totals by canonical pattern, for this library, `fc`, `background` and
            threshold. Shared across calls, it makes every pattern scanned at most once, and the
            patterns step 2 scanned never again. Filled in place.

    Returns:
        list: one `(motif, n_plasmids, score, background)` per motif, in the order given, the
        background being the carriers' mean. A motif that has no code (an IUPAC base, or a
        defined base in the spacer) gets `n=0` and `nan` for the other two.
    """
    totals = {} if totals is None else totals
    canon = canonical_pattern(pattern)
    if canon not in totals:
        totals[canon] = scan_pattern(encoded, canon, fc, background, log2fc_thr)
    n_seqs, n_depleted, _, bg_sum, _ = totals[canon]
    mirrored = pattern[1] != 0 and tuple(pattern) != canon    # spelled on the other strand
    rc_table = rc_code_table(canon) if pattern_is_self_rc(canon) else None
    out = []
    for m in motifs:
        code = encode_motif(revcomp(m) if mirrored else m, canon)
        if code is not None and rc_table is not None:
            code = min(code, int(rc_table[code]))             # the fold step 2 applied
        n = int(n_seqs[code]) if code is not None else 0
        out.append((m, n, float(n_depleted[code] / n) if n else float("nan"),
                    float(bg_sum[code] / n) if n else float("nan")))
    return out

In [ ]:
enc = encode_library(lib)

# CACNNNNGTA leaves the eleventh position undefined. What do the four bases score there?
for motif, n, s, b in variant_profile(["CACNNNNGTAA", "CACNNNNGTAC", "CACNNNNGTAG", "CACNNNNGTAT"],
                                      (3, 4, 4), enc, fcs, bg, -1):
    print(f"  {motif}  n={n:>4}  score={s:.3f}  background={b:.3f}")

  CACNNNNGTAA  n=  15  score=0.067  background=0.043
  CACNNNNGTAC  n=  20  score=1.000  background=0.043
  CACNNNNGTAG  n=  11  score=0.000  background=0.040
  CACNNNNGTAT  n= 192  score=1.000  background=0.044

Two of the four are dead and two are perfect. Whatever `CACNNNNGTA` scores as a whole, it is an
average over two populations, not one.

In [ ]:
#| hide
# Order is preserved, and a motif of a shape the encoder cannot express is reported as n=0
# rather than as a motif no plasmid carries.
_p = variant_profile(["GAGACC", "GGGGGG"], (6, 0, 0), enc, fcs, bg, -1)
test_eq([m for m, *_ in _p], ["GAGACC", "GGGGGG"])
test_eq(variant_profile(["CACNNNNGTAY"], (3, 4, 4), enc, fcs, bg, -1)[0][1], 0)
# The background is the mean over the variant's own carriers, exactly.
_has = motif_presence_matrix(enc, ["GAGACC"], [(6, 0, 0)])[0][:, 0]
test_eq(_p[0][3], bg[_has].sum() / _has.sum())

### Reading a profile

Four numbers have to become one word. A motif is a **mixture** of a site and a non-site when its
variants *split*: some fail the threshold the candidate itself had to pass, **and** the
variants are spread by at least that threshold.

Both halves are needed. Requiring only a failing variant would condemn any weak-but-real motif
that has one variant just the wrong side of the line; requiring only a spread would condemn a
strong motif whose variants merely differ. Variants carried by fewer than `min_support` plasmids
are not judged at all, and a motif with fewer than two judgeable variants gets `unknown` rather
than a guess.

In [ ]:
#| export
def verdict(profile, score_thr, min_support):
    """Call a variant profile 'mixture', 'genuine' or 'unknown'.

    Args:
        profile (list): `(motif, n, score, ...)` from `variant_profile`; only `n` and `score`
            are read.
        score_thr (float): the depletion score a candidate had to reach to be here.
        min_support (int): a variant on fewer plasmids than this is not judged.

    Returns:
        tuple: the verdict, and the spread across judgeable variants (`None` when fewer than
        two can be judged).
    """
    judged = [p[2] for p in profile if p[1] >= min_support]
    if len(judged) < 2:
        return "unknown", None
    spread = max(judged) - min(judged)
    split = any(s < score_thr for s in judged) and spread >= score_thr
    return ("mixture" if split else "genuine"), spread

In [ ]:
# Four real profiles, one per case the rule has to get right.
mixture = [("a", 15, 0.07), ("c", 20, 1.00), ("g", 11, 0.00), ("t", 192, 1.00)]
weak    = [("a", 77, 0.506), ("c", 53, 0.679), ("g", 62, 0.468), ("t", 110, 0.564)]
strong  = [("a", 555, 0.654), ("c", 409, 0.677), ("g", 526, 0.755), ("t", 667, 0.705)]
thin    = [("a", 4, 1.0), ("c", 1, 1.0), ("g", 3, 1.0), ("t", 1, 1.0)]
for name, p in [("mixture", mixture), ("weak", weak), ("strong", strong), ("thin", thin)]:
    v, spread = verdict(p, 0.5, 5)
    print(f"  {name:8s} {v:8s} spread={'  —' if spread is None else f'{spread:.3f}'}")

  mixture  mixture  spread=1.000
  weak     genuine  spread=0.211
  strong   genuine  spread=0.101
  thin     unknown  spread=  —

`weak` is the case that decides the design. One of its variants scores 0.468, below the 0.5
threshold — but all four sit within 0.21 of each other, so there is no population of non-sites
hiding inside it. It stays. `mixture` separates by a full 1.0 and goes.

`thin` cannot be judged: fewer than two of its variants reach `min_support`. That is `unknown`,
not a verdict either way, and it matters to rule 2 below.

In [ ]:
#| hide
test_eq(verdict(mixture, 0.5, 5)[0], "mixture")
test_eq(verdict(weak, 0.5, 5)[0], "genuine")      # a failing variant alone is not enough
test_eq(verdict(strong, 0.5, 5)[0], "genuine")
test_eq(verdict(thin, 0.5, 5)[0], "unknown")      # nothing with enough plasmids to judge
test_eq(round(verdict(mixture, 0.5, 5)[1], 3), 1.0)
test_eq(round(verdict(weak, 0.5, 5)[1], 3), 0.211)
# Exactly one judgeable variant is still 'unknown': a spread needs two numbers.
test_eq(verdict([("a", 99, 0.1), ("c", 1, 1.0)], 0.5, 5)[0], "unknown")

### The positions next to a motif

A motif is tested where one more defined base could go: one base out beyond each end, and the
spacer position next to each half. `_undefined_positions` lists them, each with its four variants
and their pattern. A position in the middle of a long spacer is skipped — fixing it would leave two
gaps, which is not a shape any described recognition site has, nor one `(d1, spacer, d2)` can
write.

These are also the only positions a one-base extension can add its base at, which is what ties
rules 1 and 2 together.

In [ ]:
#| export
def _undefined_positions(motif, pattern):
    """Each undefined position worth testing on a candidate, as (four variants, their pattern)."""
    d1, spacer, d2 = pattern
    width = d1 + spacer + d2
    jobs = [([b + motif for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1 + 1, spacer, d2)),
            ([motif + b for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1, spacer, d2 + 1))]
    if spacer:
        p = d1
        jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"],
                     (d1 + 1 + d2, 0, 0) if spacer == 1 else (d1 + 1, spacer - 1, d2)))
        if spacer > 1:
            p = d1 + spacer - 1
            jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"], (d1, spacer - 1, d2 + 1)))
    return jobs

In [ ]:
# NATACNNNNGTGN: four positions to test, each giving a different pattern.
for variants, vpat in _undefined_positions("ATACNNNNGTG", (4, 4, 3)):
    print(f"  {vpat}  {variants[0]}")

# A contiguous motif has no spacer, so only the two ends are testable.
print()
for variants, vpat in _undefined_positions("GGTCTC", (6, 0, 0)):
    print(f"  {vpat}  {variants[0]}")

  (5, 4, 3)  AATACNNNNGTG
  (4, 4, 4)  ATACNNNNGTGA
  (5, 3, 3)  ATACANNNGTG
  (4, 3, 4)  ATACNNNAGTG

  (7, 0, 0)  AGGTCTC
  (7, 0, 0)  GGTCTCA

In [ ]:
#| hide
# Every variant really is of the pattern it is labelled with, and the four differ at one position.
for m, pat in [("ATACNNNNGTG", (4, 4, 3)), ("GGTCTC", (6, 0, 0)), ("ACANAGG", (3, 1, 3))]:
    for variants, vpat in _undefined_positions(m, pat):
        test_eq(len(variants), 4)
        test_eq({len(v) for v in variants}, {sum(vpat)})
        test_eq(len({v for v in variants}), 4)
        d1, sp, d2 = vpat
        for v in variants:
            test_eq(v[d1:d1 + sp], "N" * sp)        # the gap is where the pattern says it is
            assert "N" not in v[:d1] + v[d1 + sp:]  # and nowhere else
test_eq(len(_undefined_positions("GGTCTC", (6, 0, 0))), 2)       # no spacer: two ends only
test_eq(len(_undefined_positions("ACANAGG", (3, 1, 3))), 3)      # a 1-base spacer: one position
test_eq(len(_undefined_positions("ATACNNNNGTG", (4, 4, 3))), 4)  # a wide spacer: both edges

### Rule 1: a mixture is not a site

`is_mixture` scores the four bases at each position next to a motif and reads the verdict. One
position that splits is enough: the motif is a site averaged with sequences that are not sites,
and it goes.

The example is a shadow in a different register. This strain's Type I site is `ATACNNNNGTG`,
pattern `(4, 4, 3)` — the spelling it is *reported* under; the scan found it as `CACNNNNGTAT` of
pattern `(3, 4, 4)`, and reporting put it on its canonical strand, the pattern following the motif.
That is why a reported pattern can be one `flexible_motif_patterns` never contains. The scan also
returns `ATANNNNTGTG`, pattern `(3, 4, 4)`: the same stretch of DNA with its gap one base to the
left. Neither string contains the other, so it is no one's extension and rule 2 cannot touch it,
although both describe mostly the same 190 plasmids. Rule 1 separates them:

In [ ]:
#| export
def is_mixture(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
               score_thr=0.5, min_support=5, totals=None):
    """Does fixing one position next to this motif split its carriers into sites and non-sites?

    Args:
        motif (str): the candidate.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library (tuple): `(fwd, rc)` from `encode_library`.
        fc_values (np.ndarray): log2 fold change per library sequence.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`. The verdict compares the variants with each other and does not
            read it; it completes the totals of a pattern scanned here, which rule 3 shares.
        log2fc_thr (float), score_thr (float), min_support (int): as elsewhere in the step.
        totals (dict): shared pattern totals, as for `variant_profile`.

    Returns:
        bool: True when some position's four bases split.
    """
    for variants, vpat in _undefined_positions(motif, pattern):
        if sum(vpat) > encoded_library[0].shape[1]:  # the padded motif is wider than the insert
            continue
        if verdict(variant_profile(variants, vpat, encoded_library, fc_values, background,
                                   log2fc_thr, totals), score_thr, min_support)[0] == "mixture":
            return True
    return False

In [ ]:
for motif, pat in [("ATANNNNTGTG", (3, 4, 4)), ("ATACNNNNGTG", (4, 4, 3))]:
    print(f"{motif}  {pat}   is_mixture = {is_mixture(motif, pat, enc, fcs, bg, -1, 0.7, 3)}")
    for variants, vpat in _undefined_positions(motif, pat):
        prof = variant_profile(variants, vpat, enc, fcs, bg, -1)
        v, spread = verdict(prof, 0.7, 3)
        cells = "  ".join(f"{s:.2f}({n})" if n else "  -- (0)" for _, n, s, _ in prof)
        print(f"   {str(vpat):10s} {v:8s} "
              f"spread={'   —' if spread is None else f'{spread:.2f}'}   {cells}")
    print()

ATANNNNTGTG  (3, 4, 4)   is_mixture = True
   (4, 4, 4)  mixture  spread=0.74   0.99(190)  0.33(3)  0.25(4)    -- (0)
   (3, 4, 5)  genuine  spread=0.07   1.00(53)  0.93(45)  0.95(56)  0.98(43)
   (4, 3, 4)  mixture  spread=1.00   0.20(5)  1.00(189)  0.00(3)    -- (0)
   (3, 3, 5)  genuine  spread=0.49   0.00(2)    -- (0)  0.99(189)  0.50(6)

ATACNNNNGTG  (4, 4, 3)   is_mixture = False
   (5, 4, 3)  unknown  spread=   —   1.00(189)  1.00(1)  1.00(1)  1.00(1)
   (4, 4, 4)  genuine  spread=0.00   1.00(54)  1.00(44)  1.00(53)  1.00(41)
   (5, 3, 3)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)
   (4, 3, 4)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)

Pinning the base next to `ATANNNNTGTG`'s left half splits the plasmids that carry it in two: 190
at 0.99 against a handful at 0.33 and 0.25, a spread of 0.74. It is a real site averaged with
sequences that are not sites, and it goes.

The real site has nothing to split. Every base at its one judgeable position scores exactly 1.00,
on 41 to 54 plasmids each — a spread of zero. The other three positions fall below `min_support`
and are not judged, which is `unknown`, not a verdict against it.

### Rule 2: a one-base extension of a site is redundant

A motif that survived rule 1 has nothing to split at any position next to it. So a candidate that is
that motif plus one defined base adds nothing: its extra base sits at one of those positions, and
rule 1 scored all four bases there and found they carry no information.

`is_extension` recognises such a pair on either strand. Every pattern is searched in one canonical
form, so adding a base to a motif's longer side can turn its shape into the mirror form, which the
scan writes on the other strand — `TACNNNNGTGA` is `CACNNNNGTA` with a base added on the left.

The filter does not test every pair. `parent_motifs` turns the question round: a candidate names
the four motifs it could be an extension of, and the filter looks those up among the survivors.

When the four bases are too thin to judge — `thin` above — rule 1 does not flag the shorter motif,
and rule 2 drops the extension: with no evidence that the extra base matters, the simpler
description is kept.

In [ ]:
#| export
def is_extension(specific, general):
    """Is `specific` the motif `general` with one more defined base, on either strand?

    The extra base sits one past an end of `general` or at an edge of its spacer -- the
    positions `_undefined_positions` tests. Both strands are checked because every pattern is
    searched in one canonical form, so adding a base to a motif's longer side can turn its shape
    into the mirror form, which the scan writes on the other strand: `TACNNNNGTGA` is
    `CACNNNNGTA` with a base added on the left.
    """
    defined = lambda m: len(m) - m.count("N")
    return defined(specific) == defined(general) + 1 and find_broad_in_specific(specific, general)

In [ ]:
#| export
def motif_shape(motif):
    """`(trimmed motif, pattern)`, or None when the string is not a `(d1, spacer, d2)` motif.

    Leading and trailing `N` are not part of a motif, and a string with two gaps is not a shape
    any pattern can express.
    """
    motif = motif.strip("N")
    if not motif:
        return None
    runs = re.findall(r"N+|[^N]+", motif)
    if len(runs) == 1:
        return motif, (len(motif), 0, 0)
    if len(runs) == 3:
        return motif, (len(runs[0]), len(runs[1]), len(runs[2]))
    return None


def parent_motifs(motif, pattern):
    """Every motif `motif` could be a one-base extension of.

    The inverse of `_undefined_positions`: the base it adds sits at an end or at a spacer edge,
    so giving up one of those four bases recovers the motif it extends. Checking these against
    the candidates is the same question as `is_extension` against every shorter candidate, at a
    handful of lookups instead of a comparison per pair.

    Returns the motif strings, without their patterns -- a caller matching against a set of
    candidate strings does not need them.
    """
    d1, spacer, d2 = pattern
    raw = [motif[1:], motif[:-1]]
    if spacer:
        raw.append(motif[:d1 - 1] + "N" + motif[d1:])                  # widen the gap leftwards
        raw.append(motif[:d1 + spacer] + "N" + motif[d1 + spacer + 1:])  # ... and rightwards
    out = []
    for s in raw:
        shaped = motif_shape(s)
        if shaped is not None and shaped[0] != motif:
            out.append(shaped[0])
    return sorted(set(out))

In [ ]:
#| hide
# parent_motifs is the inverse of is_extension: every motif it returns is one the candidate
# extends, and nothing else of that length is. Checked by brute force on the example library's
# own candidates, against the readable definition.
_cands = [("CACNNNNGTAT", (3, 4, 4)), ("TACNNNNGTGA", (3, 4, 4)), ("GGTCTCA", (7, 0, 0)),
          ("CACANNNGTAC", (4, 3, 4)), ("CCACNNNAGTA", (4, 3, 4)), ("AAGTNNNNTTAA", (4, 4, 4))]
_pool = sorted({m for m, _ in _cands} |
               {q for m, pt in _cands for q in parent_motifs(m, pt)} |
               {"GGTCTC", "CACNNNNGTA", "AAAGNNNNGTT", "CGGCCA"})
for _m, _pt in _cands:
    _by_lookup = {g for g in parent_motifs(_m, _pt) if g in _pool}
    _by_lookup |= {revcomp(g) for g in parent_motifs(_m, _pt) if revcomp(g) in _pool}
    _brute = {g for g in _pool if is_extension(_m, g)}
    test_eq(_by_lookup, _brute)
# an end base either way, and a spacer edge either way
test_eq(parent_motifs("CACNNNNGTAT", (3, 4, 4)),
        ["ACNNNNGTAT", "CACNNNNGTA", "CACNNNNNTAT", "CANNNNNGTAT"])
test_eq(parent_motifs("GGTCTCA", (7, 0, 0)), ["GGTCTC", "GTCTCA"])
# the notebook's rule-2 example: CACANNNGTAC extends CACNNNNGTAC
assert "CACNNNNGTAC" in parent_motifs("CACANNNGTAC", (4, 3, 4))
test_eq(motif_shape("NNCACNN"), ("CAC", (3, 0, 0)))
test_eq(motif_shape("CANNCANNCA"), None)          # two gaps: no pattern expresses it

In [ ]:
#| hide
test_eq(is_extension("CACNNNNGTAT", "CACNNNNGTA"), True)      # a base past the right end
test_eq(is_extension("TACNNNNGTGA", "CACNNNNGTA"), True)      # ... past the left, other strand
test_eq(is_extension("CCCCNNNNNTTTC", "CCCNNNNNNTTTC"), True)  # a spacer edge pinned
test_eq(is_extension("CACNNNNGTA", "CACNNNNGTA"), False)       # not more defined
test_eq(is_extension("CACANNNGTACC", "CACNNNNGTA"), False)     # two more defined bases
test_eq(is_extension("GGTCTCA", "CACNNNNGTA"), False)          # unrelated

`CACNNNNGTAC` passes rule 1. At the first position of its spacer, the four bases score alike:

In [ ]:
print("CACNNNNGTAC is a mixture:", is_mixture("CACNNNNGTAC", (3, 4, 4), enc, fcs, bg, -1, 0.7, 3))
for motif, n, s, _ in variant_profile([f"CAC{b}NNNGTAC" for b in "ACGT"], (4, 3, 4), enc, fcs, bg, -1):
    print(f"  {motif}  n={n:>3}  score={s:.2f}   extension of CACNNNNGTAC: "
          f"{is_extension(motif, 'CACNNNNGTAC')}")

CACNNNNGTAC is a mixture: False
  CACANNNGTAC  n=  4  score=1.00   extension of CACNNNNGTAC: True
  CACCNNNGTAC  n=  9  score=1.00   extension of CACNNNNGTAC: True
  CACGNNNGTAC  n=  4  score=1.00   extension of CACNNNNGTAC: True
  CACTNNNGTAC  n=  3  score=1.00   extension of CACNNNNGTAC: True

Every base scores 1.00, so the position carries nothing. The four are `CACNNNNGTAC` with a base
that says nothing more, and rule 2 drops them.

### Why rule 1 comes first

Take `CACNNNNGTA` again. Rule 1 found it a mixture: at the base past its right end `C` and `T`
deplete completely and `A` and `G` do not. And the two real sites, `CACNNNNGTAC` and
`CACNNNNGTAT`, are both extensions of it:

In [ ]:
print("CACNNNNGTA is a mixture:", is_mixture("CACNNNNGTA", (3, 4, 3), enc, fcs, bg, -1, 0.7, 3))
for site in ["CACNNNNGTAC", "CACNNNNGTAT"]:
    print(f"  {site} is an extension of CACNNNNGTA: {is_extension(site, 'CACNNNNGTA')}")

CACNNNNGTA is a mixture: True
  CACNNNNGTAC is an extension of CACNNNNGTA: True
  CACNNNNGTAT is an extension of CACNNNNGTA: True

In the order used here, rule 1 removes `CACNNNNGTA`; the two sites then have no surviving motif to
be an extension of, and they stay. Run rule 2 first, against every candidate, and both sites go as
extensions of `CACNNNNGTA` — then rule 1 removes `CACNNNNGTA` itself, and the strain's Type I site
has disappeared.

Within each rule the order does not matter — rule 1 judges each motif alone, and rule 2 compares
against the fixed set of rule-1 survivors — so the result never depends on the order the candidates
arrive in.

### Rule 3: a motif with an uninformative base is not the site

Rule 2 removes a motif that is a site plus one base, but only when that site is itself a
candidate. When the shorter motif fell short of the thresholds, nothing removes the longer one —
and a longer motif can clear a threshold its parent missed simply because the extra base happens
to pick out the most depleted of the parent's carriers.

Rule 3 asks the question from the other side. Put N back at one of a candidate's defined bases and
score the four bases there: if every other base behaves like the site, the candidate's base carries
no information, and the candidate is an over-specified description of something more general.

"Behaves like the site" is decided per base by comparing two models of its carriers: depleted at
the site's rate, or at their background — the mean `plasmid_background` of that base's own
carriers, the null the scan's p-values use. Each base gets its own because the base itself moves
it: on a sample where AT-rich inserts deplete more, an A or a T at the position makes its carriers
more AT-rich. The log-likelihood ratio says which model fits better, and it grows with the number
of plasmids, so it is also the confidence; a base is classified only when one model fits ten times
better. Two simpler criteria fail on real data. A fixed cut-off between the
two rates puts the boundary in the wrong place: the binomial's own crossing point depends on both
rates. And a significance test against background calls any excess site-like — with hundreds of
plasmids per base, a base depleted at four times background but a quarter of the site's rate is
"significant", and a real site would be dropped.

The site's rate starts as the candidate's own and is then re-estimated from the candidate pooled
with the bases first found site-like. The candidate was selected for scoring high, so its own rate
overstates the site's — which would make the other bases look less site-like than they are, and
keep exactly the lucky extensions this rule is for.

`classify_positions` classifies the bases at several positions of a motif at once. Rule 3 drops the
motif when, at one of them, every other base is site-like. Reporting asks the same question of a
call and acts when only *some* are: the position is degenerate, and the site is written as one
IUPAC motif (below).

In [ ]:
#| export
def relax_positions(motif, pattern):
    """The defined bases of `motif` that can be put back to N, leaving a valid pattern.

    Every base of a contiguous motif -- an interior one becomes a one-base spacer -- and, for a
    gapped motif, the outer base and the spacer-side base of each half, as long as the half keeps
    a defined base. These are the positions rule 1 tests from the other side.
    """
    d1, spacer, d2 = pattern
    if spacer == 0:
        return list(range(len(motif)))
    positions = set()
    if d1 >= 2:
        positions |= {0, d1 - 1}
    if d2 >= 2:
        positions |= {d1 + spacer, len(motif) - 1}
    return sorted(positions)


LR_THRESHOLD = 10   # a set of plasmids is classified when one model fits it this many times better


def site_or_background(n, k, site_rate, background_rate):
    """'site', 'non-site' or 'unknown' for a set of `n` plasmids of which `k` are depleted.

    Compares two models of them -- depleted at `site_rate`, or at `background_rate` -- by their
    log-likelihood ratio, which grows with `n`, so it is also the confidence: the set is
    classified only when one model fits `LR_THRESHOLD` times better. Rates must lie strictly
    between 0 and 1; a site rate no higher than background gives 'unknown'.
    """
    if site_rate <= background_rate:
        return "unknown"
    llr = (k * np.log(site_rate / background_rate)
           + (n - k) * np.log((1 - site_rate) / (1 - background_rate)))
    cut = np.log(LR_THRESHOLD)
    return "site" if llr > cut else "non-site" if llr < -cut else "unknown"


def classify_bases(profile, motif, min_support):
    """'site', 'non-site' or 'unknown' for each base other than `motif`'s at one position.

    Each base's carriers are compared under two models -- depleted at the site's rate, or at
    their own background -- by their log-likelihood ratio. The site's rate is the candidate's
    own, re-estimated once from the candidate pooled with the bases first classified site-like.

    Args:
        profile (list): `(motif, n, score, background)` for the four bases, from
            `variant_profile`.
        motif (str): the candidate, one of the four.
        min_support (int): a base carried by fewer plasmids is not classified.

    Returns:
        dict: other motif -> class, for those with at least `min_support` carriers; `None` when
        the candidate itself has too few.
    """
    own = next((p for p in profile if p[0] == motif), None)
    if own is None or own[1] < min_support:
        return None
    others = [p for p in profile if p[0] != motif and p[1] >= min_support]
    clip = lambda rate, n: min(max(rate, 0.5 / n), 1 - 0.5 / n)   # keep the logs finite

    def classify(site_rate):
        return {m: site_or_background(n, round(s * n), site_rate, b) for m, n, s, b in others}

    first = classify(clip(own[2], own[1]))
    pooled = [own] + [p for p in others if first[p[0]] == "site"]
    n = sum(p[1] for p in pooled)
    return classify(clip(sum(p[1] * p[2] for p in pooled) / n, n))


def classify_positions(motif, positions, pattern, encoded_library, fc_values, background,
                       log2fc_thr=-1, min_support=5, totals=None):
    """For each position, the class and carriers of every base `motif` does not allow there.

    At position `i`, each base `motif` does not allow gives a variant -- `motif` with that base at
    `i` -- and `classify_bases` classifies it against `motif`. A motif of A, C, G and T is profiled
    from the scan's counts (`variant_profile`); a motif with an IUPAC letter is profiled on the
    carriers of its instances (`_union_profile`).

    Args:
        motif (str): the candidate, IUPAC letters allowed at its defined positions.
        positions (list): defined positions of `motif` to classify.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library, fc_values, background, log2fc_thr, min_support, totals: as for
            `is_mixture`.

    Returns:
        dict: position -> {base: (class, n carriers)}, for the bases with at least `min_support`
        carriers; empty at every position when `motif` itself has fewer.
    """
    alts = {i: [motif[:i] + b + motif[i + 1:] for b in "ACGT" if b not in IUPAC_EXPAND[motif[i]]]
            for i in positions}
    motifs = [motif] + [v for vs in alts.values() for v in vs]
    if encode_motif(motif, pattern) is not None:          # A, C, G and T only: the scan's counts
        profile = variant_profile(motifs, pattern, encoded_library, fc_values, background,
                                  log2fc_thr, totals)
    else:
        profile = _union_profile(motifs, pattern, encoded_library, fc_values, background,
                                 log2fc_thr)
    stats = dict(zip(motifs, profile))
    out = {}
    for i, vs in alts.items():
        classes = classify_bases([profile[0]] + [stats[v] for v in vs], motif, min_support) or {}
        out[i] = {v[i]: (classes[v], stats[v][1]) for v in vs if v in classes}
    return out


def is_over_specified(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
                      min_support=5, totals=None):
    """Does `motif` have a defined base at which every other base behaves like the site?"""
    by_position = classify_positions(motif, relax_positions(motif, pattern), pattern,
                                     encoded_library, fc_values, background, log2fc_thr,
                                     min_support, totals)
    return any(classes and all(c == "site" for c, _ in classes.values())
               for classes in by_position.values())

In [ ]:
#| hide
test_eq(relax_positions("GGTCTC", (6, 0, 0)), [0, 1, 2, 3, 4, 5])
test_eq(relax_positions("CACNNNNGTAC", (3, 4, 4)), [0, 2, 7, 10])
test_eq(relax_positions("CANNNNGTAC", (2, 4, 4)), [0, 1, 6, 9])
# The two panel cases the criterion was chosen on. A real site whose other bases sit at four
# times background but a quarter of the site's rate: informative, keep.
_p = [("A", 653, 0.254, 0.058), ("C", 452, 0.991, 0.058), ("G", 475, 0.242, 0.058), ("T", 840, 0.252, 0.058)]
test_eq(set(classify_bases(_p, "C", 5).values()), {"non-site"})
# A lucky extension: every other base well above background -- uninformative, drop.
_p = [("A", 299, 0.388, 0.079), ("C", 256, 0.277, 0.079), ("G", 219, 0.516, 0.079), ("T", 251, 0.410, 0.079)]
test_eq(set(classify_bases(_p, "G", 5).values()), {"site"})
# A degenerate position (YGGCCR's Y): one other base is a site, two are not -- informative.
_p = [("A", 255, 0.082, 0.079), ("C", 219, 0.516, 0.079), ("G", 267, 0.105, 0.079), ("T", 310, 0.394, 0.079)]
test_eq(classify_bases(_p, "C", 5), {"A": "non-site", "G": "non-site", "T": "site"})
# Each base against its own carriers' background: a T depleting at 0.40 beside a site at 0.50 is
# site-like when its carriers' background is 0.08, and not when they deplete at 0.35 anyway.
test_eq(classify_bases([("C", 300, 0.5, 0.08), ("T", 300, 0.40, 0.08)], "C", 5), {"T": "site"})
test_eq(classify_bases([("C", 300, 0.5, 0.08), ("T", 300, 0.40, 0.35)], "C", 5), {"T": "non-site"})
# classify_positions is classify_bases on each position's profile, keyed by base, with each base's
# carriers: at CACNNNNGTAC's last base T is site-like (CACNNNNGTAT, 192 carriers), A and G are not.
_cls = classify_positions("CACNNNNGTAC", [10], (3, 4, 4), enc, fcs, bg, -1, 3)[10]
_prof = variant_profile(["CACNNNNGTA" + b for b in "ACGT"], (3, 4, 4), enc, fcs, bg, -1)
test_eq({b: c for b, (c, _) in _cls.items()},
        {m[-1]: c for m, c in classify_bases(_prof, "CACNNNNGTAC", 3).items()})
test_eq(_cls["T"], ("site", 192))
# Too few carriers: nothing to classify with.
test_eq(classify_bases([("A", 2, 1.0, .05), ("C", 3, 1.0, .05), ("G", 1, 1.0, .05), ("T", 2, 1.0, .05)], "C", 5), None)
# the shared test on its own: confidence grows with the number of plasmids
test_eq(site_or_background(4, 4, 0.99, 0.08), "site")
test_eq(site_or_background(4, 1, 0.667, 0.25), "unknown")      # too few to tell
test_eq(site_or_background(40, 10, 0.667, 0.25), "non-site")
test_eq(site_or_background(10, 9, 0.2, 0.3), "unknown")       # a 'site' no more depleted than background

On this library, `CCACNNNAGTA` — a shadow of the strain's Type I site that rules 1 and 2 both let
through — against `CACNNNNGTAC`, a real site:

In [ ]:
for motif, pat in [("CCACNNNAGTA", (4, 3, 4)), ("CACNNNNGTAC", (3, 4, 4))]:
    print(f"{motif}  over-specified: {is_over_specified(motif, pat, enc, fcs, bg, -1, 3)}")
    for i in relax_positions(motif, pat):
        prof = variant_profile([motif[:i] + b + motif[i + 1:] for b in "ACGT"], pat, enc, fcs, bg, -1)
        cls = classify_bases(prof, motif, 3) or {}
        cells = "  ".join(f"{m[i]}:{s:.2f}({n})" + ("" if m == motif else f"={cls.get(m, '-')[:4]}")
                          for m, n, s, _ in prof)
        print(f"   position {i:>2}  {cells}")

CCACNNNAGTA  over-specified: True
   position  0  A:0.95(42)=site  C:1.00(55)  G:1.00(45)=site  T:0.92(60)=site
   position  3  A:0.00(27)=non-  C:1.00(55)  G:0.00(70)=non-  T:0.00(40)=non-
   position  7  A:1.00(55)  C:0.50(2)=-  G:0.00(5)=non-  T:1.00(3)=site
   position 10  A:1.00(55)  C:0.00(1)=-  G:0.00(5)=non-  T:0.00(5)=non-
CACNNNNGTAC  over-specified: False
   position  0  A:0.08(60)=non-  C:1.00(20)  G:0.00(17)=non-  T:0.06(54)=non-
   position  2  A:0.04(23)=non-  C:1.00(20)  G:0.00(24)=non-  T:0.05(21)=non-
   position  7  A:0.03(29)=non-  C:0.08(13)=non-  G:1.00(20)  T:0.10(29)=non-
   position 10  A:0.07(15)=non-  C:1.00(20)  G:0.00(11)=non-  T:1.00(192)=site

At `CCACNNNAGTA`'s first base all four bases deplete almost completely — the C carries nothing, and
the motif goes. `CACNNNNGTAC` has no such position: at every one, the other bases deplete at
background. Its last position is worth a second look: `C` and `T` both deplete fully, `A` and `G`
not at all. That is a degenerate position — the strain's two Type I motifs, `CACNNNNGTAC` and
`CACNNNNGTAT` (reported as `ATACNNNNGTG`), behave like one site, `CACNNNNGTAY` — and it is why a
position counts as uninformative only when *every* other base is site-like. The pipeline reports
that site as one motif once its variants are called (*A degenerate site is one motif*, below).

On the 21-strain BB2 panel this rule removes one of the draft's Fig 3 calls, ECOR64's `GCGGCCA`: at the defaults, the
other three bases at its first position deplete at 0.61, 0.52 and 0.61 against backgrounds of 0.17
(`GCGGCCA` itself at 0.70), so the extra G carries nothing. The strain's real site, `YGGCCR`, is
too weakly restricting for a −1 threshold; at −0.5 its three concrete variants are called and
reported as `YGGCCR`.

### The filter

`filter_redundant_patterns` applies the three rules in that order. Rule 2 is a handful of lookups
per candidate and rule 3 reads patterns the scan already counted, so the filter stays linear in the
number of candidates — which matters at a permissive threshold, where a strain can produce
hundreds of thousands of them.

In [ ]:
#| export
def _patterns(df):
    """The 'pattern' column as `(d1, spacer, d2)` tuples; None where it is missing or unreadable."""
    if "pattern" not in df.columns:
        return [None] * len(df)
    out = []
    for p in df["pattern"]:
        try:
            out.append(tuple(ast.literal_eval(p) if isinstance(p, str) else p) or None)
        except (ValueError, SyntaxError, TypeError):
            out.append(None)
    return out


def motif_instances(motif, pattern):
    """The motifs of A, C, G and T that `motif` stands for: every IUPAC letter at a defined position
    expanded, the spacer left as it is."""
    d1, spacer, _ = pattern
    gap = range(d1, d1 + spacer)
    choices = [c if i in gap else sorted(IUPAC_EXPAND[c]) for i, c in enumerate(motif)]
    return ["".join(t) for t in product(*choices)]


def _instance_presence(encoded, motifs, patterns):
    """`motif_presence_matrix` for motifs with IUPAC letters: a plasmid carries a motif when it
    carries one of its instances (`motif_instances`), on either strand. Returns `(matrix, handled)`;
    a motif whose pattern is unknown, or which does not fit it, is not handled."""
    inst = [motif_instances(m, p) if p is not None else [] for m, p in zip(motifs, patterns)]
    # Each distinct instance is looked up once, however many motifs share it.
    keys = list(dict.fromkeys((x, p) for xs, p in zip(inst, patterns) for x in xs))
    col = {k: j for j, k in enumerate(keys)}
    has, ok = motif_presence_matrix(encoded, [x for x, _ in keys], [p for _, p in keys])
    presence = np.zeros((encoded[0].shape[0], len(motifs)), dtype=bool)
    handled = np.zeros(len(motifs), dtype=bool)
    for j, (xs, p) in enumerate(zip(inst, patterns)):
        cols = [col[(x, p)] for x in xs]
        if cols and ok[cols].all():
            presence[:, j] = has[:, cols].any(axis=1)
            handled[j] = True
    return presence, handled


def _carriers(encoded, motifs, patterns, log2fc_series, left_context, right_context):
    """Boolean (n_sequences, n_motifs): which plasmids carry each motif, on either strand.

    Read from the window codes of each motif's instances (`_instance_presence`); a motif whose
    pattern is unknown falls back to a regex over the sequences with their flanks.
    """
    presence, handled = _instance_presence(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()
    return presence

In [ ]:
# A motif with IUPAC letters stands for every motif of A, C, G and T it allows; the spacer stays N.
motif_instances("RTACNNNNGTG", (4, 4, 3))

['ATACNNNNGTG', 'GTACNNNNGTG']

In [ ]:
#| hide
test_eq(motif_instances("YGGCCR", (6, 0, 0)), ["CGGCCA", "CGGCCG", "TGGCCA", "TGGCCG"])
test_eq(motif_instances("RTACNNNNGTG", (4, 4, 3)), ["ATACNNNNGTG", "GTACNNNNGTG"])
test_eq(motif_instances("GGTCTC", (6, 0, 0)), ["GGTCTC"])

In [ ]:
#| hide
# Patterns come back as tuples whether stored as tuples or as strings; garbage becomes None.
test_eq(_patterns(pd.DataFrame({"pattern": ["(6, 0, 0)", (3, 4, 4), "junk", None]})),
        [(6, 0, 0), (3, 4, 4), None, None])
test_eq(_patterns(pd.DataFrame({"motif": ["GGTCTC"]})), [None])
# Carriers on either strand: GGTCTC is read as GAGACC in the second sequence. A motif without a
# pattern takes the regex path and must agree.
_s = pd.Series([0.0, 0.0, 0.0], index=["GGTCTCAA", "TTGAGACC", "TTTTTTTT"])
_pr = _carriers(encode_library(_s.index.tolist()), ["GGTCTC", "GGTCTY"], [(6, 0, 0), None],
                _s, "", "")
test_eq(_pr.tolist(), [[True, True], [True, True], [False, False]])
# A motif with IUPAC letters is carried where one of its instances is: on the 20 nt library this is
# exactly the regex over the sequences with their flanks, including for the palindromic YGGCCR,
# whose instances CGGCCA and TGGCCG are one site read on its two strands.
_ms, _ps = ["YGGCCR", "RTACNNNNGTG", "CCTHAGG", "GGTCTC"], [(6, 0, 0), (4, 4, 3), (7, 0, 0), (6, 0, 0)]
_u = _carriers(enc, _ms, _ps, log2fc_df["JJ1886_T0"], left, right)
for j, m in enumerate(_ms):
    test_eq(_u[:, j], _get_filter_for_motif(log2fc_df["JJ1886_T0"], m, left, right).to_numpy())
test_eq(_instance_presence(enc, _ms, _ps)[1].all(), True)      # none of them took the regex path

In [ ]:
#| export
def filter_redundant_patterns(df, log2fc_series, left_context, right_context,
                              log2fc_thr=-1, score_thr=0.5, min_support=5,
                              encoded=None, totals=None, background=None):
    """Keep one description per site, by three rules.

    1. **A mixture is not a site.** A candidate is dropped when fixing one position next to it
       splits the plasmids that carry it into depleting and not (`is_mixture`).
    2. **A one-base extension of a site is redundant.** A candidate is dropped when it is a
       candidate that survived rule 1 with one more defined base (`is_extension`, applied by
       looking up `parent_motifs`): rule 1 found that site's neighbouring positions carry
       nothing, so pinning one adds nothing.
    3. **A motif with an uninformative base is not the site.** A candidate is dropped when, at one
       of its defined bases, every other base behaves like the site (`is_over_specified`).

    No rule depends on the order the candidates arrive in.

    Args:
        df (pd.DataFrame): candidates, with 'motif' and 'pattern'.
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence.
        left_context (str), right_context (str): the vector flanks.
        log2fc_thr (float): a plasmid is depleted below this.
        score_thr (float): the score a candidate had to reach, reused as the bar a variant must
            clear and as the spread that marks a profile a mixture.
        min_support (int): a variant on fewer plasmids than this is not judged.
        encoded (tuple): the library from `encode_library`, if the caller already has it.
        totals (dict): shared pattern totals, as for `variant_profile`.
        background (np.ndarray): each plasmid's expected depletion rate; `plasmid_background` of
            `log2fc_series` when not given.

    Returns:
        pd.DataFrame: `df` without the redundant rows, in the original row order.
    """
    if df.empty:
        return df
    motifs = df["motif"].tolist()
    pats = _patterns(df)
    if encoded is None:
        encoded = encode_library(get_lib_seq_context(log2fc_series.index.tolist(),
                                                     left_context, right_context))
    totals = {} if totals is None else totals
    fc = log2fc_series.to_numpy()
    if background is None:
        background = plasmid_background(log2fc_series.index, fc, log2fc_thr)

    # Rule 1. A candidate whose pattern is unknown cannot be tested, and stays.
    survivors = [k for k in range(len(df)) if pats[k] is None or not is_mixture(
        motifs[k], pats[k], encoded, fc, background, log2fc_thr, score_thr, min_support, totals)]

    # Rule 2, by lookup rather than by comparing pairs: each survivor asks whether any of the
    # four motifs it could extend is itself a survivor. Comparing every pair is quadratic, and
    # at a permissive threshold a strain can reach hundreds of thousands of candidates.
    standing = {motifs[k] for k in survivors}
    standing |= {revcomp(m) for m in standing}      # a parent may be spelled on the other strand
    keep = [k for k in survivors
            if not any(g in standing for g in parent_motifs(motifs[k], pats[k]))]

    # Rule 3. Every variant it reads is in the candidate's own pattern, which step 2 counted.
    keep = [k for k in keep if pats[k] is None or not is_over_specified(
        motifs[k], pats[k], encoded, fc, background, log2fc_thr, min_support, totals)]
    return df.iloc[keep]

Six patterns over the example library, wide enough for both rules to have work to do:

In [ ]:
pats = [(6, 0, 0), (7, 0, 0), (3, 4, 3), (3, 4, 4), (4, 3, 4), (4, 4, 4)]
enc = encode_library(lib)
candidates_demo = pd.concat([process_single_flexible_pattern(p, enc, fcs, bg, -1, 0.7, 3)[0] for p in pats],
                            ignore_index=True)
_pat = lambda s: tuple(int(x) for x in s.strip("()").split(","))
mixtures = [m for m, p in zip(candidates_demo.motif, candidates_demo.pattern)
            if is_mixture(m, _pat(p), enc, fcs, bg, -1, 0.7, 3)]
rows = list(candidates_demo.itertuples())
surv = [r for r in rows if r.motif not in mixtures]
after2 = [r for r in surv if not any(is_extension(r.motif, o.motif) for o in surv)]
kept = filter_redundant_patterns(candidates_demo, log2fc_df["JJ1886_T0"], left, right,
                                 log2fc_thr=-1, score_thr=0.7, min_support=3)
print(f"{len(candidates_demo)} candidates: rule 1 drops {len(mixtures)} mixtures, rule 2 drops "
      f"{len(surv) - len(after2)} extensions, rule 3 drops {len(after2) - len(kept)} "
      f"over-specified motifs, {len(kept)} go on to step 4")
kept.sort_values("num_sequences", ascending=False)[["motif", "pattern", "fraction_depleted",
                                                    "num_sequences"]].head(8)

74 candidates: rule 1 drops 12 mixtures, rule 2 drops 24 extensions, rule 3 drops 6 over-specified motifs, 32 go on to step 4

           motif    pattern  fraction_depleted  num_sequences
14   CACNNNNGTAT  (3, 4, 4)           1.000000            192
51  AATANNNNTGTG  (4, 4, 4)           0.989474            190
12   AACNNNNCTTT  (3, 4, 4)           1.000000             63
17   CACNNNNGTAC  (3, 4, 4)           1.000000             20
1         GAGACC  (6, 0, 0)           1.000000              9
38   TGGCNNNCACA  (4, 3, 4)           0.714286              7
35   AAGTNNNGTTA  (4, 3, 4)           0.833333              6
25   GAAGNNNACAC  (4, 3, 4)           0.800000              5

The survivors include the strain's sites, on whichever strand the scan read them: `CACNNNNGTAT`
(reported as `ATACNNNNGTG`), `AACNNNNCTTT` (`AAAGNNNNGTT`), `CACNNNNGTAC` and `GAGACC`. Beside
them sits `AATANNNNTGTG`, 0.99 depleted on 190 plasmids, because nearly every plasmid that carries
it also carries `ATACNNNNGTG`; the other 27 survivors are on seven plasmids or fewer. None of them
is a site plus one base: they are the site read in a different register or a different shape, so
no string rule relates them. That is step 4's question: whether the plasmids carrying each one
still deplete once those carrying a stronger motif are set aside.

In [ ]:
#| hide
_lib = pd.Series([-5.0, -5.0, 0.0], index=["GAGACCTT", "AAGAGACC", "TTTTTTTT"])
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# Unrelated motifs describe different plasmids, so both stand.
_t = pd.DataFrame({"motif": ["GGTCTC", "AAACNNNNGTC"], "fraction_depleted": [0.95, 0.80],
                   "pattern": ["(6, 0, 0)", "(4, 4, 3)"]})
test_eq(len(filter_redundant_patterns(_t, _lib, "", "", **_kw)), 2)

# Only N is a wildcard. A full IUPAC code is not treated as covering the bases it stands for,
# so these two are unrelated to this filter. The scan only ever emits N, so this bounds what the
# filter can be asked to do rather than describing what it sees.
test_eq(find_broad_in_specific("CACNNNNGTAC", "CACNNNNGTAY"), False)

## Step 4: drop candidates whose score was borrowed

Step 3 keeps one description per site. It cannot relate two descriptions of the *same* site in
**different shapes** — `ATACNNNNGTG` of pattern `(4, 4, 3)` and `CACANNAGTA` of pattern
`(4, 2, 4)` sit on mostly the same plasmids, but neither is the other with a position left
undefined, so no rule in step 3 can see that they are one answer. What separates them is what
each has that the other does not:

In [ ]:
_pair = ["ATACNNNNGTG", "CACANNAGTA"]
_has = _carriers(enc, _pair, [(4, 4, 3), (4, 2, 4)], log2fc_df["JJ1886_T0"], left, right)
_dep = fcs < -1
print(f"shared: {(_has[:, 0] & _has[:, 1]).sum()} plasmids")
for j, other in [(0, 1), (1, 0)]:
    alone = _has[:, j] & ~_has[:, other]
    print(f"{_pair[j]:<12} n={_has[:, j].sum()}  score {_dep[_has[:, j]].mean():.3f}   "
          f"without {_pair[other]}'s plasmids: n={alone.sum()}  score {_dep[alone].mean():.3f}")

shared: 188 plasmids
ATACNNNNGTG  n=192  score 1.000   without CACANNAGTA's plasmids: n=4  score 1.000
CACANNAGTA   n=192  score 0.990   without ATACNNNNGTG's plasmids: n=4  score 0.500

Set aside the plasmids carrying `ATACNNNNGTG` and `CACANNAGTA` falls from 0.99 to 0.50 — its
score was **borrowed**. Set aside those carrying `CACANNAGTA` and `ATACNNNNGTG` holds at 1.00.
That asymmetry is the test: a candidate is dropped when, restricted to the plasmids that carry
it but no stronger candidate, it no longer reaches the `score_thr` it had to pass in the first
place. The test is on the collapse, not on how much is left: both leftovers here are four
plasmids, and judging them by size would decide the pair on a score difference of 0.01, which is
not evidence about anything.

Candidates are tested strongest first — highest fraction depleted, then most plasmids — each
against the union of the survivors ranked above it. A shadow that ranks *above* the site it
shadows would escape that pass: on the BB2 panel ECOR64's `GGCCNNNNGGCC` is 67% depleted, more
than the `YGGCCR` variants it shadows (58–62%), and 73% of its carriers carry one of them. So
after the pass every survivor is tested once more against all the others, weakest first, one
removal at a time, and `GGCCNNNNGGCC` goes.

Clearing `score_thr` is not enough for a leftover of a few plasmids: one depleted out of two is
50%. So a leftover must also be depleted beyond its background — the mean background of the
leftover plasmids, the binomial null the calls are scored against — at the scan's own cutoff: the largest p-value that clears
`q_threshold` after Benjamini-Hochberg over every motif the scan tested. Every candidate was
selected from that pool, so correcting only over the few dozen that reach step 4 would forget
the selection.

On the six-pattern search of step 3:

In [ ]:
#| export
def filter_explained_candidates(candidates_df, log2fc_series, left_context, right_context,
                                log2fc_thr=-1, score_thr=0.7, min_support=3,
                                encoded=None, p_threshold=0.05, background=None):
    """Drop candidates whose depletion is fully accounted for by stronger candidates.

    Candidates are taken strongest first. Each `X` is restricted to the plasmids that carry
    **none** of the stronger candidates still standing; if what is left no longer reaches
    `score_thr`, or is not depleted beyond its own background at `p_threshold`, `X`'s score
    was borrowed and `X` is removed. Otherwise it stands, and the plasmids that carry it join the
    set later candidates are tested against.

    After the pass, every survivor is tested again against the union of *all* the others,
    weakest first, removing one at a time: the pass tests a candidate only against those ranked
    above it, and a shadow can rank above the site it shadows.

    Args:
        candidates_df: candidates, with 'motif' and (optionally) 'pattern' columns.
        log2fc_series: the full log2FC series, indexed by sequence.
        left_context, right_context: the vector sequence flanking the insert.
        log2fc_thr: a plasmid is depleted below this.
        score_thr: fraction of a candidate's leftover plasmids that must still be depleted.
        min_support: not used: a candidate's support was established when it became one.
            Accepted so the step takes the same thresholds as the rest of the pipeline.
        encoded: the library from `encode_library`, if the caller already has it.
        p_threshold: the leftover must also be depleted beyond its background -- the mean
            background of its plasmids -- at this p-value. `find_restricted_motifs` passes the
            scan's Benjamini-Hochberg cutoff.
        background: each plasmid's expected depletion rate; `plasmid_background` of
            `log2fc_series` when not given.

    Returns:
        (kept_df, explanations) where explanations maps a dropped motif to
        (explaining motif, plasmids left, score on them).
    """
    if len(candidates_df) < 2:
        return candidates_df, {}     # nothing that could explain anything

    motifs = candidates_df['motif'].tolist()
    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence = _carriers(encoded, motifs, _patterns(candidates_df), log2fc_series,
                         left_context, right_context)

    fc = log2fc_series.to_numpy()
    if background is None:
        background = plasmid_background(log2fc_series.index, fc, log2fc_thr)
    strength = []
    for j in range(len(motifs)):
        v = fc[presence[:, j]]
        strength.append(((v < log2fc_thr).mean() if len(v) else 0.0, len(v), motifs[j]))
    # Strongest first: highest depletion fraction, then MOST plasmids. Support breaks the tie, not
    # mean log2FC, because the plasmids carrying a shadow are a subset of those carrying its
    # parent, and the subset picked out by the extra bases it requires tends to be the most
    # depleted -- so on mean log2FC a shadow outranks the site it came from and is never tested
    # against it. A subset can never have more plasmids than the set it is drawn from. The motif
    # string is the final tie-break, so the outcome does not depend on row order.
    order = sorted(range(len(motifs)), key=lambda j: (-strength[j][0], -strength[j][1], strength[j][2]))

    # A leftover stands when it still reaches score_thr AND is depleted beyond its own
    # background -- the binomial null the calls are scored against, the rate being the mean
    # background of the leftover plasmids -- at the scan's own cutoff.
    def holds(alone):
        n = int(alone.sum())
        still = float((fc[alone] < log2fc_thr).mean()) if n else 0.0
        ok = n > 0 and still >= score_thr and \
            motif_pvalues([n], [still], background[alone].sum() / n)[0] <= p_threshold
        return ok, n, still

    explanations = {}
    # The test is against the UNION of the stronger survivors: a description that overlaps
    # several co-occurring sites can keep a depleted residue against each of them separately
    # although every plasmid that carries it carries one of them.
    covered = np.zeros(presence.shape[0], dtype=bool)
    standing = []                                        # survivors, strongest first
    for x in order:
        ok, n, still = holds(presence[:, x] & ~covered)
        if not ok:
            # Name the survivor that accounts for most of X's plasmids, and say how many others
            # it took. A dropped candidate explains nothing, so it never joins `covered`.
            shared = [(int((presence[:, x] & presence[:, y]).sum()), -k, y)
                      for k, y in enumerate(standing)]
            shared = [s for s in shared if s[0] > 0]
            if shared:
                label = motifs[max(shared)[2]] + (
                    f" + {len(shared) - 1} more" if len(shared) > 1 else "")
            else:                    # fails on the plasmids that carry it; nothing to blame
                label = "(no stronger motif)"
            explanations[x] = (label, n, still)
            continue
        covered |= presence[:, x]
        standing.append(x)

    # The audit: every survivor against all the others, weakest first, one removal at a time.
    survivors = standing
    while len(survivors) > 1:
        cover = presence[:, survivors].sum(axis=1)
        for x in sorted(survivors, key=lambda j: strength[j]):
            ok, n, still = holds(presence[:, x] & (cover == 1))   # carried by x alone
            if not ok:
                overlap = max((y for y in survivors if y != x),
                              key=lambda y: int((presence[:, x] & presence[:, y]).sum()))
                explanations[x] = (motifs[overlap] + " (audit)", n, still)
                survivors.remove(x)
                break
        else:
            break

    keep = [j for j in range(len(motifs)) if j not in explanations]
    return candidates_df.iloc[keep], {motifs[x]: v for x, v in explanations.items()}

In [ ]:
_scan = [process_single_flexible_pattern(p, enc, fcs, bg, -1, 0.7, 3)[1] for p in pats]
_pv = np.concatenate(_scan)
_cut = _pv[benjamini_hochberg(_pv) < 0.05].max()          # the scan's BH cutoff at q < 0.05
after4, why = filter_explained_candidates(kept, log2fc_df["JJ1886_T0"], left, right,
                                          log2fc_thr=-1, score_thr=0.7, encoded=enc,
                                          p_threshold=_cut)
print(f"scan cutoff p <= {_cut:.1e}; {len(kept)} candidates -> {len(after4)}")
for m, (by, n, s) in sorted(why.items(), key=lambda kv: -kv[1][1]):
    print(f"  {m:<14} <- {by:<28} {n:>3} plasmids left, score {s:.2f}")
after4[["motif", "pattern", "fraction_depleted", "num_sequences"]]

scan cutoff p <= 1.5e-04; 32 candidates -> 5
  AAGTNNNNTTAA   <- AACNNNNCTTT                    3 plasmids left, score 0.67
  CACGNNNNTACC   <- CACNNNNGTAT + 1 more           3 plasmids left, score 0.67
  GTGTNNNNCGGA   <- CACNNNNGTAT                    3 plasmids left, score 0.67
  GAACNNNNGCCC   <- CACNNNNGTAC                    2 plasmids left, score 1.00
  AATANNNNTGTG   <- CACNNNNGTAT + 1 more           2 plasmids left, score 0.00
  GAAGNNNACAC    <- CACNNNNGTAT                    2 plasmids left, score 0.50
  AAGGNNNGTTC    <- AACNNNNCTTT                    2 plasmids left, score 0.50
  CCTGAGA        <- GAGACC                         2 plasmids left, score 0.50
  TGGCNNNCACA    <- CACNNNNGTAT                    2 plasmids left, score 0.00
  GACCNNNNCCTC   <- GAGACC                         1 plasmids left, score 1.00
  AGAGNNNNCACG   <- CACNNNNGTAT + 1 more           1 plasmids left, score 1.00
  CCACNNNTGTA    <- CACNNNNGTAC                    1 plasmids left, score 1.00
  AAGTNNNGTTA    <- AACNNNNCTTT + 1 more           1 plasmids left, score 0.00
  CTGGNNNNCACA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GTGTNNNNATAA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  TGTGNNNATAA    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  AAGTNNNGTTC    <- AACNNNNCTTT + 1 more           1 plasmids left, score 0.00
  CAGANNNCTCA    <- GAGACC                         1 plasmids left, score 0.00
  CCTGNNNCCTC    <- GAGACC + 1 more                1 plasmids left, score 0.00
  CGCCNNNNCACA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GACTNNNACAC    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  TGCTNNNCACA    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GCGGNNNNCACA   <- CACNNNNGTAT + 1 more           0 plasmids left, score 0.00
  CCTTNNNACAC    <- CACNNNNGTAT                    0 plasmids left, score 0.00
  GCAGNNNNCTCA   <- GAGACC                         0 plasmids left, score 0.00
  GGCANNNNCACA   <- CACNNNNGTAT                    0 plasmids left, score 0.00
  TGTGNNNNTAAA   <- CACNNNNGTAT                    0 plasmids left, score 0.00

          motif    pattern  fraction_depleted  num_sequences
1        GAGACC  (6, 0, 0)                1.0              9
12  AACNNNNCTTT  (3, 4, 4)                1.0             63
14  CACNNNNGTAT  (3, 4, 4)                1.0            192
17  CACNNNNGTAC  (3, 4, 4)                1.0             20
34  AGGTNNNGGTC  (4, 3, 4)                1.0              3

Five candidates stand: the strain's four sites and `AGGTNNNGGTC`. Every other one collapses once
the plasmids of stronger candidates are set aside — `AATANNNNTGTG`, 0.99 on 190 plasmids, keeps
two, neither depleted. `GAAGNNNACAC` shows why the leftover must also beat background: three of
its five carriers carry a site, and one of the other two is depleted. That 50% would clear the
default `score_thr` of 0.5, but against those two plasmids' background of 0.049, one depleted out
of two is p = 0.10, far above the cutoff.

`AGGTNNNGGTC` rests on three plasmids, all depleted, that no stronger candidate accounts for, so
step 4 has nothing to take from it. Whether three plasmids are enough to name a site is not step
4's question; the pipeline's default `min_support` of 5 answers it, and this search uses 3.

In [ ]:
#| hide
# Two candidates on ten plasmids each, eight of them shared. What decides is whether the two
# plasmids NOT shared still deplete beyond their background.
def _overlapping(own_depleted):
    # Every insert is 16 nt with 7 G/C, so all share one GC bin and one background.
    seqs, fc = [], []
    for i in range(8):                                   # carry both
        seqs.append("GGTCTCACGTAC" + "".join("AT"[(i >> b) & 1] for b in range(4))); fc.append(-5.0)
    for tail in ("TTGCCATTTA", "TTGCCATTAT"):            # GGTCTC alone, depleted
        seqs.append("GGTCTC" + tail); fc.append(-5.0)
    for tail in ("TTAT", "TTTA"):                        # ACGTAC alone
        seqs.append("GCGCTTACGTAC" + tail); fc.append(-5.0 if own_depleted else 0.0)
    for k in range(100):                                 # neither: a hundred untouched plasmids,
        # so the sample has a realistic background against which two depleted leftovers are evidence
        seqs.append("CCCCCCC" + "".join("AT"[(k >> b) & 1] for b in range(9))); fc.append(0.0)
    return pd.Series(fc, index=seqs)

_t = pd.DataFrame({"motif": ["GGTCTC", "ACGTAC"], "pattern": ["(6, 0, 0)", "(6, 0, 0)"],
                   "fraction_depleted": [1.0, 1.0], "num_sequences": [10, 10]})
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# its own two plasmids deplete -> ACGTAC keeps its claim
_kept, _why = filter_explained_candidates(_t, _overlapping(True), "", "", **_kw)
test_eq(sorted(_kept.motif), ["ACGTAC", "GGTCTC"])
test_eq(_why, {})

# its own two plasmids do not -> the score was borrowed from GGTCTC
_kept, _why = filter_explained_candidates(_t, _overlapping(False), "", "", **_kw)
test_eq(list(_kept.motif), ["GGTCTC"])
test_eq(_why["ACGTAC"][0], "GGTCTC")
test_eq(_why["ACGTAC"][1], 2)          # two plasmids left, well under min_support
test_eq(_why["ACGTAC"][2], 0.0)        # and they do not deplete

# Step 4 on the six-pattern search: the strain's four sites stand, with one three-plasmid motif
# that no stronger candidate accounts for, and the 190-plasmid shadow goes.
test_eq(sorted(after4.motif),
        ["AACNNNNCTTT", "AGGTNNNGGTC", "CACNNNNGTAC", "CACNNNNGTAT", "GAGACC"])
assert "AATANNNNTGTG" in why

# An empty table and a single candidate come back untouched: there is nothing to explain with.
test_eq(len(filter_explained_candidates(pd.DataFrame(), _overlapping(True), "", "")[0]), 0)
test_eq(len(filter_explained_candidates(_t.iloc[:1], _overlapping(True), "", "")[0]), 1)

## Reporting: a motif and its reverse complement are one answer

The library is scanned on both strands, so a motif and its reverse complement always carry
**identical** statistics — same supporting sequences, same depletion score, same mean log2FC.
They describe one site, and exactly one of them should appear in the output.

Left to the order candidates happen to arrive in, which one appears is a coin toss: the same site
comes back as `GAGACC` from one run and `GGTCTC` from another, and two datasets of the same strain
can disagree on the strand of every motif they find.

`canonical_motif` decides it by rule: **use the spelling REBASE uses**, so results line up with
the literature and with enzyme names people recognise (`GGTCTC` is BsaI / Eco31I). For motifs
REBASE does not know — most of what a discovery screen finds — fall back to the alphabetically
first strand. Arbitrary, but identical on every run and every machine.

This is not cosmetic. Without a rule, one site can be written two ways in the same piece of work —
`GAGACC` (BsaI) in one place and `GGTCTC` (Eco31I) in another. Those are isoschizomers: one site,
two spellings, differing only in which strand the tool happened to emit.

In [ ]:
#| export
def _canonicalise_flexible_motifs(df):
    """Put every motif in a flexible-motif result table on its canonical strand.

    A motif and its reverse complement have identical statistics, so rewriting the label loses
    nothing.
    """
    if df is None or df.empty or 'motif' not in df.columns:
        return df
    df = df.copy()
    flipped = df['motif'] != df['motif'].map(canonical_motif)
    df['motif'] = df['motif'].map(canonical_motif)
    # The pattern has to follow the motif. Reverse-complementing a (d1, spacer, d2) site gives
    # a (d2, spacer, d1) site, so a relabelled row whose pattern was left alone would describe
    # a string it does not hold -- and every consumer that pairs motif with pattern, such as
    # motif_presence_matrix, would silently decline to handle it.
    if 'pattern' in df.columns:
        def _mirror(p):
            try:
                d1, sp, d2 = ast.literal_eval(p) if isinstance(p, str) else tuple(p)
            except (ValueError, SyntaxError, TypeError):
                return p
            # With no spacer the site is contiguous and (k, 0, 0) is the spelling the
            # pattern list uses, so mirroring must not turn (6, 0, 0) into (0, 0, 6).
            m = (d1 + d2, 0, 0) if sp == 0 else (d2, sp, d1)
            return str(m) if isinstance(p, str) else m
        df.loc[flipped, 'pattern'] = df.loc[flipped, 'pattern'].map(_mirror)
    return df

In [ ]:
#| hide
# Rewrites to the canonical strand and leaves everything else alone.
_t = pd.DataFrame({'motif': ['GAGACC', 'AACNNNNCTTT'], 'pattern': [(6, 0, 0), (3, 4, 4)],
                   'num_sequences': [6, 54], 'avg_log2fc': [-3.75, -5.02]})
_out = _canonicalise_flexible_motifs(_t)
assert list(_out.motif) == ['GGTCTC', 'AAAGNNNNGTT']
assert list(_out.num_sequences) == [6, 54]

# An empty table is returned untouched rather than exploding.
assert _canonicalise_flexible_motifs(pd.DataFrame()).empty

### Is the depletion one population or two?

A real site, strong or weak, shifts the plasmids that carry it as one population. A motif that
is really a shadow of another site is a **mixture**: the carriers that also carry the real site
are destroyed, the rest are untouched, and the distribution has two modes, one of them at
background.

Two numbers decide it. Sarle's **bimodality coefficient** is above 5/9 ≈ 0.556, the value a
uniform distribution takes, when a distribution has two modes. But it also rises when the
carriers fall into two *depleted* groups: `CACNNNNGTAC` on the 20 nt JJ1886 library has 19
carriers between −6.6 and −4.4 and one at −8.6, a coefficient of 0.654, and nothing about it is
mixed. So the carriers are also split in two at the cut that best separates them
(`upper_group_median`), and `bimodal` is raised only when the coefficient is above 5/9 **and**
the upper group's median is not depleted, i.e. at or above the depletion threshold. `bimodality`
keeps the raw coefficient.

This is **independent of significance**. A shadow is highly significant and bimodal; a weak real
site is significant and unimodal; a chance call is neither. The two together say more than
either alone, so both are reported.

In [ ]:
#| export
def bimodality_coefficient(values):
    """Sarle's bimodality coefficient: (skew^2 + 1) / (kurtosis + 3(n-1)^2/((n-2)(n-3))).

    Above 5/9 the distribution is more bimodal than a uniform one. NaN below four values, where
    it is not defined, and when every value is the same.
    """
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 4 or np.allclose(v, v[0]):
        return float("nan")
    g = skew(v, bias=False)
    k = kurtosis(v, bias=False, fisher=True)
    denom = k + 3.0 * (n - 1) ** 2 / ((n - 2) * (n - 3))
    return float((g ** 2 + 1.0) / denom) if denom > 0 else float("nan")


BIMODALITY_BENCHMARK = 5.0 / 9.0


def upper_group_median(values):
    """Median of the upper group when `values` are split in two at the cut that maximises the
    between-group variance (Otsu's method: two-means in one dimension, on the sorted values).

    NaN below two finite values.
    """
    v = np.sort(np.asarray(values, dtype=float))
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 2:
        return float("nan")
    k = np.arange(1, n)                       # the lower group is v[:k]
    low = np.cumsum(v)[:-1]
    between = k * (n - k) * (low / k - (v.sum() - low) / (n - k)) ** 2
    return float(np.median(v[k[np.argmax(between)]:]))


def annotate_significance(results_df, log2fc_series, left_context, right_context,
                          all_pvalues=None, log2fc_thr=-1, q_threshold=0.05, encoded=None,
                          background=None, score_thr=0.5):
    """Add fraction_depleted_lower, background, p_value, q_value, called, bimodality and bimodal
    to a result table.

    `fraction_depleted_lower` is the one-sided lower confidence bound on the fraction of carriers
    depleted (Clopper-Pearson, at level `q_threshold`). A candidate had to reach `score_thr` --
    most of its carriers depleted -- and a call has to show it: 5 of 10 depleted is 0.5, but its
    bound is 0.22.

    `background` is the rate at which the motif's carriers would deplete with no site involved:
    the mean over them of each plasmid's GC-matched background (`plasmid_background`, computed
    from `log2fc_series` when not given). The p-value is taken against it, as in the scan.

    `all_pvalues` are the p-values of every motif the scan tested, which is what the
    Benjamini-Hochberg correction has to be computed over -- correcting only over the handful
    that survived filtering would be meaningless.

    `bimodal` marks carriers that are a mixture of depleted and background-level plasmids: a
    bimodality coefficient above 5/9 and an upper group (`upper_group_median`) that is not
    depleted at `log2fc_thr`.

    Nothing is removed. `called` marks the rows whose q-value is below `q_threshold` and whose
    `fraction_depleted_lower` reaches `score_thr`; the rest stay in the table so that a weak
    result is visible as a weak claim rather than silently absent (`find_restricted_motifs`
    returns them with `all_motifs=True`).
    """
    if results_df is None:
        return results_df
    if results_df.empty:
        # A strain with no active system is the first thing a new user runs, so the empty
        # table must have the same columns as a full one -- otherwise selecting the called
        # rows works on every strain that finds something and raises on the ones that do not.
        out = results_df.copy()
        for _c, _dt in (("fraction_depleted_lower", float), ("background", float),
                        ("p_value", float), ("q_value", float), ("called", bool),
                        ("bimodality", float), ("bimodal", bool)):
            if _c not in out.columns:
                out[_c] = pd.Series(dtype=_dt)
        return out
    # Placed beside fraction_depleted below; dropped first so a table can be annotated again.
    out = results_df.drop(columns=["fraction_depleted_lower", "background"], errors="ignore")
    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    if background is None:
        background = plasmid_background(log2fc_series.index, log2fc_series.to_numpy(), log2fc_thr)
    presence = _carriers(encoded, out["motif"].tolist(), _patterns(out), log2fc_series,
                         left_context, right_context)
    # Each motif's null is its carriers' mean background, summed exactly as the scan sums it, so
    # that a reported motif's p-value is the scan's to the last bit (see `plasmid_background`).
    rate = (background @ presence) / presence.sum(axis=0)
    n = out["num_sequences"].to_numpy()
    k = np.rint(out["fraction_depleted"].to_numpy() * n)
    at = out.columns.get_loc("fraction_depleted") + 1
    out.insert(at, "fraction_depleted_lower",
               np.where(k > 0, beta.ppf(q_threshold, np.maximum(k, 1), n - k + 1), 0.0))
    out.insert(at + 1, "background", rate)

    p = motif_pvalues(out["num_sequences"].to_numpy(), out["fraction_depleted"].to_numpy(), rate)
    out["p_value"] = p
    if all_pvalues is not None and len(all_pvalues):
        # The reported motifs were tested by the scan, so their p-values are already in
        # `all_pvalues`; appending them again counted those tests twice. Only a p-value the scan
        # never produced is a new test and joins the pool. Each motif's q is then read off the
        # adjusted pool at its own p-value -- BH q-values are a non-decreasing step function of
        # p, so tied p-values share one q.
        pool = np.asarray(all_pvalues, dtype=float)
        pool = np.sort(np.concatenate([pool, p[~np.isin(p, pool)]]))
        q_pool = benjamini_hochberg(pool)
        out["q_value"] = q_pool[np.searchsorted(pool, p, side="right") - 1]
    else:
        out["q_value"] = benjamini_hochberg(p)
    out["called"] = (out["q_value"] < q_threshold) & (out["fraction_depleted_lower"] >= score_thr)

    values = log2fc_series.to_numpy()
    carriers = [values[presence[:, j]] for j in range(len(out))]
    out["bimodality"] = [bimodality_coefficient(v) for v in carriers]
    # Two modes, the upper one at background: destroyed and untouched plasmids mixed. Two
    # depleted modes -- strong and very strong -- are a site, not a mixture.
    out["bimodal"] = (out["bimodality"] > BIMODALITY_BENCHMARK) & \
        np.array([upper_group_median(v) >= log2fc_thr for v in carriers], dtype=bool)

    return out.sort_values(["called", "q_value"], ascending=[False, True])

In [ ]:
# CACNNNNGTAC on the 20 nt library, centred as the pipeline centres it, against a made-up shadow
# whose carriers are half destroyed and half untouched.
_centred = log2fc_df["JJ1886_T0"] - log2fc_df["JJ1886_T0"].median()
_cac = _centred[_get_filter_for_motif(_centred, "CACNNNNGTAC", left, right)].to_numpy()
_shadow = np.concatenate([np.full(10, -5.0), np.random.default_rng(0).normal(0, 0.3, 10)])
for name, v in [("CACNNNNGTAC", _cac), ("shadow", _shadow)]:
    print(f"{name:<12} n={len(v)}  sorted: {np.round(np.sort(v), 1)[:3]} ... {np.round(np.sort(v), 1)[-3:]}")
    print(f"{'':<12} bimodality {bimodality_coefficient(v):.3f}   "
          f"upper group median {upper_group_median(v):+.2f}")

CACNNNNGTAC  n=20  sorted: [-8.6 -6.6 -5.9] ... [-4.6 -4.4 -4.4]
             bimodality 0.654   upper group median -4.96
shadow       n=20  sorted: [-5. -5. -5.] ... [0.2 0.3 0.4]
             bimodality 0.755   upper group median +0.03

In [ ]:
#| hide
# destroyed-or-untouched, the signature of a borrowed score
_two = np.concatenate([np.zeros(20), np.full(20, -5.0)])
assert bimodality_coefficient(_two) > BIMODALITY_BENCHMARK
# one shifted population, the signature of a real site
_one = np.random.default_rng(0).normal(-3, 0.5, 40)
assert bimodality_coefficient(_one) < BIMODALITY_BENCHMARK
assert np.isnan(bimodality_coefficient([1.0, 2.0, 3.0]))   # undefined below four values
assert np.isnan(bimodality_coefficient([1.0] * 10))        # and with no spread at all

# The split finds the gap: the upper group of a destroyed/untouched mixture sits at background,
# and that of a strong + very strong site is still depleted.
test_eq(upper_group_median(_two), 0.0)
test_eq(upper_group_median(np.r_[np.full(19, -5.0), -8.6]), -5.0)
assert np.isnan(upper_group_median([1.0]))

# The two cases of the example above. Both pass the coefficient; only the mixture is flagged.
assert bimodality_coefficient(_cac) > BIMODALITY_BENCHMARK
assert upper_group_median(_cac) < -0.5
assert bimodality_coefficient(_shadow) > BIMODALITY_BENCHMARK
assert upper_group_median(_shadow) >= -0.5

# The flag in the table: carriers of AAAAAA are half destroyed and half untouched; carriers of
# GGTCTC are all depleted, one far further than the rest. Both are bimodal by the coefficient.
_lib = pd.Series(np.r_[np.full(6, -5.0), np.zeros(6), np.full(5, -5.0), -9.0, np.zeros(8)],
                 index=[f"AAAAAA{i:06b}".replace("0", "C").replace("1", "G") for i in range(12)] +
                       [f"GGTCTC{i:06b}".replace("0", "C").replace("1", "T") for i in range(6)] +
                       [f"CCCCCC{i:06b}".replace("0", "G").replace("1", "T") for i in range(8)])
_res = pd.DataFrame({"motif": ["AAAAAA", "GGTCTC"], "pattern": ["(6, 0, 0)", "(6, 0, 0)"],
                     "fraction_depleted": [0.5, 1.0], "num_sequences": [12, 6], "avg_log2fc": [-2.5, -5.7]})
_flag = annotate_significance(_res, _lib, "", "", log2fc_thr=-0.5).set_index("motif")
assert (_flag.bimodality > BIMODALITY_BENCHMARK).all()
test_eq(_flag.bimodal.to_dict(), {"AAAAAA": True, "GGTCTC": False})
_L, _R = "AAAA", "TTTT"
_seqs = ["GGTCTCAAAAAA", "AAAAAAGGTCTC", "CCCCAAAAAAAA", "AAAAAAAACCCC"]   # all one GC content
_fc = pd.Series([-5.0, -5.0, -0.1, -0.1], index=_seqs)
_res = pd.DataFrame({"motif": ["GGTCTC"], "pattern": ["(6, 0, 0)"],
                     "fraction_depleted": [1.0], "num_sequences": [2], "avg_log2fc": [-5.0]})
_out = annotate_significance(_res, _fc, _L, _R, log2fc_thr=-1)
for _c in ("fraction_depleted_lower", "background", "p_value", "q_value", "called",
           "bimodality", "bimodal"):
    assert _c in _out.columns
# one GC content, half the plasmids below -1, so every carrier's background is 0.5
test_eq(_out.background.iloc[0], 0.5)
# the bound on the depleted fraction: 9 of 9 depleted is confidently a majority (0.05 ** (1/9) =
# 0.72), 5 of 10 is not (0.22), however small its q-value -- so it is reported but not called
_bound = lambda k, n: annotate_significance(_res.assign(num_sequences=n, fraction_depleted=k / n),
                                            _fc, _L, _R, log2fc_thr=-1, all_pvalues=[1e-20])
test_close(_bound(9, 9).fraction_depleted_lower.iloc[0], 0.05 ** (1 / 9), eps=1e-9)
test_close(_bound(5, 10).fraction_depleted_lower.iloc[0], 0.2224, eps=1e-4)
test_eq(_bound(5, 10).called.iloc[0], False)
# nothing is removed: a weak row stays, flagged, rather than disappearing
test_eq(len(_out), 1)
# an empty table must carry the SAME columns, so selecting called rows works on every strain
_empty = annotate_significance(_res.iloc[:0], _fc, _L, _R, log2fc_thr=-1)
for _c in ("fraction_depleted_lower", "background", "p_value", "q_value", "called",
           "bimodality", "bimodal"):
    assert _c in _empty.columns
# annotating an annotated table again gives the same table
pd.testing.assert_frame_equal(annotate_significance(_out, _fc, _L, _R, log2fc_thr=-1), _out)

### A degenerate site is one motif

The scan reports motifs of A, C, G and T, so a site that accepts two bases at a position comes back
as two motifs. B156 in the panel recognises `GACNNNNGTTY`, and steps 2–4 call it as `GAACNNNNGTC`
and `AAACNNNNGTC` — the site read on the other strand, `RAACNNNNGTC`, split at its first base.
Step 4 keeps both, because each depletes plasmids the other does not carry. Rule 3's tool reads the
position: at the first base of `GAACNNNNGTC`, A depletes like the site, C and T at background.

In [ ]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_panel, right_panel = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_panel = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20)
b156 = log2fc_panel["B156_R1"] - log2fc_panel["B156_R1"].median()    # centred, as the pipeline does
enc_panel = encode_library(get_lib_seq_context(b156.index.tolist(), left_panel, right_panel))
fc_b156 = b156.to_numpy()
bg_b156 = plasmid_background(b156.index, fc_b156, -0.5)

_cls = classify_positions("GAACNNNNGTC", [0], (4, 4, 3), enc_panel, fc_b156, bg_b156, -0.5)[0]
for m, n, s, b in variant_profile([x + "AACNNNNGTC" for x in "ACGT"], (4, 4, 3), enc_panel,
                                  fc_b156, bg_b156, -0.5):
    print(f"  {m}  n={n:>4}  score={s:.3f}  background={b:.3f}  {_cls.get(m[0], ('(the call)',))[0]}")

  AAACNNNNGTC  n= 894  score=0.992  background=0.140  site
  CAACNNNNGTC  n= 386  score=0.140  background=0.139  non-site
  GAACNNNNGTC  n= 291  score=0.986  background=0.139  (the call)
  TAACNNNNGTC  n= 461  score=0.141  background=0.140  non-site

Rule 3 drops a motif when every other base is site-like. Here one is and two are not, so the
position is degenerate: it becomes the IUPAC letter of the bases that behave like the site, `R`.

`generalise_motif` applies this to a call at every defined position, interior ones included —
B367's `CCYANNNNNNNNTAG` (BB2 panel) is degenerate at its third base. It changes one position at
a time, the one whose site-like bases have the most carriers, and profiles the merged motif again
until no position changes, so each further merge is judged on the carriers of the motif merged so
far. A merged motif's carriers are the plasmids that carry any of its instances
(`motif_instances`); they are counted from the presence matrix, not added up from the scan's
counts, because one plasmid can carry two instances. A position where every other base is
site-like is rule 3's case, not a degenerate one, and is left alone.

In [ ]:
#| export
def _union_profile(motifs, pattern, encoded, fc, background, log2fc_thr):
    """`variant_profile` for motifs with IUPAC letters: each scored on the plasmids carrying any of
    its instances, which the scan's per-motif counts cannot give (a plasmid can carry two)."""
    has = _instance_presence(encoded, motifs, [pattern] * len(motifs))[0]
    n = has.sum(axis=0)
    depleted = (fc < log2fc_thr).astype(float) @ has
    bg_sum = background @ has
    return [(m, int(k), float(d / k) if k else float("nan"), float(b / k) if k else float("nan"))
            for m, k, d, b in zip(motifs, n, depleted, bg_sum)]


def generalise_motif(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
                     min_support=5, totals=None):
    """`motif` with each degenerate position written as the IUPAC letter of its site-like bases.

    At every defined position the bases `motif` does not allow are classified
    (`classify_positions`). Where some, but not all, are site-like, they join the bases allowed
    there. One position changes at a time -- the one whose site-like bases have the most carriers,
    the first on a tie -- and the merged motif is classified again, on its own carriers, until no
    position changes.

    Args:
        motif (str): a called motif.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library, fc_values, background, log2fc_thr, min_support, totals: as for
            `is_mixture`.

    Returns:
        str: the merged motif, or `motif` itself when no position is degenerate.
    """
    defined = [i for i, c in enumerate(motif) if c != "N"]
    while True:
        best = None
        for i, classes in classify_positions(motif, defined, pattern, encoded_library, fc_values,
                                             background, log2fc_thr, min_support, totals).items():
            site = [b for b, (c, _) in classes.items() if c == "site"]
            # Every other base site-like is an uninformative base (rule 3), not a degenerate one.
            if site and len(site) < len(classes):
                n = sum(classes[b][1] for b in site)
                if best is None or n > best[0]:
                    best = (n, i, site)
        if best is None:
            return motif
        _, i, site = best
        motif = motif[:i] + IUPAC_COLLAPSE[IUPAC_EXPAND[motif[i]] | frozenset(site)] + motif[i + 1:]

In [ ]:
# B156's two sites, each from one of its called variants.
for seed, pat in [("GAACNNNNGTC", (4, 4, 3)), ("ACANNNNNATGG", (3, 5, 4))]:
    merged = generalise_motif(seed, pat, enc_panel, fc_b156, bg_b156, -0.5)
    print(f"  {seed} -> {merged} (reported as {canonical_motif(merged)})")

  GAACNNNNGTC -> RAACNNNNGTC (reported as GACNNNNGTTY)
  ACANNNNNATGG -> ACANNNNNRTGG (reported as CCAYNNNNNTGT)

Each case the rule must get right, on a synthetic library where the sites are known: random
20 nt inserts plus 40 inserts for each planted 8-mer (2 for a rare one); every plasmid carrying a
site is depleted.

In [ ]:
def _planted(sites, planted, n=3000, seed=0):
    """Random 20 nt inserts, plus `planted[m]` inserts carrying each 8-mer `m`; carriers of any of
    `sites` (either strand) deplete, the rest sit around 0."""
    rng = np.random.default_rng(seed)
    rand = lambda: "".join(rng.choice(list("ACGT"), 20))
    seqs = [rand() for _ in range(n)]
    for m, k in planted.items():
        for _ in range(k):
            s, at = rand(), rng.integers(0, 13)
            seqs.append(s[:at] + m + s[at + 8:])
    seqs = list(dict.fromkeys(seqs))
    hit = np.array([any(m in s or revcomp(m) in s for m in sites) for s in seqs])
    return pd.Series(np.where(hit, -3.0, rng.normal(0, 0.2, len(seqs))), index=seqs)


def _generalise(series, motif):
    fc = series.to_numpy()
    return generalise_motif(motif, (8, 0, 0), encode_library(series.index.tolist()), fc,
                            plasmid_background(series.index, fc, -0.5), -0.5)


# ACGTTGCA and GCGTTGCA are the site; CCGTTGCA is planted but not a site; TCGTTGCA is a site on
# only 4 plasmids, too few to classify.
degenerate = _planted(["ACGTTGCA", "GCGTTGCA", "TCGTTGCA"],
                      {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40, "TCGTTGCA": 2})
print("ACGTTGCA ->", _generalise(degenerate, "ACGTTGCA"))

ACGTTGCA -> RCGTTGCA

In [ ]:
#| hide
# The site-like G joins A; T, depleted but on too few plasmids to be classified, is never added.
test_eq(_get_filter_for_motif(degenerate, "TCGTTGCA", "", "").sum(), 4)
test_eq(_generalise(degenerate, "ACGTTGCA"), "RCGTTGCA")
test_eq(_generalise(degenerate, "GCGTTGCA"), "RCGTTGCA")      # the same site from either variant
# Negative: GCGTTGCA planted but at background, so ACGTTGCA's first base stays an A.
_single = _planted(["ACGTTGCA"], {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40})
test_eq(_generalise(_single, "ACGTTGCA"), "ACGTTGCA")
# Two degenerate positions, on a palindromic site (YGGCCR-like): the second merge is judged on the
# carriers of the first, through the instances of AYGGCCAT. AAGGCCAT and ACGGCCCT are planted
# at background so that each position has a non-site to set the site-like base against.
_sites = motif_instances("AYGGCCRT", (8, 0, 0))
_two = _planted(_sites, dict.fromkeys(_sites + ["AAGGCCAT", "ACGGCCCT"], 40))
test_eq(_generalise(_two, "ACGGCCAT"), "AYGGCCRT")
# Every other base site-like is rule 3's case: no merge, whatever the seed.
_all = _planted(["ACGTTGCA", "CCGTTGCA", "GCGTTGCA", "TCGTTGCA"], dict.fromkeys(
    ["ACGTTGCA", "CCGTTGCA", "GCGTTGCA", "TCGTTGCA"], 40))
test_eq(_generalise(_all, "ACGTTGCA"), "ACGTTGCA")

A merged motif replaces anything only once it is called on its own carriers.
`merge_degenerate_calls` scores it like any other row (`annotate_significance`, against the scan's
p-values: only its own p-value joins the pool, so every other row keeps its q-value), and drops the
called rows that are instances of it on either strand. When two seeds of one site stop at different
merges, only the more general is kept. `merged_from` names the rows a merged motif replaced and is
empty for every other row; uncalled rows are left as they are. It runs on the calls alone, after
step 4: earlier, the rule would also fire on the many shadows step 4 removes.

In [ ]:
#| export
def _is_instance(specific, general):
    """Does `general` allow every base of `specific`, on one strand or the other?"""
    allows = lambda s: len(s) == len(general) and all(
        IUPAC_EXPAND[a] <= IUPAC_EXPAND[b] for a, b in zip(s, general))
    return allows(specific) or allows(revcomp(specific))


def _motif_rows(motifs, patterns, log2fc_series, left_context, right_context, encoded, log2fc_thr):
    """Result-table rows -- support, fraction depleted, mean log2FC, pattern -- read off each
    motif's carriers."""
    has = _carriers(encoded, motifs, patterns, log2fc_series, left_context, right_context)
    fc = log2fc_series.to_numpy(dtype=float)
    n = has.sum(axis=0)
    return pd.DataFrame({"motif": motifs,
                         "fraction_depleted": (fc < log2fc_thr).astype(float) @ has / n,
                         "num_sequences": n, "avg_log2fc": fc @ has / n,
                         "pattern": [str(p) for p in patterns]})


def merge_degenerate_calls(table, log2fc_series, left_context, right_context, encoded, background,
                           all_pvalues, log2fc_thr=-1, q_threshold=0.05, score_thr=0.5,
                           min_support=5, totals=None):
    """Report each degenerate site as one IUPAC motif, in place of its called variants.

    Every called row is generalised (`generalise_motif`); each distinct merged motif that is not an
    instance of another is scored on its own carriers (`annotate_significance`, against
    `all_pvalues`). A called merged motif replaces the called rows that are instances of it.

    Args:
        table (pd.DataFrame): the scored result table, from `annotate_significance`.
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence, as scored.
        left_context (str), right_context (str): the vector flanks.
        encoded (tuple): the library from `encode_library`.
        background (np.ndarray): each plasmid's expected depletion rate.
        all_pvalues (np.ndarray): the p-values of every motif the scan tested.
        log2fc_thr, q_threshold, score_thr: as for `annotate_significance`.
        min_support (int), totals (dict): as for `classify_positions`.

    Returns:
        pd.DataFrame: `table` with a 'merged_from' column -- the replaced motifs joined by '+', empty
        for every other row -- and the merged rows in place of those they replaced, called rows
        first. A table with no merge comes back as it was, with the column added.
    """
    table = table.assign(merged_from="")
    called = table[table["called"]]
    fc = log2fc_series.to_numpy(dtype=float)
    totals = {} if totals is None else totals
    grown = {}                                       # canonical merged motif -> (spelling, pattern)
    for motif, pattern in zip(called["motif"], _patterns(called)):
        merged = generalise_motif(motif, pattern, encoded, fc, background, log2fc_thr,
                                  min_support, totals)
        if merged != motif:
            grown.setdefault(canonical_motif(merged), (merged, pattern))
    keep = [m for m in grown if not any(o != m and _is_instance(m, o) for o in grown)]
    if not keep:
        return table
    rows = _motif_rows([grown[m][0] for m in keep], [grown[m][1] for m in keep], log2fc_series,
                       left_context, right_context, encoded, log2fc_thr)
    scored = annotate_significance(_canonicalise_flexible_motifs(rows), log2fc_series, left_context,
                                   right_context, all_pvalues=all_pvalues, log2fc_thr=log2fc_thr,
                                   q_threshold=q_threshold, encoded=encoded,
                                   background=background, score_thr=score_thr)
    scored = scored[scored["called"]]
    if scored.empty:
        return table
    absorbed = [[m for m in called["motif"] if _is_instance(m, g)] for g in scored["motif"]]
    scored = scored.assign(merged_from=["+".join(a) for a in absorbed])
    dropped = table["called"] & table["motif"].isin([m for a in absorbed for m in a])
    out = pd.concat([table[~dropped], scored[table.columns]], ignore_index=True)
    return out.sort_values(["called", "q_value"], ascending=[False, True], kind="stable")

In [ ]:
# The synthetic site above, as the pipeline reports it: its two called variants and an unrelated
# site, GGTCTCAA, then the merge.
def _report(series, motifs, pattern=(8, 0, 0)):
    """The scored table `find_restricted_motifs` would hand to the merge, for these motifs."""
    enc_s, fc = encode_library(series.index.tolist()), series.to_numpy()
    bg_s = plasmid_background(series.index, fc, -0.5)
    pv = get_pattern_scores(enc_s, fc, pattern, -0.5, bg_s).query("num_sequences >= 5").p_value
    rows = _motif_rows(motifs, [pattern] * len(motifs), series, "", "", enc_s, -0.5)
    table = annotate_significance(rows, series, "", "", all_pvalues=pv, log2fc_thr=-0.5,
                                  encoded=enc_s, background=bg_s)
    return table, (series, "", "", enc_s, bg_s, pv)


_lib = _planted(["ACGTTGCA", "GCGTTGCA", "GGTCTCAA"],
                {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40, "GGTCTCAA": 40})
before, _args = _report(_lib, ["ACGTTGCA", "GCGTTGCA", "GGTCTCAA"])
merged = merge_degenerate_calls(before, *_args, log2fc_thr=-0.5)
merged[["motif", "num_sequences", "fraction_depleted", "q_value", "called", "merged_from"]]

      motif  num_sequences  ...  called        merged_from
1  RCGTTGCA             84  ...    True  ACGTTGCA+GCGTTGCA
0  GGTCTCAA             41  ...    True

[2 rows x 6 columns]

In [ ]:
#| hide
# One row for the degenerate site, carried by every plasmid that carries either variant -- the
# regex count of the IUPAC motif -- and called; the unrelated site's row is untouched, to the bit.
test_eq(sorted(merged.motif), ["GGTCTCAA", "RCGTTGCA"])
_row = merged.set_index("motif").loc["RCGTTGCA"]
test_eq(_row.merged_from, "ACGTTGCA+GCGTTGCA")
test_eq(_row.num_sequences, _get_filter_for_motif(_lib, "RCGTTGCA", "", "").sum())
assert _row.called
pd.testing.assert_frame_equal(merged.set_index("motif").loc[["GGTCTCAA"]].drop(columns="merged_from"),
                              before.set_index("motif").loc[["GGTCTCAA"]])
# The palindromic two-position site: its three distinct variants (the fourth is the first read on
# the other strand) become one row.
_t, _a = _report(_two, ["ACGGCCAT", "ATGGCCAT", "ACGGCCGT"])
_m = merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5)
test_eq(_m.motif.tolist(), ["AYGGCCRT"])
test_eq(sorted(_m.merged_from.iloc[0].split("+")), ["ACGGCCAT", "ACGGCCGT", "ATGGCCAT"])
test_eq(_m.num_sequences.iloc[0], _get_filter_for_motif(_two, "AYGGCCRT", "", "").sum())
# A site with one variant: nothing merges and the table comes back as it was, plus the column.
_t, _a = _report(_single, ["ACGTTGCA"])
pd.testing.assert_frame_equal(merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5),
                              _t.assign(merged_from=""))
# No call, or no row at all: unchanged, and the column is there.
_t, _a = _report(_lib, ["ACGTTGCA", "GCGTTGCA"])
_t = _t.assign(called=False)
pd.testing.assert_frame_equal(merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5), _t.assign(merged_from=""))
assert "merged_from" in merge_degenerate_calls(_t.iloc[:0], *_a, log2fc_thr=-0.5).columns
# Instances on either strand, IUPAC letters included.
assert _is_instance("CACNNNNGTAC", "RTACNNNNGTG") and _is_instance("GTACNNNNGTG", "RTACNNNNGTG")
assert not _is_instance("CACNNNNGTAA", "RTACNNNNGTG")

A palindromic site has a limit of its own. `CCTNAGG` (381A) is its own reverse complement, and its
central N pairs C with G and A with T: `CCTCAGG` is `CCTGAGG` read on the other strand. So "not G"
implies "not C": `CCTHAGG` is carried by exactly the plasmids that carry `CCTNAGG`, and the data can
only set C/G against A/T. In the panel's 381A library and the three 381A libraries of BB2, C/G is
site-like in every one; `CCTNAGG` is what they support.

In [ ]:
_cct = _carriers(enc_panel, ["CCTNAGG", "CCTHAGG", "CCTSAGG", "CCTWAGG"],
                 [(3, 1, 3), (7, 0, 0), (7, 0, 0), (7, 0, 0)], b156, left_panel, right_panel)
print("carriers of CCTNAGG, CCTHAGG, CCTSAGG, CCTWAGG:", _cct.sum(axis=0))

carriers of CCTNAGG, CCTHAGG, CCTSAGG, CCTWAGG: [595 595 240 355]

In [ ]:
#| hide
test_eq(_cct[:, 0], _cct[:, 1])      # without G is without C: the same plasmids

### Reading the result table

`find_restricted_motifs` returns the called motifs, with five columns: `motif`, `num_sequences`,
`fraction_depleted`, `avg_log2fc` and `q_value`. With `all_motifs=True` it
returns every motif that reached scoring, called or not, with all the columns below. Each column
answers one question.

- **How strong is the effect?** `fraction_depleted` is the share of carriers depleted, and
  `avg_log2fc` says how far they fall. For a weak motif in a noisy sample, compare
  `fraction_depleted` with `background` in the full table — the rate at which plasmids like the
  carriers deplete anyway: the mean, over the carriers, of the depletion rate of plasmids of the
  same insert GC content (`plasmid_background`). 0.53 depleted against a background of 0.23
  (11217 in the table below) is a small effect.
- **How sure are we?** `p_value` is the binomial probability that at least this many carriers
  are depleted if each depletes at its `background` rate. `q_value` is that p-value adjusted
  (Benjamini-Hochberg) over every motif the scan tested in the sample, 330,000 and 460,000 on
  the two example libraries: calling every motif up to a given q is expected to make that
  fraction of false calls. A call needs q < `q_threshold` (0.05). q mostly tracks
  `num_sequences`: a modest effect on many plasmids gets a tiny q.
- **Are most carriers depleted?** `fraction_depleted_lower` bounds the depleted fraction from
  below (95%). A call needs it at `score_thr` as well as a small q: on the older JJ1886 run,
  `GTCGNNNNNNNCGGA` has 7 of 12 carriers depleted (q = 10⁻³), but five of the others sit at
  background, and 7 of 12 bounds the fraction only at 0.32. A real site on as few carriers is
  depleted on nearly all of them — `GGTCTC`, 9 of 9 there, bounds it at 0.72.
- **Is it one population?** `bimodal` marks carriers that mix depleted and background-level
  plasmids, the signature of a shadow of another site; `bimodality` is the raw coefficient. It
  does not block a call.
- **Is it a degenerate site?** `merged_from` lists the called variants an IUPAC motif replaced —
  `ATACNNNNGTG+CACNNNNGTAC` for JJ1886's `RTACNNNNGTG` — and is empty for every other row.
- **Why called or not?** `called` is the verdict and `reason` (`call_reason`) says it in words.

On the BB2 panel the calls fall into recognisable groups:

| | background | fraction depleted | avg log2FC | q |
|---|---|---|---|---|
| 8097 `CGACNNNNNNNRTTA` | 0.06 | 0.97 | −1.96 | 10⁻²⁶⁴ |
| 7084 `CCCNNNNNNTTTC` | 0.20 | 0.93 | −1.70 | 10⁻¹⁹⁵ |
| 15853 `ACGNNNNNGTTG` | 0.14 | 0.87 | −1.07 | 10⁻²³⁵ |
| 16169 `YGGCCR` | 0.17 | 0.60 | −0.67 | < 10⁻³⁰⁰ |
| 8408 `GGTAAG` | 0.09 | 0.67 | −0.65 | < 10⁻³⁰⁰ |
| 11217 `GATCNNNNGCCC` | 0.23 | 0.53 | −0.42 | 0.02 |

The first three are restriction sites. `YGGCCR` (ECOR64) and `GGTAAG` (BREX in HS)
are weaker systems, also highly significant. The last is a weak, partial effect on a noisy
sample; with 26 of 49 carriers depleted its bound is 0.40, so it is not called. `all_motifs=True` keeps such rows on purpose: an effect that
is not restriction — on fitness, say — is a finding too, and the columns let a reader judge it.

**The background is per motif.** Within one sample, AT-rich inserts can deplete far more often
than GC-rich ones (`01_utils` shows it on the 20 nt library), and a motif made of A and T is
carried mostly by AT-rich inserts. Against one rate for the whole sample, H120 on the 20 nt library
calls 39 motifs, almost all AT-rich: `AATANAGAA`, for one, has 8 of 10 carriers depleted, against
a sample-wide rate of 0.085 (q = 4 × 10⁻⁵). Its carriers' own background is 0.22, and at that rate
8 of 10 is p = 1.4 × 10⁻⁴, short of H120's cutoff of 3 × 10⁻⁵. Against GC-matched backgrounds H120
keeps one call of its 39 and E1114 16 of 42, among them `YGGCCR`, whose GC-rich carriers have a
background of 0.10, below the sample's 0.145; with the bound on the depleted fraction as well, H120
calls none and E1114 eight. On the BB2 panel the draft's Fig 3 calls
keep backgrounds within 0.015 of the sample-wide rate, except 16175's GC-rich `CCGCGG` (0.17 →
0.13), and every one of them is still called.

`call_reason` puts the verdict in words: `called`, or the test that failed with the numbers that
failed it. A called row whose carriers are bimodal says so, since that is worth a look before
trusting the call.

In [ ]:
#| export
def call_reason(row, q_threshold=0.05, score_thr=0.5):
    """Why a row of the result table is called or not, in a few words.

    A call needs q below `q_threshold` and the lower bound on the depleted fraction at `score_thr`
    or above (`annotate_significance`). The reason names each test the row fails, with its numbers,
    or says "called"; a called row with bimodal carriers adds a note, since bimodality does not
    block a call.
    """
    n = int(row["num_sequences"])
    failed = []
    if not row["q_value"] < q_threshold:
        failed.append(f"not significant (q = {row['q_value']:.2g})")
    if not row["fraction_depleted_lower"] >= score_thr:
        failed.append(f"most carriers not shown depleted ({round(row['fraction_depleted'] * n)}/{n}; "
                      f"lower bound {row['fraction_depleted_lower']:.2f} < {score_thr:g})")
    if failed:
        return "; ".join(failed)
    return "called; carriers split between depleted and untouched" if row["bimodal"] else "called"


_COMPACT_COLUMNS = ["motif", "num_sequences", "fraction_depleted", "avg_log2fc", "q_value"]
_FULL_COLUMNS = _COMPACT_COLUMNS + ["pattern", "fraction_depleted_lower", "background", "p_value",
                                    "called", "bimodality", "bimodal", "merged_from"]


def _result_view(table, all_motifs, q_threshold, score_thr):
    """What `find_restricted_motifs` returns: the called rows in five columns, or every row with
    its `reason`, called first."""
    if not all_motifs:
        return (table.loc[table["called"], _COMPACT_COLUMNS]
                .sort_values(["q_value", "motif"]).reset_index(drop=True))
    reason = [call_reason(r, q_threshold, score_thr) for _, r in table.iterrows()]
    return (table[_FULL_COLUMNS].assign(reason=pd.Series(reason, index=table.index, dtype=object))
            .sort_values(["called", "q_value", "motif"], ascending=[False, True, True])
            .reset_index(drop=True))

In [ ]:
# GTCGNNNNNNNCGGA on the 20 nt JJ1886 run: significant, but 7 of 12 carriers depleted bounds the
# depleted fraction at 0.32, so most carriers are not shown depleted.
_row = lambda **kw: pd.Series({"num_sequences": 12, "fraction_depleted": 7 / 12, "q_value": 1e-3,
                               "fraction_depleted_lower": 0.32, "bimodal": True, **kw})
call_reason(_row())

'most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)'

In [ ]:
#| hide
test_eq(call_reason(_row()), "most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)")
# A row that misses only q, and one that misses both, says which.
test_eq(call_reason(_row(q_value=0.21, fraction_depleted_lower=0.6)), "not significant (q = 0.21)")
test_eq(call_reason(_row(q_value=0.21)), "not significant (q = 0.21); "
        "most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)")
# A call says "called"; with bimodal carriers it adds a note but stays a call.
test_eq(call_reason(_row(fraction_depleted_lower=0.6, bimodal=False)), "called")
test_eq(call_reason(_row(fraction_depleted_lower=0.6)),
        "called; carriers split between depleted and untouched")
# The thresholds are the caller's: q exactly at the threshold is not significant.
test_eq(call_reason(_row(q_value=0.05, fraction_depleted_lower=0.6)), "not significant (q = 0.05)")
test_eq(call_reason(_row(fraction_depleted_lower=0.6), score_thr=0.7)[:32], "most carriers not shown depleted")

In [ ]:
#| hide
# The reason agrees with `called` on every row annotate_significance scores.
_v = _result_view(pd.concat([_bound(9, 9), _bound(5, 10)]).assign(merged_from=""), True, 0.05, 0.5)
test_eq(list(_v.called), [True, False])                 # called rows first
test_eq([r.startswith("called") for r in _v.reason], list(_v.called))
# The default view keeps the called rows, in five columns; an empty table keeps the columns.
test_eq(list(_result_view(_v, False, 0.05, 0.5).columns), _COMPACT_COLUMNS)
test_eq(len(_result_view(_v, False, 0.05, 0.5)), 1)
_e = _result_view(_v.iloc[:0], True, 0.05, 0.5)
test_eq(len(_e), 0); assert "reason" in _e.columns

## When the pipeline should refuse to answer

Step 4 sets each candidate's plasmids against those of the survivors ranked above it, so its
cost grows faster than the number of candidates step 3 hands it. Thresholds too loose for a
sample can hand it tens of thousands: 7084 on the BB2 panel, run without centring, brings 22,669,
and step 4 takes five minutes over them; 5,000 of them take 45 s. `max_candidates` is checked before step 4, and past it
the pipeline **raises** `TooManyCandidatesError`. The default, 5,000, is above the most any strain
of the shipped data or the BB2 panel brings at the defaults: 3,144, E1114 in the 20 nt library
(1,928 on the BB2 panel, 15622).

Raising is deliberate. Returning the candidates instead would hand back a table with the same
columns as a real result, easy to mistake for one. They ride on the exception as `.candidates`
for inspection; a caller processing many strains should catch it, record that strain as "no
confident call", and carry on.

In [ ]:
#| export
class TooManyCandidatesError(RuntimeError):
    """Raised when step 3 leaves more candidates than step 4 will compare.

    The candidate table is available as `.candidates` for inspection. A count this large
    usually means the thresholds are too loose for the sample, not that the strain has
    thousands of sites.
    """

    def __init__(self, n_candidates, max_candidates, log2fc_thr, score_thr, min_support, candidates):
        self.n_candidates = n_candidates
        self.max_candidates = max_candidates
        self.candidates = candidates
        super().__init__(
            f"Too many candidate motifs: {n_candidates} > max_candidates={max_candidates}. "
            f"Step 4 compares candidates with each other and would not finish. This usually "
            f"means the thresholds are too permissive for this sample: check that center=True, "
            f"or try a stricter flexible_motif_log2fc_thr (currently {log2fc_thr}, e.g. -1.0), "
            f"flexible_motif_score_thr (currently {score_thr}, e.g. 0.7), or "
            f"flexible_motif_min_support (currently {min_support}, e.g. 10). "
            f"Raise max_candidates only if you know why this strain has so many candidates. "
            f"Step 3's candidates are on this exception as `.candidates`."
        )

In [ ]:
#| hide
_e = TooManyCandidatesError(200, 150, -1, 0.5, 3, pd.DataFrame({"motif": ["GGTCTC"]}))
test_eq(_e.n_candidates, 200)
test_eq(len(_e.candidates), 1)            # the candidates ride on the exception for inspection
assert "max_candidates=150" in str(_e)
assert "flexible_motif_score_thr (currently 0.5" in str(_e)

In [ ]:
#| export
def find_restricted_motifs(log2fc_series,
                           left_context_str,
                           right_context_str,
                           n_jobs=1,
                           flexible_motif_patterns=None,
                           flexible_motif_log2fc_thr=-0.5,
                           flexible_motif_min_support=5,
                           flexible_motif_score_thr=0.5,
                           max_candidates=5000,
                           q_threshold=0.05,
                           encoded_library=None,
                           center=True,
                           all_motifs=False
                           ):
    """The motifs one sample restricts: steps 2 to 4 and reporting on a log2FC series.

    The series is centred on its median; every pattern is scanned over the inserts with their
    flanks (step 2); the candidates are reduced to one description per site
    (`filter_redundant_patterns`, step 3) and cleared of those whose depletion a stronger
    candidate accounts for (`filter_explained_candidates`, step 4); the survivors are put on
    their canonical strand and scored (`annotate_significance`), and the called variants of a
    degenerate site are reported as one IUPAC motif (`merge_degenerate_calls`). Every test is against a
    GC-matched background: each plasmid's is the depletion rate of the plasmids in its insert-GC
    decile (`plasmid_background`), and a set of plasmids is tested against their mean.

    Args:
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence.
        left_context_str, right_context_str (str): the vector flanks of the insert.
        n_jobs (int): processes used to scan the patterns. 1 (default) runs in this process.
            A pattern takes about a second on a 30k-sequence library, so more is rarely worth
            the startup cost.
        flexible_motif_patterns (list): the shapes to search, as `(d1, spacer, d2)`.
            Defaults to `get_patterns()`. Each is rewritten to its `canonical_pattern` and
            duplicates dropped, so `(4, 4, 3)` is searched as `(3, 4, 4)` and never twice.
        flexible_motif_log2fc_thr (float): a plasmid counts as depleted below this, after
            centring. Default -0.5: low enough to see weakly restricting systems such as BREX,
            which a -1 threshold misses.
        flexible_motif_min_support (int): minimum plasmids for a motif to be considered. With
            every carrier depleted, the lower bound on the depleted fraction is 0.22, 0.37, 0.47
            and 0.55 for 2 to 5 carriers, so 5 is the smallest support that can be called at the
            default score threshold of 0.5 (4 at 0.45, 7 at 0.65). Lower only adds candidates and
            runtime: E1114 on the 20 nt library exceeds `max_candidates` at 2 to 4.
        flexible_motif_score_thr (float): at least this fraction of the plasmids carrying a
            candidate must be depleted, and a call must show it with confidence (the lower bound
            `fraction_depleted_lower` reaches it). Default 0.5, the value the draft's Fig 3 uses.
        max_candidates (int): the most candidates step 3 may hand to step 4, whose cost grows
            faster than their number. More raises `TooManyCandidatesError`, with the candidates
            attached. The default, 5000, is above the 3,144 that the busiest strain of the
            example data and the BB2 panel brings at the default thresholds.
        q_threshold (float): a motif is marked `called` when its Benjamini-Hochberg q-value,
            computed against its carriers' GC-matched background and over every motif the scan
            tested, falls below this.
        encoded_library (tuple): `encode_library(get_lib_seq_context(log2fc_series.index,
            left_context_str, right_context_str))`, if the caller already has it. Strains
            screened with the same library and flanks share it, so a panel encodes it once.
            It must describe exactly `log2fc_series.index`, in order.
        center (bool): subtract the series' median before anything is thresholded. The
            typical untouched plasmid sits below log2FC 0, the more so the noisier the sample, so
            without centring the same threshold would be a different stringency in every strain.
            `avg_log2fc` is then relative to the sample's own typical plasmid.
        all_motifs (bool): return every scored motif, called or not, with every column.

    Returns:
        pd.DataFrame: by default the called motifs, one row each, sorted by q then motif: 'motif',
        'num_sequences', 'fraction_depleted', 'avg_log2fc', 'q_value'. With `all_motifs=True`, every scored motif, called rows first: those columns, 'pattern', the
        others `annotate_significance` adds, 'merged_from', and 'reason' (`call_reason`).
    """
    if center:
        log2fc_series = log2fc_series - log2fc_series.median()
    candidates = pd.DataFrame(columns=['motif', 'fraction_depleted', 'num_sequences',
                                       'avg_log2fc', 'pattern'])
    report = functools.partial(annotate_significance, log2fc_thr=flexible_motif_log2fc_thr,
                               q_threshold=q_threshold, score_thr=flexible_motif_score_thr)
    view = functools.partial(_result_view, all_motifs=all_motifs, q_threshold=q_threshold,
                             score_thr=flexible_motif_score_thr)
    if log2fc_series.empty:
        print("The input series is empty; there is nothing to scan.")
        return view(report(candidates, log2fc_series, left_context_str, right_context_str,
                           all_pvalues=np.array([])).assign(merged_from=""))

    # The library is encoded once and every step below reads it.
    if encoded_library is None:
        encoded_library = encode_library(get_lib_seq_context(
            log2fc_series.index.tolist(), left_context_str, right_context_str))
    elif encoded_library[0].shape[0] != len(log2fc_series):
        raise ValueError(
            f"encoded_library holds {encoded_library[0].shape[0]} sequences but log2fc_series "
            f"has {len(log2fc_series)}; it must encode exactly this series' index, in order, "
            f"with these flanks.")
    fc = log2fc_series.to_numpy(dtype=float)
    background = plasmid_background(log2fc_series.index, fc, flexible_motif_log2fc_thr)

    if flexible_motif_patterns is None:
        flexible_motif_patterns = get_patterns()
    elif np.ndim(flexible_motif_patterns) == 1:          # one pattern rather than a list
        flexible_motif_patterns = [flexible_motif_patterns]
    # A pattern and its mirror find the same sites (the scan reads both strands), and a gapless
    # pattern is one run however it is split, so each is searched once, in canonical form.
    for p, c in sorted({(tuple(p), canonical_pattern(p)) for p in flexible_motif_patterns
                        if tuple(p) != canonical_pattern(p)}):
        print(f"Pattern {p} is searched as {c}: the same sites, read on the other strand.")
    flexible_motif_patterns = sorted({canonical_pattern(p) for p in flexible_motif_patterns},
                                     key=lambda x: (x[0] + x[2], x[1], x))

    # Step 2.
    worker = functools.partial(
        process_single_flexible_pattern, encoded_library=encoded_library,
        fc_values_for_flexible_analysis=fc, background=background,
        flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
        flexible_motif_score_thr=flexible_motif_score_thr,
        flexible_motif_min_support=flexible_motif_min_support)
    if n_jobs == 1:
        per_pattern = [worker(p) for p in tqdm(flexible_motif_patterns, desc="Scanning patterns")]
    else:
        # Each worker scans single-threaded: n_jobs processes each starting numba's thread pool
        # would ask for n_jobs x cores at once. imap keeps pattern order, so the result does not
        # depend on which worker finishes first.
        with Pool(processes=n_jobs) as pool:
            per_pattern = list(tqdm(pool.imap(functools.partial(worker, parallel=False),
                                              flexible_motif_patterns),
                                    total=len(flexible_motif_patterns), desc="Scanning patterns"))

    tested_pvalues = (np.concatenate([pv for _, pv, _ in per_pattern]) if per_pattern
                      else np.array([]))
    # The p-value a motif needs to be called: the largest that clears q_threshold over every
    # motif tested. Step 4 holds the candidates' leftovers to it, since they were selected
    # from that same pool.
    _q = benjamini_hochberg(tested_pvalues)
    scan_cutoff = tested_pvalues[_q < q_threshold].max() if (_q < q_threshold).any() else 0.0
    hits = [df for df, _, _ in per_pattern if not df.empty]
    totals = {p: t for p, (_, _, t) in zip(flexible_motif_patterns, per_pattern)}

    # Step 3, once over every pattern's candidates. It scores variants from the scan's counts,
    # so a pattern step 2 scanned is never rescanned.
    if hits:
        candidates = filter_redundant_patterns(
            pd.concat(hits, ignore_index=True), log2fc_series,
            left_context_str, right_context_str,
            log2fc_thr=flexible_motif_log2fc_thr, score_thr=flexible_motif_score_thr,
            min_support=flexible_motif_min_support, encoded=encoded_library, totals=totals,
            background=background)
        print(f"{sum(len(h) for h in hits)} candidate(s) across all patterns; "
              f"{len(candidates)} remain after step 3.")
    if len(candidates) > max_candidates:
        raise TooManyCandidatesError(len(candidates), max_candidates, flexible_motif_log2fc_thr,
                                     flexible_motif_score_thr, flexible_motif_min_support,
                                     candidates)

    # Step 4.
    candidates, explained = filter_explained_candidates(
        candidates, log2fc_series, left_context_str, right_context_str,
        log2fc_thr=flexible_motif_log2fc_thr, score_thr=flexible_motif_score_thr,
        min_support=flexible_motif_min_support, encoded=encoded_library,
        p_threshold=scan_cutoff, background=background)
    if explained:
        print(f"{len(explained)} candidate(s) whose score was borrowed:")
        for m, (by, n, s) in sorted(explained.items()):
            print(f"    {m} <- {by} (without them: n={n}, score={s:.2f})")

    # Canonicalise before printing, so the names in the log are the names in the table.
    candidates = _canonicalise_flexible_motifs(candidates)
    print(f"{len(candidates)} motif(s) scored:")
    for _, row in candidates.iterrows():
        print(f"  {row['motif']} (pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, "
              f"AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")
    table = report(candidates, log2fc_series, left_context_str, right_context_str,
                   all_pvalues=tested_pvalues, encoded=encoded_library, background=background)

    # A degenerate site's called variants, reported as one IUPAC motif.
    table = merge_degenerate_calls(
        table, log2fc_series, left_context_str, right_context_str, encoded_library, background,
        tested_pvalues, log2fc_thr=flexible_motif_log2fc_thr, q_threshold=q_threshold,
        score_thr=flexible_motif_score_thr, min_support=flexible_motif_min_support, totals=totals)
    merged = table[table["merged_from"] != ""]
    if len(merged):
        print(f"{len(merged)} degenerate site(s) reported as one motif:")
        for m, parts in zip(merged["motif"], merged["merged_from"]):
            print(f"  {m} <- {parts.replace('+', ' + ')}")
    print(f"{int(table['called'].sum())} motif(s) called.")
    return view(table)

## Putting it to work

`find_restricted_motifs` runs steps 2 to 4 and reporting on one sample. On JJ1886 in the panel,
at the defaults — every pattern of `get_patterns()`, centred, depleted below −0.5, score 0.5 — it
returns the called motifs:

In [ ]:
motifs_jj1886 = find_restricted_motifs(log2fc_panel["JJ1886_R1"], left_panel, right_panel)
motifs_jj1886

85 candidate(s) across all patterns; 4 remain after step 3.
4 motif(s) scored:
  GGTCTC (pattern (6, 0, 0)), FracDep: 0.98, AvgFC: -2.85, N: 55
  ATACNNNNGTG (pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -3.27, N: 504
  CACNNNNGTAC (pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -3.31, N: 468
  AAAGNNNNGTT (pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -3.43, N: 913
1 degenerate site(s) reported as one motif:
  RTACNNNNGTG <- ATACNNNNGTG + CACNNNNGTAC
3 motif(s) called.

Scanning patterns: 100%|##########| 43/43 [00:01<00:00, 40.62it/s]

         motif  num_sequences  fraction_depleted  avg_log2fc       q_value
0  AAAGNNNNGTT            913           0.997809   -3.425663  0.000000e+00
1  RTACNNNNGTG            963           1.000000   -3.285517  0.000000e+00
2       GGTCTC             55           0.981818   -2.851532  2.999895e-43

In [ ]:
import io, contextlib

In [ ]:
#| hide
# The strain's three sites, named on their canonical strand; the Type I site is one row, merged
# from the two variants step 4 kept.
test_eq(sorted(motifs_jj1886.motif), ["AAAGNNNNGTT", "GGTCTC", "RTACNNNNGTG"])
test_eq(list(motifs_jj1886.columns), ["motif", "num_sequences", "fraction_depleted", "avg_log2fc",
                                      "q_value"])
# all_motifs=True returns the same calls first, with every column and a reason for each row.
with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
    _all = find_restricted_motifs(log2fc_panel["JJ1886_R1"], left_panel, right_panel, all_motifs=True)
_called = _all[_all.called]
test_eq(set(_called.motif), set(motifs_jj1886.motif))
test_eq(set(_called.reason), {"called"})
test_eq(_called.set_index("motif").merged_from["RTACNNNNGTG"], "ATACNNNNGTG+CACNNNNGTAC")
# The same sites step 4 kept on the 20 nt library: two runs of one strain, one answer.
_parts = {p for m, f in zip(_called.motif, _called.merged_from) for p in (f.split("+") if f else [m])}
assert _parts <= set(_canonicalise_flexible_motifs(after4).motif)

B156's two degenerate sites, each reported as one motif. `all_motifs=True` shows the variants each
replaced:

In [ ]:
motifs_b156 = find_restricted_motifs(log2fc_panel["B156_R1"], left_panel, right_panel,
                                     all_motifs=True)
motifs_b156[["motif", "num_sequences", "q_value", "merged_from", "reason"]]

160 candidate(s) across all patterns; 4 remain after step 3.
4 motif(s) scored:
  AAACNNNNGTC (pattern (4, 4, 3)), FracDep: 0.99, AvgFC: -2.55, N: 894
  GAACNNNNGTC (pattern (4, 4, 3)), FracDep: 0.99, AvgFC: -2.48, N: 291
  ACANNNNNATGG (pattern (3, 5, 4)), FracDep: 0.99, AvgFC: -2.63, N: 536
  ACANNNNNGTGG (pattern (3, 5, 4)), FracDep: 0.99, AvgFC: -2.59, N: 399
2 degenerate site(s) reported as one motif:
  GACNNNNGTTY <- AAACNNNNGTC + GAACNNNNGTC
  CCAYNNNNNTGT <- ACANNNNNATGG + ACANNNNNGTGG
2 motif(s) called.

Scanning patterns: 100%|##########| 43/43 [00:01<00:00, 39.94it/s]

          motif  num_sequences  q_value                merged_from  reason
0  CCAYNNNNNTGT            926      0.0  ACANNNNNATGG+ACANNNNNGTGG  called
1   GACNNNNGTTY           1174      0.0    AAACNNNNGTC+GAACNNNNGTC  called

In [ ]:
#| hide
# Four called variants on B156, two sites.
test_eq(motifs_b156[motifs_b156.called].set_index("motif").merged_from.to_dict(),
        {"GACNNNNGTTY": "AAACNNNNGTC+GAACNNNNGTC", "CCAYNNNNNTGT": "ACANNNNNATGG+ACANNNNNGTGG"})

In [ ]:
#| hide
import io, contextlib

In [ ]:
#| hide
_quiet = lambda: contextlib.redirect_stderr(io.StringIO())
with contextlib.redirect_stdout(io.StringIO()), _quiet():
    # The guard runs before step 4, and the candidates it carries are step 3's.
    try:
        find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right, flexible_motif_patterns=pats,
                               max_candidates=1)
        raise AssertionError("TooManyCandidatesError not raised")
    except TooManyCandidatesError as e:
        assert e.n_candidates > 1 and len(e.candidates) == e.n_candidates
    # One pattern on its own is accepted, not only a list of them.
    _one = find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right,
                                  flexible_motif_patterns=(6, 0, 0), all_motifs=True)
    # An empty series is an empty table with the same columns as a full one, in either view.
    _none = find_restricted_motifs(log2fc_df["JJ1886_T0"].iloc[:0], left, right)
    _none_all = find_restricted_motifs(log2fc_df["JJ1886_T0"].iloc[:0], left, right, all_motifs=True)
test_eq(set(_one.pattern), {"(6, 0, 0)"})
test_eq((len(_none), len(_none_all)), (0, 0))
test_eq(list(_none.columns), _COMPACT_COLUMNS)
test_eq(list(_none_all.columns), list(_one.columns))
# A pre-encoded library must match the series it is passed with.
test_fail(lambda: find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right,
                                         encoded_library=encode_library(["ACGT"])),
          contains="encoded_library holds 1 sequences")

### A sample whose AT-rich inserts deplete

What the GC-matched background is for, on a library built to need it: 2,000 random 20 nt inserts
whose GC content varies from insert to insert. AT-rich inserts deplete often — up to 90% of them —
for no site-related reason, and 60 inserts carry a planted site, `GGTCTC`, which always depletes.
Any motif made of A and T is carried mostly by AT-rich inserts and so looks depleted.

In [ ]:
_rng = np.random.default_rng(0)
_seqs = []
for i in range(2000):
    _p = _rng.uniform(0.2, 0.8)                                  # this insert's GC content
    _s = "".join(_rng.choice(list("ACGT"), p=[(1 - _p) / 2, _p / 2, _p / 2, (1 - _p) / 2], size=20))
    if i < 60:                                                   # the planted site
        _at = _rng.integers(0, 14)
        _s = _s[:_at] + "GGTCTC" + _s[_at + 6:]
    _seqs.append(_s)
_seqs = list(dict.fromkeys(_seqs))
_gc = np.array([(s.count("G") + s.count("C")) / 20 for s in _seqs])
_site = np.array([("GGTCTC" in s) or ("GAGACC" in s) for s in _seqs])
_dep = _rng.random(len(_seqs)) < np.clip(1.2 - 2.4 * _gc, 0.03, 0.9)   # AT-rich: depleted by chance
skewed = pd.Series(np.where(_site, -3.0, np.where(_dep, -2.0, _rng.normal(0, 0.2, len(_seqs)))),
                   index=_seqs)
with contextlib.redirect_stdout(io.StringIO()), _quiet():
    _res = find_restricted_motifs(skewed, "", "", flexible_motif_patterns=(6, 0, 0))
# Only the planted site is called, against a background of plasmids like its carriers.
print("called:", list(_res.motif))

# TAAAAA shows why. Against one rate for the whole sample its carriers look strongly depleted;
# against the background of their own GC bins they deplete no more than expected.
_c = skewed - skewed.median()
_flat = get_pattern_scores(encode_library(_seqs), _c, (6, 0, 0), log2FC_thr=-0.5).set_index("motif")
_matched = get_pattern_scores(encode_library(_seqs), _c, (6, 0, 0), log2FC_thr=-0.5,
                              background=plasmid_background(_seqs, _c, -0.5)).set_index("motif")
pd.DataFrame({"sample-wide rate": _flat.loc[["GAGACC", "TAAAAA"], "p_value"],
              "GC-matched": _matched.loc[["GAGACC", "TAAAAA"], "p_value"]})

called: ['GGTCTC']

        sample-wide rate    GC-matched
motif
GAGACC      1.037600e-45  8.512096e-60
TAAAAA      8.069693e-11  1.168775e-01

In [ ]:
#| hide
test_eq(list(_res.motif), ["GGTCTC"])
# TAAAAA: strongly depleted against the sample-wide rate, not against its GC-matched background.
assert _flat.loc["TAAAAA", "p_value"] < 1e-8 < 0.01 < _matched.loc["TAAAAA", "p_value"]

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()

In [ ]:
#| hide