In [ ]:
%load_ext autoreload
%autoreload 2

# core

> Finding the DNA motifs a strain restricts, from a table of plasmid counts before and after delivery.

In [ ]:
#| default_exp core

In [ ]:
#| hide
from nbdev.showdoc import *
from fastcore.test import test_eq

In [ ]:
#| export
import ast
import pandas as pd
from tqdm import tqdm
import numpy as np
from scipy.stats import binom, kurtosis, skew
import os
import warnings
import functools
from multiprocessing import Pool, cpu_count
from collections import  defaultdict
import re
from randseq.utils import revcomp, calculate_log2fc, get_lib_seq_context, get_patterns, find_broad_in_specific, _get_filter_for_motif, canonical_motif
from typing import List, Tuple, Set, Callable

In [ ]:
#| hide
from randseq.example_data import get_example_data_dir

In [ ]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['__init__.py',
 '__pycache__',
 'countsTable.csv.gz',
 'counts_panel.csv.gz',
 'counts_panel_key.csv']

## What RandSeq measures

A library of plasmids carrying random 150 bp inserts is conjugated into a recipient strain. A
plasmid whose insert happens to contain a recognition site for an active restriction system is
destroyed on entry, so it is **depleted** relative to the input library. Sequencing the library
before and after gives, for each insert, a log2 fold change. The job of this module is to work
backwards from those fold changes to the sequence motifs responsible.

The whole pipeline is five steps:

1. counts → log2FC per plasmid
2. find motifs that sit at a **fixed position** in the read
3. set those sequences aside and scan for **position-independent** motifs
4. remove redundant descriptions of the same motif
5. rescore what survives on plasmids that carry only one candidate, and report

### The example data

Two datasets ship with the package, and it is worth being clear that **both are the same
strain**: *E. coli* JJ1886, Lab.ID 12049.

- `countsTable.csv.gz` — an earlier run, 19 strains, JJ1886 in the `JJ1886_T0` column
- `counts_panel.csv.gz` — the BB2 run, both donor replicates and eight strains chosen because
  each one demonstrates a specific design decision (see `example_data/counts_panel_key.csv`)

Having one strain measured twice, on different runs, is useful: the two must agree on which
motifs they call. Before the canonical-strand rule below they reported every motif on opposite
strands, which is how that bug was found.

### 1. Computing the log2fc of the sequences from counts data

In [ ]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df

                        K12_T0     HS_T0  ...    S88_T0  MG1655_T0
seq                                       ...
CGGAGGTACTGGGTACATTT  0.043818  0.049551  ...  0.213624   0.090458
TGGCGATAATGCCGGCTATC  0.045463  0.137127  ...  0.092292   0.101627
TTCCAGTTCACTGGTCTTCG -0.049694  0.049903  ...  0.458076   0.128330
AATTTCAGTGCCGTTCAGAT -0.251957 -0.422224  ... -0.183890  -0.180938
CTGCGGTAATAATTCCCGCC -0.178427 -0.154025  ... -0.188758  -0.186226
...                        ...       ...  ...       ...        ...
GCTTGATGTAGCCTTCGAAC -0.100518 -0.079966  ... -0.055837  -0.133185
TAATGGCAAATTGACACTCC  0.258205  0.103683  ...  0.201961   0.387054
GCTGCGCGCGGAGTTGTTCC -0.629856 -0.381054  ... -0.497605  -0.959646
GCAACACGCCAGTAAGGTGT  0.693416  0.487153  ...  0.064457   0.376418
GATAGCCGGATAGCTTAAGG -0.245685 -0.131631  ... -0.400835   0.140210

[11503 rows x 19 columns]

### Listing all the sequence motifs found in our library that follow a specific pattern 

The pattern is a list of 3 numbers:
1. The number of defined bases in the first part of the site  
2. The number of undefined bases in the middle  
3. The number of defined bases in the second part of the site

In [ ]:
#| export
# Helper function to create regex group strings for the main function
def _make_regex_group_str(length: int, content_char_class: str = "[ATGC]") -> str:
    """
    Creates a regex capturing group string.
    If length is 0, creates an empty capturing group "()".
    Otherwise, creates a group like "([ATGC]{length})".
    """
    if length > 0:
        return f"({content_char_class}{{{length}}})"
    else: # length == 0
        return "()" # Captures an empty string

def get_sites_in_seq(
    sequence_library: List[str],
    pattern: Tuple[int, int, int] = (3, 6, 4),
    no_ori: bool = True,
    custom_revcomp: Callable[[str], str] = revcomp
) -> List[Set[str]]:
    """
    Computes the list of unique sites matching a defined pattern within each sequence
    of a given library.

    The pattern specifies a motif structure: (defined_bases_part1, spacer_length, defined_bases_part2).
    For example, a pattern (3, 6, 4) looks for sites like XXXNNNNNNXXXX, where X
    represents a defined base (A, T, G, C) and N represents an undefined base in the motif.

    Args:
        sequence_library: A list of DNA sequence strings. They do NOT have to be the same
                          length -- real libraries are ragged (in the published screen only
                          ~91% of inserts were exactly the nominal 150 nt). The pattern is
                          only required to fit inside the shortest one.
        pattern: A tuple of three non-negative integers:
            1. The number of defined bases in the first part of the site.
            2. The length of the spacer (undefined bases) in the middle.
            3. The number of defined bases in the second part of the site.
        no_ori: If True (default), the search for sites is performed on both the
                provided sequence and its reverse complement. If False, only the
                provided sequence strand is searched.
        custom_revcomp: A function to compute the reverse complement. Defaults to
                        a basic internal `revcomp` function.

    Returns:
        A list of sets. Each set contains unique site strings found in the
        corresponding input sequence. Sites are represented with 'N' for the
        spacer region (e.g., "ATCNNNNGGC").

    Raises:
        ValueError: If the sequence library is empty.
        ValueError: If the pattern is not a tuple of three non-negative integers.
        ValueError: If the total length of the site defined by the pattern is zero.
        ValueError: If the total length of the site pattern exceeds the length of the
                    sequences in the library.
    """
    # --- Input Validation ---
    if not sequence_library:
        raise ValueError("Sequence library cannot be empty.")

    if not (
        isinstance(pattern, tuple) and
        len(pattern) == 3 and
        all(isinstance(p_num, int) and p_num >= 0 for p_num in pattern)
    ):
        raise ValueError(
            "Pattern must be a tuple of three non-negative integers: "
            "(defined_bases_part1, spacer_length, defined_bases_part2)."
        )

    defined_len1, spacer_len, defined_len2 = pattern
    pattern_total_length = defined_len1 + spacer_len + defined_len2

    if pattern_total_length == 0:
        # Finding motifs of total length 0 (e.g., pattern (0,0,0)) is problematic
        # as it would match everywhere. It's better to disallow it.
        raise ValueError("The total length of the site pattern (sum of its parts) cannot be zero.")

    shorter_seq = min([len(s) for s in sequence_library])
    if pattern_total_length > shorter_seq:
        raise ValueError(
            f"Site pattern's total length ({pattern_total_length}) is longer than "
            f"the shorter sequence length ({shorter_seq})."
        )

    # --- Regex Preparation ---
    # Uses the helper _make_regex_group_str to create "()" for zero-length parts.
    # This ensures three capturing groups are always present for consistent unpacking later.
    group1_str = _make_regex_group_str(defined_len1)
    # The spacer part in the original regex also used [ATGC] for the characters
    # it matched in the sequence, even though these are replaced by 'N's in the motif.
    group2_str = _make_regex_group_str(spacer_len) 
    group3_str = _make_regex_group_str(defined_len2)
    
    # The lookahead `(?=...)` is crucial for finding all overlapping sites.
    regex_pattern_str = f"(?={group1_str}{group2_str}{group3_str})"
    
    # Using re.IGNORECASE for robustness, assuming 'atgc' is equivalent to 'ATGC'.
    compiled_regex = re.compile(regex_pattern_str, re.IGNORECASE)

    # --- Site Finding ---
    all_sequence_results: List[Set[str]] = []
    
    for seq_original_case in sequence_library:
        current_sequence_sites: Set[str] = set()
        
        # Standardize sequence to uppercase for consistent processing and regex matching
        processed_seq = seq_original_case.upper()

        sequences_to_scan = [processed_seq]
        if no_ori:
            # Ensure the revcomp function also standardizes or expects uppercase
            reverse_complement_seq = custom_revcomp(processed_seq)
            sequences_to_scan.append(reverse_complement_seq)

        for target_sequence in sequences_to_scan:
            # Find all matches in the current target sequence (forward or reverse complement)
            # matches will be a list of 3-tuples due to the three capturing groups.
            matches = compiled_regex.findall(target_sequence)
            for part1, actual_spacer_bases, part2 in matches: # Unpack the 3 captured groups
                # Construct the site motif string using 'N's for the spacer region.
                # The `actual_spacer_bases` captured by the regex are intentionally
                # ignored here for the motif string, which uses a generic 'N' spacer.
                # If spacer_len is 0, 'N' * 0 is an empty string.
                site_motif = f"{part1}{'N' * spacer_len}{part2}"
                current_sequence_sites.add(site_motif)
        
        all_sequence_results.append(current_sequence_sites)

    return all_sequence_results

In [ ]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib=get_lib_seq_context(log2fc_df.index,left,right)
sites_in_seq=get_sites_in_seq(lib,pattern=(3,6,4),no_ori=True)
assert len(sites_in_seq) == len(lib)
print(f"First 5 pattern matching sequences found in the first sequence of the library:")
list(sites_in_seq[0])[:5]

First 5 pattern matching sequences found in the first sequence of the library:

['GTANNNNNNCTAG',
 'AACNNNNNNACCC',
 'ATTNNNNNNAGAG',
 'CGGNNNNNNTGGG',
 'GAGNNNNNNGGTA']

## `score`: what fraction of plasmids were depleted

Everything downstream is built on one number: of the plasmids carrying a motif, what fraction
fell below a log2FC threshold.

### Threshold convention

Thresholds appear in several places and it matters that they mean the same thing everywhere:

- a **log2FC** threshold is **strict** — a plasmid is depleted when `log2FC < thr`
- a **score or support** threshold is **inclusive** — `>= thr`

This matches the recommended operating thresholds in the paper, *"log2FC < −1; depletion score
≥ 0.5"*. It was not always consistent: candidate selection used `>` for support, so
`min_support=3` silently meant *four*. Fixing that changed support counts on the example data
(12049 `ATACNNNNGTG` 97 → 31) without changing which motifs were called.

In [ ]:
#| export
def score(FCs, thr=-1):
    """
    Returns the fraction of sequences depleted below the thr value.

    Threshold convention, applied consistently across the package and matching the recommended
    operating thresholds in the paper ("log2FC < -1; depletion score >= 0.5"):

    - a log2FC threshold is **strict**: a plasmid is depleted when ``log2FC < thr``
    - a score or support threshold is **inclusive**: ``>= thr``, so ``min_support=3`` means
      three supporting sequences, not four
    Handles empty lists of FCs by returning 0.
    """
    if len(FCs)==0:  # Check if the list is empty
        return 0.0
    return sum([x < thr for x in FCs]) / len(FCs)

In [ ]:
assert score([-2,-0.5,-0.1,-5],thr=-1) == 0.5

## Step 1: motifs at a fixed position — and why this step exists

Scanning the ends of the read for motifs that recur **at a constant offset** looks like an odd
thing to do. A restriction site is a sequence, not a position.

The reason is the vector. Each insert is scanned as `left_flank + insert + right_flank`, because
a site can straddle the junction between the two — and the flanks are identical in every plasmid,
so a site formed across a junction is pinned to a constant offset. It then shows up in a
positional scan rather than a sequence scan.

**The worked example.** In *E. albertii* B156 this step finds `GTC` at offset 4. That is not a
position-specific site. The left flank is `GTCTAGGGCGGCGGTAAAAC`, whose last four bases are
`AAAC` — so `GTC@4` **is** `AAACNNNNGTC`, formed across the junction. The flank supplies the
first half-site.

The same thing happens in JJ1886, where `GTG@0` is `ATACNNNNGTG` with `ATAC` coming from the
left flank.

Skipping this step does real damage: on JJ1886 it loses `ATACNNNNGTG` and `CACNNNNGTAC`
entirely, and on the BB2 library it lowers the other counts, because many flexible motifs match
exactly the same flank-dominated sequences and all of them then fail the rescoring in step 5.

In [ ]:
#| export
def identify_depleted_motifs_scanning_ends(log2fc_series, 
                                           scan_depth_k=7, 
                                           max_motif_length=6, 
                                           depletion_threshold=-1, 
                                           score_thr=0.85, 
                                           min_sequence_support=5):
    """
    Identifies DNA motifs associated with sequence depletion by scanning k positions
    from both the left and right ends of sequences, using a pandas Series of log2FC values.

    Args:
        log2fc_series (pd.Series): pandas Series with sequences (DNA strings) as index
                                   and log2FC values as data.
        scan_depth_k (int): The number of positions to scan from each end (0 to k inclusive).
        max_motif_length (int): The maximum length of the motif to consider.
        depletion_threshold (float): The log2FC threshold for considering a sequence depleted.
        min_sequence_support (int): The minimum number of sequences (strictly greater than this value)
                                    a motif must be found in to be included in the results.

    Returns:
        pd.DataFrame: A DataFrame with identified motifs, their length, actual 0-indexed position,
                      number of occurrences, average log2FC, and depletion score (fraction_depleted).
                      Sorted by primary depletion metrics.
    """
    if not isinstance(log2fc_series, pd.Series):
        print(f"Error: Input must be a pandas Series.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    if log2fc_series.empty:
        print(f"Error: Input Series is empty.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    current_log2fc_series = pd.to_numeric(log2fc_series.copy(), errors='coerce')
    series_name = current_log2fc_series.name if current_log2fc_series.name else "input Series"
    print(f"Analyzing motifs of length 1 to {max_motif_length}, scanning positions 0 to {scan_depth_k} from each end, for {series_name}.")
    print(f"Minimum sequence support for a motif: > {min_sequence_support} (i.e., {min_sequence_support +1} or more)")


    motif_stats_accumulator = {}

    # Iterate over (sequence_string, log2fc_value) pairs
    for seq_str, log2fc_val in current_log2fc_series.items(): 
        if pd.isna(log2fc_val) or not isinstance(seq_str, str):
            continue

        processed_positions_for_this_seq = set() 
        for motif_len in range(1, max_motif_length + 1):
            if len(seq_str) < motif_len:
                continue

            # Left scans
            for j_offset in range(scan_depth_k + 1):
                actual_pos_left = j_offset
                if actual_pos_left + motif_len <= len(seq_str):
                    if (actual_pos_left, motif_len) not in processed_positions_for_this_seq:
                        motif = seq_str[actual_pos_left : actual_pos_left + motif_len]
                        key = (motif, actual_pos_left, motif_len) 
                        if key not in motif_stats_accumulator:
                            motif_stats_accumulator[key] = []
                        motif_stats_accumulator[key].append(log2fc_val)
                        processed_positions_for_this_seq.add((actual_pos_left, motif_len))

            # Right scans
            for j_offset in range(scan_depth_k + 1):
                actual_pos_right = len(seq_str) - motif_len - j_offset
                if actual_pos_right >= 0 and actual_pos_right + motif_len <= len(seq_str):
                    if (actual_pos_right, motif_len) not in processed_positions_for_this_seq:
                        motif = seq_str[actual_pos_right : actual_pos_right + motif_len]
                        key = (motif, actual_pos_right, motif_len) 
                        if key not in motif_stats_accumulator:
                            motif_stats_accumulator[key] = []
                        motif_stats_accumulator[key].append(log2fc_val)
                        processed_positions_for_this_seq.add((actual_pos_right, motif_len))
    
    if not motif_stats_accumulator:
        print("No motifs found or no valid data to process based on scan parameters.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    # Use a list comprehension for conciseness
    results = [
        {
            'motif': key[0],             # motif_str
            'length': key[2],            # motif_len
            'position': key[1],          # actual_pos
            'num_sequences': len(fc_values_list), 
            'avg_log2fc': np.mean(fc_values_list),
            'fraction_depleted': score(fc_values_list, depletion_threshold)
        }
        for key, fc_values_list in motif_stats_accumulator.items()
        if len(fc_values_list) > min_sequence_support # Apply min_sequence_support filter
    ]
    
    if not results:
        print(f"No motifs found meeting the minimum sequence support of > {min_sequence_support}.")
        return pd.DataFrame(columns=['motif', 'length', 'position', 'num_sequences', 'avg_log2fc', 'fraction_depleted'])

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values(
        by=['fraction_depleted', 'avg_log2fc', 'num_sequences'],
        ascending=[False, True, False]
    )
    results_df = results_df.loc[results_df['fraction_depleted'] >= score_thr]
    return results_df

In [ ]:
depleted_motifs_df=identify_depleted_motifs_scanning_ends(log2fc_df["JJ1886_T0"])
depleted_motifs_df.head(10)

Analyzing motifs of length 1 to 6, scanning positions 0 to 7 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)

        motif  length  position  num_sequences  avg_log2fc  fraction_depleted
9827    AAAAG       5        11             10   -5.662158                1.0
24677  GTGCGG       6         0              6   -5.490821                1.0
14175   AAAGT       5        12             13   -5.262390                1.0
14176   CAAAG       5        11             16   -5.201596                1.0
19651   GTGCG       5         0             10   -5.107176                1.0
2921     AAAG       4        12             42   -5.076919                1.0
2931    AAAGC       5        12              9   -5.029139                1.0
19268   AAAGA       5        12             13   -4.996286                1.0
11517   GTGTC       5         0              6   -4.959089                1.0
26164   AAAGG       5        12              7   -4.943650                1.0

### Trimming to the core motif

Having found `GTG` at offset 0, the scan will also find `GTGA`, `CGTGA` and so on at the same
offset. Only one of them is the site; the others are it plus a neighbouring base that happens to
be common.

The rule: **keep the longer motif only if the extra base earns its place**, i.e. raises the
depletion fraction by more than a margin. If it does not, the extra base is not part of the
recognition site and the shorter core is the real motif.

This comparison used to be inverted, in both directions at once — a longer motif was kept only
when it scored *worse* than the core it contains, and the margin had the wrong sign. The hidden
cell below checks all four cases on hand-made tables, including the one the old code got visibly
wrong: with `GTG` at 0.90 and `GTGA` at 0.40, it kept `GTGA`.

In [ ]:
#| export
def filter_to_core_motifs(depleted_motifs_df, 
                          score_improvement_margin=0.05):
    """
    Filters a DataFrame of depleted motifs to identify underlying "core" motifs.
    A longer motif is kept only if it's significantly better than a shorter core motif it contains.

    Args:
        depleted_motifs_df (pd.DataFrame): DataFrame from identify_depleted_motifs_scanning_ends.
        score_improvement_margin (float): how much better a longer motif's 'fraction_depleted'
                                          must be than the core motif's before the extra base is
                                          treated as part of the site.

    Returns:
        pd.DataFrame: A filtered DataFrame containing potentially core motifs.
    """
    if depleted_motifs_df.empty:
        return pd.DataFrame(columns=depleted_motifs_df.columns)

    sorted_df = depleted_motifs_df.sort_values(
        by=['length','fraction_depleted'],
        ascending=[True, False]
    ).reset_index(drop=True)

    core_motifs_list = []
    
    for idx, candidate_row in sorted_df.iterrows():
        candidate_motif = candidate_row['motif']
        candidate_pos = candidate_row['position']
        candidate_len = candidate_row['length']
        candidate_score = candidate_row['fraction_depleted']
        
        is_subsumed = False
        for core_dict in core_motifs_list: 
            core_motif = core_dict['motif']
            core_pos = core_dict['position']
            core_len = core_dict['length']
            core_score = core_dict['fraction_depleted']
            
            if core_len < candidate_len and core_motif in candidate_motif:    
                relative_start = candidate_motif.find(core_motif)
                if candidate_pos + relative_start == core_pos:
                    # Keep the longer motif only if the extra base earns its place, i.e.
                    # if it raises the depletion fraction by more than the margin. If it
                    # does not, the extra base is not part of the recognition site and the
                    # shorter core is the real motif.
                    earns_its_place = candidate_score > core_score + score_improvement_margin

                    if not earns_its_place:
                        is_subsumed = True
                        break 
        
        if not is_subsumed:
            core_motifs_list.append(candidate_row.to_dict())
            
    if not core_motifs_list:
         return pd.DataFrame(columns=depleted_motifs_df.columns)
    return pd.DataFrame(core_motifs_list)

In [ ]:
#| hide
# filter_to_core_motifs on hand-made tables, where the right answer is obvious.
import pandas as pd

def _row(motif, pos, frac):
    return dict(motif=motif, position=pos, length=len(motif),
                fraction_depleted=frac, num_sequences=100, avg_log2fc=-2.0)

# The extra base adds nothing (0.90 -> 0.91, margin 0.05): the core is the real motif.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 0, 0.91)])
assert list(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif) == ["GTG"]

# The extra base matters (0.50 -> 0.95): keep both.
_t = pd.DataFrame([_row("GTG", 0, 0.50), _row("GTGA", 0, 0.95)])
assert sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif) == ["GTG", "GTGA"]

# The longer motif is WORSE (0.90 -> 0.40). The comparison used to be inverted here and
# kept GTGA precisely because it was worse.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 0, 0.40)])
assert list(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif) == ["GTG"]

# Same sequence, different position: not nested, so both stand.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 5, 0.91)])
assert sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif) == ["GTG", "GTGA"]
print("ok")

ok

In [ ]:
depleted_motifs_df=filter_to_core_motifs(depleted_motifs_df)
depleted_motifs_df.head(10)

  motif  length  position  num_sequences  avg_log2fc  fraction_depleted
0   GTG       3         0            187   -4.764500                1.0
1  AAAG       4        12             42   -5.076919                1.0

In [ ]:
#| export
def get_fold_change_values_per_site(site_sets_list, fold_changes_list):
    """
    Computes a dictionary mapping each unique site to a list of its associated
    log2 Fold Change (FC) values using collections.defaultdict for optimization.

    Args:
        site_sets_list (list): A list of sets, where each set contains the 
                               sequence motifs found in a member of the library.
        fold_changes_list (list): A list of log2FC values, corresponding to each
                                  sequence in the library.

    Returns:
        dict: A dictionary where keys are sequence motifs and values are numpy arrays
              containing the log2FC values associated with that site.
    """
    # Step 1: Initialize a defaultdict to store lists of FC values for each site.
    # defaultdict(list) will automatically create a new list for a site
    # the first time it's encountered.
    site_to_fcs_map_intermediate = defaultdict(list)

    # Step 2: Iterate through the site sets and their corresponding fold changes.
    # zip() pairs each site_set with its fc_value.
    for site_set, fc_value in zip(site_sets_list, fold_changes_list):
        # For each site in the current set, append the fc_value
        # to the list associated with that site in the dictionary.
        for site in site_set:
            site_to_fcs_map_intermediate[site].append(fc_value)

    # Step 3: Convert the lists of FC values to NumPy arrays.
    # This is done after all values are collected to efficiently create the arrays.
    site_to_fcs_map_final = {
        site: np.array(fcs_list)
        for site, fcs_list in site_to_fcs_map_intermediate.items()
    }

    return site_to_fcs_map_final

In [ ]:
pattern=(3,6,4)
set_list=get_sites_in_seq(lib,pattern=pattern,no_ori=True)
site_FCs=get_fold_change_values_per_site(set_list,log2fc_df["JJ1886_T0"].values)
site_FCs["AGCNNNNNNGGGA"]

array([ 0.02025893, -0.15083807,  0.19052559,  0.04266223,  0.22493562,
       -0.13188093,  0.0203179 ,  0.10373391, -0.18265707,  0.24137364,
       -0.10160173,  0.5539999 ,  0.19568499,  0.29179059, -0.02109236,
       -0.46896125,  0.00812423])

## Step 2: set those sequences aside — but only for discovery

Sequences carrying a fixed-position motif are removed **before** the position-independent scan,
so that a flank-driven site does not dominate the search and swamp everything else.

They are **not** removed before the rescoring in step 5. That asymmetry is deliberate and it is
worth justifying, because it looks inconsistent.

Measured on B156, for the motif `AAACNNNNGTC`:

| plasmids | depletion rate |
|---|---|
| 376 carrying the fixed motif | 0.952 |
| the other 507 | 0.966 |

Statistically the same. Those 376 are **43% of the motif's total support**, and they are genuine
evidence — excluding them from the scoring would throw away nearly half the data for no reason.

The counter-example, in the same strain, shows why one has to check rather than assume. For
`AAAGNNNNGTT` — which is JJ1886's motif, not B156's — the 9 plasmids carrying the fixed motif
deplete at 1.000 while the other 888 deplete at 0.057. There, the fixed-motif sequences really
are carrying depletion that has nothing to do with the motif being scored. It stays far below
threshold, so nothing is called, but that is the failure mode this asymmetry risks.

In [ ]:
#| export
def filter_sequences_without_core_motifs(log2fc_series, core_motifs_df):
    """
    Filters an original log2fc Series to remove sequences that contain 
    any of the specified core motifs.

    Args:
        log2fc_series (pd.Series): Series with sequences as its index and log2FC values.
        core_motifs_df (pd.DataFrame): DataFrame of core motifs, must include
                                       'motif', 'position', and 'length' columns.

    Returns:
        pd.Series: A new Series containing only sequences (and their log2FC values)
                   from log2fc_series that do not carry any of the core motifs.
    """
    if not isinstance(log2fc_series, pd.Series) or log2fc_series.empty:
        # print("Info: log2fc_series is empty or not a Series. Returning a copy.")
        return log2fc_series.copy() 
    
    expected_core_motif_cols = ['motif', 'position', 'length']
    if not isinstance(core_motifs_df, pd.DataFrame) or core_motifs_df.empty or \
       not all(col in core_motifs_df.columns for col in expected_core_motif_cols):
        print("Info: core_motifs_df is empty or invalid for filtering. Returning original log2fc_series.")
        return log2fc_series.copy()

    # Create a boolean mask, True for sequences to keep
    sequences_to_keep_mask = pd.Series(True, index=log2fc_series.index)

    # Iterate through each unique sequence string in the original Series' index
    # Using .loc for assignment to the mask handles duplicate indices in the original Series correctly
    for seq_str_to_check in log2fc_series.index.unique(): 
        if not isinstance(seq_str_to_check, str): 
            continue # Skip if index label is not a string
        
        # Check this sequence against all core motifs
        for _, motif_row in core_motifs_df.iterrows():
            motif_str = motif_row['motif']
            try:
                position = int(motif_row['position'])
                motif_len = int(motif_row['length'])
            except (ValueError, TypeError):
                # print(f"Warning: Invalid position/length for motif {motif_str} in core_motifs_df. Skipping this motif.")
                continue 

            if not isinstance(motif_str, str) or not motif_str: 
                continue

            if len(seq_str_to_check) >= position + motif_len:
                if seq_str_to_check[position : position + motif_len] == motif_str:
                    # If a motif is found, mark all occurrences of this sequence string for removal
                    sequences_to_keep_mask.loc[log2fc_series.index == seq_str_to_check] = False 
                    break # Move to the next unique sequence_str_to_check

    return log2fc_series[sequences_to_keep_mask]

In [ ]:
#| export
def get_sites_scores(site_FCs, pattern, log2FC_thr=-1):
    """ 
    Scores sites based on depletion and occurrence.
    Returns a pandas DataFrame with 'site', 'fraction_depleted', 'num_sequences', 'avg_log2fc'.
    """
    site_scores_list = []
    
    for site_key, fc_values in site_FCs.items():
        if not isinstance(fc_values, (list, np.ndarray)) or len(fc_values) == 0:
            continue # Skip if fc_values is not a list/array or is empty
            
        current_score = score(fc_values, log2FC_thr)
        num_occurrences = len(fc_values)
        avg_fc = np.mean(fc_values) if num_occurrences > 0 else np.nan
        
        site_scores_list.append({
            'motif': site_key,
            'fraction_depleted': current_score,
            'num_sequences': num_occurrences,
            'avg_log2fc': avg_fc
        })
            
    if not site_scores_list:
        return pd.DataFrame(columns=['motif', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
    return pd.DataFrame(site_scores_list)

In [ ]:
site_scores = get_sites_scores(site_FCs,pattern)
site_scores.sort_values(by=['fraction_depleted', 'num_sequences'], ascending=[False, False]).head(10)

               motif  fraction_depleted  num_sequences  avg_log2fc
16368  AGGNNNNNNCCTC           1.000000              1   -4.601867
16373  GAGNNNNNNCCCC           1.000000              1   -1.406262
3435   CACNNNNNNATTA           0.958974            195   -4.569183
3431   AATNNNNNNGTGC           0.826923             52   -3.962960
9124   AATNNNNNNGTGG           0.815385             65   -3.883041
3156   TAANNNNNNTGTG           0.785714            238   -3.746732
1071   AATNNNNNNGTGA           0.771429             70   -3.628320
15087  GAGNNNNNNGTCT           0.750000              4   -4.012801
9574   AATNNNNNNGTGT           0.740741             54   -3.485249
16126  GGTNNNNNNAGGA           0.666667              3   -2.235343

### Fast pattern scan

`get_sites_in_seq` → `get_fold_change_values_per_site` → `get_sites_scores` above is the readable reference implementation: it builds a Python set of motif strings for every sequence. On a BB2 library (30k sequences of ~150 nt plus context) that takes ~10 s and ~2 GB of RAM per pattern.

`get_pattern_scores` computes the same table with numpy. A motif of pattern `(d1, spacer, d2)` is fully described by its `d1 + d2` defined bases, so it can be stored as an integer in `[0, 4**(d1+d2))` (2 bits per base, A=0, C=1, G=2, T=3). Every per-motif statistic then becomes an `np.bincount`. The library is encoded once with `encode_library` and reused for every pattern.

In [ ]:
#| export
_BASE_CODES = np.full(256, 4, dtype=np.uint8)  # 4 = anything that is not A/C/G/T
for _i, _b in enumerate("ACGT"):
    _BASE_CODES[ord(_b)] = _BASE_CODES[ord(_b.lower())] = _i
_CODE_BASES = np.frombuffer(b"ACGT", dtype=np.uint8)

def encode_library(sequences):
    """
    Encodes DNA sequences as 2-bit base codes for `get_pattern_scores`.

    Args:
        sequences (list): DNA strings (typically library sequences with context);
            they may have different lengths.

    Returns:
        tuple: (fwd, rc) uint8 arrays of shape (n_sequences, max_length) holding the
            base codes of each sequence and of its reverse complement. A=0, C=1, G=2,
            T=3; non-ACGT characters and the padding of shorter sequences are 4.
    """
    max_len = max(len(s) for s in sequences)
    fwd = np.full((len(sequences), max_len), 4, dtype=np.uint8)
    rc = np.full_like(fwd, 4)
    for i, s in enumerate(sequences):
        codes = _BASE_CODES[np.frombuffer(s.encode(), dtype=np.uint8)]
        fwd[i, :len(s)] = codes
        rc[i, :len(s)] = np.where(codes < 4, 3 - codes, 4)[::-1]  # A<->T, C<->G
    return fwd, rc

In [ ]:
fwd, rc = encode_library(["ACGTT", "ggN"])
test_eq(fwd, np.array([[0, 1, 2, 3, 3], [2, 2, 4, 4, 4]]))
test_eq(rc,  np.array([[0, 0, 1, 2, 3], [4, 1, 1, 4, 4]]))  # AACGT and NCC, padded

In [ ]:
#| export
def _pattern_window_codes(encoded_seqs, pattern):
    """
    Motif code of every window of every sequence for `pattern` (d1, spacer, d2).
    Returns an int32 array of shape (n_sequences, n_windows); windows containing a
    base coded 4 (non-ACGT or padding) get the out-of-range code 4**(d1+d2).
    """
    d1, spacer, d2 = pattern
    width = d1 + spacer + d2
    n_windows = encoded_seqs.shape[1] - width + 1
    codes = np.zeros((encoded_seqs.shape[0], n_windows), dtype=np.int32)
    for j in list(range(d1)) + list(range(d1 + spacer, width)):  # defined positions only
        codes *= 4
        codes += encoded_seqs[:, j:j + n_windows]
    # Like the [ATGC] regex, reject windows with a non-ACGT base anywhere, spacer included.
    n_bad = np.zeros((encoded_seqs.shape[0], encoded_seqs.shape[1] + 1), dtype=np.int32)
    np.cumsum(encoded_seqs == 4, axis=1, out=n_bad[:, 1:])
    codes[n_bad[:, width:] != n_bad[:, :n_windows]] = 4 ** (d1 + d2)
    return codes

def decode_motif_codes(codes, pattern):
    """
    Converts integer motif codes of `pattern` (d1, spacer, d2) back to motif strings
    with 'N' in the spacer, e.g. CACNNNNGTAT for pattern (3, 4, 4).
    """
    d1, spacer, d2 = pattern
    n_defined = d1 + d2
    codes = np.asarray(codes, dtype=np.int64)
    out = np.full((len(codes), d1 + spacer + d2), ord("N"), dtype=np.uint8)
    bases = _CODE_BASES[(codes[:, None] >> (2 * np.arange(n_defined - 1, -1, -1))) & 3]
    out[:, :d1], out[:, d1 + spacer:] = bases[:, :d1], bases[:, d1:]
    return out.view(f"S{out.shape[1]}").ravel().astype(str).tolist()

With pattern `(1, 2, 2)`, `CAAGT` has a single window whose defined bases are C, G, T, i.e. code `1*16 + 2*4 + 3 = 27`. A window touching the `N` is rejected (code `4**3 = 64`):

In [ ]:
fwd, rc = encode_library(["CAAGT", "CAAGTN"])
test_eq(_pattern_window_codes(fwd, (1, 2, 2)), np.array([[27, 64], [27, 64]]))
test_eq(decode_motif_codes([27, 0], (1, 2, 2)), ["CNNGT", "ANNAA"])

## Is a motif's depletion more than the sample's own noise?

A scan tests an enormous number of motifs — 183,000 on the smaller example library, 750,000 on
the larger — so some will look perfect by luck alone. How many supporting plasmids a call needs
before that stops being a plausible explanation depends on the sample, not on a constant.

Under the null, a motif's depleted count is `Binomial(n, p)` where **`p` is that sample's own
background depletion rate**: the fraction of plasmids depleted when no site is involved. A noisy
sample has a higher `p` and therefore needs more evidence for the same claim, automatically.

This was checked against a permutation test that removes the plasmids carrying the confident
calls and reshuffles the rest, so that nothing real remains:

| | binomial expectation | permutation, 20 runs |
|---|---|---|
| JJ1886, n=3–4 (p=0.0178) | 0.60 spurious calls | 0.8 (max 4) |
| JJ1886, n≥5 | 0.01 | 0 |
| 12049, all n (p=0.0124) | 0.00 | 0 |

The two agree, so the analytic form can be computed for every candidate at no cost, where the
permutation takes minutes per sample. `work/permutation_fdr.py` is kept as an occasional
calibration check rather than part of the analysis.

It also explains something a fixed `min_support` cannot. 12049 is safe at n=3 not because it is
a cleaner sample but because its larger library leaves far fewer motifs sitting at tiny n.

**What this does not model.** The binomial treats a motif's plasmids as independent draws. They
are not: motifs co-occur, which is the whole subject of step 4b above. So the p-value is a screen
against chance, not a complete model of how a spurious call arises — a shadow of a real site is
highly significant by this test and still needs explaining away.

In [ ]:
#| export
def background_depletion_rate(log2fc_series, log2fc_thr=-1):
    """The fraction of plasmids depleted in this sample when no motif is involved.

    Estimated as the median-centred bulk of the library: the overwhelming majority of random
    inserts carry no recognition site, so the sample-wide rate is a good estimate of the null
    and needs no knowledge of which motifs are real.
    """
    v = np.asarray(log2fc_series, dtype=float)
    return float((v < log2fc_thr).mean()) if len(v) else 0.0


def motif_pvalues(num_sequences, fraction_depleted, background_rate):
    """P(at least this many of n plasmids depleted | null), per motif.

    Vectorized over a whole score table; the cost is negligible beside the scan itself.
    """
    n = np.asarray(num_sequences, dtype=np.int64)
    k = np.rint(np.asarray(fraction_depleted, dtype=float) * n).astype(np.int64)
    if background_rate <= 0:
        return np.where(k > 0, 0.0, 1.0)
    return binom.sf(k - 1, n, background_rate)


def benjamini_hochberg(pvalues):
    """BH-adjusted q-values. The scan tests every motif of every pattern, so the number of
    tests is large and sample-specific; correcting for it is not optional."""
    p = np.asarray(pvalues, dtype=float)
    n = len(p)
    if n == 0:
        return p
    order = np.argsort(p)
    ranked = p[order] * n / np.arange(1, n + 1)
    ranked = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.clip(ranked, 0, 1)
    return out

In [ ]:
#| export
def get_pattern_scores(encoded_library, fc_values, pattern, log2FC_thr=-1,
                       background_rate=None):
    """
    Scores every motif of `pattern` found in the library, on both strands.

    Vectorized equivalent of
    `get_sites_scores(get_fold_change_values_per_site(get_sites_in_seq(seqs, pattern, no_ori=True), fc_values), pattern, log2FC_thr)`:
    a motif is counted once per sequence that contains it on either strand.

    Args:
        encoded_library (tuple): (fwd, rc) arrays from `encode_library`.
        fc_values (list or np.ndarray): log2FC of each sequence, in library order.
        pattern (tuple): (d1, spacer, d2) motif pattern.
        log2FC_thr (float): a sequence is depleted when its log2FC is below this value.

    Returns:
        pd.DataFrame: one row per motif with 'motif', 'fraction_depleted',
            'num_sequences' and 'avg_log2fc', ordered by the first sequence that
            contains the motif.
    """
    fwd, rc = encoded_library
    fc_values = np.asarray(fc_values, dtype=float)
    n_codes = 4 ** (pattern[0] + pattern[2])
    codes = np.concatenate([_pattern_window_codes(fwd, pattern), _pattern_window_codes(rc, pattern)], axis=1)
    # Keep each motif once per sequence: sort each row and drop repeats and rejected windows.
    codes.sort(axis=1)
    keep = codes < n_codes
    keep[:, 1:] &= codes[:, 1:] != codes[:, :-1]
    seq_idx = np.nonzero(keep)[0]
    motif_codes = codes[keep]
    seq_fc = fc_values[seq_idx]
    n_seqs = np.bincount(motif_codes, minlength=n_codes)
    n_depleted = np.bincount(motif_codes, weights=seq_fc < log2FC_thr, minlength=n_codes)
    fc_sum = np.bincount(motif_codes, weights=seq_fc, minlength=n_codes)
    first_seq = np.full(n_codes, len(fc_values))
    np.minimum.at(first_seq, motif_codes, seq_idx)
    present = np.flatnonzero(n_seqs)
    present = present[np.argsort(first_seq[present], kind="stable")]
    frac = n_depleted[present] / n_seqs[present]
    if background_rate is None:
        background_rate = float((fc_values < log2FC_thr).mean())
    return pd.DataFrame({
        'motif': decode_motif_codes(present, pattern),
        'fraction_depleted': frac,
        'num_sequences': n_seqs[present],
        'avg_log2fc': fc_sum[present] / n_seqs[present],
        # Against this sample's own noise, not a global constant.
        'p_value': motif_pvalues(n_seqs[present], frac, background_rate),
    })

A small example that can be checked by hand. `GAGACC` is in the first two sequences, and so is its reverse complement `GGTCTC` (found on the other strand). Only the first sequence is depleted (log2FC below -1):

In [ ]:
toy_scores = get_pattern_scores(encode_library(["GAGACCTT", "AAGAGACC", "TTTTTTTT"]), [-2, 0.5, -3], (6, 0, 0))
toy = toy_scores.set_index('motif')
# Named columns, so adding a statistic to the table does not break the check.
cols = ['fraction_depleted', 'num_sequences', 'avg_log2fc']
test_eq(toy.loc['GAGACC', cols].tolist(), [0.5, 2, -0.75])
test_eq(toy.loc['GGTCTC', cols].tolist(), [0.5, 2, -0.75])   # the same site, other strand
test_eq(toy.loc['TTTTTT', cols].tolist(), [1.0, 1, -3.0])
toy_scores

     motif  fraction_depleted  num_sequences  avg_log2fc   p_value
0   AAGGTC                1.0              1       -2.00  0.666667
1   AGACCT                1.0              1       -2.00  0.666667
2   AGGTCT                1.0              1       -2.00  0.666667
3   GACCTT                1.0              1       -2.00  0.666667
4   GAGACC                0.5              2       -0.75  0.888889
5   GGTCTC                0.5              2       -0.75  0.888889
6   AAGAGA                0.0              1        0.50  1.000000
7   AGAGAC                0.0              1        0.50  1.000000
8   GTCTCT                0.0              1        0.50  1.000000
9   TCTCTT                0.0              1        0.50  1.000000
10  AAAAAA                1.0              1       -3.00  0.666667
11  TTTTTT                1.0              1       -3.00  0.666667

`get_pattern_scores` gives exactly the same table as the reference implementation, here on the JJ1886 library for patterns with and without a spacer, and on sequences of different lengths containing an `N`:

In [ ]:
def _reference_scores(seqs, fcs, pattern):
    ref = get_sites_scores(get_fold_change_values_per_site(get_sites_in_seq(seqs, pattern, no_ori=True), fcs), pattern)
    return ref.set_index('motif').sort_index()

def _check_same_scores(seqs, fcs, pattern):
    ref = _reference_scores(seqs, fcs, pattern)
    fast = get_pattern_scores(encode_library(seqs), fcs, pattern).set_index('motif').sort_index()
    test_eq(fast.index.tolist(), ref.index.tolist())
    test_eq(fast.num_sequences.tolist(), ref.num_sequences.tolist())
    assert np.allclose(fast.fraction_depleted, ref.fraction_depleted, rtol=0, atol=1e-12)
    assert np.allclose(fast.avg_log2fc, ref.avg_log2fc, rtol=0, atol=1e-9)
    return len(ref)

fcs = log2fc_df["JJ1886_T0"].values
for pattern in [(6, 0, 0), (2, 1, 3), (4, 4, 3), (3, 6, 4)]:
    print(pattern, _check_same_scores(lib, fcs, pattern), "motifs identical")
_check_same_scores(["ACGTACGTTTGACCAAAG", "GGGGCACAAAAGTATCC", "TTGACAANCCGTAC"], [-2., 0.5, -3.], (3, 4, 4))

(6, 0, 0) 4096 motifs identical
(2, 1, 3) 1024 motifs identical
(4, 4, 3) 16382 motifs identical
(3, 6, 4) 16377 motifs identical

30

In [ ]:
#| export
def process_single_flexible_pattern(
    current_flex_pattern,
    encoded_library,
    fc_values_for_flexible_analysis,
    flexible_motif_log2fc_thr,
    flexible_motif_score_thr,
    flexible_motif_min_support,
    return_pvalues=False
):
    """
    Scores all motifs of one flexible pattern and keeps the candidates with
    fraction_depleted >= flexible_motif_score_thr and num_sequences >= flexible_motif_min_support.

    Args:
        current_flex_pattern (tuple): (d1, spacer, d2) motif pattern.
        encoded_library (tuple): (fwd, rc) arrays from `encode_library` (sequences with context).
        fc_values_for_flexible_analysis (list): log2FC of each sequence, in library order.
        flexible_motif_log2fc_thr (float): log2FC below which a sequence counts as depleted.
        flexible_motif_score_thr (float): minimum fraction_depleted (exclusive).
        flexible_motif_min_support (int): minimum number of sequences (exclusive).

    Returns:
        pd.DataFrame: candidate motifs with 'motif', 'fraction_depleted', 'num_sequences',
            'avg_log2fc' and 'pattern' (the pattern as a string).
    """
    scores = get_pattern_scores(encoded_library, fc_values_for_flexible_analysis,
                                current_flex_pattern, log2FC_thr=flexible_motif_log2fc_thr)
    scores['pattern'] = str(current_flex_pattern)
    kept = scores[(scores['fraction_depleted'] >= flexible_motif_score_thr) &
                  (scores['num_sequences'] >= flexible_motif_min_support)]
    if return_pvalues:
        # every motif with enough support was a test, and the multiple-testing
        # correction has to know about all of them, not just the survivors
        tested = scores[scores['num_sequences'] >= flexible_motif_min_support]
        return kept, tested['p_value'].to_numpy()
    return kept

In [ ]:
candidates = process_single_flexible_pattern((4, 4, 3), encode_library(lib), fcs, -1, 0.7, 3)
assert {"ATACNNNNGTG", "AAAGNNNNGTT"} <= set(candidates.motif)
candidates.sort_values('num_sequences', ascending=False).head()

            motif  fraction_depleted  ...        p_value    pattern
3280  CACANNNNTAT           0.964467  ...  2.555113e-250  (4, 4, 3)
3276  ATACNNNNGTG           1.000000  ...  2.946431e-265  (4, 4, 3)
6403  TCACNNNNGTA           0.849315  ...   8.486502e-74  (4, 4, 3)
7377  CCACNNNNGTA           0.907692  ...   3.305633e-74  (4, 4, 3)
2573  AAAGNNNNGTT           1.000000  ...   1.588045e-87  (4, 4, 3)

[5 rows x 6 columns]

## Step 4: removing redundant descriptions of the same motif

The scan enumerates many patterns, so one real site gets described several ways at once. A motif
is dropped when another motif in the set describes the same thing at least as well:

- a **specific** motif is dropped if the **general** one it is a version of is not significantly
  worse — the extra bases add nothing
- a **general** motif is dropped if a **specific** version is significantly better — the extra
  bases matter
- of two equivalent motifs, the lower-scoring one goes

### Why the order candidates arrive in must not matter

A motif and its reverse complement always score identically, so the last rule is a tie, and ties
used to be broken on **row position**. That made the answer depend on the order patterns happened
to be scanned in — and the serial and pooled scans use different orders, so the same candidates
could be filtered two different ways.

Candidates are now sorted on their own content before processing and ties are broken on the
motif string. `tests/test_order_independence.py` checks this by filtering shuffled copies of real
candidate sets and asserting the answer does not move.

### What this filter cannot do, and why it matters

It collapses motifs related by **IUPAC generality** — one being a degenerate version of another.
It does not collapse motifs related by **shift in register**, because as strings those are
unrelated.

That gap is visible on LMR_503. The site there is `CACNNNNGTAY`, and the candidate set contains
eight descriptions of it:

| candidate | decomposes as |
|---|---|
| `CACNNNNGTAC` | `CAC-NNNN-GTA` + `C` |
| `TACNNNNGTGG` | `C` + `CAC-NNNN-GTA` |
| `CACTNNAGTA` | `CAC-TNNA-GTA` |
| `CACANNGGTA` | `CAC-ANNG-GTA` |

All at spacer 4 — the same site, over-specified. They are not alternative spacings: holding the
half-sites fixed and varying only the spacer gives median log2FC −1.81 at spacer 4 against −0.03
at every other spacing, with an RM-knockout strain flat throughout as a control.

The filter cannot collapse them to `CACNNNNGTA` because the real site is degenerate at the last
position, so `CACNNNNGTA` also matches uncut sites and scores about half as well (0.52 against
1.00). The rule correctly declines to prefer a genuinely worse general motif. The design simply
has no way to say *these eight are one site with a degenerate position*.

The consequence lands in step 5.

In [ ]:
#| export
def filter_redundant_patterns(df, score_margin=0.05):
    """
    Filters a DataFrame of patterns, removing redundant motifs based on
    specificity and a score condition.

    A motif 'p1' is considered redundant and removed if there is another
    motif 'p2' in the DataFrame such that:

    1. p1 is a specific version of p2 AND
       p2.score > p1.score - score_margin
       (general is not significantly worse  → drop specific)

    OR

    2. p1 is a general version of p2 AND
       p2.score > p1.score + score_margin
       (specific is significantly better → drop general)

    3. For equivalent motifs the one with the lower score is dropped.
       If scores are equal, the tie is broken on the motif string, so the outcome does not
       depend on the order the candidates were produced in.

    Args:
        df (pd.DataFrame): DataFrame with 'motif' and 'fraction_depleted'
            columns.
        score_margin (float): Margin used to relax score comparisons.

    Returns:
        pd.DataFrame: A filtered DataFrame with redundant rows removed.
    """
    indices_to_drop = set()
    df_reset = df.reset_index()

    # Process candidates in a fixed, content-derived order. Without this the outcome depends on
    # the order patterns happened to be scanned in -- which differs between the single-process
    # and multiprocessing pipelines, and between runs -- so the same set of candidates could be
    # filtered two different ways. Sorting here makes the result a function of the candidate
    # SET alone.
    _sort_on = ['_canonical', 'motif']
    df_reset['_canonical'] = df_reset['motif'].map(canonical_motif)
    if 'pattern' in df_reset.columns:
        df_reset['_pattern'] = df_reset['pattern'].astype(str)
        _sort_on = ['_pattern'] + _sort_on
    df_reset = (df_reset.sort_values(_sort_on, kind='mergesort')
                        .drop(columns=[c for c in ('_canonical', '_pattern') if c in df_reset])
                        .reset_index(drop=True))

    for i, p1 in df_reset.iterrows():
        if i in indices_to_drop:
            continue

        for j, p2 in df_reset.iterrows():
            if i == j or j in indices_to_drop:
                continue

            motif1, score1 = p1['motif'], p1['fraction_depleted']
            motif2, score2 = p2['motif'], p2['fraction_depleted']

            is_p1_subset_of_p2 = find_broad_in_specific(motif1, motif2)

            if not is_p1_subset_of_p2:
                continue

            is_p2_subset_of_p1 = find_broad_in_specific(motif2, motif1)

            if not is_p2_subset_of_p1:
                # p1 is STRICTLY more specific than p2 (p2 is the general motif).

                if score2 > score1 - score_margin:
                    # General motif (p2) is not significantly worse → drop
                    # the specific one (p1).
                    indices_to_drop.add(i)
                    break

                elif score1 > score2 + score_margin:
                    # Specific motif (p1) is significantly better → drop
                    # the general one (p2).
                    indices_to_drop.add(j)
                    # Do NOT break: p1 might still be redundant w.r.t. other
                    # motifs in a later iteration.

            else:
                # p1 and p2 are equivalent.  Drop the worse one; break ties
                # by higher reset-index.
                if score1 < score2:
                    indices_to_drop.add(i)
                    break
                elif score1 == score2 and motif1 > motif2:
                    # Equal scores: break the tie on the motif itself, not on row position.
                    # A motif and its reverse complement always score identically, so this is
                    # the common case; deciding it by position is what made the choice of
                    # strand depend on scan order. The label is canonicalised on output
                    # anyway, so which of the pair survives here is not user-visible.
                    indices_to_drop.add(i)
                    break

    original_indices_to_drop = df_reset.loc[list(indices_to_drop)]['index']
    return df.drop(original_indices_to_drop)

## Reading motif presence off the window codes

Step 5 asks one question of every candidate: which sequences contain it, on either strand? That
used to be a Python regex evaluated per sequence per motif, then every pair of motifs
intersected — both halves quadratic.

`_pattern_window_codes` above already computes the integer code of every window of every
sequence, so presence is a **lookup in that array**, done once per pattern instead of once per
motif. On the real panel this took the rescoring step from 4.6 s to 0.7 s, and it is why an
RM-deficient strain is no longer the slow case.

`encode_motif` is the inverse of `decode_motif_codes`. It returns `None` for anything it cannot
represent — an IUPAC-degenerate motif has no single code — and those fall back to the regex, so
the answer is unchanged rather than approximated. Getting that wrong would silently mis-assign
sequences, so `tests/test_vectorized_presence.py` checks the two agree element for element, not
just on summary statistics.

In [ ]:
#| export
def encode_motif(motif, pattern):
    """Integer code of `motif` under `pattern`, inverse of `decode_motif_codes`.

    Returns None if the motif does not fit the pattern or contains a base outside ACGT --
    IUPAC-degenerate motifs have no single code and fall back to the regex path.
    """
    d1, spacer, d2 = pattern
    if len(motif) != d1 + spacer + d2:
        return None
    defined = motif[:d1] + motif[d1 + spacer:]
    if d1 + spacer + d2 and any(c != "N" for c in motif[d1:d1 + spacer]):
        return None                       # spacer must be undefined
    code = 0
    for ch in defined:
        v = "ACGT".find(ch)
        if v < 0:
            return None
        code = code * 4 + v
    return code

In [ ]:
#| export
def motif_presence_matrix(encoded_library, motifs, patterns):
    """Boolean (n_sequences, n_motifs): does sequence i contain motif j, on either strand?

    One pass per distinct pattern rather than one per motif, and a lookup into the window codes
    rather than a regex per sequence. Motifs whose pattern is unknown, or which contain IUPAC
    ambiguity codes, are left as all-False here; the caller falls back to the regex path for
    those, so behaviour is unchanged and only the common case gets faster.

    Returns `(matrix, handled)` where `handled` marks the motifs the matrix actually covers.
    """
    fwd, rc = encoded_library
    n_seq = fwd.shape[0]
    matrix = np.zeros((n_seq, len(motifs)), dtype=bool)
    handled = np.zeros(len(motifs), dtype=bool)

    by_pattern = defaultdict(list)
    for j, (motif, pattern) in enumerate(zip(motifs, patterns)):
        if pattern is None:
            continue
        code = encode_motif(motif, pattern)
        if code is not None:
            by_pattern[pattern].append((j, code))

    for pattern, entries in by_pattern.items():
        n_codes = 4 ** (pattern[0] + pattern[2])
        # code -> column in `matrix`, or -1 for codes we do not care about
        lookup = np.full(n_codes + 1, -1, dtype=np.int32)
        for j, code in entries:
            lookup[code] = j
        codes = np.concatenate(
            [_pattern_window_codes(fwd, pattern), _pattern_window_codes(rc, pattern)], axis=1)
        cols = lookup[codes]
        rows, where = np.nonzero(cols >= 0)
        if len(rows):
            matrix[rows, cols[rows, where]] = True
        for j, _ in entries:
            handled[j] = True

    return matrix, handled

In [ ]:
#| export
def _unique_hit_stats(matrix, fc_values, log2fc_thr):
    """Per-motif statistics over sequences carrying exactly one of the motifs in `matrix`.

    Co-occurring motifs are the reason this step exists: a sequence carrying two candidates
    cannot tell us which one depleted it, so it is excluded from both. Counting how many
    candidates each sequence carries, once, replaces intersecting every pair of motifs.
    """
    fc = np.asarray(fc_values, dtype=float)
    only_one = matrix.sum(axis=1) == 1
    unique = matrix & only_one[:, None]
    n_seqs = unique.sum(axis=0)
    with np.errstate(invalid="ignore", divide="ignore"):
        n_depleted = (unique & (fc < log2fc_thr)[:, None]).sum(axis=0)
        fc_sum = (unique * fc[:, None]).sum(axis=0)
        frac = np.where(n_seqs > 0, n_depleted / np.maximum(n_seqs, 1), 0.0)
        # 0.0 rather than NaN for a motif with no unique sequences, matching
        # the behaviour this replaced; such motifs are dropped by the filter anyway.
        avg = np.where(n_seqs > 0, fc_sum / np.maximum(n_seqs, 1), 0.0)
    return n_seqs, frac, avg

## Step 4b: drop candidates whose signal a stronger motif already explains

The redundancy filter above compares motif *strings*. That catches a motif that is a degenerate
version of another, but not a motif that describes the same site in a way the string comparison
cannot see — a different length, a different pattern, or the other strand.

On LMR_503 the site is `CACNNNNGTAY`, and 19 further candidates survive string-based filtering:
`TACNNNNGTGG`, `CACTNNAGTA`, `ACACNNNAGTA` and so on. Decoding them, every one is
`CAC-NNNN-GTA` at the same spacing, with an extra base pinned somewhere that does not matter and
**the `Y` position left free**. That is why they score just over 0.5: about half of each one's
plasmids carry a real site and are destroyed, the other half carry nothing and are untouched.
The score is borrowed.

The test that catches this needs no new threshold. For a candidate `X` and a **stronger**
candidate `Y`, look at the plasmids carrying `X` but **not** `Y`. If `X` still depletes them, it
is a site in its own right. If it does not, its entire signal came from `Y` and it is a shadow.
"Still depletes" means the score threshold `X` had to pass in the first place.

Two properties make this work where the earlier steps do not:

- **It is directional.** The unique-hit step in step 5 is symmetric: a plasmid carrying two
  candidates is excluded from *both*, so several descriptions of one site annihilate each other
  and all of them lose their support. Here only a stronger motif may explain a weaker one, so
  the real site survives intact.
- **It is about plasmids, not strings.** `TACNNNNGTGG` and `CACNNNNGTAY` are unrelated as
  strings — different length, different pattern, opposite strand — but 51% of the first one's
  plasmids carry the second.

Measured on LMR_503, this takes 24 candidates to 5, and the support of the real site recovers
from 6 plasmids to 421 (1.3% to 91.5% of the plasmids that contain it), because the shadows are
no longer taking its evidence in step 5.

It keeps what it should. `CACNNNNGTAC` survives the stronger `CACNNNNGTAT`, because on plasmids
lacking `GTAT` it still depletes — they are the two halves of the degenerate `Y`. BREX in
*E. coli* HS survives, because nothing stronger explains it. CFT073's weak motif survives. An
RM-knockout strain still calls nothing.

In [ ]:
#| export
def filter_explained_candidates(candidates_df, log2fc_series, left_context, right_context,
                                log2fc_thr=-1, score_thr=0.7, min_support=3):
    """Drop candidates whose depletion is fully accounted for by a stronger candidate.

    For each candidate `X`, taken from weakest to strongest, look for a stronger candidate `Y`
    such that `X` restricted to the plasmids that do **not** carry `Y` no longer reaches
    `score_thr`. If one exists, `X` contributes no depletion of its own and is removed.

    No threshold is introduced: the test re-applies the score and support thresholds the
    candidate already had to pass, to the conditional set.

    Args:
        candidates_df: surviving candidates, with 'motif' and (optionally) 'pattern' columns.
        log2fc_series: the full log2FC series, indexed by sequence.
        left_context, right_context: the vector sequence flanking the insert.
        log2fc_thr: a plasmid is depleted below this.
        score_thr: fraction of plasmids that must still be depleted for a candidate to stand
            on its own.
        min_support: a candidate with fewer than this many plasmids left after removing `Y`'s
            has nothing to stand on either.

    Returns:
        (kept_df, explanations) where explanations maps a dropped motif to
        (explaining motif, plasmids left, score on them).
    """
    if candidates_df.empty or len(candidates_df) < 2:
        return candidates_df, {}

    motifs = candidates_df['motif'].tolist()
    if 'pattern' in candidates_df.columns:
        patterns = []
        for p in candidates_df['pattern']:
            try:
                patterns.append(tuple(ast.literal_eval(p)) if isinstance(p, str) else tuple(p))
            except (ValueError, SyntaxError):
                patterns.append(None)
    else:
        patterns = [None] * len(motifs)

    encoded = encode_library(
        get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence, handled = motif_presence_matrix(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()

    fc = log2fc_series.to_numpy()
    strength = []
    for j in range(len(motifs)):
        v = fc[presence[:, j]]
        strength.append(((v < log2fc_thr).mean() if len(v) else 0.0,
                         v.mean() if len(v) else 0.0,
                         motifs[j]))
    # Strongest first. The motif string is the final tie-break so the order, and therefore the
    # outcome, is a function of the candidates rather than of the row order they arrive in.
    order = sorted(range(len(motifs)),
                   key=lambda j: (-strength[j][0], strength[j][1], strength[j][2]))

    explanations = {}
    for rank, x in enumerate(order):
        for y in order[:rank]:
            if y in explanations:
                continue                       # a shadow cannot explain anything
            alone = presence[:, x] & ~presence[:, y]
            n = int(alone.sum())
            v = fc[alone]
            still = float((v < log2fc_thr).mean()) if n else 0.0
            if n < min_support or still < score_thr:
                explanations[x] = (motifs[y], n, still)
                break

    keep = [j for j in range(len(motifs)) if j not in explanations]
    return (candidates_df.iloc[keep],
            {motifs[x]: v for x, v in explanations.items()})

## Step 5: rescore on plasmids carrying exactly one candidate

A plasmid carrying two candidate motifs cannot tell us which one depleted it, so it is excluded
from both. What remains — plasmids carrying exactly one — is the evidence that actually
distinguishes candidates, and `num_sequences` counts those.

### `num_sequences` is a property of the candidate set, not of the motif

This is the single most important thing to understand about the output. Admit one more
overlapping candidate and every motif it overlaps loses plasmids. Measured on the BB2 panel:

| strain | motif | contains | counted | retained |
|---|---|---|---|---|
| 8097 | `CGACNNNNNNNATTA` | 138 | 138 | **100%** |
| 16226 | `AAAGNNNNGTT` | 897 | 895 | **99.8%** |
| 15846 | `ATACNNNNGTG` | 484 | 16 | **3.3%** |
| 15846 | `CACNNNNGTAC` | 460 | 6 | **1.3%** |

Where retention is high, `num_sequences` measures evidence and is stable. Where it is a percent
or two, it is a small residual of a large number and any change to the candidate set swings it —
which is exactly what happens to the over-specified variants described in step 4. An `n=6` that
is 6-of-460 means something quite different from an `n=138` that is 138-of-138, and the two
should not be compared as though they were the same quantity.

### Two things that are deliberately not done

**Rescoring runs on the full series**, including the sequences set aside in step 2 — see the
measurement there.

**The rescoring is not iterated.** Dropping a motif frees its plasmids to count as unique for
the survivors, so the step could be repeated to a fixed point. It converges at the second
iteration and never changes which motifs are called — but it inflates support enormously
(12049 `CACNNNNGTAC`: 17 → 441), because each round re-admits the plasmids that were excluded
for carrying more than one candidate. Iterating converges on approximately not having excluded
them at all, which is the step undoing itself. One pass is the intended semantics.

In [ ]:
#| export
def update_motif_scores_from_unique_hits(
    flexible_motifs_df,
    log2fc_series,
    left_context,
    right_context,
    flexible_motif_log2fc_thr=-1,
    flexible_motif_min_support=3,
    flexible_motif_score_thr=0.85
):
    """
    Updates a DataFrame of motifs with new scores based on unique sequence
    hits (sequences not matched by any other motif) and filters the result.

    Args:
        flexible_motifs_df (pd.DataFrame): DataFrame with a 'motif' column.
        log2fc_series (pd.Series): Series with DNA sequences as index and values.
        left_context (str): DNA string to prepend for matching.
        right_context (str): DNA string to append for matching.
        flexible_motif_log2fc_thr (float): The log2fc threshold for the score function.
        flexible_motif_min_support (int): The minimum number of unique sequences required.
        flexible_motif_score_thr (float): The minimum fraction_depleted score required.

    Returns:
        pd.DataFrame: A new, filtered DataFrame with updated scores.
    """
    if flexible_motifs_df.empty:
        # No candidates is a normal outcome, not an error -- an RM-deficient strain
        # reaches here legitimately. Return the empty frame with its columns intact.
        return flexible_motifs_df.copy()

    all_motifs = flexible_motifs_df['motif'].tolist()

    # Which pattern each motif came from, so presence can be read off the window codes.
    if 'pattern' in flexible_motifs_df.columns:
        patterns = []
        for p in flexible_motifs_df['pattern']:
            try:
                patterns.append(tuple(ast.literal_eval(p)) if isinstance(p, str) else tuple(p))
            except (ValueError, SyntaxError):
                patterns.append(None)
    else:
        patterns = [None] * len(all_motifs)

    encoded = encode_library(
        get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence, handled = motif_presence_matrix(encoded, all_motifs, patterns)

    # Anything the fast path could not encode -- an IUPAC-degenerate motif, or one whose
    # pattern is unknown -- falls back to the regex search, so the answer is unchanged.
    fallback = np.flatnonzero(~handled)
    if len(fallback):
        print(f"  {len(fallback)} motif(s) need the regex path (IUPAC or unknown pattern)")
        for j in tqdm(fallback, desc="  Building filters"):
            presence[:, j] = _get_filter_for_motif(
                log2fc_series, all_motifs[j], left_context, right_context).to_numpy()

    n_seqs, frac_depleted, avg_log2fc = _unique_hit_stats(
        presence, log2fc_series.to_numpy(), flexible_motif_log2fc_thr)
    new_metrics = [{'fraction_depleted': f, 'num_sequences': int(n), 'avg_log2fc': a}
                   for f, n, a in zip(frac_depleted, n_seqs, avg_log2fc)]

    df_updated = flexible_motifs_df.copy()
    metrics_df = pd.DataFrame(new_metrics, index=df_updated.index)

    df_updated['fraction_depleted'] = metrics_df['fraction_depleted']
    df_updated['num_sequences'] = metrics_df['num_sequences']
    df_updated['avg_log2fc'] = metrics_df['avg_log2fc']

    final_df = df_updated[
        (df_updated['avg_log2fc'] < flexible_motif_log2fc_thr) &
        (df_updated['num_sequences'] >= flexible_motif_min_support) &
        (df_updated['fraction_depleted'] >= flexible_motif_score_thr)
    ]

    return final_df

## Reporting: a motif and its reverse complement are one answer

The library is scanned on both strands, so a motif and its reverse complement always carry
**identical** statistics — same supporting sequences, same depletion score, same mean log2FC.
They describe one site, and exactly one of them should appear in the output.

Which one used to depend on the order candidates arrived in. The same site was reported as
`GAGACC` in one run and `GGTCTC` in another, and the two shipped JJ1886 datasets — the same
strain measured twice — disagreed on the strand of every motif they found.

`canonical_motif` decides it by rule: **use the spelling REBASE uses**, so results line up with
the literature and with enzyme names people recognise (`GGTCTC` is BsaI / Eco31I). For motifs
REBASE does not know — most of what a discovery screen finds — fall back to the alphabetically
first strand. Arbitrary, but identical on every run and every machine.

This is not cosmetic. Without it a paper can call one site two things: the manuscript this
package supports describes the JJ1886 site as "the low-abundance **BsaI** motif (**GAGACC**)" in
one section and "5′-**GGTCTC**-3′ ... the widespread ST131 **Eco31I**" in another. Those are
isoschizomers — one site, two spellings, because the tool emitted whichever strand won a tie.

**Fixed-position motifs are deliberately not canonicalised.** That table records a motif *at an
offset*, and an offset is only meaningful on one strand: `GTG` at position 0 is not
interchangeable with `CAC` at position 0. The two tables therefore use different conventions,
which is worth knowing when reading them side by side.

### Is the depletion one population or two?

A real site, strong or weak, affects the plasmids that carry it: the distribution of their
log2FC is shifted, and it is one population. A motif that is really a shadow of another site is
a **mixture** — some of its plasmids carry the real site and are destroyed, the rest carry
nothing and are untouched — so its distribution is bimodal with a hole in the middle.

The bimodality coefficient summarises that in one number. The conventional benchmark is
5/9 ≈ 0.556, the value a uniform distribution takes; above it a distribution is more
bimodal than uniform. Measured on known cases:

| | BC |
|---|---|
| shadows of `CACNNNNGTAY` | 0.647, 0.666, 0.667 |
| 381A's one real call | 0.423 |
| real strong sites | 0.349, 0.361 |
| CFT073, a weak system | 0.250 |
| BREX in *E. coli* HS | 0.236 |

The benchmark sits in the gap with margin on both sides, and BREX is not flagged despite having
the broadest distribution of any real call — which was the thing to check, since BREX depletes
weakly with many escapers.

This is **independent of significance**. A shadow is highly significant (q ≈ 0) and bimodal; a
weak real site is significant and unimodal; a chance call is neither. The two together say more
than either alone, so both are reported.

In [ ]:
#| export
def bimodality_coefficient(values):
    """Sarle's bimodality coefficient: (skew^2 + 1) / (kurtosis + 3(n-1)^2/((n-2)(n-3))).

    Above 5/9 the distribution is more bimodal than a uniform one. Here that means the motif's
    plasmids fall into two groups -- destroyed and untouched -- which is the signature of a
    motif that is really a diluted version of a different site, or of something wrong with the
    data. Returns NaN below four values, where it is not defined.
    """
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 4 or np.allclose(v, v[0]):
        return float("nan")
    g = skew(v, bias=False)
    k = kurtosis(v, bias=False, fisher=True)
    denom = k + 3.0 * (n - 1) ** 2 / ((n - 2) * (n - 3))
    return float((g ** 2 + 1.0) / denom) if denom > 0 else float("nan")


BIMODALITY_BENCHMARK = 5.0 / 9.0


def annotate_significance(results_df, log2fc_series, left_context, right_context,
                          all_pvalues=None, log2fc_thr=-1, q_threshold=0.05):
    """Add p_value, q_value, called and bimodality to a result table.

    `all_pvalues` are the p-values of every motif the scan tested, which is what the
    Benjamini-Hochberg correction has to be computed over -- correcting only over the handful
    that survived filtering would be meaningless.

    Nothing is removed. `called` marks the rows that clear `q_threshold`; the rest stay in the
    table so that a weak result is visible as a weak claim rather than silently absent.
    """
    if results_df is None or results_df.empty:
        return results_df
    out = results_df.copy()
    rate = background_depletion_rate(log2fc_series, log2fc_thr)

    p = motif_pvalues(out["num_sequences"].to_numpy(),
                      out["fraction_depleted"].to_numpy(), rate)
    out["p_value"] = p
    if all_pvalues is not None and len(all_pvalues):
        pool = np.concatenate([np.asarray(all_pvalues, dtype=float), p])
        q_all = benjamini_hochberg(pool)
        out["q_value"] = q_all[-len(p):]
    else:
        out["q_value"] = benjamini_hochberg(p)
    out["called"] = out["q_value"] < q_threshold

    # Presence comes from the window codes, not a regex per sequence -- the same vectorized
    # path the rest of the pipeline uses. Motifs the fast path cannot encode fall back.
    motifs = out["motif"].tolist()
    if "pattern" in out.columns:
        patterns = []
        for pat in out["pattern"]:
            try:
                patterns.append(tuple(ast.literal_eval(pat)) if isinstance(pat, str) else tuple(pat))
            except (ValueError, SyntaxError):
                patterns.append(None)
    else:
        patterns = [None] * len(motifs)

    encoded = encode_library(
        get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence, handled = motif_presence_matrix(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()

    values = log2fc_series.to_numpy()
    out["bimodality"] = [bimodality_coefficient(values[presence[:, j]])
                         for j in range(len(motifs))]
    out["bimodal"] = out["bimodality"] > BIMODALITY_BENCHMARK

    return out.sort_values(["called", "q_value"], ascending=[False, True])

## When the pipeline should refuse to answer

A strain with no real motif is the **hard** case, not the easy one: with nothing to find, many
near-threshold candidates survive into a step that compares them pairwise. That is exactly what
a new user runs first, as a negative control.

`max_candidates` is the guard. It used to warn and return the **unfiltered candidate list**,
which has the same columns as a real result and is easy to mistake for one — in the published
Fig 3 table that produced 344 of 374 rows from a single strain, which then flowed into the
downstream IUPAC merge as motifs like `SSBNNSVNN`. Nothing published was wrong, because that
strain is dropped from the figure by hand, but the only thing preventing it was remembering to.

Raising is safer. The candidates are still attached to the exception for inspection, and a
caller processing many strains should catch it, record that strain as "no confident call", and
carry on rather than losing the run.

In [ ]:
#| export
class TooManyCandidatesError(RuntimeError):
    """Raised when the flexible-motif search produces more candidates than it will score.

    The unfiltered candidate table is available as `.candidates` for inspection. It is **not**
    a result: these motifs have not been through the unique-hit rescoring that removes
    co-occurring and redundant sites.
    """

    def __init__(self, n_candidates, max_candidates, log2fc_thr, score_thr, min_support, candidates):
        self.n_candidates = n_candidates
        self.max_candidates = max_candidates
        self.candidates = candidates
        super().__init__(
            f"Too many candidate motifs: {n_candidates} > max_candidates={max_candidates}. "
            f"The unique-hit scoring step is O(N^2) and would not finish. This usually means the "
            f"thresholds are too permissive for this data. Try a stricter "
            f"flexible_motif_log2fc_thr (currently {log2fc_thr}, e.g. -0.8 or -1.0), "
            f"flexible_motif_score_thr (currently {score_thr}, e.g. 0.7 or 0.85), or "
            f"flexible_motif_min_support (currently {min_support}, e.g. 5 or 10). "
            f"Raise max_candidates only if you know why this strain has so many candidates. "
            f"The unfiltered candidates are on this exception as `.candidates`."
        )

In [ ]:
#| export
def _canonicalise_flexible_motifs(df):
    """Put every motif in a flexible-motif result table on its canonical strand.

    A motif and its reverse complement have identical statistics, so rewriting the label loses
    nothing. If both strands of one site somehow survive into the same table they collapse to a
    single row and a warning is issued, because that means the redundancy filter let a duplicate
    through.
    """
    if df is None or df.empty or 'motif' not in df.columns:
        return df
    df = df.copy()
    df['motif'] = df['motif'].map(canonical_motif)
    subset = [c for c in ('motif', 'pattern') if c in df.columns]
    duplicated = df.duplicated(subset=subset)
    if duplicated.any():
        dropped = df.loc[duplicated, 'motif'].tolist()
        warnings.warn(
            f"Both strands of the same site survived redundancy filtering and have been "
            f"collapsed: {dropped}. This is a bug in the redundancy filter, not in the data.",
            stacklevel=2,
        )
        df = df[~duplicated]
    return df

In [ ]:
#| hide
import pandas as pd

# Rewrites to the canonical strand and leaves everything else alone.
_t = pd.DataFrame({'motif': ['GAGACC', 'AACNNNNCTTT'], 'pattern': [(6, 0, 0), (3, 4, 4)],
                   'num_sequences': [6, 54], 'avg_log2fc': [-3.75, -5.02]})
_out = _canonicalise_flexible_motifs(_t)
assert list(_out.motif) == ['GGTCTC', 'AAAGNNNNGTT']
assert list(_out.num_sequences) == [6, 54]

# An empty table is returned untouched rather than exploding.
assert _canonicalise_flexible_motifs(pd.DataFrame()).empty

# Both strands of one site in one table collapse to a single row, with a warning.
_dup = pd.DataFrame({'motif': ['GAGACC', 'GGTCTC'], 'pattern': [(6, 0, 0), (6, 0, 0)],
                     'num_sequences': [6, 6], 'avg_log2fc': [-3.75, -3.75]})
import warnings as _w
with _w.catch_warnings(record=True) as _rec:
    _w.simplefilter('always')
    _collapsed = _canonicalise_flexible_motifs(_dup)
assert len(_collapsed) == 1 and _collapsed.motif.iloc[0] == 'GGTCTC'
assert len(_rec) == 1
print('ok')

ok

In [ ]:
#| export

def find_restricted_motifs(log2fc_series,
                           left_context_str,
                           right_context_str,
                           n_jobs=1,
                           fixed_motif_scan_depth_k=6,
                           fixed_motif_max_length=4,
                           fixed_motif_depletion_thr=-1,
                           fixed_motif_score_thr=0.85,
                           fixed_motif_min_support=5,
                           core_motif_score_margin=0.05,
                           flexible_motif_patterns=[(6,0,0),(3,4,4)],
                           flexible_motif_log2fc_thr=-1,
                           flexible_motif_min_support=5,
                           flexible_motif_score_thr=0.7,
                           core_flexible_motif_score_margin=0.2,
                           max_candidates=150,
                           q_threshold=0.05
                           ):
    """
    Full pipeline to identify fixed-position core motifs and then
    position-independent motifs in the remaining sequences.

    Every flexible pattern is scanned, then the two-way filter_redundant_patterns is applied
    once over all candidates, and the survivors are rescored on unique hits over the full
    log2fc_series. Sequences carrying a fixed-position core motif are included
    in the rescoring on purpose: fixed motifs at the sequence ends are often a
    flexible motif straddling the library context (e.g. JJ1886's GTG at
    position 0 is ATACNNNNGTG with ATAC in the left context).

    Args:
        n_jobs (int): processes used to scan the flexible patterns. 1 (default) runs in this
            process. With the vectorized scan a pattern takes about a second on a 30k-sequence
            library, so more is rarely worth the startup cost.
        flexible_motif_min_support (int): minimum plasmids for a motif to be considered. The
            default of 5 is set by a permutation test rather than by taste: on the smaller
            example library, motifs with 3-4 supporting plasmids arise by chance about once per
            scan (0.8 measured over 20 permutations, 0.60 expected analytically), and none at
            all arise at 5 or above. It cannot go higher than about 6 without deleting a real
            call -- BsaI on JJ1886 has only 6 supporting plasmids there.
        q_threshold (float): a motif is marked `called` when its Benjamini-Hochberg q-value,
            computed against this sample's own background depletion rate and over every motif
            the scan tested, falls below this. Motifs that do not clear it are still returned,
            flagged, rather than dropped.
        max_candidates (int): Safety limit on the number of candidate flexible
            motifs before entering the O(N²) update_motif_scores_from_unique_hits
            step.  If more candidates are found the function aborts that step,
            prints guidance on tightening thresholds, and returns the raw
            (unfiltered) candidates so the caller can inspect them.
            Default: 150.
    """
    print("--- Starting Fixed-Position Motif Analysis (on original short sequences) ---")
    depleted_fixed_motifs_df = identify_depleted_motifs_scanning_ends(
        log2fc_series,
        scan_depth_k=fixed_motif_scan_depth_k,
        max_motif_length=fixed_motif_max_length,
        depletion_threshold=fixed_motif_depletion_thr,
        score_thr=fixed_motif_score_thr,
        min_sequence_support=fixed_motif_min_support
    )
    core_fixed_motifs_df = filter_to_core_motifs(
        depleted_fixed_motifs_df,
        score_improvement_margin=core_motif_score_margin
    )
    del depleted_fixed_motifs_df

    if core_fixed_motifs_df.empty:
        print("No core motifs found at fixed positions.")
    else:
        print(f"Found {len(core_fixed_motifs_df)} core motifs at fixed positions:")
        for _, row in core_fixed_motifs_df.iterrows():
            print(f"  - Fixed Motif: {row['motif']}, Pos: {row['position']}, Len: {row['length']}, FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    print("\n--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---")
    log2fc_series_for_flexible_analysis = filter_sequences_without_core_motifs(
        log2fc_series,
        core_fixed_motifs_df
    )
    if len(log2fc_series_for_flexible_analysis) == len(log2fc_series):
        print("No sequences were filtered out based on fixed-position core motifs (or no core motifs found).")
    else:
        print(f"Filtered log2fc_series for flexible analysis: {len(log2fc_series_for_flexible_analysis)} sequences remaining.")

    if log2fc_series_for_flexible_analysis.empty:
        print("No sequences remaining for flexible motif analysis after filtering.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
        return core_fixed_motifs_df, annotate_significance(
            _canonicalise_flexible_motifs(flexible_motifs_results_df),
            log2fc_series, left_context_str, right_context_str,
            all_pvalues=tested_pvalues, log2fc_thr=flexible_motif_log2fc_thr,
            q_threshold=q_threshold)

    short_sequences_for_flex_analysis = log2fc_series_for_flexible_analysis.index.tolist()
    encoded_library_for_flex = encode_library(get_lib_seq_context(
        short_sequences_for_flex_analysis,
        left_context_str,
        right_context_str
    ))
    fc_values_for_flexible_analysis = log2fc_series_for_flexible_analysis.tolist()
    del log2fc_series_for_flexible_analysis

    cumulative_flexible_motifs_df = pd.DataFrame()

    if not isinstance(flexible_motif_patterns, list):
        print("Warning: flexible_motif_patterns should be a list. Wrapping it in a list.")
        flexible_motif_patterns = [flexible_motif_patterns]

    flexible_motif_patterns = sorted(flexible_motif_patterns, key=lambda x: (x[0]+x[2], x[1]))

    if n_jobs == 1:
        per_pattern = [
            process_single_flexible_pattern(
                p, encoded_library_for_flex, fc_values_for_flexible_analysis,
                flexible_motif_log2fc_thr, flexible_motif_score_thr,
                flexible_motif_min_support, return_pvalues=True)
            for p in tqdm(flexible_motif_patterns, desc="Scanning patterns")
        ]
    else:
        worker = functools.partial(
            process_single_flexible_pattern,
            encoded_library=encoded_library_for_flex,
            fc_values_for_flexible_analysis=fc_values_for_flexible_analysis,
            flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
            flexible_motif_score_thr=flexible_motif_score_thr,
            flexible_motif_min_support=flexible_motif_min_support,
            return_pvalues=True)
        with Pool(processes=n_jobs) as pool:
            # imap preserves pattern order, so the result does not depend on which worker
            # finishes first.
            per_pattern = list(tqdm(pool.imap(worker, flexible_motif_patterns),
                                    total=len(flexible_motif_patterns),
                                    desc="Scanning patterns"))

    tested_pvalues = np.concatenate([pv for _, pv in per_pattern]) if per_pattern else np.array([])
    hits = [df for df, _ in per_pattern if not df.empty]
    if hits:
        # Every pattern is scanned first and the redundancy filter runs once over all
        # candidates, rather than after each pattern. Filtering incrementally made the
        # outcome depend on the order patterns were scanned in; with the filter now
        # order-independent the two agree, and doing it once is simpler and faster.
        cumulative_flexible_motifs_df = filter_redundant_patterns(
            pd.concat(hits, ignore_index=True),
            score_margin=core_flexible_motif_score_margin,
        )
        print(f"{sum(len(h) for h in hits)} candidate(s) across all patterns; "
              f"{len(cumulative_flexible_motifs_df)} remain after redundancy filtering.")

    if cumulative_flexible_motifs_df.empty:
        print(f"\nNo flexible motifs found meeting initial support > {flexible_motif_min_support} and score > {flexible_motif_score_thr} for any provided pattern.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
    else:
        cumulative_flexible_motifs_df, _explained = filter_explained_candidates(
            cumulative_flexible_motifs_df, log2fc_series, left_context_str, right_context_str,
            log2fc_thr=flexible_motif_log2fc_thr, score_thr=flexible_motif_score_thr,
            min_support=flexible_motif_min_support)
        if _explained:
            print(f"{len(_explained)} candidate(s) explained by a stronger motif:")
            for _m, (_by, _n, _s) in sorted(_explained.items()):
                print(f"    {_m} <- {_by} (without it: n={_n}, score={_s:.2f})")

        n_candidates = len(cumulative_flexible_motifs_df)
        print(f"\n{n_candidates} candidate motifs remain. Now filtering to core flexible motifs...")

        if n_candidates > max_candidates:
            raise TooManyCandidatesError(
                n_candidates,
                max_candidates,
                flexible_motif_log2fc_thr,
                flexible_motif_score_thr,
                flexible_motif_min_support,
                cumulative_flexible_motifs_df,
            )

        print("\nNow filtering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds")
        print(f"(Scoring {n_candidates} candidate motifs — this step is O(N²), may take a moment...)")

        flexible_motifs_results_df = update_motif_scores_from_unique_hits(
            cumulative_flexible_motifs_df,
            log2fc_series,
            left_context_str,
            right_context_str,
            flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
            flexible_motif_min_support=flexible_motif_min_support,
            flexible_motif_score_thr=flexible_motif_score_thr
        )

        print(f"\n{len(flexible_motifs_results_df)} motifs remaining:")
        if flexible_motifs_results_df.empty:
            print("No core flexible motifs remained after filtering.")
        else:
            for _, row in flexible_motifs_results_df.iterrows():
                print(f"{row['motif']} (from pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    return core_fixed_motifs_df, annotate_significance(
            _canonicalise_flexible_motifs(flexible_motifs_results_df),
            log2fc_series, left_context_str, right_context_str,
            all_pvalues=tested_pvalues, log2fc_thr=flexible_motif_log2fc_thr,
            q_threshold=q_threshold)

In [ ]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)

patterns = get_patterns()
core_fixed_motifs_df, flexible_motifs_df = find_restricted_motifs(log2fc_df["JJ1886_T0"], 
                        left,
                        right, 
                        fixed_motif_scan_depth_k=6,
                        fixed_motif_max_length=4,
                        fixed_motif_depletion_thr=-1,
                        fixed_motif_score_thr=0.85,
                        fixed_motif_min_support=5,
                        core_motif_score_margin=0.05,
                        flexible_motif_patterns=[(6,0,0),(7,0,0),(4,2,4),(4,4,3),(4,3,4),(4,4,4)],
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_min_support=3,
                        flexible_motif_score_thr=0.7
                        )

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Analyzing motifs of length 1 to 4, scanning positions 0 to 6 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 2 core motifs at fixed positions:
  - Fixed Motif: GTG, Pos: 0, Len: 3, FracDep: 1.00, AvgFC: -4.76, N: 187
  - Fixed Motif: AAAG, Pos: 12, Len: 4, FracDep: 1.00, AvgFC: -5.08, N: 42

--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---
Filtered log2fc_series for flexible analysis: 11275 sequences remaining.
86 candidate(s) across all patterns; 27 remain after redundancy filtering.
19 candidate(s) explained by a stronger motif:
    AAGGNNNGTTC <- AAAGNNNNGTT (without it: n=2, score=0.50)
    AAGTNNNGTTA <- AAAGNNNNGTT (without it: n=1, score=0.00)
    AAGTNNNNTTAA <- AAAGNNNNGTT (without it: n=3, score=0.67)
    ACACNNNCGTA <- GTACNNNNGTG (without it: n=1, score=0.00)
    CACCNNCGTA <- GTACNNNNGTG (without it: n=2, score=0.50)
    CAGANNNCTCA <- AGAGNNCTCA (without it: n=1, score=0.00)
    CAGANNTCTC <- AGAGNNCTCA (without it: n=0, score=0.00)
    CCACNNNTGTA <- GTACNNNNGTG (without it: n=1, score=1.00)
    CCTCNNCCTC <- AGAGNNCTCA (without it: n=1, score=0.00)
    CCTGAGA <- AGAGNNCTCA (without it: n=2, score=0.50)
    CCTGNNNCCTC <- AGAGNNCTCA (without it: n=2, score=0.50)
    CTGANNCCTC <- AGAGNNCTCA (without it: n=1, score=0.00)
    GAACNNNNGCCC <- GTACNNNNGTG (without it: n=2, score=1.00)
    GACCNNGACC <- GTACNNNNGTG (without it: n=2, score=1.00)
    GACCNNNNCCTC <- AGAGNNCTCA (without it: n=1, score=1.00)
    GCACNNNNGTA <- GCACNNNAGTA (without it: n=2, score=0.50)
    GCAGNNNNCTCA <- AGAGNNCTCA (without it: n=0, score=0.00)
    GTACNNACGA <- GTACNNNNGTG (without it: n=3, score=0.67)
    TACGNNNGTGA <- GTACNNNNGTG (without it: n=3, score=0.33)

8 candidate motifs remain. Now filtering to core flexible motifs...

Now filtering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds
(Scoring 8 candidate motifs — this step is O(N²), may take a moment...)

5 motifs remaining:
GAGACC (from pattern (6, 0, 0)), FracDep: 1.00, AvgFC: -3.75, N: 6
GTACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -5.05, N: 16
ATACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.74, N: 148
AAAGNNNNGTT (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -5.04, N: 61
AGGTNNNGGTC (from pattern (4, 3, 4)), FracDep: 1.00, AvgFC: -1.08, N: 3

Scanning patterns: 100%|##########| 6/6 [00:00<00:00, 38.94it/s]

In [ ]:
core_fixed_motifs_df

  motif  length  position  num_sequences  avg_log2fc  fraction_depleted
0   GTG       3         0            187   -4.764500                1.0
1  AAAG       4        12             42   -5.076919                1.0

In [ ]:
flexible_motifs_df

          motif  fraction_depleted  num_sequences  ...  called  bimodality bimodal
11  ATACNNNNGTG                1.0            148  ...    True    0.405340   False
13  AAAGNNNNGTT                1.0             61  ...    True    0.402660   False
10  CACNNNNGTAC                1.0             16  ...    True    0.653875    True
0        GGTCTC                1.0              6  ...    True    0.391853   False
36  AGGTNNNGGTC                1.0              3  ...   False         NaN   False

[5 rows x 10 columns]

In [ ]:
#| export
def find_restricted_motifs_mp(*args, cpu_count=1, **kwargs):
    """Deprecated alias for `find_restricted_motifs`; pass `n_jobs` instead of `cpu_count`.

    The two used to be separate implementations that could disagree: this one scanned every
    pattern and filtered redundancy once, while `find_restricted_motifs` filtered after each
    pattern. With the redundancy filter now independent of candidate order the two give
    identical results, verified on JJ1886, 12049, LMR_503 and B156, so there is one
    implementation and this name forwards to it.

    Kept because external scripts call it -- notably `generate_fig3_motifs.py` in the paper
    repository. New code should call `find_restricted_motifs(..., n_jobs=...)`.
    """
    warnings.warn(
        "find_restricted_motifs_mp is deprecated; call find_restricted_motifs(..., "
        "n_jobs=...) instead. cpu_count is forwarded to n_jobs.",
        DeprecationWarning, stacklevel=2)
    return find_restricted_motifs(*args, n_jobs=cpu_count, **kwargs)

## Failure modes, on real strains

The shipped panel exists so that each of these can be run, not just read. See
`example_data/counts_panel_key.csv`.

**Thresholds are not universal.** The defaults were tuned on restriction–modification systems.
BREX interference is weaker: *E. coli* HS has a known BREX system recognising `GGTAAG`, and at
the default `-1.0` the pipeline calls **nothing** for it. At `-0.5` it calls `GGTAAG`. A user
applying the defaults to a BREX strain and concluding "no activity" would be wrong.

**Specificity, demonstrated isogenically.** EDL933 calls `CACNNNNNNNCTGG`; its isogenic RM
knockout `EDL933_dRM` calls nothing. A negative result from an unrelated strain proves much less
than a matched pair.

**A motif already in your vector cannot be detected.** Every plasmid carries it, so there is no
motif-free baseline to deplete against. The published screen hit exactly this and had to change
backbone to recover a masked Type I motif. A negative result for such a motif is meaningless
rather than informative, so check your backbone before believing one.

**Library size sets what you can detect.** Expected plasmids carrying a given 6 bp motif is
roughly `n_members × 2 × (insert_len − 5) / 4096`. Long bipartite Type I motifs need a much
larger library than short Type II sites. Below about 100 supporting plasmids a real motif may
simply be missed.

In [ ]:
#| eval: false
# The BREX case, run rather than asserted. E. coli HS (Lab.ID 8408) has a known BREX system
# recognising GGTAAG; the default threshold is too strict to see it.
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
log2fc_hs = calculate_log2fc(counts_panel[["Control_R1", "HS_R1"]],
                             reference_column="Control_R1", count_threshold=10)["HS_R1"]
left_bb2, right_bb2 = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"

for thr in (-1.0, -0.5):
    _fixed, flex = find_restricted_motifs(
        log2fc_hs, left_bb2, right_bb2,
        flexible_motif_patterns=get_patterns(),
        flexible_motif_log2fc_thr=thr, flexible_motif_score_thr=0.5)
    called = list(flex["motif"]) if flex is not None and not flex.empty else []
    print(f"log2FC threshold {thr}: {called or 'nothing called'}")

### Example: strain 12049 (JJ1886), RandSeq BB2 library

`counts_panel.csv.gz` holds UMI counts for strain 12049 (replicate R1) and the `Control` input library, for the BB2 library (flanked by the `left_bb2` / `right_bb2` contexts below). Thresholds used throughout: a sequence counts as depleted at log2FC ≤ -1, and a motif is kept when ≥ 50% of the sequences carrying it are depleted (score ≥ 0.5).

In [ ]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_bb2, right_bb2 = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_12049 = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20, pseudocount=1)
log2fc_12049.describe()

         Control_R2     JJ1886_R1  ...  EDL933_dRM_R1  EDL933_dRM_R2
count  30108.000000  30108.000000  ...   30108.000000   30108.000000
mean      -0.095335     -0.145983  ...      -0.051041      -0.264967
std        0.662484      0.925720  ...       0.477549       0.946920
min       -4.604587     -7.545017  ...      -8.050974      -7.464945
25%       -0.158043     -0.189782  ...      -0.303039      -0.651040
50%       -0.002551      0.046866  ...      -0.067980      -0.180923
75%        0.151623      0.261892  ...       0.181672       0.259139
max        1.402258      2.155107  ...       2.393285       3.121144

[8 rows x 17 columns]

In [ ]:
core_fixed_12049, flexible_12049 = find_restricted_motifs_mp(log2fc_12049["JJ1886_R1"],
                        left_bb2,
                        right_bb2,
                        fixed_motif_depletion_thr=-1,
                        flexible_motif_patterns=get_patterns(),
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_score_thr=0.5,
                        cpu_count=1)

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Analyzing motifs of length 1 to 4, scanning positions 0 to 6 from each end, for JJ1886_R1.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 1 core motifs at fixed positions:
  - Fixed Motif: CTTT, Pos: 4, Len: 4, FracDep: 0.99, AvgFC: -3.31, N: 242

--- Starting Position-Independent Motif Analysis on Filtered Sequences (with context) ---
Filtered log2fc_series for flexible analysis: 29866 sequences remaining.
126 candidate(s) across all patterns; 22 remain after redundancy filtering.
18 candidate(s) explained by a stronger motif:
    ACACNNNAGTA <- CACNNNNGTAC (without it: n=168, score=0.39)
    ACACNNNCGTA <- CACNNNNGTAC (without it: n=91, score=0.44)
    ACACNNNGGTA <- CACNNNNGTAC (without it: n=83, score=0.39)
    ACACNNNTGTA <- CACNNNNGTAC (without it: n=111, score=0.36)
    CACANNCGTA <- CACNNNNGTAC (without it: n=110, score=0.43)
    CACANNGGTA <- CACNNNNGTAC (without it: n=81, score=0.42)
    CACCNNAGTA <- CACNNNNGTAC (without it: n=108, score=0.39)
    CACCNNCGTA <- CACNNNNGTAC (without it: n=104, score=0.35)
    CACCNNGGTA <- CACNNNNGTAC (without it: n=63, score=0.49)
    CACGNNAGTA <- CACNNNNGTAC (without it: n=84, score=0.38)
    CACGNNCGTA <- CACNNNNGTAC (without it: n=51, score=0.31)
    CACGNNTGTA <- CACNNNNGTAC (without it: n=71, score=0.31)
    CACTNNAGTA <- CACNNNNGTAC (without it: n=126, score=0.40)
    CACTNNCGTA <- CACNNNNGTAC (without it: n=54, score=0.37)
    CACTNNGGTA <- CACNNNNGTAC (without it: n=85, score=0.39)
    CACTNNTGTA <- CACNNNNGTAC (without it: n=95, score=0.41)
    TACNNNNGTGC <- CACNNNNGTAC (without it: n=289, score=0.37)
    TACNNNNGTGG <- CACNNNNGTAC (without it: n=319, score=0.34)

4 candidate motifs remain. Now filtering to core flexible motifs...

Now filtering to remove sequences with multiple motifs from the analysis and dropping motifs that no longer pass the thresholds
(Scoring 4 candidate motifs — this step is O(N²), may take a moment...)

4 motifs remaining:
GAGACC (from pattern (6, 0, 0)), FracDep: 0.94, AvgFC: -2.75, N: 52
CACNNNNGTAT (from pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -3.21, N: 483
CACNNNNGTAC (from pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -3.24, N: 441
AACNNNNCTTT (from pattern (3, 4, 4)), FracDep: 0.99, AvgFC: -3.37, N: 882

<ipython-input-48-b7b120ca4b06>:1: DeprecationWarning: find_restricted_motifs_mp is deprecated; call find_restricted_motifs(..., n_jobs=...) instead. cpu_count is forwarded to n_jobs.
  core_fixed_12049, flexible_12049 = find_restricted_motifs_mp(log2fc_12049["JJ1886_R1"],
Scanning patterns: 100%|##########| 43/43 [00:08<00:00,  4.86it/s]

In [ ]:
core_fixed_12049

  motif  length  position  num_sequences  avg_log2fc  fraction_depleted
0  CTTT       4         4            242   -3.311566           0.987603

In [ ]:
flexible_12049

          motif  fraction_depleted  num_sequences  ...  called  bimodality bimodal
29  ATACNNNNGTG           0.995859            483  ...    True    0.273289   False
32  CACNNNNGTAC           1.000000            441  ...    True    0.274410   False
33  AAAGNNNNGTT           0.994331            882  ...    True    0.249124   False
0        GGTCTC           0.942308             52  ...    True    0.363638   False

[4 rows x 10 columns]

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()