In [ ]:
%load_ext autoreload
%autoreload 2

# core

> Finding the DNA motifs a strain restricts, from a table of plasmid counts before and after delivery.

In [ ]:
#| default_exp core

In [ ]:
#| hide
from nbdev.showdoc import *
from fastcore.test import test_close, test_eq, test_fail

In [ ]:
#| export
import ast
import functools
import re
from itertools import product
from multiprocessing import Pool
import numpy as np
import pandas as pd
from scipy.stats import beta, kurtosis, skew
from tqdm import tqdm
from randseq.coding import encode_library, _encode_motif, _motif_presence_matrix, _pattern_is_self_rc, _rc_code_table
from randseq.fast import _scan_pattern, _scores_from_totals
from randseq.utils import (_IUPAC_COLLAPSE, _IUPAC_EXPAND, revcomp, calculate_log2fc, get_lib_seq_context,
                           get_patterns, _canonical_pattern, _get_filter_for_motif,
                           canonical_motif, plasmid_background, _motif_pvalues, _benjamini_hochberg)

In [ ]:
#| hide
import os
from randseq.example_data import get_example_data_dir
from randseq.fast import _get_pattern_scores

In [ ]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['__init__.py',
 '__pycache__',
 'countsTable.csv.gz',
 'counts_panel.csv.gz',
 'counts_panel_key.csv',
 'pMin_backbone.fasta']

## What RandSeq measures

A library of plasmids carrying random inserts is conjugated into a recipient strain. A plasmid
whose insert contains a site recognised by an active restriction system is destroyed on entry, so
it is **depleted** relative to the input library. This module works back from each plasmid's
depletion to the motifs responsible.

### The method in four sentences

Every plasmid gets a **log2FC**: how much rarer it became after delivery. Every motif gets the
plasmids that contain it, and so a set of log2FC values. A motif's **score** is the fraction of
those values below a threshold — what fraction of the plasmids carrying this motif were
destroyed. Everything after that is deciding **which of the many motifs that score well is the
actual site**.

In steps:

1. counts → log2FC per plasmid
2. score every motif of every requested pattern — **the scan**
3. keep one description per site, discarding the same site written more or less specifically
4. drop a candidate whose score was borrowed from a stronger one
5. report each motif on its canonical strand, tested against the depletion of plasmids of the
   same GC content, with a degenerate site written as one IUPAC motif

Steps 3 and 4 are two halves of one problem: **one real site makes many motifs score well.**
Step 3 compares motif *strings*; step 4 compares the *plasmids* motifs are found in, which relates
descriptions too different for a string rule. Which motifs an experiment could have found at all
depends on the vector and the library, not on this code: `03_design` works that out.

### The example data

- `countsTable.csv.gz` — 19 recipient strains, with the donor `MFDpir` as the input library;
  11,629 inserts of 20 nt
- `counts_panel.csv.gz` — 8 recipient strains and two donor replicates (`Control_R1`,
  `Control_R2`), each strain picked to exercise one behaviour of the pipeline
  (`example_data/counts_panel_key.csv` says which); 34,217 inserts, mostly 150 nt

*E. coli* JJ1886 is in both, so two measurements of one strain must agree on which motifs they
call and on which strand they name them.

## Step 1: counts → log2FC per plasmid

The input is a table of read counts, one row per insert sequence and one column per sample, one of
which is the input library. `calculate_log2fc` turns it into a log2 fold change per insert against
that column: inserts too rare in the input are dropped, a pseudocount is added, each sample is
converted to shares and normalised so that its median plasmid sits at 0. `01_utils` explains each
choice (*Counts to log2 fold change*). Everything downstream works on one column: a Series indexed
by insert sequence.

In [ ]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df

                        K12_T0     HS_T0  ...    S88_T0  MG1655_T0
seq                                       ...
CGGAGGTACTGGGTACATTT  0.053839  0.052486  ...  0.208060   0.129389
TGGCGATAATGCCGGCTATC  0.055484  0.140062  ...  0.086728   0.140558
TTCCAGTTCACTGGTCTTCG -0.039673  0.052838  ...  0.452512   0.167261
AATTTCAGTGCCGTTCAGAT -0.241936 -0.419289  ... -0.189453  -0.142007
CTGCGGTAATAATTCCCGCC -0.168407 -0.151090  ... -0.194322  -0.147295
...                        ...       ...  ...       ...        ...
GCTTGATGTAGCCTTCGAAC -0.090498 -0.077031  ... -0.061401  -0.094254
TAATGGCAAATTGACACTCC  0.268225  0.106618  ...  0.196397   0.425986
GCTGCGCGCGGAGTTGTTCC -0.619835 -0.378119  ... -0.503168  -0.920714
GCAACACGCCAGTAAGGTGT  0.703437  0.490088  ...  0.058894   0.415349
GATAGCCGGATAGCTTAAGG -0.235664 -0.128696  ... -0.406399   0.179141

[11503 rows x 19 columns]

## Step 2: score every motif

Every motif of every **pattern** is scored over `left_flank + insert + right_flank`, on both
strands. A pattern is the shape of a site, `(d1, spacer, d2)`: defined bases, undefined gap,
defined bases. `(6, 0, 0)` is a contiguous site like `GGTCTC`; `(3, 4, 4)` a bipartite site like
`CACNNNNGTAT`. `get_patterns()` returns the shapes REBASE records for Type I, II and III systems;
a site whose shape is not searched cannot be found.

The flanks are scanned because a site can **straddle the junction** between insert and vector. In
the 150 nt panel library the left flank ends in `AAAC`, so every insert that starts `NNNNGTC`
completes B156's site `AAACNNNNGTC`: 382 of the 894 plasmids that carry the site in B156 carry it
across the junction.

A motif is counted **once per plasmid**, however often it occurs there, and a motif and its
**reverse complement are one motif**. Thresholds keep one convention throughout the package: a
log2FC threshold is strict (`log2FC < thr`), a score or support threshold inclusive (`>= thr`, so
`min_support=3` means three supporting plasmids, not four).

Step 2 for one motif, by hand: `GAGACC` is in the first two sequences, in the second read on the
other strand as `GGTCTC`.

In [ ]:
_seqs = ["GAGACCTT", "AAGAGACC", "TTTTTTTT"]
_fc = [-2.0, 0.5, -3.0]

carries = [("GAGACC" in s) or ("GGTCTC" in s) for s in _seqs]   # either strand, one motif
vals = [f for f, c in zip(_fc, carries) if c]
print(f"plasmids carrying GAGACC : {[s for s, c in zip(_seqs, carries) if c]}")
print(f"their log2FC             : {vals}")
print(f"score, fraction below -1 : {np.mean(np.array(vals) < -1)}")

plasmids carrying GAGACC : ['GAGACCTT', 'AAGAGACC']
their log2FC             : [-2.0, 0.5]
score, fraction below -1 : 0.5

The scan does this for every motif of every pattern at once, on integer codes rather than
strings: `04_coding` shows how, and `05_fast` adds an optional compiled kernel. Both are tested to
give exactly the table of a readable string-based scan (`tests/reference_scan.py`).

### On the example library

From here on the examples use JJ1886 in the 20 nt library: the inserts with their flanks
(`get_lib_seq_context`), their log2FC, and each plasmid's background — the depletion rate of
plasmids of similar insert GC content, which every test is taken against (`plasmid_background`
in `01_utils` explains why). `_scan_candidates` scans one pattern and keeps the motifs that pass
the support and score thresholds.

In [ ]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib = get_lib_seq_context(log2fc_df.index, left, right)
fcs = log2fc_df["JJ1886_T0"].values
bg = plasmid_background(log2fc_df.index, fcs, -1)
print(f"{len(lib)} sequences, each {len(lib[0])} nt with the flanks added")
lib[0][:60]

11503 sequences, each 60 nt with the flanks added

'GTCCTAGGTATAATACTAGTCGGAGGTACTGGGTACATTTGTTTTAGAGCTAGAAATAGC'

In [ ]:
#| export
def _scan_candidates(
    pattern,
    encoded_library,
    fc_values,
    background,
    log2fc_thr,
    score_thr,
    min_support,
    parallel=True,
):
    """
    Scores all motifs of one pattern and keeps the candidates with
    fraction_depleted >= score_thr and num_sequences >= min_support.

    Args:
        pattern (tuple): (d1, spacer, d2) motif pattern.
        encoded_library (tuple): (fwd, rc) arrays from `encode_library` (sequences with context).
        fc_values (list): log2FC of each sequence, in library order.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`.
        log2fc_thr (float): log2FC below which a sequence counts as depleted.
        score_thr (float): minimum fraction_depleted (inclusive, `>=`).
        min_support (int): minimum number of sequences (inclusive, `>=`).
        parallel (bool): passed to `_scan_pattern`; False inside a pool worker.

    Returns:
        (pd.DataFrame, np.ndarray, tuple): the surviving candidates -- 'motif',
            'fraction_depleted', 'num_sequences', 'avg_log2fc', 'p_value' and 'pattern' (the
            pattern as a string) -- the p-value of *every* motif that had enough support to be a
            test, survivor or not, and the pattern's totals from `_scan_pattern`, so that later
            steps can look motifs of this pattern up rather than scan it again.

    Both are returned because the Benjamini-Hochberg correction needs the full set of tests, and
    only this function ever sees it: the candidates that fail the score threshold are discarded
    here, but they were still tested, and a correction that ignored them would be wrong.
    """
    fc = np.asarray(fc_values, dtype=float)
    totals = _scan_pattern(encoded_library, pattern, fc, background,
                          log2fc_thr, parallel)
    n_seqs, n_depleted, bg_sum = totals[0], totals[1], totals[3]
    # Only the candidates are turned into strings; the tests stay arrays. A pattern has up to
    # 4**8 motifs present, and decoding every one of them was most of this step's time.
    tested = np.flatnonzero(n_seqs >= max(min_support, 1))
    frac = n_depleted[tested] / n_seqs[tested]
    kept = _scores_from_totals(totals, pattern,
                               tested[frac >= score_thr])
    kept['pattern'] = str(pattern)
    return kept, _motif_pvalues(n_seqs[tested], frac, bg_sum[tested] / n_seqs[tested]), totals

In [ ]:
show_doc(_scan_candidates)

def _scan_candidates(
    pattern, encoded_library, fc_values, background, log2fc_thr, score_thr, min_support, parallel:bool=True
):"""Scores all motifs of one pattern and keeps the candidates with
fraction_depleted >= score_thr and num_sequences >= min_support.

Args:
    pattern (tuple): (d1, spacer, d2) motif pattern.
    encoded_library (tuple): (fwd, rc) arrays from `encode_library` (sequences with context).
    fc_values (list): log2FC of each sequence, in library order.
    background (np.ndarray): each sequence's expected depletion rate, from
        `plasmid_background`.
    log2fc_thr (float): log2FC below which a sequence counts as depleted.
    score_thr (float): minimum fraction_depleted (inclusive, `>=`).
    min_support (int): minimum number of sequences (inclusive, `>=`).
    parallel (bool): passed to `_scan_pattern`; False inside a pool worker.

Returns:
    (pd.DataFrame, np.ndarray, tuple): the surviving candidates -- 'motif',
        'fraction_depleted', 'num_sequences', 'avg_log2fc', 'p_value' and 'pattern' (the
        pattern as a string) -- the p-value of *every* motif that had enough support to be a
        test, survivor or not, and the pattern's totals from `_scan_pattern`, so that later
        steps can look motifs of this pattern up rather than scan it again.

Both are returned because the Benjamini-Hochberg correction needs the full set of tests, and
only this function ever sees it: the candidates that fail the score threshold are discarded
here, but they were still tested, and a correction that ignored them would be wrong."""

In [ ]:
candidates, tested, _ = _scan_candidates((3, 4, 4), encode_library(lib), fcs, bg, -1, 0.7, 3)
# far more motifs were tested than survived -- the correction has to account for all of them
print(f"{len(candidates)} candidates kept out of {len(tested)} tested")
candidates.sort_values('num_sequences', ascending=False).head()

8 candidates kept out of 16296 tested

         motif  fraction_depleted  ...        p_value    pattern
1  ATANNNNTGTG           0.964467  ...  4.479256e-244  (3, 4, 4)
2  CACNNNNGTAT           1.000000  ...  2.601024e-258  (3, 4, 4)
4  TACNNNNGTGA           0.849315  ...   4.842427e-72  (3, 4, 4)
6  TACNNNNGTGG           0.907692  ...   1.440987e-72  (3, 4, 4)
0  AACNNNNCTTT           1.000000  ...   1.372226e-86  (3, 4, 4)

[5 rows x 6 columns]

In [ ]:
#| hide
# The scan reports whichever strand it read; these are the same two sites as ATACNNNNGTG and
# AAAGNNNNGTT, which is how they are spelled once canonicalised for reporting.
assert {"CACNNNNGTAT", "AACNNNNCTTT"} <= set(candidates.motif)

## Step 3: one description per site

The scan returns one site described several ways. In this library the Type I site `CACNNNNGTAT`
also comes back as `CACNNNNGTA`, one base shorter, and `CACNNNNGTAC` comes back once for each
base pinned at the first position of its spacer (`CACANNNGTAC`, `CACCNNNGTAC`, …). Step 3 keeps
one description per site, with one tool and three rules applied in this order:

- **the variant profile**: pin one position next to a motif to each of A, C, G and T, and score
  the four motifs
- **rule 1, a mixture is not a site**: drop a motif when some position next to it splits its four
  variants into depleting and not
- **rule 2, a one-base extension of a site is redundant**: drop a motif that is a rule-1 survivor
  plus one defined base
- **rule 3, a motif with an uninformative base is not the site**: drop a motif when putting N back
  at one of its defined bases gives four bases that all behave like the site

### The variant profile

`_variant_profile` scores a set of related motifs — typically the four bases at one position —
from the counts step 2 made (`_scan_pattern`), so a variant is scored exactly as the scan scored
it, and a pattern is scanned at most once however many motifs need it.

In [ ]:
#| export
def _variant_profile(motifs, pattern, encoded, fc, background, log2fc_thr, totals=None):
    """Support, depletion score and background for each of a set of related motifs.

    Read off the pattern's totals from `_scan_pattern` -- the counts step 2 makes -- so a
    variant is scored exactly as it would have been had its pattern been scanned there.

    Args:
        motifs (list): motif strings, all of the same `pattern`.
        pattern (tuple): the `(d1, spacer, d2)` shape they share.
        encoded (tuple): `(fwd, rc)` from `encode_library`.
        fc (np.ndarray): log2 fold change per library sequence, in the same order.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`.
        log2fc_thr (float): a plasmid is depleted below this.
        totals (dict): totals by canonical pattern, for this library, `fc`, `background` and
            threshold. Shared across calls, it makes every pattern scanned at most once, and the
            patterns step 2 scanned never again. Filled in place.

    Returns:
        list: one `(motif, n_plasmids, score, background)` per motif, in the order given, the
        background being the carriers' mean. A motif that has no code (an IUPAC base, or a
        defined base in the spacer) gets `n=0` and `nan` for the other two.
    """
    totals = {} if totals is None else totals
    canon = _canonical_pattern(pattern)
    if canon not in totals:
        totals[canon] = _scan_pattern(encoded, canon, fc, background, log2fc_thr)
    n_seqs, n_depleted, _, bg_sum, _ = totals[canon]
    mirrored = pattern[1] != 0 and tuple(pattern) != canon    # spelled on the other strand
    rc_table = _rc_code_table(canon) if _pattern_is_self_rc(canon) else None
    out = []
    for m in motifs:
        code = _encode_motif(revcomp(m) if mirrored else m, canon)
        if code is not None and rc_table is not None:
            code = min(code, int(rc_table[code]))             # the fold step 2 applied
        n = int(n_seqs[code]) if code is not None else 0
        out.append((m, n, float(n_depleted[code] / n) if n else float("nan"),
                    float(bg_sum[code] / n) if n else float("nan")))
    return out

In [ ]:
show_doc(_variant_profile)

def _variant_profile(
    motifs, pattern, encoded, fc, background, log2fc_thr, totals:NoneType=None
):"""Support, depletion score and background for each of a set of related motifs.

Read off the pattern's totals from `_scan_pattern` -- the counts step 2 makes -- so a
variant is scored exactly as it would have been had its pattern been scanned there.

Args:
    motifs (list): motif strings, all of the same `pattern`.
    pattern (tuple): the `(d1, spacer, d2)` shape they share.
    encoded (tuple): `(fwd, rc)` from `encode_library`.
    fc (np.ndarray): log2 fold change per library sequence, in the same order.
    background (np.ndarray): each sequence's expected depletion rate, from
        `plasmid_background`.
    log2fc_thr (float): a plasmid is depleted below this.
    totals (dict): totals by canonical pattern, for this library, `fc`, `background` and
        threshold. Shared across calls, it makes every pattern scanned at most once, and the
        patterns step 2 scanned never again. Filled in place.

Returns:
    list: one `(motif, n_plasmids, score, background)` per motif, in the order given, the
    background being the carriers' mean. A motif that has no code (an IUPAC base, or a
    defined base in the spacer) gets `n=0` and `nan` for the other two."""

In [ ]:
enc = encode_library(lib)

# CACNNNNGTA leaves the eleventh position undefined. What do the four bases score there?
for motif, n, s, b in _variant_profile(["CACNNNNGTAA", "CACNNNNGTAC", "CACNNNNGTAG", "CACNNNNGTAT"],
                                      (3, 4, 4), enc, fcs, bg, -1):
    print(f"  {motif}  n={n:>4}  score={s:.3f}  background={b:.3f}")

  CACNNNNGTAA  n=  15  score=0.067  background=0.045
  CACNNNNGTAC  n=  20  score=1.000  background=0.044
  CACNNNNGTAG  n=  11  score=0.000  background=0.042
  CACNNNNGTAT  n= 192  score=1.000  background=0.046

Two of the four are dead and two are perfect. Whatever `CACNNNNGTA` scores as a whole, it is an
average over two populations, not one.

In [ ]:
#| hide
# Order is preserved, and a motif of a shape the encoder cannot express is reported as n=0
# rather than as a motif no plasmid carries.
_p = _variant_profile(["GAGACC", "GGGGGG"], (6, 0, 0), enc, fcs, bg, -1)
test_eq([m for m, *_ in _p], ["GAGACC", "GGGGGG"])
test_eq(_variant_profile(["CACNNNNGTAY"], (3, 4, 4), enc, fcs, bg, -1)[0][1], 0)
# The background is the mean over the variant's own carriers, exactly.
_has = _motif_presence_matrix(enc, ["GAGACC"], [(6, 0, 0)])[0][:, 0]
test_eq(_p[0][3], bg[_has].sum() / _has.sum())

A profile is a **mixture** when its variants *split*: some fail the score threshold the candidate
had to pass, **and** the variants spread by at least that threshold. Both halves are needed: a
failing variant alone would condemn a weak real site with one variant just below the line, and a
spread alone a strong site whose variants merely differ. Variants on fewer than `min_support`
plasmids are not judged, and fewer than two judgeable variants is `unknown`.

In [ ]:
#| export
def _verdict(profile, score_thr, min_support):
    """Call a variant profile 'mixture', 'genuine' or 'unknown'.

    Args:
        profile (list): `(motif, n, score, ...)` from `_variant_profile`; only `n` and `score`
            are read.
        score_thr (float): the depletion score a candidate had to reach to be here.
        min_support (int): a variant on fewer plasmids than this is not judged.

    Returns:
        tuple: the verdict, and the spread across judgeable variants (`None` when fewer than
        two can be judged).
    """
    judged = [p[2] for p in profile if p[1] >= min_support]
    if len(judged) < 2:
        return "unknown", None
    spread = max(judged) - min(judged)
    split = any(s < score_thr for s in judged) and spread >= score_thr
    return ("mixture" if split else "genuine"), spread

In [ ]:
show_doc(_verdict)

def _verdict(
    profile, score_thr, min_support
):"""Call a variant profile 'mixture', 'genuine' or 'unknown'.

Args:
    profile (list): `(motif, n, score, ...)` from `_variant_profile`; only `n` and `score`
        are read.
    score_thr (float): the depletion score a candidate had to reach to be here.
    min_support (int): a variant on fewer plasmids than this is not judged.

Returns:
    tuple: the verdict, and the spread across judgeable variants (`None` when fewer than
    two can be judged)."""

In [ ]:
# Four real profiles, one per case the rule has to get right.
mixture = [("a", 15, 0.07), ("c", 20, 1.00), ("g", 11, 0.00), ("t", 192, 1.00)]
weak    = [("a", 77, 0.506), ("c", 53, 0.679), ("g", 62, 0.468), ("t", 110, 0.564)]
strong  = [("a", 555, 0.654), ("c", 409, 0.677), ("g", 526, 0.755), ("t", 667, 0.705)]
thin    = [("a", 4, 1.0), ("c", 1, 1.0), ("g", 3, 1.0), ("t", 1, 1.0)]
for name, p in [("mixture", mixture), ("weak", weak), ("strong", strong), ("thin", thin)]:
    v, spread = _verdict(p, 0.5, 5)
    print(f"  {name:8s} {v:8s} spread={'  —' if spread is None else f'{spread:.3f}'}")

  mixture  mixture  spread=1.000
  weak     genuine  spread=0.211
  strong   genuine  spread=0.101
  thin     unknown  spread=  —

`weak` decides the design: one variant scores 0.468, below the 0.5 threshold, but all four sit
within 0.21 of each other, so no population of non-sites hides inside it. `thin` is `unknown`,
which matters to rule 2.

In [ ]:
#| hide
test_eq(_verdict(mixture, 0.5, 5)[0], "mixture")
test_eq(_verdict(weak, 0.5, 5)[0], "genuine")      # a failing variant alone is not enough
test_eq(_verdict(strong, 0.5, 5)[0], "genuine")
test_eq(_verdict(thin, 0.5, 5)[0], "unknown")      # nothing with enough plasmids to judge
test_eq(round(_verdict(mixture, 0.5, 5)[1], 3), 1.0)
test_eq(round(_verdict(weak, 0.5, 5)[1], 3), 0.211)
# Exactly one judgeable variant is still 'unknown': a spread needs two numbers.
test_eq(_verdict([("a", 99, 0.1), ("c", 1, 1.0)], 0.5, 5)[0], "unknown")

A motif is tested where one more defined base could go: one base beyond each end, and the spacer
position next to each half (`_undefined_positions`). A position in the middle of a long spacer is
skipped: fixing it would leave two gaps, a shape `(d1, spacer, d2)` cannot write. These are also
the only positions a one-base extension can add its base at, which ties rules 1 and 2 together.

In [ ]:
#| export
def _undefined_positions(motif, pattern):
    """Each undefined position worth testing on a candidate, as (four variants, their pattern)."""
    d1, spacer, d2 = pattern
    width = d1 + spacer + d2
    jobs = [([b + motif for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1 + 1, spacer, d2)),
            ([motif + b for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1, spacer, d2 + 1))]
    if spacer:
        p = d1
        jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"],
                     (d1 + 1 + d2, 0, 0) if spacer == 1 else (d1 + 1, spacer - 1, d2)))
        if spacer > 1:
            p = d1 + spacer - 1
            jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"], (d1, spacer - 1, d2 + 1)))
    return jobs

In [ ]:
show_doc(_undefined_positions)

def _undefined_positions(
    motif, pattern
):"""Each undefined position worth testing on a candidate, as (four variants, their pattern)."""

In [ ]:
# NATACNNNNGTGN: four positions to test, each giving a different pattern.
for variants, vpat in _undefined_positions("ATACNNNNGTG", (4, 4, 3)):
    print(f"  {vpat}  {variants[0]}")

# A contiguous motif has no spacer, so only the two ends are testable.
print()
for variants, vpat in _undefined_positions("GGTCTC", (6, 0, 0)):
    print(f"  {vpat}  {variants[0]}")

  (5, 4, 3)  AATACNNNNGTG
  (4, 4, 4)  ATACNNNNGTGA
  (5, 3, 3)  ATACANNNGTG
  (4, 3, 4)  ATACNNNAGTG

  (7, 0, 0)  AGGTCTC
  (7, 0, 0)  GGTCTCA

In [ ]:
#| hide
# Every variant really is of the pattern it is labelled with, and the four differ at one position.
for m, pat in [("ATACNNNNGTG", (4, 4, 3)), ("GGTCTC", (6, 0, 0)), ("ACANAGG", (3, 1, 3))]:
    for variants, vpat in _undefined_positions(m, pat):
        test_eq(len(variants), 4)
        test_eq({len(v) for v in variants}, {sum(vpat)})
        test_eq(len({v for v in variants}), 4)
        d1, sp, d2 = vpat
        for v in variants:
            test_eq(v[d1:d1 + sp], "N" * sp)        # the gap is where the pattern says it is
            assert "N" not in v[:d1] + v[d1 + sp:]  # and nowhere else
test_eq(len(_undefined_positions("GGTCTC", (6, 0, 0))), 2)       # no spacer: two ends only
test_eq(len(_undefined_positions("ACANAGG", (3, 1, 3))), 3)      # a 1-base spacer: one position
test_eq(len(_undefined_positions("ATACNNNNGTG", (4, 4, 3))), 4)  # a wide spacer: both edges

### Rule 1: a mixture is not a site

`_is_mixture` reads the profile at each position next to a motif; one split is enough. The scan
finds this strain's Type I site as `CACNNNNGTAT` (reported on its canonical strand as
`ATACNNNNGTG`, pattern `(4, 4, 3)`), and also `ATANNNNTGTG`: the same stretch of DNA with its gap
one base to the left. Neither string contains the other, so rule 2 cannot relate them, although
both describe mostly the same 190 plasmids. Rule 1 separates them:

In [ ]:
#| export
def _is_mixture(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
               score_thr=0.5, min_support=5, totals=None):
    """Does fixing one position next to this motif split its carriers into sites and non-sites?

    Args:
        motif (str): the candidate.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library (tuple): `(fwd, rc)` from `encode_library`.
        fc_values (np.ndarray): log2 fold change per library sequence.
        background (np.ndarray): each sequence's expected depletion rate, from
            `plasmid_background`. The verdict compares the variants with each other and does not
            read it; it completes the totals of a pattern scanned here, which rule 3 shares.
        log2fc_thr (float), score_thr (float), min_support (int): as elsewhere in the step.
        totals (dict): shared pattern totals, as for `_variant_profile`.

    Returns:
        bool: True when some position's four bases split.
    """
    for variants, vpat in _undefined_positions(motif, pattern):
        if sum(vpat) > encoded_library[0].shape[1]:  # the padded motif is wider than the insert
            continue
        if _verdict(_variant_profile(variants, vpat, encoded_library, fc_values, background,
                                   log2fc_thr, totals), score_thr, min_support)[0] == "mixture":
            return True
    return False

In [ ]:
show_doc(_is_mixture)

def _is_mixture(
    motif, pattern, encoded_library, fc_values, background, log2fc_thr:int=-1, score_thr:float=0.5,
    min_support:int=5, totals:NoneType=None
):"""Does fixing one position next to this motif split its carriers into sites and non-sites?

Args:
    motif (str): the candidate.
    pattern (tuple): its `(d1, spacer, d2)` shape.
    encoded_library (tuple): `(fwd, rc)` from `encode_library`.
    fc_values (np.ndarray): log2 fold change per library sequence.
    background (np.ndarray): each sequence's expected depletion rate, from
        `plasmid_background`. The verdict compares the variants with each other and does not
        read it; it completes the totals of a pattern scanned here, which rule 3 shares.
    log2fc_thr (float), score_thr (float), min_support (int): as elsewhere in the step.
    totals (dict): shared pattern totals, as for `_variant_profile`.

Returns:
    bool: True when some position's four bases split."""

In [ ]:
for motif, pat in [("ATANNNNTGTG", (3, 4, 4)), ("ATACNNNNGTG", (4, 4, 3))]:
    print(f"{motif}  {pat}   _is_mixture = {_is_mixture(motif, pat, enc, fcs, bg, -1, 0.7, 3)}")
    for variants, vpat in _undefined_positions(motif, pat):
        prof = _variant_profile(variants, vpat, enc, fcs, bg, -1)
        v, spread = _verdict(prof, 0.7, 3)
        cells = "  ".join(f"{s:.2f}({n})" if n else "  -- (0)" for _, n, s, _ in prof)
        print(f"   {str(vpat):10s} {v:8s} "
              f"spread={'   —' if spread is None else f'{spread:.2f}'}   {cells}")
    print()

ATANNNNTGTG  (3, 4, 4)   _is_mixture = True
   (4, 4, 4)  mixture  spread=0.74   0.99(190)  0.33(3)  0.25(4)    -- (0)
   (3, 4, 5)  genuine  spread=0.07   1.00(53)  0.93(45)  0.95(56)  0.98(43)
   (4, 3, 4)  mixture  spread=1.00   0.20(5)  1.00(189)  0.00(3)    -- (0)
   (3, 3, 5)  genuine  spread=0.49   0.00(2)    -- (0)  0.99(189)  0.50(6)

ATACNNNNGTG  (4, 4, 3)   _is_mixture = False
   (5, 4, 3)  unknown  spread=   —   1.00(189)  1.00(1)  1.00(1)  1.00(1)
   (4, 4, 4)  genuine  spread=0.00   1.00(54)  1.00(44)  1.00(53)  1.00(41)
   (5, 3, 3)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)
   (4, 3, 4)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)

Pinning the base next to `ATANNNNTGTG`'s left half splits its carriers: 190 at 0.99 against a
handful at 0.33 and 0.25. The real site has nothing to split: every base at its one judgeable
position scores 1.00; its other three positions have too few plasmids to judge.

### Rule 2: a one-base extension of a site is redundant

A rule-1 survivor has nothing to split at any position next to it, so a candidate that is that
motif plus one defined base adds nothing: rule 1 scored all four bases at that position and found
no difference. The filter does not compare every pair: `_parent_motifs` lists the motifs a
candidate could extend, and the filter looks them up among the survivors, on either strand
(`_is_extension` is the pairwise definition it is tested against). When the four bases are too thin
to judge, rule 1 keeps the shorter motif and rule 2 drops the extension: with no evidence that
the extra base matters, the simpler description is kept.

In [ ]:
#| hide
# The string test _is_extension is built on: N in `broad` matches any base, every other
# letter literally, on either strand and anywhere along `specific`. Notebook only.
def _check_specific_matches_broad(specific, broad):
  """
  Whether `specific` matches `broad` position by position, `N` in `broad` matching anything.

  Both strings must be the same length. An `N` in `specific` has no special meaning: it only
  matches an `N` in `broad`.

  Args:
    specific: The string that is being checked.
    broad: The string that contains the pattern, where 'N' is a wildcard.

  Returns:
    True if the 'specific' string matches the 'broad' pattern, False otherwise.
  """
  if len(specific) != len(broad):
    return False

  for spec_char, broad_char in zip(specific, broad):
    if spec_char == broad_char or broad_char == 'N':
      continue
    return False
  return True

def _find_broad_in_specific(specific, broad):
  """
  Whether `broad`, or its reverse complement, occurs anywhere in `specific`.

  Each window of `specific` the length of `broad` is compared with
  `_check_specific_matches_broad` (`N` in `broad` is a wildcard), forward first, then against
  `revcomp(broad)`. A `broad` longer than `specific` is never found; an empty one always is.

  Args:
    specific: the motif (or sequence) searched in.
    broad: the motif searched for.

  Returns:
    True if 'broad' or its reverse complement is found in 'specific', False otherwise.
  """
  if len(specific) < len(broad):
    return False

  broad_len = len(broad)
  if broad_len == 0:
      return True

  # 1. Check the forward orientation
  is_forward_match = any(_check_specific_matches_broad(specific[i:i + broad_len], broad)
                         for i in range(len(specific) - broad_len + 1))

  if is_forward_match:
    return True

  # 2. If no forward match, check the reverse complement orientation
  broad_rev_comp = revcomp(broad)
  is_reverse_match = any(_check_specific_matches_broad(specific[i:i + broad_len], broad_rev_comp)
                         for i in range(len(specific) - broad_len + 1))

  return is_reverse_match

In [ ]:
#| code-fold: true
#| code-summary: "Source: _is_extension (notebook only)"
def _is_extension(specific, general):
    """Is `specific` the motif `general` with one more defined base, on either strand?

    The extra base sits one past an end of `general` or at an edge of its spacer -- the
    positions `_undefined_positions` tests. Both strands are checked because every pattern is
    searched in one canonical form, so adding a base to a motif's longer side can turn its shape
    into the mirror form, which the scan writes on the other strand: `TACNNNNGTGA` is
    `CACNNNNGTA` with a base added on the left.
    """
    defined = lambda m: len(m) - m.count("N")
    return defined(specific) == defined(general) + 1 and _find_broad_in_specific(specific, general)

In [ ]:
#| hide
# Same length: N in the broad motif matches a base, N in the specific one only matches N.
test_eq(_check_specific_matches_broad("CACTNNNGTAC", "CACNNNNGTAC"), True)
test_eq(_check_specific_matches_broad("CACNNNNGTAC", "CACTNNNGTAC"), False)
test_eq(_check_specific_matches_broad("CACNNNNGTAC", "CACNNNNGTA"), False)   # length differs

# The direction matters: the broad motif is the one with more N.
test_eq(_find_broad_in_specific("AACGNNTT", "AACNNNTT"), True)
test_eq(_find_broad_in_specific("AACNNNTT", "AACGNNTT"), False)
# Found anywhere along a longer specific motif, never in a shorter one.
test_eq(_find_broad_in_specific("GGATGCC", "ATG"), True)
test_eq(_find_broad_in_specific("ATG", "GATGC"), False)
# On either strand: GTACNNNTGTG is CACANNNGTAC reversed and complemented.
test_eq(_find_broad_in_specific("GTACNNNTGTG", "CACNNNNGTAC"), True)
test_eq(_find_broad_in_specific("GGCTT", "AAGCC"), True)

In [ ]:
#| export
def _motif_shape(motif):
    """`(trimmed motif, pattern)`, or None when the string is not a `(d1, spacer, d2)` motif.

    Leading and trailing `N` are not part of a motif, and a string with two gaps is not a shape
    any pattern can express.
    """
    motif = motif.strip("N")
    if not motif:
        return None
    runs = re.findall(r"N+|[^N]+", motif)
    if len(runs) == 1:
        return motif, (len(motif), 0, 0)
    if len(runs) == 3:
        return motif, (len(runs[0]), len(runs[1]), len(runs[2]))
    return None


def _parent_motifs(motif, pattern):
    """Every motif `motif` could be a one-base extension of.

    The inverse of `_undefined_positions`: the base it adds sits at an end or at a spacer edge,
    so giving up one of those four bases recovers the motif it extends. Checking these against
    the candidates is the same question as asking, of every shorter candidate, whether this motif
    extends it -- at a handful of lookups instead of a comparison per pair.

    Returns the motif strings, without their patterns -- a caller matching against a set of
    candidate strings does not need them.
    """
    d1, spacer, d2 = pattern
    raw = [motif[1:], motif[:-1]]
    if spacer:
        raw.append(motif[:d1 - 1] + "N" + motif[d1:])                  # widen the gap leftwards
        raw.append(motif[:d1 + spacer] + "N" + motif[d1 + spacer + 1:])  # ... and rightwards
    out = []
    for s in raw:
        shaped = _motif_shape(s)
        if shaped is not None and shaped[0] != motif:
            out.append(shaped[0])
    return sorted(set(out))

In [ ]:
#| hide
# _parent_motifs is the inverse of _is_extension: every motif it returns is one the candidate
# extends, and nothing else of that length is. Checked by brute force on the example library's
# own candidates, against the readable definition.
_cands = [("CACNNNNGTAT", (3, 4, 4)), ("TACNNNNGTGA", (3, 4, 4)), ("GGTCTCA", (7, 0, 0)),
          ("CACANNNGTAC", (4, 3, 4)), ("CCACNNNAGTA", (4, 3, 4)), ("AAGTNNNNTTAA", (4, 4, 4))]
_pool = sorted({m for m, _ in _cands} |
               {q for m, pt in _cands for q in _parent_motifs(m, pt)} |
               {"GGTCTC", "CACNNNNGTA", "AAAGNNNNGTT", "CGGCCA"})
for _m, _pt in _cands:
    _by_lookup = {g for g in _parent_motifs(_m, _pt) if g in _pool}
    _by_lookup |= {revcomp(g) for g in _parent_motifs(_m, _pt) if revcomp(g) in _pool}
    _brute = {g for g in _pool if _is_extension(_m, g)}
    test_eq(_by_lookup, _brute)
# an end base either way, and a spacer edge either way
test_eq(_parent_motifs("CACNNNNGTAT", (3, 4, 4)),
        ["ACNNNNGTAT", "CACNNNNGTA", "CACNNNNNTAT", "CANNNNNGTAT"])
test_eq(_parent_motifs("GGTCTCA", (7, 0, 0)), ["GGTCTC", "GTCTCA"])
# the notebook's rule-2 example: CACANNNGTAC extends CACNNNNGTAC
assert "CACNNNNGTAC" in _parent_motifs("CACANNNGTAC", (4, 3, 4))
test_eq(_motif_shape("NNCACNN"), ("CAC", (3, 0, 0)))
test_eq(_motif_shape("CANNCANNCA"), None)          # two gaps: no pattern expresses it

In [ ]:
#| hide
test_eq(_is_extension("CACNNNNGTAT", "CACNNNNGTA"), True)      # a base past the right end
test_eq(_is_extension("TACNNNNGTGA", "CACNNNNGTA"), True)      # ... past the left, other strand
test_eq(_is_extension("CCCCNNNNNTTTC", "CCCNNNNNNTTTC"), True)  # a spacer edge pinned
test_eq(_is_extension("CACNNNNGTA", "CACNNNNGTA"), False)       # not more defined
test_eq(_is_extension("CACANNNGTACC", "CACNNNNGTA"), False)     # two more defined bases
test_eq(_is_extension("GGTCTCA", "CACNNNNGTA"), False)          # unrelated

`CACNNNNGTAC` passes rule 1. At the first position of its spacer, the four bases score alike:

In [ ]:
print("CACNNNNGTAC is a mixture:", _is_mixture("CACNNNNGTAC", (3, 4, 4), enc, fcs, bg, -1, 0.7, 3))
for motif, n, s, _ in _variant_profile([f"CAC{b}NNNGTAC" for b in "ACGT"], (4, 3, 4), enc, fcs, bg, -1):
    print(f"  {motif}  n={n:>3}  score={s:.2f}   extension of CACNNNNGTAC: "
          f"{_is_extension(motif, 'CACNNNNGTAC')}")

CACNNNNGTAC is a mixture: False
  CACANNNGTAC  n=  4  score=1.00   extension of CACNNNNGTAC: True
  CACCNNNGTAC  n=  9  score=1.00   extension of CACNNNNGTAC: True
  CACGNNNGTAC  n=  4  score=1.00   extension of CACNNNNGTAC: True
  CACTNNNGTAC  n=  3  score=1.00   extension of CACNNNNGTAC: True

Every base scores 1.00, so the four are `CACNNNNGTAC` plus a base that says nothing, and rule 2
drops them.

**Why rule 1 comes first.** `CACNNNNGTA` is a mixture, and both real sites, `CACNNNNGTAC` and
`CACNNNNGTAT`, are extensions of it:

In [ ]:
print("CACNNNNGTA is a mixture:", _is_mixture("CACNNNNGTA", (3, 4, 3), enc, fcs, bg, -1, 0.7, 3))
for site in ["CACNNNNGTAC", "CACNNNNGTAT"]:
    print(f"  {site} is an extension of CACNNNNGTA: {_is_extension(site, 'CACNNNNGTA')}")

CACNNNNGTA is a mixture: True
  CACNNNNGTAC is an extension of CACNNNNGTA: True
  CACNNNNGTAT is an extension of CACNNNNGTA: True

Rule 1 removes `CACNNNNGTA`, so the two sites have no surviving motif to extend, and they stay.
Run rule 2 first and both go as extensions of `CACNNNNGTA`, which rule 1 then removes too: the
strain's Type I site disappears. Within each rule the order of the candidates does not matter, so
neither does the result.

### Rule 3: a motif with an uninformative base is not the site

Rule 2 needs the shorter motif to be a candidate. When it fell short of the thresholds, a longer
motif can still clear them because its extra base happens to pick out the most depleted of the
shorter one's carriers. Rule 3 asks from the other side: put N back at one of a candidate's
defined bases and classify the other three bases there. If every one behaves like the site, the
candidate's base carries no information.

A base is classified by comparing two models of its carriers — depleted at the site's rate, or at
their own background — by their log-likelihood ratio, which grows with the number of plasmids and
so is also the confidence: a base is classified when one model fits ten times better. Simpler
criteria fail: a fixed cut-off between the two rates misplaces the boundary, which depends on both,
and a test against background calls site-like a base depleted at four times background but a
quarter of the site's rate. The site's rate is the candidate's own, re-estimated once from the
candidate pooled with the bases first found site-like, because a candidate selected for scoring
high overstates it.

Rule 3 drops a motif when, at one position, *every* other base is site-like. When only some are,
the position is degenerate, and reporting writes it as an IUPAC letter (below).

In [ ]:
#| export
def _relax_positions(motif, pattern):
    """The defined bases of `motif` that can be put back to N, leaving a valid pattern.

    Every base of a contiguous motif -- an interior one becomes a one-base spacer -- and, for a
    gapped motif, the outer base and the spacer-side base of each half, as long as the half keeps
    a defined base. These are the positions rule 1 tests from the other side.
    """
    d1, spacer, d2 = pattern
    if spacer == 0:
        return list(range(len(motif)))
    positions = set()
    if d1 >= 2:
        positions |= {0, d1 - 1}
    if d2 >= 2:
        positions |= {d1 + spacer, len(motif) - 1}
    return sorted(positions)


_LR_THRESHOLD = 10   # a set of plasmids is classified when one model fits it this many times better


def _site_or_background(n, k, site_rate, background_rate):
    """'site', 'non-site' or 'unknown' for a set of `n` plasmids of which `k` are depleted.

    Compares two models of them -- depleted at `site_rate`, or at `background_rate` -- by their
    log-likelihood ratio, which grows with `n`, so it is also the confidence: the set is
    classified only when one model fits `_LR_THRESHOLD` times better. Rates must lie strictly
    between 0 and 1; a site rate no higher than background gives 'unknown'.
    """
    if site_rate <= background_rate:
        return "unknown"
    llr = (k * np.log(site_rate / background_rate)
           + (n - k) * np.log((1 - site_rate) / (1 - background_rate)))
    cut = np.log(_LR_THRESHOLD)
    return "site" if llr > cut else "non-site" if llr < -cut else "unknown"


def _classify_bases(profile, motif, min_support):
    """'site', 'non-site' or 'unknown' for each base other than `motif`'s at one position.

    Each base's carriers are compared under two models -- depleted at the site's rate, or at
    their own background -- by their log-likelihood ratio. The site's rate is the candidate's
    own, re-estimated once from the candidate pooled with the bases first classified site-like.

    Args:
        profile (list): `(motif, n, score, background)` for the four bases, from
            `_variant_profile`.
        motif (str): the candidate, one of the four.
        min_support (int): a base carried by fewer plasmids is not classified.

    Returns:
        dict: other motif -> class, for those with at least `min_support` carriers; `None` when
        the candidate itself has too few.
    """
    own = next((p for p in profile if p[0] == motif), None)
    if own is None or own[1] < min_support:
        return None
    others = [p for p in profile if p[0] != motif and p[1] >= min_support]
    clip = lambda rate, n: min(max(rate, 0.5 / n), 1 - 0.5 / n)   # keep the logs finite

    def classify(site_rate):
        return {m: _site_or_background(n, round(s * n), site_rate, b) for m, n, s, b in others}

    first = classify(clip(own[2], own[1]))
    pooled = [own] + [p for p in others if first[p[0]] == "site"]
    n = sum(p[1] for p in pooled)
    return classify(clip(sum(p[1] * p[2] for p in pooled) / n, n))


def _classify_positions(motif, positions, pattern, encoded_library, fc_values, background,
                       log2fc_thr=-1, min_support=5, totals=None):
    """For each position, the class and carriers of every base `motif` does not allow there.

    At position `i`, each base `motif` does not allow gives a variant -- `motif` with that base at
    `i` -- and `_classify_bases` classifies it against `motif`. A motif of A, C, G and T is profiled
    from the scan's counts (`_variant_profile`); a motif with an IUPAC letter is profiled on the
    carriers of its instances (`_union_profile`).

    Args:
        motif (str): the candidate, IUPAC letters allowed at its defined positions.
        positions (list): defined positions of `motif` to classify.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library, fc_values, background, log2fc_thr, min_support, totals: as for
            `_is_mixture`.

    Returns:
        dict: position -> {base: (class, n carriers)}, for the bases with at least `min_support`
        carriers; empty at every position when `motif` itself has fewer.
    """
    alts = {i: [motif[:i] + b + motif[i + 1:] for b in "ACGT" if b not in _IUPAC_EXPAND[motif[i]]]
            for i in positions}
    motifs = [motif] + [v for vs in alts.values() for v in vs]
    if _encode_motif(motif, pattern) is not None:          # A, C, G and T only: the scan's counts
        profile = _variant_profile(motifs, pattern, encoded_library, fc_values, background,
                                  log2fc_thr, totals)
    else:
        profile = _union_profile(motifs, pattern, encoded_library, fc_values, background,
                                 log2fc_thr)
    stats = dict(zip(motifs, profile))
    out = {}
    for i, vs in alts.items():
        classes = _classify_bases([profile[0]] + [stats[v] for v in vs], motif, min_support) or {}
        out[i] = {v[i]: (classes[v], stats[v][1]) for v in vs if v in classes}
    return out


def _is_over_specified(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
                      min_support=5, totals=None):
    """Does `motif` have a defined base at which every other base behaves like the site?"""
    by_position = _classify_positions(motif, _relax_positions(motif, pattern), pattern,
                                     encoded_library, fc_values, background, log2fc_thr,
                                     min_support, totals)
    return any(classes and all(c == "site" for c, _ in classes.values())
               for classes in by_position.values())

In [ ]:
show_doc(_relax_positions)
show_doc(_classify_bases)
show_doc(_classify_positions)
show_doc(_is_over_specified)

def _is_over_specified(
    motif, pattern, encoded_library, fc_values, background, log2fc_thr:int=-1, min_support:int=5,
    totals:NoneType=None
):"""Does `motif` have a defined base at which every other base behaves like the site?"""

In [ ]:
#| hide
test_eq(_relax_positions("GGTCTC", (6, 0, 0)), [0, 1, 2, 3, 4, 5])
test_eq(_relax_positions("CACNNNNGTAC", (3, 4, 4)), [0, 2, 7, 10])
test_eq(_relax_positions("CANNNNGTAC", (2, 4, 4)), [0, 1, 6, 9])
# Two cases the criterion was chosen on. A real site whose other bases sit at four
# times background but a quarter of the site's rate: informative, keep.
_p = [("A", 653, 0.254, 0.058), ("C", 452, 0.991, 0.058), ("G", 475, 0.242, 0.058), ("T", 840, 0.252, 0.058)]
test_eq(set(_classify_bases(_p, "C", 5).values()), {"non-site"})
# A lucky extension: every other base well above background -- uninformative, drop.
_p = [("A", 299, 0.388, 0.079), ("C", 256, 0.277, 0.079), ("G", 219, 0.516, 0.079), ("T", 251, 0.410, 0.079)]
test_eq(set(_classify_bases(_p, "G", 5).values()), {"site"})
# A degenerate position: one other base is a site, two are not -- informative.
_p = [("A", 255, 0.082, 0.079), ("C", 219, 0.516, 0.079), ("G", 267, 0.105, 0.079), ("T", 310, 0.394, 0.079)]
test_eq(_classify_bases(_p, "C", 5), {"A": "non-site", "G": "non-site", "T": "site"})
# Each base against its own carriers' background: a T depleting at 0.40 beside a site at 0.50 is
# site-like when its carriers' background is 0.08, and not when they deplete at 0.35 anyway.
test_eq(_classify_bases([("C", 300, 0.5, 0.08), ("T", 300, 0.40, 0.08)], "C", 5), {"T": "site"})
test_eq(_classify_bases([("C", 300, 0.5, 0.08), ("T", 300, 0.40, 0.35)], "C", 5), {"T": "non-site"})
# _classify_positions is _classify_bases on each position's profile, keyed by base, with each base's
# carriers: at CACNNNNGTAC's last base T is site-like (CACNNNNGTAT, 192 carriers), A and G are not.
_cls = _classify_positions("CACNNNNGTAC", [10], (3, 4, 4), enc, fcs, bg, -1, 3)[10]
_prof = _variant_profile(["CACNNNNGTA" + b for b in "ACGT"], (3, 4, 4), enc, fcs, bg, -1)
test_eq({b: c for b, (c, _) in _cls.items()},
        {m[-1]: c for m, c in _classify_bases(_prof, "CACNNNNGTAC", 3).items()})
test_eq(_cls["T"], ("site", 192))
# Too few carriers: nothing to classify with.
test_eq(_classify_bases([("A", 2, 1.0, .05), ("C", 3, 1.0, .05), ("G", 1, 1.0, .05), ("T", 2, 1.0, .05)], "C", 5), None)
# the shared test on its own: confidence grows with the number of plasmids
test_eq(_site_or_background(4, 4, 0.99, 0.08), "site")
test_eq(_site_or_background(4, 1, 0.667, 0.25), "unknown")      # too few to tell
test_eq(_site_or_background(40, 10, 0.667, 0.25), "non-site")
test_eq(_site_or_background(10, 9, 0.2, 0.3), "unknown")       # a 'site' no more depleted than background

`CCACNNNAGTA`, a shadow of the strain's Type I site that rules 1 and 2 let through, against
`CACNNNNGTAC`, a real site:

In [ ]:
for motif, pat in [("CCACNNNAGTA", (4, 3, 4)), ("CACNNNNGTAC", (3, 4, 4))]:
    print(f"{motif}  over-specified: {_is_over_specified(motif, pat, enc, fcs, bg, -1, 3)}")
    for i in _relax_positions(motif, pat):
        prof = _variant_profile([motif[:i] + b + motif[i + 1:] for b in "ACGT"], pat, enc, fcs, bg, -1)
        cls = _classify_bases(prof, motif, 3) or {}
        cells = "  ".join(f"{m[i]}:{s:.2f}({n})" + ("" if m == motif else f"={cls.get(m, '-')[:4]}")
                          for m, n, s, _ in prof)
        print(f"   position {i:>2}  {cells}")

CCACNNNAGTA  over-specified: True
   position  0  A:0.95(42)=site  C:1.00(55)  G:1.00(45)=site  T:0.92(60)=site
   position  3  A:0.00(27)=non-  C:1.00(55)  G:0.01(70)=non-  T:0.00(40)=non-
   position  7  A:1.00(55)  C:0.50(2)=-  G:0.00(5)=non-  T:1.00(3)=site
   position 10  A:1.00(55)  C:0.00(1)=-  G:0.00(5)=non-  T:0.00(5)=non-
CACNNNNGTAC  over-specified: False
   position  0  A:0.08(60)=non-  C:1.00(20)  G:0.00(17)=non-  T:0.06(54)=non-
   position  2  A:0.04(23)=non-  C:1.00(20)  G:0.00(24)=non-  T:0.05(21)=non-
   position  7  A:0.03(29)=non-  C:0.08(13)=non-  G:1.00(20)  T:0.10(29)=non-
   position 10  A:0.07(15)=non-  C:1.00(20)  G:0.00(11)=non-  T:1.00(192)=site

At `CCACNNNAGTA`'s first base all four bases deplete almost completely, so its `C` carries
nothing and the motif goes. At every position of `CACNNNNGTAC` the other bases deplete at
background, except at its last: there `T` depletes like `C`, and `A` and `G` do not. That is a
degenerate position — `CACNNNNGTAC` and `CACNNNNGTAT` behave as one site, `CACNNNNGTAY` — and
the reason rule 3 requires *every* other base to be site-like.

### The filter

`_filter_redundant_patterns` applies the three rules in order. Rule 2 is a handful of lookups per
candidate and rule 3 reads patterns the scan already counted, so the filter stays linear in the
number of candidates. Six patterns over the example library:

In [ ]:
#| export
def _patterns(df):
    """The 'pattern' column as `(d1, spacer, d2)` tuples; None where it is missing or unreadable."""
    if "pattern" not in df.columns:
        return [None] * len(df)
    out = []
    for p in df["pattern"]:
        try:
            out.append(tuple(ast.literal_eval(p) if isinstance(p, str) else p) or None)
        except (ValueError, SyntaxError, TypeError):
            out.append(None)
    return out


def _motif_instances(motif, pattern):
    """The motifs of A, C, G and T that `motif` stands for: every IUPAC letter at a defined position
    expanded, the spacer left as it is."""
    d1, spacer, _ = pattern
    gap = range(d1, d1 + spacer)
    choices = [c if i in gap else sorted(_IUPAC_EXPAND[c]) for i, c in enumerate(motif)]
    return ["".join(t) for t in product(*choices)]


def _instance_presence(encoded, motifs, patterns):
    """`_motif_presence_matrix` for motifs with IUPAC letters: a plasmid carries a motif when it
    carries one of its instances (`_motif_instances`), on either strand. Returns `(matrix, handled)`;
    a motif whose pattern is unknown, or which does not fit it, is not handled."""
    inst = [_motif_instances(m, p) if p is not None else [] for m, p in zip(motifs, patterns)]
    # Each distinct instance is looked up once, however many motifs share it.
    keys = list(dict.fromkeys((x, p) for xs, p in zip(inst, patterns) for x in xs))
    col = {k: j for j, k in enumerate(keys)}
    has, ok = _motif_presence_matrix(encoded, [x for x, _ in keys], [p for _, p in keys])
    presence = np.zeros((encoded[0].shape[0], len(motifs)), dtype=bool)
    handled = np.zeros(len(motifs), dtype=bool)
    for j, (xs, p) in enumerate(zip(inst, patterns)):
        cols = [col[(x, p)] for x in xs]
        if cols and ok[cols].all():
            presence[:, j] = has[:, cols].any(axis=1)
            handled[j] = True
    return presence, handled


def _carriers(encoded, motifs, patterns, log2fc_series, left_context, right_context):
    """Boolean (n_sequences, n_motifs): which plasmids carry each motif, on either strand.

    Read from the window codes of each motif's instances (`_instance_presence`); a motif whose
    pattern is unknown falls back to a regex over the sequences with their flanks.
    """
    presence, handled = _instance_presence(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()
    return presence

In [ ]:
show_doc(_carriers)

def _carriers(
    encoded, motifs, patterns, log2fc_series, left_context, right_context
):"""Boolean (n_sequences, n_motifs): which plasmids carry each motif, on either strand.

Read from the window codes of each motif's instances (`_instance_presence`); a motif whose
pattern is unknown falls back to a regex over the sequences with their flanks."""

In [ ]:
#| hide
test_eq(_motif_instances("YGGCCR", (6, 0, 0)), ["CGGCCA", "CGGCCG", "TGGCCA", "TGGCCG"])
test_eq(_motif_instances("RTACNNNNGTG", (4, 4, 3)), ["ATACNNNNGTG", "GTACNNNNGTG"])
test_eq(_motif_instances("GGTCTC", (6, 0, 0)), ["GGTCTC"])

In [ ]:
#| hide
# Patterns come back as tuples whether stored as tuples or as strings; garbage becomes None.
test_eq(_patterns(pd.DataFrame({"pattern": ["(6, 0, 0)", (3, 4, 4), "junk", None]})),
        [(6, 0, 0), (3, 4, 4), None, None])
test_eq(_patterns(pd.DataFrame({"motif": ["GGTCTC"]})), [None])
# Carriers on either strand: GGTCTC is read as GAGACC in the second sequence. A motif without a
# pattern takes the regex path and must agree.
_s = pd.Series([0.0, 0.0, 0.0], index=["GGTCTCAA", "TTGAGACC", "TTTTTTTT"])
_pr = _carriers(encode_library(_s.index.tolist()), ["GGTCTC", "GGTCTY"], [(6, 0, 0), None],
                _s, "", "")
test_eq(_pr.tolist(), [[True, True], [True, True], [False, False]])
# A motif with IUPAC letters is carried where one of its instances is: on the 20 nt library this is
# exactly the regex over the sequences with their flanks, including for the palindromic YGGCCR,
# whose instances CGGCCA and TGGCCG are one site read on its two strands.
_ms, _ps = ["YGGCCR", "RTACNNNNGTG", "CCTHAGG", "GGTCTC"], [(6, 0, 0), (4, 4, 3), (7, 0, 0), (6, 0, 0)]
_u = _carriers(enc, _ms, _ps, log2fc_df["JJ1886_T0"], left, right)
for j, m in enumerate(_ms):
    test_eq(_u[:, j], _get_filter_for_motif(log2fc_df["JJ1886_T0"], m, left, right).to_numpy())
test_eq(_instance_presence(enc, _ms, _ps)[1].all(), True)      # none of them took the regex path

In [ ]:
#| export
def _filter_redundant_patterns(df, log2fc_series, left_context, right_context,
                              log2fc_thr=-1, score_thr=0.5, min_support=5,
                              encoded=None, totals=None, background=None):
    """Keep one description per site, by three rules.

    1. **A mixture is not a site.** A candidate is dropped when fixing one position next to it
       splits the plasmids that carry it into depleting and not (`_is_mixture`).
    2. **A one-base extension of a site is redundant.** A candidate is dropped when it is a
       candidate that survived rule 1 with one more defined base (found by looking up
       `_parent_motifs`): rule 1 found that site's neighbouring positions carry
       nothing, so pinning one adds nothing.
    3. **A motif with an uninformative base is not the site.** A candidate is dropped when, at one
       of its defined bases, every other base behaves like the site (`_is_over_specified`).

    No rule depends on the order the candidates arrive in.

    Args:
        df (pd.DataFrame): candidates, with 'motif' and 'pattern'.
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence.
        left_context (str), right_context (str): the vector flanks.
        log2fc_thr (float): a plasmid is depleted below this.
        score_thr (float): the score a candidate had to reach, reused as the bar a variant must
            clear and as the spread that marks a profile a mixture.
        min_support (int): a variant on fewer plasmids than this is not judged.
        encoded (tuple): the library from `encode_library`, if the caller already has it.
        totals (dict): shared pattern totals, as for `_variant_profile`.
        background (np.ndarray): each plasmid's expected depletion rate; `plasmid_background` of
            `log2fc_series` when not given.

    Returns:
        pd.DataFrame: `df` without the redundant rows, in the original row order.
    """
    if df.empty:
        return df
    motifs = df["motif"].tolist()
    pats = _patterns(df)
    if encoded is None:
        encoded = encode_library(get_lib_seq_context(log2fc_series.index.tolist(),
                                                     left_context, right_context))
    totals = {} if totals is None else totals
    fc = log2fc_series.to_numpy()
    if background is None:
        background = plasmid_background(log2fc_series.index, fc, log2fc_thr)

    # Rule 1. A candidate whose pattern is unknown cannot be tested, and stays.
    survivors = [k for k in range(len(df)) if pats[k] is None or not _is_mixture(
        motifs[k], pats[k], encoded, fc, background, log2fc_thr, score_thr, min_support, totals)]

    # Rule 2, by lookup rather than by comparing pairs: each survivor asks whether any of the
    # four motifs it could extend is itself a survivor. Comparing every pair is quadratic, and
    # at a permissive threshold a strain can reach hundreds of thousands of candidates.
    standing = {motifs[k] for k in survivors}
    standing |= {revcomp(m) for m in standing}      # a parent may be spelled on the other strand
    keep = [k for k in survivors
            if not any(g in standing for g in _parent_motifs(motifs[k], pats[k]))]

    # Rule 3. Every variant it reads is in the candidate's own pattern, which step 2 counted.
    keep = [k for k in keep if pats[k] is None or not _is_over_specified(
        motifs[k], pats[k], encoded, fc, background, log2fc_thr, min_support, totals)]
    return df.iloc[keep]

In [ ]:
show_doc(_filter_redundant_patterns)

def _filter_redundant_patterns(
    df, log2fc_series, left_context, right_context, log2fc_thr:int=-1, score_thr:float=0.5, min_support:int=5,
    encoded:NoneType=None, totals:NoneType=None, background:NoneType=None
):"""Keep one description per site, by three rules.

1. **A mixture is not a site.** A candidate is dropped when fixing one position next to it
   splits the plasmids that carry it into depleting and not (`_is_mixture`).
2. **A one-base extension of a site is redundant.** A candidate is dropped when it is a
   candidate that survived rule 1 with one more defined base (found by looking up
   `_parent_motifs`): rule 1 found that site's neighbouring positions carry
   nothing, so pinning one adds nothing.
3. **A motif with an uninformative base is not the site.** A candidate is dropped when, at one
   of its defined bases, every other base behaves like the site (`_is_over_specified`).

No rule depends on the order the candidates arrive in.

Args:
    df (pd.DataFrame): candidates, with 'motif' and 'pattern'.
    log2fc_series (pd.Series): log2 fold change, indexed by insert sequence.
    left_context (str), right_context (str): the vector flanks.
    log2fc_thr (float): a plasmid is depleted below this.
    score_thr (float): the score a candidate had to reach, reused as the bar a variant must
        clear and as the spread that marks a profile a mixture.
    min_support (int): a variant on fewer plasmids than this is not judged.
    encoded (tuple): the library from `encode_library`, if the caller already has it.
    totals (dict): shared pattern totals, as for `_variant_profile`.
    background (np.ndarray): each plasmid's expected depletion rate; `plasmid_background` of
        `log2fc_series` when not given.

Returns:
    pd.DataFrame: `df` without the redundant rows, in the original row order."""

In [ ]:
pats = [(6, 0, 0), (7, 0, 0), (3, 4, 3), (3, 4, 4), (4, 3, 4), (4, 4, 4)]
enc = encode_library(lib)
candidates_demo = pd.concat([_scan_candidates(p, enc, fcs, bg, -1, 0.7, 3)[0] for p in pats],
                            ignore_index=True)
_pat = lambda s: tuple(int(x) for x in s.strip("()").split(","))
mixtures = [m for m, p in zip(candidates_demo.motif, candidates_demo.pattern)
            if _is_mixture(m, _pat(p), enc, fcs, bg, -1, 0.7, 3)]
rows = list(candidates_demo.itertuples())
surv = [r for r in rows if r.motif not in mixtures]
after2 = [r for r in surv if not any(_is_extension(r.motif, o.motif) for o in surv)]
kept = _filter_redundant_patterns(candidates_demo, log2fc_df["JJ1886_T0"], left, right,
                                 log2fc_thr=-1, score_thr=0.7, min_support=3)
print(f"{len(candidates_demo)} candidates: rule 1 drops {len(mixtures)} mixtures, rule 2 drops "
      f"{len(surv) - len(after2)} extensions, rule 3 drops {len(after2) - len(kept)} "
      f"over-specified motifs, {len(kept)} go on to step 4")
kept.sort_values("num_sequences", ascending=False)[["motif", "pattern", "fraction_depleted",
                                                    "num_sequences"]].head(8)

75 candidates: rule 1 drops 12 mixtures, rule 2 drops 24 extensions, rule 3 drops 6 over-specified motifs, 33 go on to step 4

           motif    pattern  fraction_depleted  num_sequences
14   CACNNNNGTAT  (3, 4, 4)           1.000000            192
51  AATANNNNTGTG  (4, 4, 4)           0.989474            190
12   AACNNNNCTTT  (3, 4, 4)           1.000000             63
17   CACNNNNGTAC  (3, 4, 4)           1.000000             20
1         GAGACC  (6, 0, 0)           1.000000              9
38   TGGCNNNCACA  (4, 3, 4)           0.714286              7
35   AAGTNNNGTTA  (4, 3, 4)           0.833333              6
25   GAAGNNNACAC  (4, 3, 4)           0.800000              5

The survivors include the strain's sites, on whichever strand the scan read them: `CACNNNNGTAT`
(reported as `ATACNNNNGTG`), `AACNNNNCTTT` (`AAAGNNNNGTT`), `CACNNNNGTAC` and `GAGACC`. Beside
them sits `AATANNNNTGTG`, 0.99 depleted on 190 plasmids, because nearly every plasmid that carries
it also carries `ATACNNNNGTG`; the other 28 survivors are on seven plasmids or fewer. None of them
is a site plus one base, so no string rule relates them to a site: that is step 4's question.

In [ ]:
#| hide
_lib = pd.Series([-5.0, -5.0, 0.0], index=["GAGACCTT", "AAGAGACC", "TTTTTTTT"])
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# Unrelated motifs describe different plasmids, so both stand.
_t = pd.DataFrame({"motif": ["GGTCTC", "AAACNNNNGTC"], "fraction_depleted": [0.95, 0.80],
                   "pattern": ["(6, 0, 0)", "(4, 4, 3)"]})
test_eq(len(_filter_redundant_patterns(_t, _lib, "", "", **_kw)), 2)

# Only N is a wildcard. A full IUPAC code is not treated as covering the bases it stands for,
# so these two are unrelated to this filter. The scan only ever emits N, so this bounds what the
# filter can be asked to do rather than describing what it sees.
test_eq(_find_broad_in_specific("CACNNNNGTAC", "CACNNNNGTAY"), False)

## Step 4: drop candidates whose score was borrowed

Two descriptions of one site in different shapes — `ATACNNNNGTG` of pattern `(4, 4, 3)` and
`CACANNAGTA` of `(4, 2, 4)` — sit on mostly the same plasmids, but neither is the other with a
position left undefined. What separates them is what each has that the other does not:

In [ ]:
_pair = ["ATACNNNNGTG", "CACANNAGTA"]
_has = _carriers(enc, _pair, [(4, 4, 3), (4, 2, 4)], log2fc_df["JJ1886_T0"], left, right)
_dep = fcs < -1
print(f"shared: {(_has[:, 0] & _has[:, 1]).sum()} plasmids")
for j, other in [(0, 1), (1, 0)]:
    alone = _has[:, j] & ~_has[:, other]
    print(f"{_pair[j]:<12} n={_has[:, j].sum()}  score {_dep[_has[:, j]].mean():.3f}   "
          f"without {_pair[other]}'s plasmids: n={alone.sum()}  score {_dep[alone].mean():.3f}")

shared: 188 plasmids
ATACNNNNGTG  n=192  score 1.000   without CACANNAGTA's plasmids: n=4  score 1.000
CACANNAGTA   n=192  score 0.990   without ATACNNNNGTG's plasmids: n=4  score 0.500

Without the plasmids carrying `ATACNNNNGTG`, `CACANNAGTA` falls from 0.99 to 0.50: its score was
**borrowed**. Without those carrying `CACANNAGTA`, `ATACNNNNGTG` holds at 1.00. A candidate is
dropped when, restricted to the plasmids that carry it but no stronger candidate, it no longer
reaches `score_thr`. The test is on the collapse, not on what is left: both leftovers here are four
plasmids.

Candidates are tested strongest first — highest fraction depleted, then most plasmids — each
against the union of the survivors ranked above it. Every survivor is then tested again against
all the others, weakest first, because a shadow can rank above the site it shadows. A leftover must
also be depleted beyond its own background at the scan's cutoff: the largest p-value that clears
`q_threshold` after Benjamini-Hochberg over every motif the scan tested, the pool every candidate
was selected from. On the six-pattern search of step 3:

In [ ]:
#| export
def _filter_explained_candidates(candidates_df, log2fc_series, left_context, right_context,
                                log2fc_thr=-1, score_thr=0.7, min_support=3,
                                encoded=None, p_threshold=0.05, background=None):
    """Drop candidates whose depletion is fully accounted for by stronger candidates.

    Candidates are taken strongest first. Each `X` is restricted to the plasmids that carry
    **none** of the stronger candidates still standing; if what is left no longer reaches
    `score_thr`, or is not depleted beyond its own background at `p_threshold`, `X`'s score
    was borrowed and `X` is removed. Otherwise it stands, and the plasmids that carry it join the
    set later candidates are tested against.

    After the pass, every survivor is tested again against the union of *all* the others,
    weakest first, removing one at a time: the pass tests a candidate only against those ranked
    above it, and a shadow can rank above the site it shadows.

    Args:
        candidates_df: candidates, with 'motif' and (optionally) 'pattern' columns.
        log2fc_series: the full log2FC series, indexed by sequence.
        left_context, right_context: the vector sequence flanking the insert.
        log2fc_thr: a plasmid is depleted below this.
        score_thr: fraction of a candidate's leftover plasmids that must still be depleted.
        min_support: not used: a candidate's support was established when it became one.
            Accepted so the step takes the same thresholds as the rest of the pipeline.
        encoded: the library from `encode_library`, if the caller already has it.
        p_threshold: the leftover must also be depleted beyond its background -- the mean
            background of its plasmids -- at this p-value. `find_restricted_motifs` passes the
            scan's Benjamini-Hochberg cutoff.
        background: each plasmid's expected depletion rate; `plasmid_background` of
            `log2fc_series` when not given.

    Returns:
        (kept_df, explanations) where explanations maps a dropped motif to
        (explaining motif, plasmids left, score on them).
    """
    if len(candidates_df) < 2:
        return candidates_df, {}     # nothing that could explain anything

    motifs = candidates_df['motif'].tolist()
    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence = _carriers(encoded, motifs, _patterns(candidates_df), log2fc_series,
                         left_context, right_context)

    fc = log2fc_series.to_numpy()
    if background is None:
        background = plasmid_background(log2fc_series.index, fc, log2fc_thr)
    strength = []
    for j in range(len(motifs)):
        v = fc[presence[:, j]]
        strength.append(((v < log2fc_thr).mean() if len(v) else 0.0, len(v), motifs[j]))
    # Strongest first: highest depletion fraction, then MOST plasmids. Support breaks the tie, not
    # mean log2FC, because the plasmids carrying a shadow are a subset of those carrying its
    # parent, and the subset picked out by the extra bases it requires tends to be the most
    # depleted -- so on mean log2FC a shadow outranks the site it came from and is never tested
    # against it. A subset can never have more plasmids than the set it is drawn from. The motif
    # string is the final tie-break, so the outcome does not depend on row order.
    order = sorted(range(len(motifs)), key=lambda j: (-strength[j][0], -strength[j][1], strength[j][2]))

    # A leftover stands when it still reaches score_thr AND is depleted beyond its own
    # background -- the binomial null the calls are scored against, the rate being the mean
    # background of the leftover plasmids -- at the scan's own cutoff.
    def holds(alone):
        n = int(alone.sum())
        still = float((fc[alone] < log2fc_thr).mean()) if n else 0.0
        ok = n > 0 and still >= score_thr and \
            _motif_pvalues([n], [still], background[alone].sum() / n)[0] <= p_threshold
        return ok, n, still

    explanations = {}
    # The test is against the UNION of the stronger survivors: a description that overlaps
    # several co-occurring sites can keep a depleted residue against each of them separately
    # although every plasmid that carries it carries one of them.
    covered = np.zeros(presence.shape[0], dtype=bool)
    standing = []                                        # survivors, strongest first
    for x in order:
        ok, n, still = holds(presence[:, x] & ~covered)
        if not ok:
            # Name the survivor that accounts for most of X's plasmids, and say how many others
            # it took. A dropped candidate explains nothing, so it never joins `covered`.
            shared = [(int((presence[:, x] & presence[:, y]).sum()), -k, y)
                      for k, y in enumerate(standing)]
            shared = [s for s in shared if s[0] > 0]
            if shared:
                label = motifs[max(shared)[2]] + (
                    f" + {len(shared) - 1} more" if len(shared) > 1 else "")
            else:                    # fails on the plasmids that carry it; nothing to blame
                label = "(no stronger motif)"
            explanations[x] = (label, n, still)
            continue
        covered |= presence[:, x]
        standing.append(x)

    # The audit: every survivor against all the others, weakest first, one removal at a time.
    survivors = standing
    while len(survivors) > 1:
        cover = presence[:, survivors].sum(axis=1)
        for x in sorted(survivors, key=lambda j: strength[j]):
            ok, n, still = holds(presence[:, x] & (cover == 1))   # carried by x alone
            if not ok:
                overlap = max((y for y in survivors if y != x),
                              key=lambda y: int((presence[:, x] & presence[:, y]).sum()))
                explanations[x] = (motifs[overlap] + " (audit)", n, still)
                survivors.remove(x)
                break
        else:
            break

    keep = [j for j in range(len(motifs)) if j not in explanations]
    return candidates_df.iloc[keep], {motifs[x]: v for x, v in explanations.items()}

In [ ]:
show_doc(_filter_explained_candidates)

def _filter_explained_candidates(
    candidates_df, log2fc_series, left_context, right_context, log2fc_thr:int=-1, score_thr:float=0.7,
    min_support:int=3, encoded:NoneType=None, p_threshold:float=0.05, background:NoneType=None
):"""Drop candidates whose depletion is fully accounted for by stronger candidates.

Candidates are taken strongest first. Each `X` is restricted to the plasmids that carry
**none** of the stronger candidates still standing; if what is left no longer reaches
`score_thr`, or is not depleted beyond its own background at `p_threshold`, `X`'s score
was borrowed and `X` is removed. Otherwise it stands, and the plasmids that carry it join the
set later candidates are tested against.

After the pass, every survivor is tested again against the union of *all* the others,
weakest first, removing one at a time: the pass tests a candidate only against those ranked
above it, and a shadow can rank above the site it shadows.

Args:
    candidates_df: candidates, with 'motif' and (optionally) 'pattern' columns.
    log2fc_series: the full log2FC series, indexed by sequence.
    left_context, right_context: the vector sequence flanking the insert.
    log2fc_thr: a plasmid is depleted below this.
    score_thr: fraction of a candidate's leftover plasmids that must still be depleted.
    min_support: not used: a candidate's support was established when it became one.
        Accepted so the step takes the same thresholds as the rest of the pipeline.
    encoded: the library from `encode_library`, if the caller already has it.
    p_threshold: the leftover must also be depleted beyond its background -- the mean
        background of its plasmids -- at this p-value. `find_restricted_motifs` passes the
        scan's Benjamini-Hochberg cutoff.
    background: each plasmid's expected depletion rate; `plasmid_background` of
        `log2fc_series` when not given.

Returns:
    (kept_df, explanations) where explanations maps a dropped motif to
    (explaining motif, plasmids left, score on them)."""

In [ ]:
_scan = [_scan_candidates(p, enc, fcs, bg, -1, 0.7, 3)[1] for p in pats]
_pv = np.concatenate(_scan)
_cut = _pv[_benjamini_hochberg(_pv) < 0.05].max()          # the scan's BH cutoff at q < 0.05
after4, why = _filter_explained_candidates(kept, log2fc_df["JJ1886_T0"], left, right,
                                          log2fc_thr=-1, score_thr=0.7, encoded=enc,
                                          p_threshold=_cut)
print(f"scan cutoff p <= {_cut:.1e}; {len(kept)} candidates -> {len(after4)}")
for m, (by, n, s) in sorted(why.items(), key=lambda kv: -kv[1][1]):
    print(f"  {m:<14} <- {by:<28} {n:>3} plasmids left, score {s:.2f}")
after4[["motif", "pattern", "fraction_depleted", "num_sequences"]]

scan cutoff p <= 1.4e-04; 33 candidates -> 5
  AAGTNNNNTTAA   <- AACNNNNCTTT                    3 plasmids left, score 0.67
  CACGNNNNTACC   <- CACNNNNGTAT + 1 more           3 plasmids left, score 0.67
  GTGTNNNNCGGA   <- CACNNNNGTAT                    3 plasmids left, score 0.67
  CTCTNNNNTCTC   <- CACNNNNGTAT                    3 plasmids left, score 0.67
  GAACNNNNGCCC   <- CACNNNNGTAC                    2 plasmids left, score 1.00
  AATANNNNTGTG   <- CACNNNNGTAT + 1 more           2 plasmids left, score 0.00
  GAAGNNNACAC    <- CACNNNNGTAT                    2 plasmids left, score 0.50
  AAGGNNNGTTC    <- AACNNNNCTTT                    2 plasmids left, score 0.50
  CCTGAGA        <- GAGACC                         2 plasmids left, score 0.50
  TGGCNNNCACA    <- CACNNNNGTAT                    2 plasmids left, score 0.00
  GACCNNNNCCTC   <- GAGACC                         1 plasmids left, score 1.00
  AGAGNNNNCACG   <- CACNNNNGTAT + 1 more           1 plasmids left, score 1.00
  CCACNNNTGTA    <- CACNNNNGTAC                    1 plasmids left, score 1.00
  AAGTNNNGTTA    <- AACNNNNCTTT + 1 more           1 plasmids left, score 0.00
  CTGGNNNNCACA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GTGTNNNNATAA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  TGTGNNNATAA    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  AAGTNNNGTTC    <- AACNNNNCTTT + 1 more           1 plasmids left, score 0.00
  CAGANNNCTCA    <- GAGACC                         1 plasmids left, score 0.00
  CCTGNNNCCTC    <- GAGACC + 1 more                1 plasmids left, score 0.00
  CGCCNNNNCACA   <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GACTNNNACAC    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  TGCTNNNCACA    <- CACNNNNGTAT                    1 plasmids left, score 0.00
  GCGGNNNNCACA   <- CACNNNNGTAT + 1 more           0 plasmids left, score 0.00
  CCTTNNNACAC    <- CACNNNNGTAT                    0 plasmids left, score 0.00
  GCAGNNNNCTCA   <- GAGACC                         0 plasmids left, score 0.00
  GGCANNNNCACA   <- CACNNNNGTAT                    0 plasmids left, score 0.00
  TGTGNNNNTAAA   <- CACNNNNGTAT                    0 plasmids left, score 0.00

          motif    pattern  fraction_depleted  num_sequences
1        GAGACC  (6, 0, 0)                1.0              9
12  AACNNNNCTTT  (3, 4, 4)                1.0             63
14  CACNNNNGTAT  (3, 4, 4)                1.0            192
17  CACNNNNGTAC  (3, 4, 4)                1.0             20
34  AGGTNNNGGTC  (4, 3, 4)                1.0              3

Five candidates stand: the strain's four sites and `AGGTNNNGGTC`, which rests on three depleted
plasmids that no stronger candidate accounts for (this search uses `min_support=3`; the default of
5 would not have admitted it). `AATANNNNTGTG` keeps two of its 190 plasmids, neither depleted.
`GAAGNNNACAC` shows why a leftover must also beat background: one of its two leftover plasmids is
depleted, 50%, but against their background of 0.050 that is p = 0.10, far above the cutoff.

In [ ]:
#| hide
# Two candidates on ten plasmids each, eight of them shared. What decides is whether the two
# plasmids NOT shared still deplete beyond their background.
def _overlapping(own_depleted):
    # Every insert is 16 nt with 7 G/C, so all share one GC bin and one background.
    seqs, fc = [], []
    for i in range(8):                                   # carry both
        seqs.append("GGTCTCACGTAC" + "".join("AT"[(i >> b) & 1] for b in range(4))); fc.append(-5.0)
    for tail in ("TTGCCATTTA", "TTGCCATTAT"):            # GGTCTC alone, depleted
        seqs.append("GGTCTC" + tail); fc.append(-5.0)
    for tail in ("TTAT", "TTTA"):                        # ACGTAC alone
        seqs.append("GCGCTTACGTAC" + tail); fc.append(-5.0 if own_depleted else 0.0)
    for k in range(100):                                 # neither: a hundred untouched plasmids,
        # so the sample has a realistic background against which two depleted leftovers are evidence
        seqs.append("CCCCCCC" + "".join("AT"[(k >> b) & 1] for b in range(9))); fc.append(0.0)
    return pd.Series(fc, index=seqs)

_t = pd.DataFrame({"motif": ["GGTCTC", "ACGTAC"], "pattern": ["(6, 0, 0)", "(6, 0, 0)"],
                   "fraction_depleted": [1.0, 1.0], "num_sequences": [10, 10]})
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# its own two plasmids deplete -> ACGTAC keeps its claim
_kept, _why = _filter_explained_candidates(_t, _overlapping(True), "", "", **_kw)
test_eq(sorted(_kept.motif), ["ACGTAC", "GGTCTC"])
test_eq(_why, {})

# its own two plasmids do not -> the score was borrowed from GGTCTC
_kept, _why = _filter_explained_candidates(_t, _overlapping(False), "", "", **_kw)
test_eq(list(_kept.motif), ["GGTCTC"])
test_eq(_why["ACGTAC"][0], "GGTCTC")
test_eq(_why["ACGTAC"][1], 2)          # two plasmids left, well under min_support
test_eq(_why["ACGTAC"][2], 0.0)        # and they do not deplete

# Step 4 on the six-pattern search: the strain's four sites stand, with one three-plasmid motif
# that no stronger candidate accounts for, and the 190-plasmid shadow goes.
test_eq(sorted(after4.motif),
        ["AACNNNNCTTT", "AGGTNNNGGTC", "CACNNNNGTAC", "CACNNNNGTAT", "GAGACC"])
assert "AATANNNNTGTG" in why

# An empty table and a single candidate come back untouched: there is nothing to explain with.
test_eq(len(_filter_explained_candidates(pd.DataFrame(), _overlapping(True), "", "")[0]), 0)
test_eq(len(_filter_explained_candidates(_t.iloc[:1], _overlapping(True), "", "")[0]), 1)

## Reporting

A motif and its reverse complement carry identical statistics, so each reported motif is put on
its canonical strand (`canonical_motif`, `01_utils`), its pattern mirrored to follow it: a site
comes back as `GGTCTC`, never `GAGACC`, in every run and every dataset of the same strain.

In [ ]:
#| export
def _canonicalise_motifs(df):
    """Put every motif in a result table on its canonical strand.

    A motif and its reverse complement have identical statistics, so rewriting the label loses
    nothing.
    """
    if df is None or df.empty or 'motif' not in df.columns:
        return df
    df = df.copy()
    flipped = df['motif'] != df['motif'].map(canonical_motif)
    df['motif'] = df['motif'].map(canonical_motif)
    # The pattern has to follow the motif. Reverse-complementing a (d1, spacer, d2) site gives
    # a (d2, spacer, d1) site, so a relabelled row whose pattern was left alone would describe
    # a string it does not hold -- and every consumer that pairs motif with pattern, such as
    # _motif_presence_matrix, would silently decline to handle it.
    if 'pattern' in df.columns:
        def _mirror(p):
            try:
                d1, sp, d2 = ast.literal_eval(p) if isinstance(p, str) else tuple(p)
            except (ValueError, SyntaxError, TypeError):
                return p
            # With no spacer the site is contiguous and (k, 0, 0) is the spelling the
            # pattern list uses, so mirroring must not turn (6, 0, 0) into (0, 0, 6).
            m = (d1 + d2, 0, 0) if sp == 0 else (d2, sp, d1)
            return str(m) if isinstance(p, str) else m
        df.loc[flipped, 'pattern'] = df.loc[flipped, 'pattern'].map(_mirror)
    return df

In [ ]:
#| hide
# Rewrites to the canonical strand and leaves everything else alone.
_t = pd.DataFrame({'motif': ['GAGACC', 'AACNNNNCTTT'], 'pattern': [(6, 0, 0), (3, 4, 4)],
                   'num_sequences': [6, 54], 'avg_log2fc': [-3.75, -5.02]})
_out = _canonicalise_motifs(_t)
assert list(_out.motif) == ['GGTCTC', 'AAAGNNNNGTT']
assert list(_out.num_sequences) == [6, 54]

# An empty table is returned untouched rather than exploding.
assert _canonicalise_motifs(pd.DataFrame()).empty

### Is the depletion one population or two?

A real site shifts its carriers as one population. A shadow of another site is a **mixture**: the
carriers that also carry the real site are destroyed, the rest untouched. Sarle's **bimodality
coefficient** exceeds 5/9, its value for a uniform distribution, when a distribution has two modes
— but also when the carriers fall into two *depleted* groups: `CACNNNNGTAC` on the 20 nt JJ1886
library has 19 carriers between −6.6 and −4.4 and one at −8.6, a coefficient of 0.654. So
`bimodal` also requires that, split in two where they separate best, the upper group is not
depleted (its median at or above `log2fc_thr`); `bimodality` keeps the raw coefficient. A shadow
is significant and bimodal, a weak real site significant and unimodal, so both are reported;
bimodality does not block a call.

`_annotate_significance` adds these two columns to the result table, with the p- and q-values and
the bound on the depleted fraction (*Reading the result table*, below).

In [ ]:
#| export
def _bimodality_coefficient(values):
    """Sarle's bimodality coefficient: (skew^2 + 1) / (kurtosis + 3(n-1)^2/((n-2)(n-3))).

    Above 5/9 the distribution is more bimodal than a uniform one. NaN below four values, where
    it is not defined, and when every value is the same.
    """
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 4 or np.allclose(v, v[0]):
        return float("nan")
    g = skew(v, bias=False)
    k = kurtosis(v, bias=False, fisher=True)
    denom = k + 3.0 * (n - 1) ** 2 / ((n - 2) * (n - 3))
    return float((g ** 2 + 1.0) / denom) if denom > 0 else float("nan")


_BIMODALITY_BENCHMARK = 5.0 / 9.0


def _upper_group_median(values):
    """Median of the upper group when `values` are split in two at the cut that maximises the
    between-group variance (Otsu's method: two-means in one dimension, on the sorted values).

    NaN below two finite values.
    """
    v = np.sort(np.asarray(values, dtype=float))
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 2:
        return float("nan")
    k = np.arange(1, n)                       # the lower group is v[:k]
    low = np.cumsum(v)[:-1]
    between = k * (n - k) * (low / k - (v.sum() - low) / (n - k)) ** 2
    return float(np.median(v[k[np.argmax(between)]:]))


def _annotate_significance(results_df, log2fc_series, left_context, right_context,
                          all_pvalues=None, log2fc_thr=-1, q_threshold=0.05, encoded=None,
                          background=None, score_thr=0.5):
    """Add fraction_depleted_lower, background, p_value, q_value, called, bimodality and bimodal
    to a result table.

    `fraction_depleted_lower` is the one-sided lower confidence bound on the fraction of carriers
    depleted (Clopper-Pearson, at level `q_threshold`). A candidate had to reach `score_thr` --
    most of its carriers depleted -- and a call has to show it: 5 of 10 depleted is 0.5, but its
    bound is 0.22.

    `background` is the rate at which the motif's carriers would deplete with no site involved:
    the mean over them of each plasmid's GC-matched background (`plasmid_background`, computed
    from `log2fc_series` when not given). The p-value is taken against it, as in the scan.

    `all_pvalues` are the p-values of every motif the scan tested, which is what the
    Benjamini-Hochberg correction has to be computed over -- correcting only over the handful
    that survived filtering would be meaningless.

    `bimodal` marks carriers that are a mixture of depleted and background-level plasmids: a
    bimodality coefficient above 5/9 and, when the carriers are split in two where they separate
    best, an upper group that is not depleted at `log2fc_thr`.

    Nothing is removed. `called` marks the rows whose q-value is below `q_threshold` and whose
    `fraction_depleted_lower` reaches `score_thr`; the rest stay in the table so that a weak
    result is visible as a weak claim rather than silently absent (`find_restricted_motifs`
    returns them with `all_motifs=True`).
    """
    if results_df is None:
        return results_df
    if results_df.empty:
        # A strain with no active system is the first thing a new user runs, so the empty
        # table must have the same columns as a full one -- otherwise selecting the called
        # rows works on every strain that finds something and raises on the ones that do not.
        out = results_df.copy()
        for _c, _dt in (("fraction_depleted_lower", float), ("background", float),
                        ("p_value", float), ("q_value", float), ("called", bool),
                        ("bimodality", float), ("bimodal", bool)):
            if _c not in out.columns:
                out[_c] = pd.Series(dtype=_dt)
        return out
    # Placed beside fraction_depleted below; dropped first so a table can be annotated again.
    out = results_df.drop(columns=["fraction_depleted_lower", "background"], errors="ignore")
    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    if background is None:
        background = plasmid_background(log2fc_series.index, log2fc_series.to_numpy(), log2fc_thr)
    presence = _carriers(encoded, out["motif"].tolist(), _patterns(out), log2fc_series,
                         left_context, right_context)
    # Each motif's null is its carriers' mean background, summed exactly as the scan sums it, so
    # that a reported motif's p-value is the scan's to the last bit (see `plasmid_background`).
    rate = (background @ presence) / presence.sum(axis=0)
    n = out["num_sequences"].to_numpy()
    k = np.rint(out["fraction_depleted"].to_numpy() * n)
    at = out.columns.get_loc("fraction_depleted") + 1
    out.insert(at, "fraction_depleted_lower",
               np.where(k > 0, beta.ppf(q_threshold, np.maximum(k, 1), n - k + 1), 0.0))
    out.insert(at + 1, "background", rate)

    p = _motif_pvalues(out["num_sequences"].to_numpy(), out["fraction_depleted"].to_numpy(), rate)
    out["p_value"] = p
    if all_pvalues is not None and len(all_pvalues):
        # The reported motifs were tested by the scan, so their p-values are already in
        # `all_pvalues`; appending them again counted those tests twice. Only a p-value the scan
        # never produced is a new test and joins the pool. Each motif's q is then read off the
        # adjusted pool at its own p-value -- BH q-values are a non-decreasing step function of
        # p, so tied p-values share one q.
        pool = np.asarray(all_pvalues, dtype=float)
        pool = np.sort(np.concatenate([pool, p[~np.isin(p, pool)]]))
        q_pool = _benjamini_hochberg(pool)
        out["q_value"] = q_pool[np.searchsorted(pool, p, side="right") - 1]
    else:
        out["q_value"] = _benjamini_hochberg(p)
    out["called"] = (out["q_value"] < q_threshold) & (out["fraction_depleted_lower"] >= score_thr)

    values = log2fc_series.to_numpy()
    carriers = [values[presence[:, j]] for j in range(len(out))]
    out["bimodality"] = [_bimodality_coefficient(v) for v in carriers]
    # Two modes, the upper one at background: destroyed and untouched plasmids mixed. Two
    # depleted modes -- strong and very strong -- are a site, not a mixture.
    out["bimodal"] = (out["bimodality"] > _BIMODALITY_BENCHMARK) & \
        np.array([_upper_group_median(v) >= log2fc_thr for v in carriers], dtype=bool)

    return out.sort_values(["called", "q_value"], ascending=[False, True])

In [ ]:
#| hide
# CACNNNNGTAC on the 20 nt library against a made-up shadow whose carriers are half destroyed and
# half untouched.
_cac = log2fc_df["JJ1886_T0"][_get_filter_for_motif(log2fc_df["JJ1886_T0"], "CACNNNNGTAC", left, right)].to_numpy()
_shadow = np.concatenate([np.full(10, -5.0), np.random.default_rng(0).normal(0, 0.3, 10)])
for name, v in [("CACNNNNGTAC", _cac), ("shadow", _shadow)]:
    print(f"{name:<12} n={len(v)}  sorted: {np.round(np.sort(v), 1)[:3]} ... {np.round(np.sort(v), 1)[-3:]}")
    print(f"{'':<12} bimodality {_bimodality_coefficient(v):.3f}   "
          f"upper group median {_upper_group_median(v):+.2f}")

CACNNNNGTAC  n=20  sorted: [-8.6 -6.6 -5.9] ... [-4.6 -4.4 -4.4]
             bimodality 0.654   upper group median -4.96
shadow       n=20  sorted: [-5. -5. -5.] ... [0.2 0.3 0.4]
             bimodality 0.755   upper group median +0.03

In [ ]:
#| hide
# destroyed-or-untouched, the signature of a borrowed score
_two = np.concatenate([np.zeros(20), np.full(20, -5.0)])
assert _bimodality_coefficient(_two) > _BIMODALITY_BENCHMARK
# one shifted population, the signature of a real site
_one = np.random.default_rng(0).normal(-3, 0.5, 40)
assert _bimodality_coefficient(_one) < _BIMODALITY_BENCHMARK
assert np.isnan(_bimodality_coefficient([1.0, 2.0, 3.0]))   # undefined below four values
assert np.isnan(_bimodality_coefficient([1.0] * 10))        # and with no spread at all

# The split finds the gap: the upper group of a destroyed/untouched mixture sits at background,
# and that of a strong + very strong site is still depleted.
test_eq(_upper_group_median(_two), 0.0)
test_eq(_upper_group_median(np.r_[np.full(19, -5.0), -8.6]), -5.0)
assert np.isnan(_upper_group_median([1.0]))

# The two cases of the example above. Both pass the coefficient; only the mixture is flagged.
assert _bimodality_coefficient(_cac) > _BIMODALITY_BENCHMARK
assert _upper_group_median(_cac) < -0.5
assert _bimodality_coefficient(_shadow) > _BIMODALITY_BENCHMARK
assert _upper_group_median(_shadow) >= -0.5

# The flag in the table: carriers of AAAAAA are half destroyed and half untouched; carriers of
# GGTCTC are all depleted, one far further than the rest. Both are bimodal by the coefficient.
_lib = pd.Series(np.r_[np.full(6, -5.0), np.zeros(6), np.full(5, -5.0), -9.0, np.zeros(8)],
                 index=[f"AAAAAA{i:06b}".replace("0", "C").replace("1", "G") for i in range(12)] +
                       [f"GGTCTC{i:06b}".replace("0", "C").replace("1", "T") for i in range(6)] +
                       [f"CCCCCC{i:06b}".replace("0", "G").replace("1", "T") for i in range(8)])
_res = pd.DataFrame({"motif": ["AAAAAA", "GGTCTC"], "pattern": ["(6, 0, 0)", "(6, 0, 0)"],
                     "fraction_depleted": [0.5, 1.0], "num_sequences": [12, 6], "avg_log2fc": [-2.5, -5.7]})
_flag = _annotate_significance(_res, _lib, "", "", log2fc_thr=-0.5).set_index("motif")
assert (_flag.bimodality > _BIMODALITY_BENCHMARK).all()
test_eq(_flag.bimodal.to_dict(), {"AAAAAA": True, "GGTCTC": False})
_L, _R = "AAAA", "TTTT"
_seqs = ["GGTCTCAAAAAA", "AAAAAAGGTCTC", "CCCCAAAAAAAA", "AAAAAAAACCCC"]   # all one GC content
_fc = pd.Series([-5.0, -5.0, -0.1, -0.1], index=_seqs)
_res = pd.DataFrame({"motif": ["GGTCTC"], "pattern": ["(6, 0, 0)"],
                     "fraction_depleted": [1.0], "num_sequences": [2], "avg_log2fc": [-5.0]})
_out = _annotate_significance(_res, _fc, _L, _R, log2fc_thr=-1)
for _c in ("fraction_depleted_lower", "background", "p_value", "q_value", "called",
           "bimodality", "bimodal"):
    assert _c in _out.columns
# one GC content, half the plasmids below -1, so every carrier's background is 0.5
test_eq(_out.background.iloc[0], 0.5)
# the bound on the depleted fraction: 9 of 9 depleted is confidently a majority (0.05 ** (1/9) =
# 0.72), 5 of 10 is not (0.22), however small its q-value -- so it is reported but not called
_bound = lambda k, n: _annotate_significance(_res.assign(num_sequences=n, fraction_depleted=k / n),
                                            _fc, _L, _R, log2fc_thr=-1, all_pvalues=[1e-20])
test_close(_bound(9, 9).fraction_depleted_lower.iloc[0], 0.05 ** (1 / 9), eps=1e-9)
test_close(_bound(5, 10).fraction_depleted_lower.iloc[0], 0.2224, eps=1e-4)
test_eq(_bound(5, 10).called.iloc[0], False)
# nothing is removed: a weak row stays, flagged, rather than disappearing
test_eq(len(_out), 1)
# an empty table must carry the SAME columns, so selecting called rows works on every strain
_empty = _annotate_significance(_res.iloc[:0], _fc, _L, _R, log2fc_thr=-1)
for _c in ("fraction_depleted_lower", "background", "p_value", "q_value", "called",
           "bimodality", "bimodal"):
    assert _c in _empty.columns
# annotating an annotated table again gives the same table
pd.testing.assert_frame_equal(_annotate_significance(_out, _fc, _L, _R, log2fc_thr=-1), _out)

In [ ]:
#| hide
# A library whose AT-rich inserts deplete for no site-related reason, and 60 inserts carrying a
# planted GGTCTC that always depletes. Against one rate for the whole sample the AT-only TAAAAA
# looks strongly depleted; against its carriers' GC-matched background it does not.
_at_rng = np.random.default_rng(0)
_at_seqs = []
for _i in range(2000):
    _p = _at_rng.uniform(0.2, 0.8)                                  # this insert's GC content
    _s = "".join(_at_rng.choice(list("ACGT"), p=[(1 - _p) / 2, _p / 2, _p / 2, (1 - _p) / 2], size=20))
    if _i < 60:
        _pos = _at_rng.integers(0, 14)
        _s = _s[:_pos] + "GGTCTC" + _s[_pos + 6:]
    _at_seqs.append(_s)
_at_seqs = list(dict.fromkeys(_at_seqs))
_at_gc = np.array([(s.count("G") + s.count("C")) / 20 for s in _at_seqs])
_at_site = np.array([("GGTCTC" in s) or ("GAGACC" in s) for s in _at_seqs])
_at_dep = _at_rng.random(len(_at_seqs)) < np.clip(1.2 - 2.4 * _at_gc, 0.03, 0.9)
_at_rich = pd.Series(np.where(_at_site, -3.0, np.where(_at_dep, -2.0, _at_rng.normal(0, 0.2, len(_at_seqs)))),
                     index=_at_seqs)
_at_rich = _at_rich - _at_rich.median()
_at_flat = _get_pattern_scores(encode_library(_at_seqs), _at_rich, (6, 0, 0), log2FC_thr=-0.5).set_index("motif")
_at_matched = _get_pattern_scores(encode_library(_at_seqs), _at_rich, (6, 0, 0), log2FC_thr=-0.5,
                                 background=plasmid_background(_at_seqs, _at_rich, -0.5)).set_index("motif")
assert _at_flat.loc["TAAAAA", "p_value"] < 1e-8 < 0.01 < _at_matched.loc["TAAAAA", "p_value"]
assert _at_matched.loc["GAGACC", "p_value"] < 1e-10                 # the real site stays significant

### A degenerate site is one motif

The scan reports motifs of A, C, G and T, so a site that accepts two bases at a position comes back
as two motifs. B156 in the example panel recognises `GACNNNNGTTY`; steps 2–4 call `GAACNNNNGTC`
and `AAACNNNNGTC` — the site read on the other strand, split at its first base — and keep both,
because each depletes plasmids the other does not carry. Rule 3's classification reads the
position:

In [ ]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_panel, right_panel = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_panel = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20)
b156 = log2fc_panel["B156_R1"]
enc_panel = encode_library(get_lib_seq_context(b156.index.tolist(), left_panel, right_panel))
fc_b156 = b156.to_numpy()
bg_b156 = plasmid_background(b156.index, fc_b156, -0.5)

_cls = _classify_positions("GAACNNNNGTC", [0], (4, 4, 3), enc_panel, fc_b156, bg_b156, -0.5)[0]
for m, n, s, b in _variant_profile([x + "AACNNNNGTC" for x in "ACGT"], (4, 4, 3), enc_panel,
                                  fc_b156, bg_b156, -0.5):
    print(f"  {m}  n={n:>4}  score={s:.3f}  background={b:.3f}  {_cls.get(m[0], ('(the call)',))[0]}")

  AAACNNNNGTC  n= 894  score=0.992  background=0.140  site
  CAACNNNNGTC  n= 386  score=0.140  background=0.139  non-site
  GAACNNNNGTC  n= 291  score=0.986  background=0.139  (the call)
  TAACNNNNGTC  n= 461  score=0.141  background=0.140  non-site

One other base is site-like and two are not, so the position is degenerate and becomes `R`.
`_generalise_motif` applies this to every defined position of a call, one position at a time — the
one whose site-like bases have the most carriers — and classifies the merged motif again on its own
carriers until nothing changes. A merged motif's carriers are the plasmids carrying any of its
instances, counted from the presence matrix, since one plasmid can carry two.

In [ ]:
#| export
def _union_profile(motifs, pattern, encoded, fc, background, log2fc_thr):
    """`_variant_profile` for motifs with IUPAC letters: each scored on the plasmids carrying any of
    its instances, which the scan's per-motif counts cannot give (a plasmid can carry two)."""
    has = _instance_presence(encoded, motifs, [pattern] * len(motifs))[0]
    n = has.sum(axis=0)
    depleted = (fc < log2fc_thr).astype(float) @ has
    bg_sum = background @ has
    return [(m, int(k), float(d / k) if k else float("nan"), float(b / k) if k else float("nan"))
            for m, k, d, b in zip(motifs, n, depleted, bg_sum)]


def _generalise_motif(motif, pattern, encoded_library, fc_values, background, log2fc_thr=-1,
                     min_support=5, totals=None):
    """`motif` with each degenerate position written as the IUPAC letter of its site-like bases.

    At every defined position the bases `motif` does not allow are classified
    (`_classify_positions`). Where some, but not all, are site-like, they join the bases allowed
    there. One position changes at a time -- the one whose site-like bases have the most carriers,
    the first on a tie -- and the merged motif is classified again, on its own carriers, until no
    position changes.

    Args:
        motif (str): a called motif.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library, fc_values, background, log2fc_thr, min_support, totals: as for
            `_is_mixture`.

    Returns:
        str: the merged motif, or `motif` itself when no position is degenerate.
    """
    defined = [i for i, c in enumerate(motif) if c != "N"]
    while True:
        best = None
        for i, classes in _classify_positions(motif, defined, pattern, encoded_library, fc_values,
                                             background, log2fc_thr, min_support, totals).items():
            site = [b for b, (c, _) in classes.items() if c == "site"]
            # Every other base site-like is an uninformative base (rule 3), not a degenerate one.
            if site and len(site) < len(classes):
                n = sum(classes[b][1] for b in site)
                if best is None or n > best[0]:
                    best = (n, i, site)
        if best is None:
            return motif
        _, i, site = best
        motif = motif[:i] + _IUPAC_COLLAPSE[_IUPAC_EXPAND[motif[i]] | frozenset(site)] + motif[i + 1:]

In [ ]:
show_doc(_generalise_motif)

def _generalise_motif(
    motif, pattern, encoded_library, fc_values, background, log2fc_thr:int=-1, min_support:int=5,
    totals:NoneType=None
):"""`motif` with each degenerate position written as the IUPAC letter of its site-like bases.

At every defined position the bases `motif` does not allow are classified
(`_classify_positions`). Where some, but not all, are site-like, they join the bases allowed
there. One position changes at a time -- the one whose site-like bases have the most carriers,
the first on a tie -- and the merged motif is classified again, on its own carriers, until no
position changes.

Args:
    motif (str): a called motif.
    pattern (tuple): its `(d1, spacer, d2)` shape.
    encoded_library, fc_values, background, log2fc_thr, min_support, totals: as for
        `_is_mixture`.

Returns:
    str: the merged motif, or `motif` itself when no position is degenerate."""

In [ ]:
# B156's two sites, each from one of its called variants.
for seed, pat in [("GAACNNNNGTC", (4, 4, 3)), ("ACANNNNNATGG", (3, 5, 4))]:
    merged = _generalise_motif(seed, pat, enc_panel, fc_b156, bg_b156, -0.5)
    print(f"  {seed} -> {merged} (reported as {canonical_motif(merged)})")

  GAACNNNNGTC -> RAACNNNNGTC (reported as GACNNNNGTTY)
  ACANNNNNATGG -> ACANNNNNRTGG (reported as CCAYNNNNNTGT)

In [ ]:
#| hide
def _planted(sites, planted, n=3000, seed=0):
    """Random 20 nt inserts, plus `planted[m]` inserts carrying each 8-mer `m`; carriers of any of
    `sites` (either strand) deplete, the rest sit around 0."""
    rng = np.random.default_rng(seed)
    rand = lambda: "".join(rng.choice(list("ACGT"), 20))
    seqs = [rand() for _ in range(n)]
    for m, k in planted.items():
        for _ in range(k):
            s, at = rand(), rng.integers(0, 13)
            seqs.append(s[:at] + m + s[at + 8:])
    seqs = list(dict.fromkeys(seqs))
    hit = np.array([any(m in s or revcomp(m) in s for m in sites) for s in seqs])
    return pd.Series(np.where(hit, -3.0, rng.normal(0, 0.2, len(seqs))), index=seqs)


def _generalise(series, motif):
    fc = series.to_numpy()
    return _generalise_motif(motif, (8, 0, 0), encode_library(series.index.tolist()), fc,
                            plasmid_background(series.index, fc, -0.5), -0.5)


# ACGTTGCA and GCGTTGCA are the site; CCGTTGCA is planted but not a site; TCGTTGCA is a site on
# only 4 plasmids, too few to classify.
degenerate = _planted(["ACGTTGCA", "GCGTTGCA", "TCGTTGCA"],
                      {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40, "TCGTTGCA": 2})
print("ACGTTGCA ->", _generalise(degenerate, "ACGTTGCA"))

ACGTTGCA -> RCGTTGCA

In [ ]:
#| hide
# The site-like G joins A; T, depleted but on too few plasmids to be classified, is never added.
test_eq(_get_filter_for_motif(degenerate, "TCGTTGCA", "", "").sum(), 4)
test_eq(_generalise(degenerate, "ACGTTGCA"), "RCGTTGCA")
test_eq(_generalise(degenerate, "GCGTTGCA"), "RCGTTGCA")      # the same site from either variant
# Negative: GCGTTGCA planted but at background, so ACGTTGCA's first base stays an A.
_single = _planted(["ACGTTGCA"], {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40})
test_eq(_generalise(_single, "ACGTTGCA"), "ACGTTGCA")
# Two degenerate positions, on a palindromic site (YGGCCR-like): the second merge is judged on the
# carriers of the first, through the instances of AYGGCCAT. AAGGCCAT and ACGGCCCT are planted
# at background so that each position has a non-site to set the site-like base against.
_sites = _motif_instances("AYGGCCRT", (8, 0, 0))
_two = _planted(_sites, dict.fromkeys(_sites + ["AAGGCCAT", "ACGGCCCT"], 40))
test_eq(_generalise(_two, "ACGGCCAT"), "AYGGCCRT")
# Every other base site-like is rule 3's case: no merge, whatever the seed.
_all = _planted(["ACGTTGCA", "CCGTTGCA", "GCGTTGCA", "TCGTTGCA"], dict.fromkeys(
    ["ACGTTGCA", "CCGTTGCA", "GCGTTGCA", "TCGTTGCA"], 40))
test_eq(_generalise(_all, "ACGTTGCA"), "ACGTTGCA")

`_merge_degenerate_calls` scores each merged motif on its own carriers, against the scan's
p-values; when it is called, it replaces the called rows that are its instances on either strand,
and `merged_from` names them. It runs on the calls alone, after step 4 has removed the shadows the
rule would otherwise fire on. B156's result, below, shows both its sites merged.

In [ ]:
#| export
def _is_instance(specific, general):
    """Does `general` allow every base of `specific`, on one strand or the other?"""
    allows = lambda s: len(s) == len(general) and all(
        _IUPAC_EXPAND[a] <= _IUPAC_EXPAND[b] for a, b in zip(s, general))
    return allows(specific) or allows(revcomp(specific))


def _motif_rows(motifs, patterns, log2fc_series, left_context, right_context, encoded, log2fc_thr):
    """Result-table rows -- support, fraction depleted, mean log2FC, pattern -- read off each
    motif's carriers."""
    has = _carriers(encoded, motifs, patterns, log2fc_series, left_context, right_context)
    fc = log2fc_series.to_numpy(dtype=float)
    n = has.sum(axis=0)
    return pd.DataFrame({"motif": motifs,
                         "fraction_depleted": (fc < log2fc_thr).astype(float) @ has / n,
                         "num_sequences": n, "avg_log2fc": fc @ has / n,
                         "pattern": [str(p) for p in patterns]})


def _merge_degenerate_calls(table, log2fc_series, left_context, right_context, encoded, background,
                           all_pvalues, log2fc_thr=-1, q_threshold=0.05, score_thr=0.5,
                           min_support=5, totals=None):
    """Report each degenerate site as one IUPAC motif, in place of its called variants.

    Every called row is generalised (`_generalise_motif`); each distinct merged motif that is not an
    instance of another is scored on its own carriers (`_annotate_significance`, against
    `all_pvalues`). A called merged motif replaces the called rows that are instances of it.

    Args:
        table (pd.DataFrame): the scored result table, from `_annotate_significance`.
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence, as scored.
        left_context (str), right_context (str): the vector flanks.
        encoded (tuple): the library from `encode_library`.
        background (np.ndarray): each plasmid's expected depletion rate.
        all_pvalues (np.ndarray): the p-values of every motif the scan tested.
        log2fc_thr, q_threshold, score_thr: as for `_annotate_significance`.
        min_support (int), totals (dict): as for `_classify_positions`.

    Returns:
        pd.DataFrame: `table` with a 'merged_from' column -- the replaced motifs joined by '+', empty
        for every other row -- and the merged rows in place of those they replaced, called rows
        first. A table with no merge comes back as it was, with the column added.
    """
    table = table.assign(merged_from="")
    called = table[table["called"]]
    fc = log2fc_series.to_numpy(dtype=float)
    totals = {} if totals is None else totals
    grown = {}                                       # canonical merged motif -> (spelling, pattern)
    for motif, pattern in zip(called["motif"], _patterns(called)):
        merged = _generalise_motif(motif, pattern, encoded, fc, background, log2fc_thr,
                                  min_support, totals)
        if merged != motif:
            grown.setdefault(canonical_motif(merged), (merged, pattern))
    keep = [m for m in grown if not any(o != m and _is_instance(m, o) for o in grown)]
    if not keep:
        return table
    rows = _motif_rows([grown[m][0] for m in keep], [grown[m][1] for m in keep], log2fc_series,
                       left_context, right_context, encoded, log2fc_thr)
    scored = _annotate_significance(_canonicalise_motifs(rows), log2fc_series, left_context,
                                   right_context, all_pvalues=all_pvalues, log2fc_thr=log2fc_thr,
                                   q_threshold=q_threshold, encoded=encoded,
                                   background=background, score_thr=score_thr)
    scored = scored[scored["called"]]
    if scored.empty:
        return table
    absorbed = [[m for m in called["motif"] if _is_instance(m, g)] for g in scored["motif"]]
    scored = scored.assign(merged_from=["+".join(a) for a in absorbed])
    dropped = table["called"] & table["motif"].isin([m for a in absorbed for m in a])
    out = pd.concat([table[~dropped], scored[table.columns]], ignore_index=True)
    return out.sort_values(["called", "q_value"], ascending=[False, True], kind="stable")

In [ ]:
#| hide
# The synthetic site above, as the pipeline reports it: its two called variants and an unrelated
# site, GGTCTCAA, then the merge.
def _report(series, motifs, pattern=(8, 0, 0)):
    """The scored table `find_restricted_motifs` would hand to the merge, for these motifs."""
    enc_s, fc = encode_library(series.index.tolist()), series.to_numpy()
    bg_s = plasmid_background(series.index, fc, -0.5)
    pv = _get_pattern_scores(enc_s, fc, pattern, -0.5, bg_s).query("num_sequences >= 5").p_value
    rows = _motif_rows(motifs, [pattern] * len(motifs), series, "", "", enc_s, -0.5)
    table = _annotate_significance(rows, series, "", "", all_pvalues=pv, log2fc_thr=-0.5,
                                  encoded=enc_s, background=bg_s)
    return table, (series, "", "", enc_s, bg_s, pv)


_lib = _planted(["ACGTTGCA", "GCGTTGCA", "GGTCTCAA"],
                {"ACGTTGCA": 40, "GCGTTGCA": 40, "CCGTTGCA": 40, "GGTCTCAA": 40})
before, _args = _report(_lib, ["ACGTTGCA", "GCGTTGCA", "GGTCTCAA"])
merged = _merge_degenerate_calls(before, *_args, log2fc_thr=-0.5)
merged[["motif", "num_sequences", "fraction_depleted", "q_value", "called", "merged_from"]]

      motif  num_sequences  ...  called        merged_from
1  RCGTTGCA             84  ...    True  ACGTTGCA+GCGTTGCA
0  GGTCTCAA             41  ...    True

[2 rows x 6 columns]

In [ ]:
#| hide
# One row for the degenerate site, carried by every plasmid that carries either variant -- the
# regex count of the IUPAC motif -- and called; the unrelated site's row is untouched, to the bit.
test_eq(sorted(merged.motif), ["GGTCTCAA", "RCGTTGCA"])
_row = merged.set_index("motif").loc["RCGTTGCA"]
test_eq(_row.merged_from, "ACGTTGCA+GCGTTGCA")
test_eq(_row.num_sequences, _get_filter_for_motif(_lib, "RCGTTGCA", "", "").sum())
assert _row.called
pd.testing.assert_frame_equal(merged.set_index("motif").loc[["GGTCTCAA"]].drop(columns="merged_from"),
                              before.set_index("motif").loc[["GGTCTCAA"]])
# The palindromic two-position site: its three distinct variants (the fourth is the first read on
# the other strand) become one row.
_t, _a = _report(_two, ["ACGGCCAT", "ATGGCCAT", "ACGGCCGT"])
_m = _merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5)
test_eq(_m.motif.tolist(), ["AYGGCCRT"])
test_eq(sorted(_m.merged_from.iloc[0].split("+")), ["ACGGCCAT", "ACGGCCGT", "ATGGCCAT"])
test_eq(_m.num_sequences.iloc[0], _get_filter_for_motif(_two, "AYGGCCRT", "", "").sum())
# A site with one variant: nothing merges and the table comes back as it was, plus the column.
_t, _a = _report(_single, ["ACGTTGCA"])
pd.testing.assert_frame_equal(_merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5),
                              _t.assign(merged_from=""))
# No call, or no row at all: unchanged, and the column is there.
_t, _a = _report(_lib, ["ACGTTGCA", "GCGTTGCA"])
_t = _t.assign(called=False)
pd.testing.assert_frame_equal(_merge_degenerate_calls(_t, *_a, log2fc_thr=-0.5), _t.assign(merged_from=""))
assert "merged_from" in _merge_degenerate_calls(_t.iloc[:0], *_a, log2fc_thr=-0.5).columns
# Instances on either strand, IUPAC letters included.
assert _is_instance("CACNNNNGTAC", "RTACNNNNGTG") and _is_instance("GTACNNNNGTG", "RTACNNNNGTG")
assert not _is_instance("CACNNNNGTAA", "RTACNNNNGTG")

A palindromic site has a limit of its own. In `CCTNAGG` (381A) the central N pairs C with G and A
with T, so `CCTHAGG` (not G, hence not C on the other strand) is carried by exactly the plasmids
carrying `CCTNAGG`: the data can only set C/G against A/T. In both 381A replicates A/T is
site-like beside C/G, so `CCTNAGG` is what the data support.

In [ ]:
_cct = _carriers(enc_panel, ["CCTNAGG", "CCTHAGG", "CCTSAGG", "CCTWAGG"],
                 [(3, 1, 3), (7, 0, 0), (7, 0, 0), (7, 0, 0)], b156, left_panel, right_panel)
print("carriers of CCTNAGG, CCTHAGG, CCTSAGG, CCTWAGG:", _cct.sum(axis=0))

carriers of CCTNAGG, CCTHAGG, CCTSAGG, CCTWAGG: [595 595 240 355]

In [ ]:
#| hide
test_eq(_cct[:, 0], _cct[:, 1])      # without G is without C: the same plasmids
# In both 381A replicates the A/T reading of the central base is site-like beside C/G.
for _s in ("381A_R1", "381A_R2"):
    _x = log2fc_panel[_s]
    _f = _x.to_numpy()
    _cls = _classify_positions("CCTSAGG", [3], (7, 0, 0), enc_panel, _f,
                              plasmid_background(_x.index, _f, -0.5), -0.5)[3]
    test_eq({b: c for b, (c, _) in _cls.items()}, {"A": "site", "T": "site"})

### Reading the result table

`find_restricted_motifs` returns the called motifs in five columns: `motif`, `num_sequences`,
`fraction_depleted`, `avg_log2fc` and `q_value`. With `all_motifs=True` it returns every motif
that reached scoring, called or not, with all the columns below.

- **How strong is the effect?** `fraction_depleted` is the share of carriers depleted, and
  `avg_log2fc` says how far they fall. Compare `fraction_depleted` with `background`, the rate at
  which plasmids like the carriers deplete anyway (`plasmid_background`): 0.55 against 0.21
  (`GGCGNNNNNNNCGCC` in *The example panel at a glance*, below) is a small effect.
- **How sure are we?** `p_value` is the binomial probability of at least this many depleted
  carriers at their `background` rate, and `q_value` adjusts it over every motif the scan tested
  in the sample (`01_utils`, *Is a motif's depletion more than the sample's own noise?*). A call
  needs q < `q_threshold`.
- **Are most carriers depleted?** `fraction_depleted_lower` is a 95% lower bound on the depleted
  fraction, and a call needs it at `score_thr` too. On the 20 nt JJ1886 library `GTCGNNNNNNNCGGA`
  has 7 of 12 carriers depleted (q = 10⁻³) but bounds the fraction only at 0.32; `GGTCTC`, 9 of 9,
  bounds it at 0.72.
- **Is it one population?** `bimodal` marks carriers that mix destroyed and untouched plasmids;
  `bimodality` is the raw coefficient.
- **Is it a degenerate site?** `merged_from` lists the called variants an IUPAC motif replaced,
  and is empty for every other row.
- **Why called or not?** `called` is the verdict, and `reason` (`call_reason`) says it in words:
  `called`, or each test that failed with its numbers. A called row whose carriers are bimodal
  says so, since that is worth a look before trusting the call.

In [ ]:
#| export
def call_reason(row, q_threshold=0.05, score_thr=0.5):
    """Why a row of the result table is called or not, in a few words.

    A call needs q below `q_threshold` and the lower bound on the depleted fraction at `score_thr`
    or above. The reason names each test the row fails, with its numbers, or says "called"; a called row with bimodal carriers adds a note, since bimodality does not
    block a call.
    """
    n = int(row["num_sequences"])
    failed = []
    if not row["q_value"] < q_threshold:
        failed.append(f"not significant (q = {row['q_value']:.2g})")
    if not row["fraction_depleted_lower"] >= score_thr:
        failed.append(f"most carriers not shown depleted ({round(row['fraction_depleted'] * n)}/{n}; "
                      f"lower bound {row['fraction_depleted_lower']:.2f} < {score_thr:g})")
    if failed:
        return "; ".join(failed)
    return "called; carriers split between depleted and untouched" if row["bimodal"] else "called"


_COMPACT_COLUMNS = ["motif", "num_sequences", "fraction_depleted", "avg_log2fc", "q_value"]
_FULL_COLUMNS = _COMPACT_COLUMNS + ["pattern", "fraction_depleted_lower", "background", "p_value",
                                    "called", "bimodality", "bimodal", "merged_from"]


def _result_view(table, all_motifs, q_threshold, score_thr):
    """What `find_restricted_motifs` returns: the called rows in five columns, or every row with
    its `reason`, called first."""
    if not all_motifs:
        return (table.loc[table["called"], _COMPACT_COLUMNS]
                .sort_values(["q_value", "motif"]).reset_index(drop=True))
    reason = [call_reason(r, q_threshold, score_thr) for _, r in table.iterrows()]
    return (table[_FULL_COLUMNS].assign(reason=pd.Series(reason, index=table.index, dtype=object))
            .sort_values(["called", "q_value", "motif"], ascending=[False, True, True])
            .reset_index(drop=True))

In [ ]:
# GTCGNNNNNNNCGGA on the 20 nt JJ1886 run: significant, but 7 of 12 carriers depleted bounds the
# depleted fraction at 0.32, so most carriers are not shown depleted.
_row = lambda **kw: pd.Series({"num_sequences": 12, "fraction_depleted": 7 / 12, "q_value": 1e-3,
                               "fraction_depleted_lower": 0.32, "bimodal": True, **kw})
call_reason(_row())

'most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)'

In [ ]:
#| hide
test_eq(call_reason(_row()), "most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)")
# A row that misses only q, and one that misses both, says which.
test_eq(call_reason(_row(q_value=0.21, fraction_depleted_lower=0.6)), "not significant (q = 0.21)")
test_eq(call_reason(_row(q_value=0.21)), "not significant (q = 0.21); "
        "most carriers not shown depleted (7/12; lower bound 0.32 < 0.5)")
# A call says "called"; with bimodal carriers it adds a note but stays a call.
test_eq(call_reason(_row(fraction_depleted_lower=0.6, bimodal=False)), "called")
test_eq(call_reason(_row(fraction_depleted_lower=0.6)),
        "called; carriers split between depleted and untouched")
# The thresholds are the caller's: q exactly at the threshold is not significant.
test_eq(call_reason(_row(q_value=0.05, fraction_depleted_lower=0.6)), "not significant (q = 0.05)")
test_eq(call_reason(_row(fraction_depleted_lower=0.6), score_thr=0.7)[:32], "most carriers not shown depleted")

In [ ]:
#| hide
# The reason agrees with `called` on every row _annotate_significance scores.
_v = _result_view(pd.concat([_bound(9, 9), _bound(5, 10)]).assign(merged_from=""), True, 0.05, 0.5)
test_eq(list(_v.called), [True, False])                 # called rows first
test_eq([r.startswith("called") for r in _v.reason], list(_v.called))
# The default view keeps the called rows, in five columns; an empty table keeps the columns.
test_eq(list(_result_view(_v, False, 0.05, 0.5).columns), _COMPACT_COLUMNS)
test_eq(len(_result_view(_v, False, 0.05, 0.5)), 1)
_e = _result_view(_v.iloc[:0], True, 0.05, 0.5)
test_eq(len(_e), 0); assert "reason" in _e.columns

## Running the pipeline

Steps 2 to 4 and reporting, on one sample. Thresholds too loose for a sample can leave step 3 with
tens of thousands of candidates, which step 4 would compare for minutes; past `max_candidates` the
pipeline raises `TooManyCandidatesError` instead of returning a table.

In [ ]:
#| export
class TooManyCandidatesError(RuntimeError):
    """Raised when step 3 leaves more candidates than step 4 will compare.

    The candidate table is available as `.candidates` for inspection. A count this large
    usually means the thresholds are too loose for the sample, not that the strain has
    thousands of sites.
    """

    def __init__(self, n_candidates, max_candidates, log2fc_thr, score_thr, min_support, candidates):
        self.n_candidates = n_candidates
        self.max_candidates = max_candidates
        self.candidates = candidates
        super().__init__(
            f"Too many candidate motifs: {n_candidates} > max_candidates={max_candidates}. "
            f"Step 4 compares candidates with each other and would not finish. This usually "
            f"means the thresholds are too permissive for this sample: check that the log2FC are "
            f"median-normalised, as calculate_log2fc returns them, "
            f"or try a stricter log2fc_thr (currently {log2fc_thr}, e.g. -1.0), "
            f"score_thr (currently {score_thr}, e.g. 0.7), or "
            f"min_support (currently {min_support}, e.g. 10). "
            f"Raise max_candidates only if you know why this strain has so many candidates. "
            f"Step 3's candidates are on this exception as `.candidates`."
        )

In [ ]:
#| hide
_e = TooManyCandidatesError(200, 150, -1, 0.5, 3, pd.DataFrame({"motif": ["GGTCTC"]}))
test_eq(_e.n_candidates, 200)
test_eq(len(_e.candidates), 1)            # the candidates ride on the exception for inspection
assert "max_candidates=150" in str(_e)
assert "score_thr (currently 0.5" in str(_e)
assert "median-normalised" in str(_e)

In [ ]:
#| export
def find_restricted_motifs(log2fc_series,
                           left_context_str,
                           right_context_str,
                           n_jobs=1,
                           patterns=None,
                           log2fc_thr=-0.5,
                           min_support=5,
                           score_thr=0.5,
                           max_candidates=5000,
                           q_threshold=0.05,
                           encoded_library=None,
                           all_motifs=False
                           ):
    """The motifs one sample restricts: steps 2 to 4 and reporting on a log2FC series.

    It expects log2FC as `calculate_log2fc` returns them (median-normalised); normalise your own
    values the same way if you compute them elsewhere. Every pattern is scanned over the inserts
    with their flanks (step 2); the candidates are reduced to one description per site (step 3)
    and cleared of those whose depletion a stronger candidate accounts for (step 4); the
    survivors are put on their canonical strand and scored, and the called variants of a
    degenerate site are reported as one IUPAC motif. Every test is against a GC-matched
    background: each plasmid's is the depletion rate of the plasmids in its insert-GC
    decile (`plasmid_background`), and a set of plasmids is tested against their mean.

    Args:
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence, median-normalised
            as `calculate_log2fc` returns it. It is used as given.
        left_context_str, right_context_str (str): the vector flanks of the insert.
        n_jobs (int): processes used to scan the patterns. 1 (default) runs in this process.
            A pattern takes about a second on a 30k-sequence library, so more is rarely worth
            the startup cost.
        patterns (list): the shapes to search, as `(d1, spacer, d2)`. Defaults to
            `get_patterns()`. A pattern and its mirror find the same sites, so each is searched
            once, in one form: `(4, 4, 3)` is searched as `(3, 4, 4)`.
        log2fc_thr (float): a plasmid counts as depleted below this, relative to the sample's
            median plasmid. Default -0.5: low enough to see weakly restricting systems such as BREX,
            which a -1 threshold misses.
        min_support (int): minimum plasmids for a motif to be considered. With
            every carrier depleted, the lower bound on the depleted fraction is 0.22, 0.37, 0.47
            and 0.55 for 2 to 5 carriers, so 5 is the smallest support that can be called at the
            default score threshold of 0.5 (4 at 0.45, 7 at 0.65). Lower only adds candidates and
            runtime: E1114 on the 20 nt library exceeds `max_candidates` at 2 to 4.
        score_thr (float): at least this fraction of the plasmids carrying a
            candidate must be depleted, and a call must show it with confidence (the lower bound
            `fraction_depleted_lower` reaches it). Default 0.5.
        max_candidates (int): the most candidates step 3 may hand to step 4, whose cost grows
            faster than their number. Past it the pipeline raises `TooManyCandidatesError` rather
            than return the candidates as a table that would look like a result; they ride on the
            exception as `.candidates`. A caller screening many strains should catch it and record
            that strain as "no confident call". The default, 5000, is above the 3,258 candidates
            that the busiest strain of the example data (E1114, 20 nt library) brings at the
            default thresholds.
        q_threshold (float): a motif is marked `called` when its Benjamini-Hochberg q-value,
            computed against its carriers' GC-matched background and over every motif the scan
            tested, falls below this.
        encoded_library (tuple): `encode_library(get_lib_seq_context(log2fc_series.index,
            left_context_str, right_context_str))`, if the caller already has it. Strains
            screened with the same library and flanks share it, so a panel of strains encodes it once.
            It must describe exactly `log2fc_series.index`, in order.
        all_motifs (bool): return every scored motif, called or not, with every column.

    Returns:
        pd.DataFrame: by default the called motifs, one row each, sorted by q then motif: 'motif',
        'num_sequences', 'fraction_depleted', 'avg_log2fc', 'q_value'. With `all_motifs=True`, every scored motif, called rows first: those columns, 'pattern', the
        others `_annotate_significance` adds, 'merged_from', and 'reason' (`call_reason`).
    """
    candidates = pd.DataFrame(columns=['motif', 'fraction_depleted', 'num_sequences',
                                       'avg_log2fc', 'pattern'])
    report = functools.partial(_annotate_significance, log2fc_thr=log2fc_thr,
                               q_threshold=q_threshold, score_thr=score_thr)
    view = functools.partial(_result_view, all_motifs=all_motifs, q_threshold=q_threshold,
                             score_thr=score_thr)
    if log2fc_series.empty:
        print("The input series is empty; there is nothing to scan.")
        return view(report(candidates, log2fc_series, left_context_str, right_context_str,
                           all_pvalues=np.array([])).assign(merged_from=""))

    # The library is encoded once and every step below reads it.
    if encoded_library is None:
        encoded_library = encode_library(get_lib_seq_context(
            log2fc_series.index.tolist(), left_context_str, right_context_str))
    elif encoded_library[0].shape[0] != len(log2fc_series):
        raise ValueError(
            f"encoded_library holds {encoded_library[0].shape[0]} sequences but log2fc_series "
            f"has {len(log2fc_series)}; it must encode exactly this series' index, in order, "
            f"with these flanks.")
    fc = log2fc_series.to_numpy(dtype=float)
    background = plasmid_background(log2fc_series.index, fc, log2fc_thr)

    if patterns is None:
        patterns = get_patterns()
    elif np.ndim(patterns) == 1:          # one pattern rather than a list
        patterns = [patterns]
    # A pattern and its mirror find the same sites (the scan reads both strands), and a gapless
    # pattern is one run however it is split, so each is searched once, in canonical form.
    for p, c in sorted({(tuple(p), _canonical_pattern(p)) for p in patterns
                        if tuple(p) != _canonical_pattern(p)}):
        print(f"Pattern {p} is searched as {c}: the same sites, read on the other strand.")
    patterns = sorted({_canonical_pattern(p) for p in patterns},
                                     key=lambda x: (x[0] + x[2], x[1], x))

    # Step 2.
    worker = functools.partial(
        _scan_candidates, encoded_library=encoded_library,
        fc_values=fc, background=background, log2fc_thr=log2fc_thr,
        score_thr=score_thr, min_support=min_support)
    if n_jobs == 1:
        per_pattern = [worker(p) for p in tqdm(patterns, desc="Scanning patterns")]
    else:
        # Each worker scans single-threaded: n_jobs processes each starting numba's thread pool
        # would ask for n_jobs x cores at once. imap keeps pattern order, so the result does not
        # depend on which worker finishes first.
        with Pool(processes=n_jobs) as pool:
            per_pattern = list(tqdm(pool.imap(functools.partial(worker, parallel=False),
                                              patterns),
                                    total=len(patterns), desc="Scanning patterns"))

    tested_pvalues = (np.concatenate([pv for _, pv, _ in per_pattern]) if per_pattern
                      else np.array([]))
    # The p-value a motif needs to be called: the largest that clears q_threshold over every
    # motif tested. Step 4 holds the candidates' leftovers to it, since they were selected
    # from that same pool.
    _q = _benjamini_hochberg(tested_pvalues)
    scan_cutoff = tested_pvalues[_q < q_threshold].max() if (_q < q_threshold).any() else 0.0
    hits = [df for df, _, _ in per_pattern if not df.empty]
    totals = {p: t for p, (_, _, t) in zip(patterns, per_pattern)}

    # Step 3, once over every pattern's candidates. It scores variants from the scan's counts,
    # so a pattern step 2 scanned is never rescanned.
    if hits:
        candidates = _filter_redundant_patterns(
            pd.concat(hits, ignore_index=True), log2fc_series,
            left_context_str, right_context_str,
            log2fc_thr=log2fc_thr, score_thr=score_thr,
            min_support=min_support, encoded=encoded_library, totals=totals,
            background=background)
        print(f"{sum(len(h) for h in hits)} candidate(s) across all patterns; "
              f"{len(candidates)} remain after step 3.")
    if len(candidates) > max_candidates:
        raise TooManyCandidatesError(len(candidates), max_candidates, log2fc_thr,
                                     score_thr, min_support,
                                     candidates)

    # Step 4.
    candidates, explained = _filter_explained_candidates(
        candidates, log2fc_series, left_context_str, right_context_str,
        log2fc_thr=log2fc_thr, score_thr=score_thr,
        min_support=min_support, encoded=encoded_library,
        p_threshold=scan_cutoff, background=background)
    if explained:
        print(f"{len(explained)} candidate(s) whose score was borrowed:")
        for m, (by, n, s) in sorted(explained.items()):
            print(f"    {m} <- {by} (without them: n={n}, score={s:.2f})")

    # Canonicalise before printing, so the names in the log are the names in the table.
    candidates = _canonicalise_motifs(candidates)
    print(f"{len(candidates)} motif(s) scored:")
    for _, row in candidates.iterrows():
        print(f"  {row['motif']} (pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, "
              f"AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")
    table = report(candidates, log2fc_series, left_context_str, right_context_str,
                   all_pvalues=tested_pvalues, encoded=encoded_library, background=background)

    # A degenerate site's called variants, reported as one IUPAC motif.
    table = _merge_degenerate_calls(
        table, log2fc_series, left_context_str, right_context_str, encoded_library, background,
        tested_pvalues, log2fc_thr=log2fc_thr, q_threshold=q_threshold,
        score_thr=score_thr, min_support=min_support, totals=totals)
    merged = table[table["merged_from"] != ""]
    if len(merged):
        print(f"{len(merged)} degenerate site(s) reported as one motif:")
        for m, parts in zip(merged["motif"], merged["merged_from"]):
            print(f"  {m} <- {parts.replace('+', ' + ')}")
    print(f"{int(table['called'].sum())} motif(s) called.")
    return view(table)

## Putting it to work

JJ1886 in the panel, at the defaults — every pattern of `get_patterns()`, a plasmid depleted below
−0.5, score 0.5:

In [ ]:
motifs_jj1886 = find_restricted_motifs(log2fc_panel["JJ1886_R1"], left_panel, right_panel)
motifs_jj1886

85 candidate(s) across all patterns; 4 remain after step 3.
4 motif(s) scored:
  GGTCTC (pattern (6, 0, 0)), FracDep: 0.98, AvgFC: -2.85, N: 55
  ATACNNNNGTG (pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -3.27, N: 504
  CACNNNNGTAC (pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -3.31, N: 468
  AAAGNNNNGTT (pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -3.43, N: 913
1 degenerate site(s) reported as one motif:
  RTACNNNNGTG <- ATACNNNNGTG + CACNNNNGTAC
3 motif(s) called.

Scanning patterns: 100%|##########| 43/43 [00:01<00:00, 41.98it/s]

         motif  num_sequences  fraction_depleted  avg_log2fc       q_value
0  AAAGNNNNGTT            913           0.997809   -3.425663  0.000000e+00
1  RTACNNNNGTG            963           1.000000   -3.285517  0.000000e+00
2       GGTCTC             55           0.981818   -2.851532  2.999895e-43

In [ ]:
import io, contextlib

In [ ]:
#| hide
# The strain's three sites, named on their canonical strand; the Type I site is one row, merged
# from the two variants step 4 kept.
test_eq(sorted(motifs_jj1886.motif), ["AAAGNNNNGTT", "GGTCTC", "RTACNNNNGTG"])
test_eq(list(motifs_jj1886.columns), ["motif", "num_sequences", "fraction_depleted", "avg_log2fc",
                                      "q_value"])
# all_motifs=True returns the same calls first, with every column and a reason for each row.
with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
    _all = find_restricted_motifs(log2fc_panel["JJ1886_R1"], left_panel, right_panel, all_motifs=True)
_called = _all[_all.called]
test_eq(set(_called.motif), set(motifs_jj1886.motif))
test_eq(set(_called.reason), {"called"})
test_eq(_called.set_index("motif").merged_from["RTACNNNNGTG"], "ATACNNNNGTG+CACNNNNGTAC")
# The same sites step 4 kept on the 20 nt library: two runs of one strain, one answer.
_parts = {p for m, f in zip(_called.motif, _called.merged_from) for p in (f.split("+") if f else [m])}
assert _parts <= set(_canonicalise_motifs(after4).motif)

B156's two degenerate sites, each reported as one motif; `all_motifs=True` shows the variants each
replaced:

In [ ]:
motifs_b156 = find_restricted_motifs(log2fc_panel["B156_R1"], left_panel, right_panel,
                                     all_motifs=True)
motifs_b156[["motif", "num_sequences", "q_value", "merged_from", "reason"]]

160 candidate(s) across all patterns; 4 remain after step 3.
4 motif(s) scored:
  AAACNNNNGTC (pattern (4, 4, 3)), FracDep: 0.99, AvgFC: -2.55, N: 894
  GAACNNNNGTC (pattern (4, 4, 3)), FracDep: 0.99, AvgFC: -2.48, N: 291
  ACANNNNNATGG (pattern (3, 5, 4)), FracDep: 0.99, AvgFC: -2.63, N: 536
  ACANNNNNGTGG (pattern (3, 5, 4)), FracDep: 0.99, AvgFC: -2.59, N: 399
2 degenerate site(s) reported as one motif:
  GACNNNNGTTY <- AAACNNNNGTC + GAACNNNNGTC
  CCAYNNNNNTGT <- ACANNNNNATGG + ACANNNNNGTGG
2 motif(s) called.

Scanning patterns: 100%|##########| 43/43 [00:00<00:00, 58.92it/s]

          motif  num_sequences  q_value                merged_from  reason
0  CCAYNNNNNTGT            926      0.0  ACANNNNNATGG+ACANNNNNGTGG  called
1   GACNNNNGTTY           1174      0.0    AAACNNNNGTC+GAACNNNNGTC  called

In [ ]:
#| hide
# Four called variants on B156, two sites.
test_eq(motifs_b156[motifs_b156.called].set_index("motif").merged_from.to_dict(),
        {"GACNNNNGTTY": "AAACNNNNGTC+GAACNNNNGTC", "CCAYNNNNNTGT": "ACANNNNNATGG+ACANNNNNGTGG"})

In [ ]:
#| hide
_quiet = lambda: contextlib.redirect_stderr(io.StringIO())
with contextlib.redirect_stdout(io.StringIO()), _quiet():
    # The guard runs before step 4, and the candidates it carries are step 3's.
    try:
        find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right, patterns=pats,
                               max_candidates=1)
        raise AssertionError("TooManyCandidatesError not raised")
    except TooManyCandidatesError as e:
        assert e.n_candidates > 1 and len(e.candidates) == e.n_candidates
    # The busiest strain of the example data at the defaults: E1114, 3,258 candidates after step 3.
    try:
        find_restricted_motifs(log2fc_df["E1114_T0"], left, right, max_candidates=3000)
        raise AssertionError("TooManyCandidatesError not raised")
    except TooManyCandidatesError as e:
        test_eq(e.n_candidates, 3258)
    # One pattern on its own is accepted, not only a list of them.
    _one = find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right,
                                  patterns=(6, 0, 0), all_motifs=True)
    # An empty series is an empty table with the same columns as a full one, in either view.
    _none = find_restricted_motifs(log2fc_df["JJ1886_T0"].iloc[:0], left, right)
    _none_all = find_restricted_motifs(log2fc_df["JJ1886_T0"].iloc[:0], left, right, all_motifs=True)
    # On the AT-rich library above, only the planted site is called.
    _at_calls = find_restricted_motifs(_at_rich, "", "", patterns=(6, 0, 0))
test_eq(list(_at_calls.motif), ["GGTCTC"])
test_eq(set(_one.pattern), {"(6, 0, 0)"})
test_eq((len(_none), len(_none_all)), (0, 0))
test_eq(list(_none.columns), _COMPACT_COLUMNS)
test_eq(list(_none_all.columns), list(_one.columns))
# A pre-encoded library must match the series it is passed with.
test_fail(lambda: find_restricted_motifs(log2fc_df["JJ1886_T0"], left, right,
                                         encoded_library=encode_library(["ACGT"])),
          contains="encoded_library holds 1 sequences")

### The example panel at a glance

Every strain of the example panel at the defaults: replicate R1, plus EDL933_dRM_R2, the one
library with a scored row that is not called. `sample_rate` is the share of all the sample's
plasmids depleted, the rate a motif would be tested against without a GC-matched background.

In [ ]:
panel_calls = []
for s in [c for c in log2fc_panel.columns if c.endswith("_R1")] + ["EDL933_dRM_R2"]:
    x = log2fc_panel[s]
    with contextlib.redirect_stdout(io.StringIO()), _quiet():
        t = find_restricted_motifs(x, left_panel, right_panel, encoded_library=enc_panel, all_motifs=True)
    panel_calls.append(t.assign(sample=s, sample_rate=(x < -0.5).mean()))
panel_calls = pd.concat(panel_calls, ignore_index=True)
panel_calls[["sample", "motif", "num_sequences", "sample_rate", "background", "fraction_depleted",
             "fraction_depleted_lower", "avg_log2fc", "q_value", "called"]].round(
    {"sample_rate": 3, "background": 3, "fraction_depleted": 3, "fraction_depleted_lower": 3, "avg_log2fc": 2})

           sample            motif  ...        q_value  called
0       JJ1886_R1      AAAGNNNNGTT  ...   0.000000e+00    True
1       JJ1886_R1      RTACNNNNGTG  ...   0.000000e+00    True
2       JJ1886_R1           GGTCTC  ...   2.999895e-43    True
3       CFT073_R1   GAGNNNNNNNGTCA  ...  3.873944e-156    True
4           HS_R1           GGTAAG  ...   0.000000e+00    True
5      LMR_503_R1      AAAGNNNNGTT  ...   0.000000e+00    True
6      LMR_503_R1      RTACNNNNGTG  ...   0.000000e+00    True
7      LMR_503_R1     ACGNNNNNGTTG  ...  7.910596e-224    True
8      LMR_503_R1           GGTCTC  ...   1.262662e-32    True
9         B156_R1     CCAYNNNNNTGT  ...   0.000000e+00    True
10        B156_R1      GACNNNNGTTY  ...   0.000000e+00    True
11        381A_R1          CCTNAGG  ...  4.131717e-103    True
12      EDL933_R1   CACNNNNNNNCTGG  ...  7.219223e-223    True
13  EDL933_dRM_R2  GGCGNNNNNNNCGCC  ...   4.240548e-02   False

[14 rows x 10 columns]

The RM sites of JJ1886, LMR_503, B156, CFT073 and EDL933 deplete 84% to 100% of their carriers,
against backgrounds of 0.09 to 0.19. HS's BREX site `GGTAAG` is a weaker system: 64% of its
carriers depleted, by 0.65 log2 on average, yet on 1,879 carriers it is as significant as the
strongest RM site. 381A is a noisy sample, with 30% of all its plasmids depleted; `CCTNAGG` is
called at 74% against that. EDL933_dRM_R1 calls nothing.

The last row is a weak, partial effect: 23 of `GGCGNNNNNNNCGCC`'s 42 carriers are depleted in
EDL933_dRM_R2 (q = 0.04), but the bound on that fraction is 0.41, so it is not called.
`all_motifs=True` keeps such rows: an effect that is not restriction — on fitness, say — is a
finding too. On these calls the GC-matched background stays within 0.02 of the sample's rate,
except for CFT073's `GAGNNNNNNNGTCA` (0.14 against 0.17).

In [ ]:
#| hide
_pc = panel_calls.set_index(["sample", "motif"])
_c = panel_calls[panel_calls.called]
# One scored row is not called: the weak partial effect, 23 of 42 carriers, bound 0.41.
test_eq(list(panel_calls[~panel_calls.called].motif), ["GGCGNNNNNNNCGCC"])
_w = _pc.loc[("EDL933_dRM_R2", "GGCGNNNNNNNCGCC")]
test_eq((round(_w.fraction_depleted * _w.num_sequences), _w.num_sequences), (23, 42))
test_close(_w.fraction_depleted_lower, 0.41, eps=0.005)
test_close(_w.background, 0.21, eps=0.005)
test_close(_w.q_value, 0.04, eps=0.005)
# The RM sites: 84% to 100% of carriers depleted, backgrounds 0.09 to 0.19.
_rm = _c[~_c.motif.isin(["GGTAAG", "CCTNAGG"])]
assert 0.835 <= _rm.fraction_depleted.min() < 0.845 and _rm.fraction_depleted.max() == 1.0
assert 0.085 <= _rm.background.min() and _rm.background.max() < 0.195
# BREX in HS: 64% depleted, by 0.65 log2, on 1,879 carriers, with q as small as any RM site's.
_hs = _pc.loc[("HS_R1", "GGTAAG")]
test_close(_hs.fraction_depleted, 0.64, eps=0.005); test_close(_hs.avg_log2fc, -0.65, eps=0.01)
test_eq(_hs.num_sequences, 1879); test_eq(_hs.q_value, _c.q_value.min())
# 381A: 30% of all plasmids depleted, CCTNAGG at 74%; the RM knockout calls nothing.
_a = _pc.loc[("381A_R1", "CCTNAGG")]
test_close(_a.sample_rate, 0.30, eps=0.005); test_close(_a.fraction_depleted, 0.74, eps=0.005)
test_eq((panel_calls["sample"] == "EDL933_dRM_R1").sum(), 0)
# GC-matched background within 0.02 of the sample rate on every call but CFT073's.
test_eq(set(_c[(_c.background - _c.sample_rate).abs() >= 0.02].motif), {"GAGNNNNNNNGTCA"})

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()

In [ ]:
#| hide