In [1]:
%load_ext autoreload
%autoreload 2

# core

> Finding the DNA motifs a strain restricts, from a table of plasmid counts before and after delivery.

In [2]:
#| default_exp core

In [3]:
#| hide
from nbdev.showdoc import *
from fastcore.test import test_eq, test_fail

In [4]:
#| export
import ast
import pandas as pd
from tqdm import tqdm
import numpy as np
from scipy.stats import kurtosis, skew
import os
import warnings
import functools
from multiprocessing import Pool, cpu_count
from collections import  defaultdict
import re
from randseq.coding import (encode_library, _pattern_window_codes, decode_motif_codes,
                            encode_motif, motif_presence_matrix,
                            pattern_is_self_rc, rc_code_table)
from randseq import fast as _fast
from randseq.utils import (score, revcomp, calculate_log2fc, get_lib_seq_context, get_patterns,
                           canonical_pattern,
                           find_broad_in_specific, _get_filter_for_motif, canonical_motif,
                           background_depletion_rate, motif_pvalues, benjamini_hochberg)

In [5]:
#| hide
from randseq.example_data import get_example_data_dir

In [6]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['__init__.py',
 '__pycache__',
 'countsTable.csv.gz',
 'counts_panel.csv.gz',
 'counts_panel_key.csv',
 'pMin_backbone.fasta']

## What RandSeq measures

A library of plasmids carrying random inserts is conjugated into a recipient strain. A plasmid
whose insert happens to contain a recognition site for an active restriction system is destroyed
on entry, so it is **depleted** relative to the input library. Sequencing the library before and
after gives, for each insert, a log2 fold change. The job of this module is to work backwards
from those fold changes to the sequence motifs responsible.

Nothing here is tied to a particular insert length, and the inserts need not all be the same
length: the scan works on whatever strings the count table is indexed by, and the two example
libraries used below differ by nearly an order of magnitude. What the insert length does decide
is which motifs the experiment could have found at all — `03_design` works that out from the
library size and the insert length.

### The method in four sentences

Every plasmid gets a **log2FC**: how much rarer it became after delivery. Every motif gets the
plasmids that contain it, and so a set of log2FC values. A motif's **score** is the fraction of
those values below a threshold — what fraction of the plasmids carrying this motif were
destroyed. Everything after that is deciding **which of the many motifs that score well is the
actual site**.

That last sentence is the bulk of the work. As three steps, then reporting:

1. counts → log2FC per plasmid
2. score every motif of every requested architecture — **the scan**
3. keep one description per site, discarding the same site written more or less specifically
4. drop a candidate whose score was borrowed from a stronger one
5. report, with each motif's depletion weighed against the sample's own background

Steps 3 and 4 are two halves of one problem: **one real site makes many motifs score well.**
Step 3 works on motif *strings*, and settles descriptions that differ by a defined position.
Step 4 works on *plasmids*, and settles descriptions in architectures too different for any string
rule to relate. Those four are the whole thing, and the first part of this notebook is nothing
else.

The second part of this notebook takes up a separate concern — what happens to a recognition site
that falls across the boundary between the vector and the insert — and adds a check that plugs
into step 4.

### Before trusting a negative result

This notebook is the algorithm. Whether the experiment could have found a given motif in the
first place is a separate question, decided by the vector and the library rather than by the
code: a site already present in the plasmid backbone is carried by every member of the library
and usually cannot be detected at all, and a motif with more defined bases than the insert can
supply carriers for cannot be called either. `03_design` works both out, and ships the tooling to
check them for your own vector and library. A negative result is not interpretable without it.

### The example data

Two count tables ship with the package, and they are deliberately unlike each other.

- `countsTable.csv.gz` — 19 recipient strains, with the donor `MFDpir` as the input library;
  11,629 inserts of 20 nt
- `counts_panel.csv.gz` — 8 recipient strains and donor replicates (`Control_R1`), each strain
  picked to exercise one specific behaviour of the pipeline; `example_data/counts_panel_key.csv`
  says which. 34,217 inserts, mostly 150 nt and ragged at the short end

So the two differ in insert length, in library size, and in their **vector flanks** — the last of
which matters more than it sounds, for reasons the second part of this notebook takes up.

*E. coli* JJ1886 appears in both, which makes it a useful consistency check — two measurements of
one strain must agree on which motifs they call, and on which strand they name them. That is a
check the canonical-strand rule below has to pass.

## Step 1: counts → log2FC per plasmid

The input is a table of read counts: **one row per insert sequence, one column per sample**. One
column holds the input library — the donor, before delivery — and every other column is a
recipient strain.

`calculate_log2fc` turns that into a fold change per insert, against the input column:

- **`count_threshold`** drops inserts too rare in the input to measure, keeping those seen
  *more than* this many times (so `20` keeps 21 and above). An insert read three times gives a
  fold change that is mostly sampling noise.
- **`pseudocount`** is added to every count first, so an insert driven to zero yields a finite
  number instead of `-inf`.
- counts are then converted to **relative abundance** — each column divided by its own sum — so
  that samples sequenced to different depths are comparable, and the reference column is dropped
  from the result.

Everything downstream works on a single column of this table: a Series indexed by insert
sequence, valued by log2 fold change.

In [7]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df

                        K12_T0     HS_T0  ...    S88_T0  MG1655_T0
seq                                       ...
CGGAGGTACTGGGTACATTT  0.043818  0.049551  ...  0.213624   0.090458
TGGCGATAATGCCGGCTATC  0.045463  0.137127  ...  0.092292   0.101627
TTCCAGTTCACTGGTCTTCG -0.049694  0.049903  ...  0.458076   0.128330
AATTTCAGTGCCGTTCAGAT -0.251957 -0.422224  ... -0.183890  -0.180938
CTGCGGTAATAATTCCCGCC -0.178427 -0.154025  ... -0.188758  -0.186226
...                        ...       ...  ...       ...        ...
GCTTGATGTAGCCTTCGAAC -0.100518 -0.079966  ... -0.055837  -0.133185
TAATGGCAAATTGACACTCC  0.258205  0.103683  ...  0.201961   0.387054
GCTGCGCGCGGAGTTGTTCC -0.629856 -0.381054  ... -0.497605  -0.959646
GCAACACGCCAGTAAGGTGT  0.693416  0.487153  ...  0.064457   0.376418
GATAGCCGGATAGCTTAAGG -0.245685 -0.131631  ... -0.400835   0.140210

[11503 rows x 19 columns]

## Step 2: the position-independent scan

Every motif of every **pattern** is scored over `left_flank + insert + right_flank`, on both
strands. A pattern is the shape of a site, written as three numbers — defined bases in the first
half, undefined bases between, defined bases in the second. `(6, 0, 0)` is a contiguous 6 bp site
like `GGTCTC`; `(3, 4, 4)` is a bipartite site like `CACNNNNGTAT`. `get_patterns()` in
`randseq.utils` returns the architectures REBASE records for Type I, II and III systems.

The flanks are included because a site can **straddle the junction** between the insert and the
vector — part of it spelled by the insert, part by the flank. A plasmid carrying such a site is
cut like any other, so a scan that looked at the insert alone would see the depletion and miss
what caused it.

Two rules define what "the plasmids containing a motif" means, and both matter for reading the
output:

- a motif is counted **once per plasmid**, however many times it occurs in that plasmid
- a motif and its **reverse complement are the same motif** — the library is scanned on both
  strands and the two are collapsed before counting

The search space is the caller's: `flexible_motif_patterns` lists the architectures to enumerate,
and a site whose shape is not in that list cannot be found. The second part of this notebook is
about one way that goes wrong.

The rest of this section is what the scan costs and how it is kept exact.

### What the scan computes, on three sequences

Before any machinery, the whole of step 2 for a single motif, by hand. `GAGACC` is present in the
first two sequences — in the second it is read on the other strand, as `GGTCTC`, and the two are
one motif. Collect the log2FC of the plasmids that carry it, and the score is the fraction of
those below the threshold. Thresholds keep one convention throughout the package: a **log2FC**
threshold is strict (`log2FC < thr`), a **score or support** threshold inclusive (`>= thr`, so
`min_support=3` means three supporting sequences, not four).

In [8]:
_seqs = ["GAGACCTT", "AAGAGACC", "TTTTTTTT"]
_fc = [-2.0, 0.5, -3.0]

carries = [("GAGACC" in s) or ("GGTCTC" in s) for s in _seqs]   # either strand, one motif
vals = [f for f, c in zip(_fc, carries) if c]
print(f"plasmids carrying GAGACC : {[s for s, c in zip(_seqs, carries) if c]}")
print(f"their log2FC             : {vals}")
print(f"score, fraction below -1 : {score(vals, thr=-1)}")

plasmids carrying GAGACC : ['GAGACCTT', 'AAGAGACC']
their log2FC             : [-2.0, 0.5]
score, fraction below -1 : 0.5

That is step 2 for one motif. The scan does it for **every** motif of every requested
architecture at once, which is the only reason any machinery is needed.

### How the scan is made fast

Scoring every motif of every pattern is where the runtime goes, so the scan does not work on
strings. Each library sequence is encoded once as 2-bit base codes, and a motif of pattern
`(d1, spacer, d2)` becomes an **integer** — its `d1 + d2` defined bases read as a base-4
numeral — so every per-motif statistic is an `np.bincount` over those integers. The alternative,
building a Python set of motif strings per sequence, costs roughly 10 s and 2 GB of RAM per
pattern on a 30k-sequence library against well under a second here.

`randseq.coding` holds that machinery — `encode_library`, `_pattern_window_codes`,
`decode_motif_codes`, `encode_motif`, `motif_presence_matrix` — together with the proofs that it
is exact. What matters in this notebook is only the contract:

- a window containing **any** non-ACGT base is rejected, padding included
- a motif is counted **once per sequence** that contains it, on either strand
- decoding is the exact inverse of encoding, so a reported motif string is the motif that was
  counted

A readable implementation of the same scan lives outside the package as
`tests/reference_scan.py`, and `tests/test_reference_scan.py` requires the two to produce
identical tables — so the fast path cannot quietly drift from the obvious one.

When numba is installed (`randseq[fast]`), `get_pattern_scores` runs steps A and B below as a
single compiled pass from `randseq.fast` instead, about thirteen times faster on eight cores.
What follows is still what it computes: the kernel is tested to return the same totals as these
numpy steps, on every shipped pattern.

### The scan in three steps

Scoring a pattern is one function, but it is three operations, and each has an output worth
seeing. The library below is twelve inserts of twelve bases with a site planted in four of
them — `GAGACC`, which reads `GGTCTC` on the other strand — and those four are the depleted
ones. Everything is small enough to check by eye.

In [9]:
demo_lib = ["GAGACCTTAACG", "TTGAGACCGCAT", "ACGGTCTCAATG", "CCAAGAGACCTT",
            "ACGTTGCAATGC", "TTACGCATTGCA", "GCATTACGGTTA", "ATGCCATTGCAA",
            "CATGCAATTGCG", "TTGCAATGCCAT", "GCAATTGCATGC", "ATTGCCATGCAA"]
demo_fc = np.array([-2.5, -3.0, -3.5, -3.0, 0.2, -0.1, 0.0, 0.3, -0.2, 0.1, 0.0, -0.3])

pd.DataFrame({"insert": demo_lib, "log2FC": demo_fc,
              "carries the site": [("GAGACC" in s) or ("GGTCTC" in s) for s in demo_lib],
              "depleted (< -1)": demo_fc < -1})

          insert  log2FC  carries the site  depleted (< -1)
0   GAGACCTTAACG    -2.5              True             True
1   TTGAGACCGCAT    -3.0              True             True
2   ACGGTCTCAATG    -3.5              True             True
3   CCAAGAGACCTT    -3.0              True             True
4   ACGTTGCAATGC     0.2             False            False
5   TTACGCATTGCA    -0.1             False            False
6   GCATTACGGTTA     0.0             False            False
7   ATGCCATTGCAA     0.3             False            False
8   CATGCAATTGCG    -0.2             False            False
9   TTGCAATGCCAT     0.1             False            False
10  GCAATTGCATGC     0.0             False            False
11  ATTGCCATGCAA    -0.3             False            False

The four carriers are exactly the four depleted plasmids, so a correct scan must report
`GAGACC` with a depletion fraction of 1.0 on a support of 4. Nothing else in the library should
come close.

**The library, encoded.** Before any scanning, `encode_library` turns the strings into 2-bit
base codes — `A=0 C=1 G=2 T=3`, anything else `4` — and returns the reverse complement
alongside, so both strands are available without re-encoding anything.

In [10]:
demo_fwd, demo_rc = encode_library(demo_lib)
print(f"fwd {demo_fwd.shape} {demo_fwd.dtype}, rc {demo_rc.shape}\n")
pd.DataFrame(demo_fwd[:4], index=demo_lib[:4])

fwd (12, 12) uint8, rc (12, 12)

              0   1   2   3   4   5   6   7   8   9   10  11
GAGACCTTAACG   2   0   2   0   1   1   3   3   0   0   1   2
TTGAGACCGCAT   3   3   2   0   2   0   1   1   2   1   0   3
ACGGTCTCAATG   0   1   2   2   3   1   3   1   0   0   3   2
CCAAGAGACCTT   1   1   0   0   2   0   2   0   1   1   3   3

Row `i` of `rc` is the reverse complement of sequence `i`, left-aligned in the same way — not a
reversal of the padded row. For the first insert:

In [11]:
print(f"      {demo_lib[0]}   {demo_fwd[0].tolist()}")
print(f"  rc  {revcomp(demo_lib[0])}   {demo_rc[0].tolist()}")

      GAGACCTTAACG   [2, 0, 2, 0, 1, 1, 3, 3, 0, 0, 1, 2]
  rc  CGTTAAGGTCTC   [1, 2, 3, 3, 0, 0, 2, 2, 3, 1, 3, 1]

**Step A — which motifs does each sequence contain?** Scan every window of both strands, then
reduce to one entry per *sequence and motif*: a motif occurring several times in one insert, or
once on each strand, is still one plasmid carrying it.

A site is double-stranded, so `GAGACC` and `GGTCTC` are one motif and must not be counted twice.
Whether both spellings even reach this point is decided by the pattern — a motif of
`(d1, spacer, d2)` reverse-complements into one of `(d2, spacer, d1)`. When that is the same
shape, as it is for `(6, 0, 0)`, the scan finds the site once per strand and the two codes are
**folded onto one** here. When it is not, the rc spelling belongs to another pattern's code space
and never appears, so there is nothing to fold. `randseq.coding` carries that rule and its proof;
the effect is that every pattern emits exactly one row per plasmid per site.

In [12]:
#| export
def motif_occurrences(encoded_library, pattern):
    """Which motifs each sequence contains, as parallel `(sequence index, motif code)` arrays.

    Both strands are scanned and the result is reduced to one entry per sequence per motif, so
    a motif occurring several times in one sequence -- or once on each strand -- is counted
    once. Where a pattern is self-reverse-complementary the two spellings of a site are folded
    onto one code first, so `GAGACC` and `GGTCTC` come back as a single motif rather than two
    rows carrying identical statistics. Windows containing a non-ACGT base, or running off the
    end of a short sequence, are dropped: both carry the out-of-range code that
    `_pattern_window_codes` assigns.

    Returns:
        (seq_idx, motif_codes): equal-length int arrays. `seq_idx` is non-decreasing, so the
        pairs come out grouped by sequence.
    """
    fwd, rc = encoded_library
    n_codes = 4 ** (pattern[0] + pattern[2])
    codes = np.concatenate([_pattern_window_codes(fwd, pattern),
                            _pattern_window_codes(rc, pattern)], axis=1)
    if pattern_is_self_rc(pattern):
        # One site, two spellings, both in this code space -- fold each onto the smaller of the
        # pair. Rejected windows keep their out-of-range code: they are not in the table, so
        # they are held out of the lookup and passed through untouched.
        table = rc_code_table(pattern)
        inside = codes < n_codes
        codes = np.where(inside, np.minimum(codes, table[np.where(inside, codes, 0)]), codes)
    codes.sort(axis=1)                                  # repeats become adjacent
    keep = codes < n_codes                              # drop rejected windows
    keep[:, 1:] &= codes[:, 1:] != codes[:, :-1]        # drop repeats within a sequence
    return np.nonzero(keep)[0], codes[keep]

In [13]:
seq_idx, motif_codes = motif_occurrences(encode_library(demo_lib), (6, 0, 0))
occurrences = pd.DataFrame({
    "sequence": [demo_lib[i] for i in seq_idx],
    "motif": decode_motif_codes(motif_codes, (6, 0, 0)),
    # the code IS the motif: A=0 C=1 G=2 T=3, read as a base-4 numeral
    "code (base 4)": [np.base_repr(c, 4).zfill(6) for c in motif_codes],
    "code": motif_codes})
print(f"{len(occurrences)} (sequence, motif) pairs from {len(demo_lib)} sequences")
occurrences.head(8)

82 (sequence, motif) pairs from 12 sequences

       sequence   motif code (base 4)  code
0  GAGACCTTAACG  AAGGTC        002231   173
1  GAGACCTTAACG  ACCTTA        011330   380
2  GAGACCTTAACG  AGACCT        020113   535
3  GAGACCTTAACG  CCTTAA        113300  1520
4  GAGACCTTAACG  CGTTAA        123300  1776
5  GAGACCTTAACG  CTTAAC        133001  1985
6  GAGACCTTAACG  GAGACC        202011  2181
7  TTGAGACCGCAT  ACCGCA        011210   356

Each row is one plasmid carrying one motif, and the base-4 column shows that a code is not an
arbitrary label — it **is** the motif. `GAGACC` is `202011` because `A=0 C=1 G=2 T=3`. The
integer is just that numeral in decimal, which is what makes every per-motif statistic an
`np.bincount`.

A 12 bp insert holds seven 6-mers per strand. Folding the strands together means those fourteen
windows collapse to at most seven distinct motifs — fewer still when a motif occurs twice in one
insert, or is its own reverse complement.

Pulling out just the planted site shows what the scan is going to score:

In [14]:
occurrences[occurrences.motif.isin(["GAGACC", "GGTCTC"])]

        sequence   motif code (base 4)  code
6   GAGACCTTAACG  GAGACC        202011  2181
11  TTGAGACCGCAT  GAGACC        202011  2181
18  ACGGTCTCAATG  GAGACC        202011  2181
27  CCAAGAGACCTT  GAGACC        202011  2181

Four sequences, one row each. `GGTCTC` is **not** a separate entry: it is the same site read on
the other strand, and Step A folded the pair onto the single code shown. Which of the two
spellings survives is decided by the code, not by biology — the smaller numeral wins, here
`GAGACC`. *Reporting* is where that is re-spelled to the name the literature uses, which for this
site is `GGTCTC`.

None of the twelve inserts above contains anything but `ACGT`, and all are the same length, so
neither rejection rule has shown itself yet. Both are about windows: a window containing a base
other than `ACGT` is dropped, and so is one that runs past the end of a short sequence (the
encoding pads short sequences with the same code an `N` gets). Three inserts show both:

In [15]:
edge = ["GAGACCTT",           # clean
        "GAGACCTTNAAAAAA",    # an N at position 8, then six more bases
        "GAGAC"]              # shorter than the 6-base pattern
_s, _c = motif_occurrences(encode_library(edge), (6, 0, 0))
pd.DataFrame({"sequence": [edge[i] for i in _s], "motif": decode_motif_codes(_c, (6, 0, 0))})

          sequence   motif
0         GAGACCTT  AAGGTC
1         GAGACCTT  AGACCT
2         GAGACCTT  GAGACC
3  GAGACCTTNAAAAAA  AAAAAA
4  GAGACCTTNAAAAAA  AAGGTC
5  GAGACCTTNAAAAAA  AGACCT
6  GAGACCTTNAAAAAA  GAGACC

The second insert keeps everything the first has — those windows end before the `N` — loses the
six windows that cover position 8, and picks up `AAAAAA` from the clean stretch after it (`TTTTTT`
on the other strand, folded). The third is padded to the library's width, every window runs into
the padding, and it contributes nothing.

In [16]:
#| hide
_by = {e: sorted(m for i, m in zip(_s.tolist(), decode_motif_codes(_c, (6, 0, 0))) if edge[i] == e)
       for e in edge}
test_eq(_by["GAGACCTT"], ["AAGGTC", "AGACCT", "GAGACC"])
test_eq(_by["GAGACCTTNAAAAAA"], ["AAAAAA", "AAGGTC", "AGACCT", "GAGACC"])   # N windows dropped
test_eq(_by["GAGAC"], [])                                                   # too short: none
test_eq(len(motif_occurrences(encode_library(["GAGNCC"]), (6, 0, 0))[0]), 0)  # N anywhere kills it

**Step B — group those pairs by motif.** Every statistic the scan reports is a sum over the
sequences carrying a motif, so each is one `np.bincount`. `first_seq` is kept so the output can
be ordered by where a motif first appears, which makes the table a function of the library
rather than of hash order.

In [17]:
#| export
def _motif_totals(seq_idx, motif_codes, fc_values, log2FC_thr, n_codes):
    """Per motif code: sequences carrying it, how many of those are depleted, the sum of their
    log2FC, and the index of the first sequence that carries it.

    Sums rather than means, because `np.bincount` adds; the means are taken once at the end.
    """
    seq_fc = fc_values[seq_idx]
    n_seqs = np.bincount(motif_codes, minlength=n_codes)
    n_depleted = np.bincount(motif_codes, weights=seq_fc < log2FC_thr, minlength=n_codes)
    fc_sum = np.bincount(motif_codes, weights=seq_fc, minlength=n_codes)
    first_seq = np.full(n_codes, len(fc_values))
    np.minimum.at(first_seq, motif_codes, seq_idx)
    return n_seqs, n_depleted, fc_sum, first_seq

In [18]:
n_seqs, n_depleted, fc_sum, first_seq = _motif_totals(
    seq_idx, motif_codes, demo_fc, -1, 4 ** 6)

present = np.flatnonzero(n_seqs)                 # the motifs this library actually contains
totals = pd.DataFrame({"motif": decode_motif_codes(present, (6, 0, 0)),
                       "n_seqs": n_seqs[present], "n_depleted": n_depleted[present],
                       "sum_log2fc": fc_sum[present], "first_seq": first_seq[present]})
print(f"{len(totals)} motifs present out of {4 ** 6} possible")
totals.sort_values(["n_depleted", "n_seqs"], ascending=False).head(6)

53 motifs present out of 4096 possible

     motif  n_seqs  n_depleted  sum_log2fc  first_seq
43  GAGACC       4         4.0       -12.0          0
2   AAGGTC       2         2.0        -5.5          0
13  AGACCG       2         2.0        -6.5          1
14  AGACCT       2         2.0        -5.5          0
47  GTCTCA       2         2.0        -6.5          1
50  TCTCAA       2         2.0        -6.5          1

`GAGACC` tops the table with four sequences, all four depleted — one row for the site, since
Step A folded `GGTCTC` into it. Only the motifs actually present get a row; the other codes
have a count of zero and are dropped.

**Step C — turn the totals into the reported numbers.** `fraction_depleted` is
`n_depleted / n_seqs`, `avg_log2fc` is `fc_sum / n_seqs`, and the p-value compares the depleted
count against this sample's own background rate. That is all that is left to do:

In [19]:
#| export
def scan_pattern(encoded_library, pattern, fc_values, log2FC_thr=-1, parallel=True):
    """Steps A and B for one pattern: per motif code, how many sequences carry it, how many of
    those are depleted, the sum of their log2FC, and the first sequence that carries it.

    The compiled kernel from `randseq.fast` when numba is installed, `motif_occurrences` and
    `_motif_totals` otherwise -- the same four arrays either way. Every count the pipeline makes
    of "the plasmids carrying a motif" comes from here, so no two steps can disagree on it.
    """
    fc_values = np.asarray(fc_values, dtype=float)
    if _fast.HAVE_NUMBA:
        return _fast.pattern_totals(encoded_library, pattern, fc_values, log2FC_thr,
                                    parallel=parallel)
    seq_idx, motif_codes = motif_occurrences(encoded_library, pattern)
    return _motif_totals(seq_idx, motif_codes, fc_values, log2FC_thr,
                         4 ** (pattern[0] + pattern[2]))


def _scores_from_totals(totals, pattern, codes, background_rate):
    """Step C for the given motif codes: the reported statistics, ordered by first sequence."""
    n_seqs, n_depleted, fc_sum, first_seq = totals
    codes = codes[np.argsort(first_seq[codes], kind="stable")]
    frac = n_depleted[codes] / n_seqs[codes]
    return pd.DataFrame({
        'motif': decode_motif_codes(codes, pattern),
        'fraction_depleted': frac,
        'num_sequences': n_seqs[codes],
        'avg_log2fc': fc_sum[codes] / n_seqs[codes],
        # P(at least this many of n depleted | null), against THIS sample's background
        # rate rather than a constant -- see `01_utils`.
        'p_value': motif_pvalues(n_seqs[codes], frac, background_rate),
    })


def get_pattern_scores(encoded_library, fc_values, pattern, log2FC_thr=-1,
                       background_rate=None, parallel=True):
    """
    Scores every motif of `pattern` found in the library, on both strands.

    Steps A, B and C above: find the (sequence, motif) pairs, total them per motif, and turn
    the totals into the reported statistics. A motif is counted once per sequence that contains
    it on either strand. `tests/reference_scan.py` holds a readable implementation of the same
    scan, and `tests/test_reference_scan.py` requires the two to give identical tables.

    When numba is installed, steps A and B run as one compiled pass instead (`randseq.fast`),
    which returns the same totals; `tests/test_fast_scan.py` requires the two paths to agree.

    Args:
        encoded_library (tuple): (fwd, rc) arrays from `encode_library`.
        fc_values (list or np.ndarray): log2FC of each sequence, in library order.
        pattern (tuple): (d1, spacer, d2) motif pattern.
        log2FC_thr (float): a sequence is depleted when its log2FC is below this value.
        background_rate (float): the null depletion rate the p-value is taken against;
            defaults to this library's own.
        parallel (bool): let the compiled path use numba's threads. Ignored on the numpy path.

    Returns:
        pd.DataFrame: one row per motif with 'motif', 'fraction_depleted',
            'num_sequences', 'avg_log2fc' and 'p_value', ordered by the first sequence that
            contains the motif.
    """
    fc_values = np.asarray(fc_values, dtype=float)
    totals = scan_pattern(encoded_library, pattern, fc_values, log2FC_thr, parallel)   # A + B
    if background_rate is None:
        # The one definition of the null rate, shared with `annotate_significance`: the q-value
        # correction recognises a reported motif's test by its p-value, so the two must agree to
        # the last bit.
        background_rate = background_depletion_rate(fc_values, log2FC_thr)
    return _scores_from_totals(totals, pattern, np.flatnonzero(totals[0]), background_rate)  # C

In [20]:
scores = get_pattern_scores(encode_library(demo_lib), demo_fc, (6, 0, 0))
scores.sort_values(["fraction_depleted", "num_sequences"], ascending=False).head(6)

     motif  fraction_depleted  num_sequences  avg_log2fc   p_value
6   GAGACC                1.0              4       -3.00  0.012346
0   AAGGTC                1.0              2       -2.75  0.111111
2   AGACCT                1.0              2       -2.75  0.111111
8   AGACCG                1.0              2       -3.25  0.111111
11  GTCTCA                1.0              2       -3.25  0.111111
12  TCTCAA                1.0              2       -3.25  0.111111

The planted site comes out at `fraction_depleted` 1.0 on four plasmids with a mean log2FC of
−3.0. The motifs below it are fragments of the same depleted inserts — 6-mers overlapping the
planted site — on two plasmids each: too few to judge, which is what
`flexible_motif_min_support` exists to discard.

In [21]:
#| hide
cols = ['fraction_depleted', 'num_sequences', 'avg_log2fc']
_t = scores.set_index('motif')
test_eq(_t.loc['GAGACC', cols].tolist(), [1.0, 4, -3.0])
assert 'GGTCTC' not in _t.index        # folded onto GAGACC: one site, one row, not two

# Step A: one entry per sequence per motif, however often it occurs or on whichever strand.
_e = encode_library(["GAGACCGAGACC", "TTTTTTTT"])          # GAGACC occurs TWICE in the first
_s, _c = motif_occurrences(_e, (6, 0, 0))
_pairs = list(zip(_s.tolist(), decode_motif_codes(_c, (6, 0, 0))))
test_eq(len(_pairs), len(set(_pairs)))                     # no (sequence, motif) pair repeats
test_eq(sum(1 for s, m in _pairs if s == 0 and m == "GAGACC"), 1)   # twice, both strands -> one
test_eq(sum(1 for s, m in _pairs if s == 0 and m == "GGTCTC"), 0)   # the rc spelling is folded
test_eq(sorted(m for s, m in _pairs if s == 1), ["AAAAAA"])         # TTTTTT folds onto AAAAAA
test_eq(len(motif_occurrences(encode_library(["NNNNNNNN"]), (6, 0, 0))[0]), 0)

# An asymmetric pattern has nothing to fold, and is left exactly as it was: the rc of a
# (4, 4, 3) motif is a (3, 4, 4) motif, which is not in this code space at all.
_sa, _ca = motif_occurrences(encode_library(["AAATACCCCCGTGAAA"]), (4, 4, 3))
test_eq(sum(1 for m in decode_motif_codes(_ca, (4, 4, 3)) if m == "ATACNNNNGTG"), 1)

# Step B: the totals are sums over exactly those pairs.
_n, _d, _f, _first = _motif_totals(_s, _c, np.array([-5.0, 0.0]), -1, 4 ** 6)
_g = encode_motif("GAGACC", (6, 0, 0))
test_eq((int(_n[_g]), int(_d[_g]), float(_f[_g]), int(_first[_g])), (1, 1, -5.0, 0))
_ta = encode_motif("AAAAAA", (6, 0, 0))                    # the folded home of TTTTTT
test_eq((int(_n[_ta]), int(_d[_ta]), int(_first[_ta])), (1, 0, 1))
test_eq(int(_n[encode_motif("CCCCCC", (6, 0, 0))]), 0)     # absent -> no sequences

### The real library

So far the scan has run on twelve inserts made up by hand. From here on the notebook works on the
example library instead: the inserts with their vector flanks added, and the matching log2FC
values. `get_lib_seq_context` builds the scanned strings, and `process_single_flexible_pattern`
below wraps the scan with the support and score thresholds that turn scores into candidates.

In [22]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib = get_lib_seq_context(log2fc_df.index, left, right)
fcs = log2fc_df["JJ1886_T0"].values
print(f"{len(lib)} sequences, each {len(lib[0])} nt with the flanks added")
lib[0][:60]

11503 sequences, each 60 nt with the flanks added

'GTCCTAGGTATAATACTAGTCGGAGGTACTGGGTACATTTGTTTTAGAGCTAGAAATAGC'

In [23]:
#| export
def process_single_flexible_pattern(
    current_flex_pattern,
    encoded_library,
    fc_values_for_flexible_analysis,
    flexible_motif_log2fc_thr,
    flexible_motif_score_thr,
    flexible_motif_min_support,
    parallel=True,
):
    """
    Scores all motifs of one flexible pattern and keeps the candidates with
    fraction_depleted >= flexible_motif_score_thr and num_sequences >= flexible_motif_min_support.

    Args:
        current_flex_pattern (tuple): (d1, spacer, d2) motif pattern.
        encoded_library (tuple): (fwd, rc) arrays from `encode_library` (sequences with context).
        fc_values_for_flexible_analysis (list): log2FC of each sequence, in library order.
        flexible_motif_log2fc_thr (float): log2FC below which a sequence counts as depleted.
        flexible_motif_score_thr (float): minimum fraction_depleted (inclusive, `>=`).
        flexible_motif_min_support (int): minimum number of sequences (inclusive, `>=`).
        parallel (bool): passed to `get_pattern_scores`; False inside a pool worker.

    Returns:
        (pd.DataFrame, np.ndarray, tuple): the surviving candidates -- 'motif',
            'fraction_depleted', 'num_sequences', 'avg_log2fc' and 'pattern' (the pattern as a
            string) -- the p-value of *every* motif that had enough support to be a test,
            survivor or not, and the pattern's totals from `scan_pattern`, so that later steps
            can look motifs of this pattern up rather than scan it again.

    Both are returned because the Benjamini-Hochberg correction needs the full set of tests, and
    only this function ever sees it: the candidates that fail the score threshold are discarded
    here, but they were still tested, and a correction that ignored them would be wrong.
    """
    fc = np.asarray(fc_values_for_flexible_analysis, dtype=float)
    totals = scan_pattern(encoded_library, current_flex_pattern, fc,
                          flexible_motif_log2fc_thr, parallel)
    n_seqs, n_depleted = totals[0], totals[1]
    background = background_depletion_rate(fc, flexible_motif_log2fc_thr)
    # Only the candidates are turned into strings; the tests stay arrays. A pattern has up to
    # 4**8 motifs present, and decoding every one of them was most of this step's time.
    tested = np.flatnonzero(n_seqs >= max(flexible_motif_min_support, 1))
    frac = n_depleted[tested] / n_seqs[tested]
    kept = _scores_from_totals(totals, current_flex_pattern,
                               tested[frac >= flexible_motif_score_thr], background)
    kept['pattern'] = str(current_flex_pattern)
    return kept, motif_pvalues(n_seqs[tested], frac, background), totals

In [24]:
candidates, tested, _ = process_single_flexible_pattern((3, 4, 4), encode_library(lib), fcs, -1, 0.7, 3)
# The scan reports whichever strand it read; these are the same two sites as ATACNNNNGTG and
# AAAGNNNNGTT, which is how they are spelled once canonicalised for reporting.
assert {"CACNNNNGTAT", "AACNNNNCTTT"} <= set(candidates.motif)
# far more motifs were tested than survived -- the correction has to account for all of them
print(f"{len(candidates)} candidates kept out of {len(tested)} tested")
candidates.sort_values('num_sequences', ascending=False).head()

8 candidates kept out of 16296 tested

         motif  fraction_depleted  ...        p_value    pattern
1  ATANNNNTGTG           0.964467  ...  2.555113e-250  (3, 4, 4)
2  CACNNNNGTAT           1.000000  ...  2.946431e-265  (3, 4, 4)
4  TACNNNNGTGA           0.849315  ...   8.486502e-74  (3, 4, 4)
6  TACNNNNGTGG           0.907692  ...   3.305633e-74  (3, 4, 4)
0  AACNNNNCTTT           1.000000  ...   1.588045e-87  (3, 4, 4)

[5 rows x 6 columns]

## Step 3: removing redundant descriptions of the same motif

One site comes back described several ways, with positions pinned that are not part of it.
This step keeps one description per site.

When **one motif is another with a position left undefined**, which to keep is settled by
scoring **all four bases at that position**:

- the four sit together → the position carries no information → the general motif is the site
- they separate into depleting and not → the general motif is a **mixture** of a site and a
  non-site, and the variants that deplete are the sites

Scoring all four is what makes the answer independent of the search space. The variants are
*computed*, not looked up among the candidates, so adding a coarser architecture to
`flexible_motif_patterns` cannot change which motif survives.

### Scoring the four bases at one position

The question step 3 asks over and over is the same one: *given a motif with a position left
undefined, what does each of the four bases score there?* `variant_profile` answers it — four
motifs in, their support and depletion score out.

In [25]:
#| export
def variant_profile(motifs, pattern, encoded, fc, log2fc_thr, totals=None):
    """Support and depletion score for each of a set of related motifs.

    Read off the pattern's totals from `scan_pattern` -- the counts step 2 makes -- so a
    variant is scored exactly as it would have been had its pattern been scanned there.

    Args:
        motifs (list): motif strings, all of the same `pattern`.
        pattern (tuple): the `(d1, spacer, d2)` shape they share.
        encoded (tuple): `(fwd, rc)` from `encode_library`.
        fc (np.ndarray): log2 fold change per library sequence, in the same order.
        log2fc_thr (float): a plasmid is depleted below this.
        totals (dict): totals by canonical pattern, for this library, `fc` and threshold.
            Shared across calls, it makes every pattern scanned at most once, and the patterns
            step 2 scanned never again. Filled in place.

    Returns:
        list: one `(motif, n_plasmids, score)` per motif, in the order given. A motif that has
        no code (an IUPAC base, or a defined base in the spacer) gets `n=0` and a score of `nan`.
    """
    totals = {} if totals is None else totals
    canon = canonical_pattern(pattern)
    if canon not in totals:
        totals[canon] = scan_pattern(encoded, canon, fc, log2fc_thr)
    n_seqs, n_depleted = totals[canon][0], totals[canon][1]
    mirrored = pattern[1] != 0 and tuple(pattern) != canon    # spelled on the other strand
    rc_table = rc_code_table(canon) if pattern_is_self_rc(canon) else None
    out = []
    for m in motifs:
        code = encode_motif(revcomp(m) if mirrored else m, canon)
        if code is not None and rc_table is not None:
            code = min(code, int(rc_table[code]))             # the fold step 2 applied
        n = int(n_seqs[code]) if code is not None else 0
        out.append((m, n, float(n_depleted[code] / n) if n else float("nan")))
    return out

In [26]:
enc = encode_library(lib)

# CACNNNNGTA leaves the eleventh position undefined. What do the four bases score there?
for motif, n, s in variant_profile(["CACNNNNGTAA", "CACNNNNGTAC", "CACNNNNGTAG", "CACNNNNGTAT"],
                                   (3, 4, 4), enc, fcs, -1):
    print(f"  {motif}  n={n:>4}  score={s:.3f}")

  CACNNNNGTAA  n=  15  score=0.067
  CACNNNNGTAC  n=  20  score=1.000
  CACNNNNGTAG  n=  11  score=0.000
  CACNNNNGTAT  n= 192  score=1.000

Two of the four are dead and two are perfect. Whatever `CACNNNNGTA` scores as a whole, it is an
average over two populations, not one.

In [27]:
#| hide
# Order is preserved, and a motif of a shape the encoder cannot express is reported as n=0
# rather than as a motif no plasmid carries.
_p = variant_profile(["GAGACC", "GGGGGG"], (6, 0, 0), enc, fcs, -1)
test_eq([m for m, _, _ in _p], ["GAGACC", "GGGGGG"])
test_eq(variant_profile(["CACNNNNGTAY"], (3, 4, 4), enc, fcs, -1)[0][1], 0)

### Reading a profile

Four numbers have to become one word. A motif is a **mixture** of a site and a non-site when its
variants are *bimodal*: some fail the threshold the candidate itself had to pass, **and** the
variants are spread by at least that threshold.

Both halves are needed. Requiring only a failing variant would condemn any weak-but-real motif
that has one variant just the wrong side of the line; requiring only a spread would condemn a
strong motif whose variants merely differ. Variants carried by fewer than `min_support` plasmids
are not judged at all, and a motif with fewer than two judgeable variants gets `unknown` rather
than a guess.

In [28]:
#| export
def verdict(profile, score_thr, min_support):
    """Call a variant profile 'mixture', 'genuine' or 'unknown'.

    Args:
        profile (list): `(motif, n, score)` triples, from `variant_profile`.
        score_thr (float): the depletion score a candidate had to reach to be here.
        min_support (int): a variant on fewer plasmids than this is not judged.

    Returns:
        tuple: the verdict, and the spread across judgeable variants (`None` when fewer than
        two can be judged).
    """
    judged = [s for _, n, s in profile if n >= min_support]
    if len(judged) < 2:
        return "unknown", None
    spread = max(judged) - min(judged)
    bimodal = any(s < score_thr for s in judged) and spread >= score_thr
    return ("mixture" if bimodal else "genuine"), spread

In [29]:
# Four real profiles, one per case the rule has to get right.
mixture = [("a", 15, 0.07), ("c", 20, 1.00), ("g", 11, 0.00), ("t", 192, 1.00)]
weak    = [("a", 77, 0.506), ("c", 53, 0.679), ("g", 62, 0.468), ("t", 110, 0.564)]
strong  = [("a", 555, 0.654), ("c", 409, 0.677), ("g", 526, 0.755), ("t", 667, 0.705)]
thin    = [("a", 4, 1.0), ("c", 1, 1.0), ("g", 3, 1.0), ("t", 1, 1.0)]
for name, p in [("mixture", mixture), ("weak", weak), ("strong", strong), ("thin", thin)]:
    v, spread = verdict(p, 0.5, 5)
    print(f"  {name:8s} {v:8s} spread={'  —' if spread is None else f'{spread:.3f}'}")

  mixture  mixture  spread=1.000
  weak     genuine  spread=0.211
  strong   genuine  spread=0.101
  thin     unknown  spread=  —

`weak` is the case that decides the design. One of its variants scores 0.468, below the 0.5
threshold — but all four sit within 0.21 of each other, so there is no population of non-sites
hiding inside it. It stays. `mixture` separates by a full 1.0 and goes.

In [30]:
#| hide
test_eq(verdict(mixture, 0.5, 5)[0], "mixture")
test_eq(verdict(weak, 0.5, 5)[0], "genuine")      # a failing variant alone is not enough
test_eq(verdict(strong, 0.5, 5)[0], "genuine")
test_eq(verdict(thin, 0.5, 5)[0], "unknown")      # nothing with enough plasmids to judge
test_eq(round(verdict(mixture, 0.5, 5)[1], 3), 1.0)
test_eq(round(verdict(weak, 0.5, 5)[1], 3), 0.211)
# Exactly one judgeable variant is still 'unknown': a spread needs two numbers.
test_eq(verdict([("a", 99, 0.1), ("c", 1, 1.0)], 0.5, 5)[0], "unknown")

### Every position worth testing, with no second candidate

`_variants` needs two candidates. A motif can also be a mixture when **nothing else in the table
contests it** — most importantly when a shadow of a real site sits at a different register, so
that neither motif contains the other and no pairwise comparison can relate them.

`_undefined_positions` asks the question of a candidate alone, by padding it with `N` and testing
each padded position in turn: one base out beyond each end, and the spacer positions next to each
half. A position in the middle of a long spacer is skipped — fixing it would leave two gaps,
which is not a shape any described recognition site has, nor one `(d1, spacer, d2)` can write.

In [31]:
#| export
def _undefined_positions(motif, pattern):
    """Each undefined position worth testing on a candidate, as (four variants, their pattern)."""
    d1, spacer, d2 = pattern
    width = d1 + spacer + d2
    jobs = [([b + motif for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1 + 1, spacer, d2)),
            ([motif + b for b in "ACGT"], (width + 1, 0, 0) if spacer == 0 else (d1, spacer, d2 + 1))]
    if spacer:
        p = d1
        jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"],
                     (d1 + 1 + d2, 0, 0) if spacer == 1 else (d1 + 1, spacer - 1, d2)))
        if spacer > 1:
            p = d1 + spacer - 1
            jobs.append(([motif[:p] + b + motif[p + 1:] for b in "ACGT"], (d1, spacer - 1, d2 + 1)))
    return jobs

In [32]:
# NATACNNNNGTGN: four positions to test, each giving a different pattern.
for variants, vpat in _undefined_positions("ATACNNNNGTG", (4, 4, 3)):
    print(f"  {vpat}  {variants[0]}")

# A contiguous motif has no spacer, so only the two ends are testable.
print()
for variants, vpat in _undefined_positions("GGTCTC", (6, 0, 0)):
    print(f"  {vpat}  {variants[0]}")

  (5, 4, 3)  AATACNNNNGTG
  (4, 4, 4)  ATACNNNNGTGA
  (5, 3, 3)  ATACANNNGTG
  (4, 3, 4)  ATACNNNAGTG

  (7, 0, 0)  AGGTCTC
  (7, 0, 0)  GGTCTCA

In [33]:
#| hide
# Every variant really is of the pattern it is labelled with, and the four differ at one position.
for m, pat in [("ATACNNNNGTG", (4, 4, 3)), ("GGTCTC", (6, 0, 0)), ("ACANAGG", (3, 1, 3))]:
    for variants, vpat in _undefined_positions(m, pat):
        test_eq(len(variants), 4)
        test_eq({len(v) for v in variants}, {sum(vpat)})
        test_eq(len({v for v in variants}), 4)
        d1, sp, d2 = vpat
        for v in variants:
            test_eq(v[d1:d1 + sp], "N" * sp)        # the gap is where the pattern says it is
            assert "N" not in v[:d1] + v[d1 + sp:]  # and nowhere else
test_eq(len(_undefined_positions("GGTCTC", (6, 0, 0))), 2)       # no spacer: two ends only
test_eq(len(_undefined_positions("ACANAGG", (3, 1, 3))), 3)      # a 1-base spacer: one position
test_eq(len(_undefined_positions("ATACNNNNGTG", (4, 4, 3))), 4)  # a wide spacer: both edges

### The standalone test

`is_mixture` is the three above put together: for each testable position, score the four bases and
read the verdict. One bimodal position is enough to condemn the motif.

This is the readable form. `filter_redundant_patterns` runs the same test over all its
survivors at once, because the survivors share far fewer patterns than they have positions
to test and the window codes for a pattern are read once either way.

This strain's Type I site is `ATACNNNNGTG`, pattern `(4, 4, 3)` — the spelling it is
*reported* under. The scan found it as `CACNNNNGTAT` of pattern `(3, 4, 4)`, and reporting put it
on its canonical strand; reverse-complementing a site turns `(d1, spacer, d2)` into
`(d2, spacer, d1)`, so the pattern has to follow the motif. That is why a reported pattern can be
one `flexible_motif_patterns` never contains. The scan also returns
`ATANNNNTGTG`, pattern `(3, 4, 4)` — the same stretch of DNA read in a **different register**, its
gap sitting one base to the left. Neither string contains the other, so no pairwise comparison can
relate them, and both describe mostly the same 190 plasmids. Only the standalone test separates
them:

In [34]:
#| export
def is_mixture(motif, pattern, encoded_library, fc_values, log2fc_thr=-1,
               score_thr=0.5, min_support=5, totals=None):
    """Does fixing one undefined position split this motif's plasmids into sites and non-sites?

    Args:
        motif (str): the candidate.
        pattern (tuple): its `(d1, spacer, d2)` shape.
        encoded_library (tuple): `(fwd, rc)` from `encode_library`.
        fc_values (np.ndarray): log2 fold change per library sequence.
        log2fc_thr (float), score_thr (float), min_support (int): as elsewhere in the step.
        totals (dict): shared pattern totals, as for `variant_profile`.

    Returns:
        bool: True when some position's four bases are bimodal.
    """
    for variants, vpat in _undefined_positions(motif, pattern):
        if sum(vpat) > encoded_library[0].shape[1]:  # the padded motif is wider than the insert
            continue
        if verdict(variant_profile(variants, vpat, encoded_library, fc_values, log2fc_thr,
                                   totals), score_thr, min_support)[0] == "mixture":
            return True
    return False

In [35]:
for motif, pat in [("ATANNNNTGTG", (3, 4, 4)), ("ATACNNNNGTG", (4, 4, 3))]:
    print(f"{motif}  {pat}   is_mixture = {is_mixture(motif, pat, enc, fcs, -1, 0.7, 3)}")
    for variants, vpat in _undefined_positions(motif, pat):
        prof = variant_profile(variants, vpat, enc, fcs, -1)
        v, spread = verdict(prof, 0.7, 3)
        cells = "  ".join(f"{s:.2f}({n})" if n else "  -- (0)" for _, n, s in prof)
        print(f"   {str(vpat):10s} {v:8s} "
              f"spread={'   —' if spread is None else f'{spread:.2f}'}   {cells}")
    print()

ATANNNNTGTG  (3, 4, 4)   is_mixture = True
   (4, 4, 4)  mixture  spread=0.74   0.99(190)  0.33(3)  0.25(4)    -- (0)
   (3, 4, 5)  genuine  spread=0.07   1.00(53)  0.93(45)  0.95(56)  0.98(43)
   (4, 3, 4)  mixture  spread=1.00   0.20(5)  1.00(189)  0.00(3)    -- (0)
   (3, 3, 5)  genuine  spread=0.49   0.00(2)    -- (0)  0.99(189)  0.50(6)

ATACNNNNGTG  (4, 4, 3)   is_mixture = False
   (5, 4, 3)  unknown  spread=   —   1.00(189)  1.00(1)  1.00(1)  1.00(1)
   (4, 4, 4)  genuine  spread=0.00   1.00(54)  1.00(44)  1.00(53)  1.00(41)
   (5, 3, 3)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)
   (4, 3, 4)  unknown  spread=   —     -- (0)  1.00(1)  1.00(2)  1.00(189)

Pinning the base next to `ATANNNNTGTG`'s left half splits its plasmids in two: 190 at 0.99 against
a handful at 0.33 and 0.25, a spread of 0.74. It is a real site averaged with sequences that are
not sites, and it goes.

The real site has nothing to split. Every base at its one judgeable position scores exactly 1.00,
on 41 to 54 plasmids each — a spread of zero. The other three positions fall below `min_support`
and are not judged, which is `unknown`, not a verdict against it.

### The filter

`filter_redundant_patterns` applies the two rules to every pair, then runs the standalone test over
whatever survives.

In [36]:
#| export
def is_extension(specific, general):
    """Is `specific` the motif `general` with one more defined base, on either strand?

    The extra base sits one past an end of `general` or at an edge of its spacer -- the
    positions `_undefined_positions` tests. Both strands are checked because every pattern is
    searched in one canonical form, so adding a base to a motif's longer side can turn its shape
    into the mirror form, which the scan writes on the other strand: `TACNNNNGTGA` is
    `CACNNNNGTA` with a base added on the left.
    """
    defined = lambda m: len(m) - m.count("N")
    return defined(specific) == defined(general) + 1 and find_broad_in_specific(specific, general)


def filter_redundant_patterns(df, log2fc_series, left_context, right_context,
                              log2fc_thr=-1, score_thr=0.5, min_support=5,
                              encoded=None, totals=None):
    """Keep one description per site, by two rules.

    1. **A mixture is not a site.** A candidate is dropped when fixing one position next to it
       splits its plasmids into depleting and not (`is_mixture`).
    2. **A one-base extension of a site is redundant.** A candidate is dropped when it is a
       candidate that survived rule 1 with one more defined base (`is_extension`): rule 1 found
       that site's neighbouring positions carry nothing, so pinning one adds nothing.

    Neither rule depends on the order the candidates arrive in.

    Args:
        df (pd.DataFrame): candidates, with 'motif' and 'pattern'.
        log2fc_series (pd.Series): log2 fold change, indexed by insert sequence.
        left_context (str), right_context (str): the vector flanks.
        log2fc_thr (float): a plasmid is depleted below this.
        score_thr (float): the score a candidate had to reach, reused as the bar a variant must
            clear and as the spread that marks a profile bimodal.
        min_support (int): a variant on fewer plasmids than this is not judged.
        encoded (tuple): the library from `encode_library`, if the caller already has it.
        totals (dict): shared pattern totals, as for `variant_profile`.

    Returns:
        pd.DataFrame: `df` without the redundant rows, in the original row order.
    """
    if df.empty:
        return df
    motifs = df["motif"].tolist()
    pats = []
    for pat in (df["pattern"] if "pattern" in df.columns else [None] * len(df)):
        try:
            pats.append(tuple(ast.literal_eval(pat)) if isinstance(pat, str) else (tuple(pat) if pat else None))
        except Exception:
            pats.append(None)
    if encoded is None:
        encoded = encode_library(get_lib_seq_context(log2fc_series.index.tolist(),
                                                     left_context, right_context))
    totals = {} if totals is None else totals
    fc = log2fc_series.to_numpy()

    # Rule 1. A candidate whose pattern is unknown cannot be tested, and stays.
    survivors = [k for k in range(len(df)) if pats[k] is None or not is_mixture(
        motifs[k], pats[k], encoded, fc, log2fc_thr, score_thr, min_support, totals)]

    # Rule 2. A one-base extension has exactly one more defined base, so each survivor is only
    # compared with the survivors one base shorter, not with every other candidate.
    by_defined = defaultdict(list)
    for k in survivors:
        by_defined[len(motifs[k]) - motifs[k].count("N")].append(k)
    keep = [k for k in survivors
            if not any(is_extension(motifs[k], motifs[j])
                       for j in by_defined[len(motifs[k]) - motifs[k].count("N") - 1])]
    return df.iloc[keep]

In [37]:
#| hide
test_eq(is_extension("CACNNNNGTAT", "CACNNNNGTA"), True)      # a base past the right end
test_eq(is_extension("TACNNNNGTGA", "CACNNNNGTA"), True)      # ... past the left, other strand
test_eq(is_extension("CCCCNNNNNTTTC", "CCCNNNNNNTTTC"), True)  # a spacer edge pinned
test_eq(is_extension("CACNNNNGTA", "CACNNNNGTA"), False)       # not more defined
test_eq(is_extension("CACANNNGTACC", "CACNNNNGTA"), False)     # two more defined bases
test_eq(is_extension("GGTCTCA", "CACNNNNGTA"), False)          # unrelated

Three patterns over the example library, all of them in `get_patterns()`. There is no
`(4, 4, 3)`: it is the mirror of `(3, 4, 4)`, scanning one on both strands already finds every
site of the other, and the pipeline rewrites it as `(3, 4, 4)`:

In [38]:
enc = encode_library(lib)
redundant_demo = pd.concat(
    [process_single_flexible_pattern(p, enc, fcs, -1, 0.7, 3)[0]
     for p in [(6, 0, 0), (3, 4, 3), (3, 4, 4)]], ignore_index=True)
redundant_demo[["motif", "pattern", "fraction_depleted", "num_sequences"]]

          motif    pattern  fraction_depleted  num_sequences
0        AGTGTG  (6, 0, 0)           0.820961            229
1        GAGACC  (6, 0, 0)           1.000000              9
2    CACNNNNGTA  (3, 4, 3)           0.894958            238
3   AACNNNNCTTT  (3, 4, 4)           1.000000             63
4   ATANNNNTGTG  (3, 4, 4)           0.964467            197
5   CACNNNNGTAT  (3, 4, 4)           1.000000            192
6   TACNNNNGTGC  (3, 4, 4)           0.978723             47
7   TACNNNNGTGA  (3, 4, 4)           0.849315             73
8   CACNNNNGTAC  (3, 4, 4)           1.000000             20
9   TACNNNNGTGG  (3, 4, 4)           0.907692             65
10  TACNNNNGTGT  (3, 4, 4)           0.867925             53

`GAGACC` and `AGTGTG` appear once each. `(6, 0, 0)` is its own mirror, so a contiguous site is
found on both strands within one pattern — and Step A folded the two spellings onto one row, so
`GGTCTC` is not a separate candidate. The bipartite patterns are not their own mirrors, and their
sites appear once anyway.

The interesting pair is `CACNNNNGTA` from `(3, 4, 3)` against the longer `(3, 4, 4)` motifs that
contain it. It scores 0.895 — worse than they do, but on more plasmids. Scoring all four bases at
the position they disagree on settles it:

In [39]:
# the position one past the right end of CACNNNNGTA, where CACNNNNGTAT pins a T
profile = variant_profile(["CACNNNNGTA" + b for b in "ACGT"], (3, 4, 4),
                          encode_library(lib), fcs, -1)
for motif, n, score in profile:
    print(f"  {motif:14s} n={n:>4}  score={score:.3f}")
print(f"\n  verdict: {verdict(profile, 0.7, 3)[0]}, spread {verdict(profile, 0.7, 3)[1]:.2f}")

  CACNNNNGTAA    n=  15  score=0.067
  CACNNNNGTAC    n=  20  score=1.000
  CACNNNNGTAG    n=  11  score=0.000
  CACNNNNGTAT    n= 192  score=1.000

  verdict: mixture, spread 1.00

Two of the four are dead and two are perfect. `CACNNNNGTA` is not a site that happens to score
0.895 — it is `CACNNNNGTAC` and `CACNNNNGTAT` averaged with two sequences that are not sites at
all. So it goes, and the two that work stay.

In [40]:
filter_redundant_patterns(
    redundant_demo, log2fc_df["JJ1886_T0"], left, right,
    log2fc_thr=-1, score_thr=0.7, min_support=3)[
    ["motif", "pattern", "fraction_depleted", "num_sequences"]]

         motif    pattern  fraction_depleted  num_sequences
1       GAGACC  (6, 0, 0)           1.000000              9
3  AACNNNNCTTT  (3, 4, 4)           1.000000             63
5  CACNNNNGTAT  (3, 4, 4)           1.000000            192
6  TACNNNNGTGC  (3, 4, 4)           0.978723             47
8  CACNNNNGTAC  (3, 4, 4)           1.000000             20

Five survive, and the strand rule had nothing to do: no mirror pairs reached this step.
`CACNNNNGTA` goes because the variant test above found it a mixture. Three of the four
`TACNNNNGTG` variants go too, as do `AGTGTG` and `ATANNNNTGTG`. Each fails the standalone test:
fixing one more undefined position splits its plasmids into depleting and not. What survives
here is the input to step 4, which asks whether each one still has plasmids of its own.

This ran on four patterns rather than the full set, so that the tables stayed small enough to
read. The worked example at the end of the notebook shows the full search.

In [41]:
#| hide
_lib = pd.Series([-5.0, -5.0, 0.0], index=["GAGACCTT", "AAGAGACC", "TTTTTTTT"])
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# Unrelated motifs describe different plasmids, so both stand.
_t = pd.DataFrame({"motif": ["GGTCTC", "AAACNNNNGTC"], "fraction_depleted": [0.95, 0.80],
                   "pattern": ["(6, 0, 0)", "(4, 4, 3)"]})
test_eq(len(filter_redundant_patterns(_t, _lib, "", "", **_kw)), 2)

# Only N is a wildcard. A full IUPAC code is not treated as covering the bases it stands for,
# so these two are unrelated to this filter. The scan only ever emits N, so this bounds what the
# filter can be asked to do rather than describing what it sees.
test_eq(find_broad_in_specific("CACNNNNGTAC", "CACNNNNGTAY"), False)

# Why the loop never sees two candidates that contain each other. Mutual containment is ONLY
# ever the reverse complement, which canonical patterns and the Step A fold rule out: it forces equal length, and at equal
# length N-wildcard matching both ways forces identical strings unless the match is found in the
# other orientation. Checked over every short motif.
import itertools as _it
for _L in (3, 4):
    for _a, _b in _it.permutations(["".join(p) for p in _it.product("ACGTN", repeat=_L)], 2):
        if find_broad_in_specific(_a, _b) and find_broad_in_specific(_b, _a):
            test_eq(_a, revcomp(_b))

## Naming a set of plasmids by a fixed-position motif

A motif recorded at a known offset names a set of plasmids without a search: the offset says where
to look, so testing it is a slice comparison. `fixed_motif_presence` builds that set, and
`fixed_motif_labels` names it. The second part of this notebook is where such tables come from,
and the check at the end of the pipeline uses them to ask whether every fixed-position motif found
has a reported motif that accounts for it.

In [42]:
#| export
def fixed_motif_presence(log2fc_series, fixed_motifs_df):
    """Boolean (n_sequences, n_fixed): does sequence i carry fixed motif j at its offset?

    The offset is read from the motif's own anchoring end, so this is correct on a library of
    ragged inserts: a right-anchored motif is looked for at the same distance from the end of
    every sequence, however long that sequence is.
    """
    seqs = list(log2fc_series.index)
    if fixed_motifs_df is None or len(fixed_motifs_df) == 0:
        return np.zeros((len(seqs), 0), dtype=bool)
    columns = []
    for row in fixed_motifs_df.itertuples():
        pos, n = int(row.position), int(row.length)
        anchor = getattr(row, 'anchor', 'left')
        if anchor == 'left':
            columns.append(np.array([s[pos:pos + n] == row.motif for s in seqs], dtype=bool))
        else:
            columns.append(np.array([len(s) >= pos + n and
                                     s[len(s) - pos - n:len(s) - pos] == row.motif
                                     for s in seqs], dtype=bool))
    return np.column_stack(columns)


def fixed_motif_labels(fixed_motifs_df):
    """`MOTIF@L4` / `MOTIF@R0` -- the motif, the anchoring end, and the offset from it."""
    if fixed_motifs_df is None or len(fixed_motifs_df) == 0:
        return []
    return [f"{r.motif}@{getattr(r, 'anchor', 'left')[0].upper()}{int(r.position)}"
            for r in fixed_motifs_df.itertuples()]

In [43]:
#| hide
# The offset is read from the motif's own anchoring end, so the SAME bases elsewhere do not
# count -- and a right-anchored motif means the same thing in inserts of different lengths.
_fx = pd.DataFrame([dict(motif="GTG", anchor="left", position=0, length=3,
                         fraction_depleted=1.0, num_sequences=2, avg_log2fc=-5.0),
                    dict(motif="AC", anchor="left", position=3, length=2,
                         fraction_depleted=1.0, num_sequences=1, avg_log2fc=-5.0),
                    dict(motif="GT", anchor="right", position=1, length=2,
                         fraction_depleted=1.0, num_sequences=2, avg_log2fc=-5.0)])
_s = pd.Series([-5.0, -0.1, -5.0, -0.2, -5.0],
               index=["GTGACGT", "AAACGTA", "GTGTTTT", "TTACTTT", "AAAAAAAGTC"])
_p = fixed_motif_presence(_s, _fx)
test_eq(_p[:, 0].tolist(), [True, False, True, False, False])   # GTG at offset 0 from the left
test_eq(_p[:, 1].tolist(), [True, False, False, False, False])  # AC at offset 3 from the left
# GT one base in from the end: true for AAACGTA (...GTa) and for the 10-mer (...GTc),
# which are different lengths -- that is the point of anchoring on the end
test_eq(_p[:, 2].tolist(), [False, True, False, False, True])
test_eq(fixed_motif_labels(_fx), ["GTG@L0", "AC@L3", "GT@R1"])
# no fixed motifs is a normal outcome, and must give a well-shaped empty matrix
test_eq(fixed_motif_presence(_s, pd.DataFrame()).shape, (5, 0))
test_eq(fixed_motif_presence(_s, None).shape, (5, 0))

## Step 4: drop candidates whose score was borrowed

Step 3 keeps one description per site. It cannot relate two descriptions of the *same* site in
**different architectures** — `ATACNNNNGTG` of pattern `(4, 4, 3)` and `CACANNAGTA` of pattern
`(4, 2, 4)` sit on the same 188 plasmids, but neither is the other with a position left undefined,
so no rule in step 3 can see that they are one answer.

What separates them is what each has that the other does not:

```
ATACNNNNGTG   n=192        CACANNAGTA   n=192        shared  188
ATACNNNNGTG only   n=4   score 1.000
CACANNAGTA  only   n=4   score 0.500
```

Remove `ATACNNNNGTG`'s plasmids and `CACANNAGTA` falls from 0.990 to 0.500 — its score was
**borrowed**. Remove `CACANNAGTA`'s and `ATACNNNNGTG` holds at 1.000. That asymmetry is the test:
a candidate is dropped when, restricted to the plasmids it does not share with a stronger
candidate, it no longer reaches the `score_thr` it had to pass in the first place.

The test is on the collapse, not on how much is left. Both residues here are four plasmids —
judging them by size would decide the pair on a score difference of 0.01, which is not evidence
about anything.

In [44]:
#| export
def filter_explained_candidates(candidates_df, log2fc_series, left_context, right_context,
                                log2fc_thr=-1, score_thr=0.7, min_support=3,
                                fixed_motifs_df=None, encoded=None):
    """Drop candidates whose depletion is fully accounted for by stronger candidates.

    Candidates are taken strongest first. Each `X` is restricted to the plasmids that carry
    **none** of the stronger candidates still standing; if what is left no longer reaches
    `score_thr`, `X`'s score was borrowed and `X` is removed. Otherwise it stands, and its own
    plasmids join the set later candidates are tested against.

    The test is against the *union* of the stronger survivors, not against each in turn. A
    description that overlaps several co-occurring sites can keep a depleted residue against
    every one of them separately while carrying no plasmid that none of them explains -- on the
    older JJ1886 run, `CCACNNNAGTA` had 55 carriers, all depleted, every one of which also
    carried one of the four real sites, and a pairwise test kept it.

    The test is on the **collapse**, not on the size of what is left: a motif whose residue is
    empty has nothing of its own, and one whose residue still depletes keeps its claim however
    few plasmids it rests on. Scoring a residue against `min_support` instead would decide
    near-complete overlaps on which description happened to score a hundredth higher, since
    neither residue would be large enough to judge.

    No threshold is introduced: the test re-applies `score_thr` to the conditional set.

    Args:
        candidates_df: surviving candidates, with 'motif' and (optionally) 'pattern' columns.
        log2fc_series: the full log2FC series, indexed by sequence.
        left_context, right_context: the vector sequence flanking the insert.
        log2fc_thr: a plasmid is depleted below this.
        score_thr: fraction of plasmids that must still be depleted for a candidate to stand
            on its own.
        min_support: unused by the residue test, which is relative -- the candidate's support
            was already established when it became a candidate. Accepted so that the step takes
            the same thresholds as the rest of the pipeline.
        fixed_motifs_df: the fixed-position motifs, offered as additional explainers. They can
            explain a candidate but are never themselves dropped, because they are not being
            reported as sites, and they never explain a candidate they merely tie with. This matters when the real site cannot be written as any scanned
            pattern: nothing in the candidate set can then account for the junction plasmids,
            and every candidate overlapping them borrows depletion that has no owner.

    Returns:
        (kept_df, explanations) where explanations maps a dropped motif to
        (explaining motif, plasmids left, score on them).
    """
    if candidates_df.empty:
        return candidates_df, {}
    if len(candidates_df) < 2 and (fixed_motifs_df is None or len(fixed_motifs_df) == 0):
        return candidates_df, {}     # nothing that could explain anything

    motifs = candidates_df['motif'].tolist()
    if 'pattern' in candidates_df.columns:
        patterns = []
        for p in candidates_df['pattern']:
            try:
                patterns.append(tuple(ast.literal_eval(p)) if isinstance(p, str) else tuple(p))
            except (ValueError, SyntaxError):
                patterns.append(None)
    else:
        patterns = [None] * len(motifs)

    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence, handled = motif_presence_matrix(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()

    # Fixed-position motifs join as explainer-only columns, after the candidates, so an
    # index below n_candidates is droppable and one at or above it is not.
    n_candidates = len(motifs)
    presence = np.hstack([presence, fixed_motif_presence(log2fc_series, fixed_motifs_df)])
    motifs = motifs + fixed_motif_labels(fixed_motifs_df)

    fc = log2fc_series.to_numpy()
    strength = []
    for j in range(len(motifs)):
        v = fc[presence[:, j]]
        strength.append(((v < log2fc_thr).mean() if len(v) else 0.0,
                         len(v),
                         motifs[j]))
    # Strongest first: highest depletion fraction, then MOST plasmids. Support breaks the tie,
    # not mean log2FC, because a shadow is a subset of its parent's plasmids, and a subset
    # picked out by the extra bases it requires tends to keep the most depleted of them -- so on
    # mean log2FC a shadow systematically outranks the site it came from, is never tested against
    # it, and survives. On the older JJ1886 run CCACNNNAGTA (55 plasmids, mean -4.85) sorted above
    # its parent ATACNNNNGTG (192, -4.76) and stood, although every one of its plasmids carried a
    # known site. A subset can never have more plasmids than the set it is drawn from.
    # The motif string is the final tie-break so the order, and therefore the outcome, is a
    # function of the candidates rather than of the row order they arrive in.
    # On a tie, a candidate outranks a fixed-position motif. A junction-formed site can be
    # described by a flexible motif covering exactly the fixed motif's plasmids, in which case
    # the two tie on every statistic -- and the fixed motif must not be allowed to explain it
    # away, because the fixed motif is evidence about the junction while the candidate is the
    # answer. Without this the label string decides, and the real call survives or is discarded
    # depending on how it happens to sort.
    order = sorted(range(len(motifs)),
                   key=lambda j: (-strength[j][0], -strength[j][1],
                                  1 if j >= n_candidates else 0, strength[j][2]))

    explanations = {}
    covered = np.zeros(presence.shape[0], dtype=bool)   # plasmids a stronger survivor carries
    standing = []                                        # those survivors, strongest first
    for x in order:
        if x < n_candidates:
            alone = presence[:, x] & ~covered
            n = int(alone.sum())
            v = fc[alone]
            still = float((v < log2fc_thr).mean()) if n else 0.0
            if n == 0 or still < score_thr:
                # Name the survivor that accounts for most of X's plasmids, and say how many
                # others it took. A shadow cannot explain anything, so it never joins `covered`.
                shared = [(int((presence[:, x] & presence[:, y]).sum()), -k, y)
                          for k, y in enumerate(standing)]
                shared = [s for s in shared if s[0] > 0]
                if shared:
                    label = motifs[max(shared)[2]] + (
                        f" + {len(shared) - 1} more" if len(shared) > 1 else "")
                else:                    # fails on its own plasmids; nothing to blame
                    label = "(no stronger motif)"
                explanations[x] = (label, n, still)
                continue
        # A fixed motif explains but is never dropped; a candidate that stood joins it.
        covered |= presence[:, x]
        standing.append(x)

    keep = [j for j in range(n_candidates) if j not in explanations]
    return (candidates_df.iloc[keep],
            {motifs[x]: v for x, v in explanations.items()})

In [45]:
#| hide
# Two candidates on ten plasmids each, eight of them shared. What decides is whether the two
# plasmids NOT shared still deplete -- not that there are only two of them. Under a support
# floor of 5 neither residue could be judged and the pair would be settled by score order.
def _overlapping(own_depleted):
    seqs, fc = [], []
    for i in range(8):                                   # carry both
        seqs.append(f"GGTCTCACGTAC{'ACGT'[i % 4]}{'ACGT'[(i // 4) % 4]}"); fc.append(-5.0)
    for i in range(2):                                   # GGTCTC alone, depleted
        seqs.append(f"GGTCTCTTTTTT{'AC'[i]}A"); fc.append(-5.0)
    for i in range(2):                                   # ACGTAC alone
        seqs.append(f"TTTTTTACGTAC{'AC'[i]}A"); fc.append(-5.0 if own_depleted else 0.0)
    for i in range(6):                                   # neither
        seqs.append(f"TTTTTTTTTTTT{'ACGTAC'[i]}A"); fc.append(0.0)
    return pd.Series(fc, index=seqs)

_t = pd.DataFrame({"motif": ["GGTCTC", "ACGTAC"], "pattern": ["(6, 0, 0)", "(6, 0, 0)"],
                   "fraction_depleted": [1.0, 1.0], "num_sequences": [10, 10]})
_kw = dict(log2fc_thr=-1, score_thr=0.5, min_support=5)

# its own two plasmids deplete -> ACGTAC keeps its claim
_kept, _why = filter_explained_candidates(_t, _overlapping(True), "", "", **_kw)
test_eq(sorted(_kept.motif), ["ACGTAC", "GGTCTC"])
test_eq(_why, {})

# its own two plasmids do not -> the score was borrowed from GGTCTC
_kept, _why = filter_explained_candidates(_t, _overlapping(False), "", "", **_kw)
test_eq(list(_kept.motif), ["GGTCTC"])
test_eq(_why["ACGTAC"][0], "GGTCTC")
test_eq(_why["ACGTAC"][1], 2)          # two plasmids left, well under min_support
test_eq(_why["ACGTAC"][2], 0.0)        # and they do not deplete

# An empty table and a single candidate come back untouched: there is nothing to explain with.
test_eq(len(filter_explained_candidates(pd.DataFrame(), _overlapping(True), "", "")[0]), 0)
test_eq(len(filter_explained_candidates(_t.iloc[:1], _overlapping(True), "", "")[0]), 1)

## Reporting: a motif and its reverse complement are one answer

The library is scanned on both strands, so a motif and its reverse complement always carry
**identical** statistics — same supporting sequences, same depletion score, same mean log2FC.
They describe one site, and exactly one of them should appear in the output.

Left to the order candidates happen to arrive in, which one appears is a coin toss: the same site
comes back as `GAGACC` from one run and `GGTCTC` from another, and two datasets of the same strain
can disagree on the strand of every motif they find.

`canonical_motif` decides it by rule: **use the spelling REBASE uses**, so results line up with
the literature and with enzyme names people recognise (`GGTCTC` is BsaI / Eco31I). For motifs
REBASE does not know — most of what a discovery screen finds — fall back to the alphabetically
first strand. Arbitrary, but identical on every run and every machine.

This is not cosmetic. Without a rule, one site can be written two ways in the same piece of work —
`GAGACC` (BsaI) in one place and `GGTCTC` (Eco31I) in another. Those are isoschizomers: one site,
two spellings, differing only in which strand the tool happened to emit.

### Is the depletion one population or two?

A real site, strong or weak, affects the plasmids that carry it: the distribution of their
log2FC is shifted, and it is one population. A motif that is really a shadow of another site is
a **mixture** — some of its plasmids carry the real site and are destroyed, the rest carry
nothing and are untouched — so its distribution is bimodal with a hole in the middle.

The bimodality coefficient summarises that in one number. The conventional benchmark is
5/9 ≈ 0.556, the value a uniform distribution takes; above it a distribution is more
bimodal than uniform. Measured on known cases:

| | BC |
|---|---|
| shadows of `CACNNNNGTAY` | 0.647, 0.666, 0.667 |
| 381A's one real call | 0.423 |
| real strong sites | 0.349, 0.361 |
| CFT073, a weak system | 0.250 |
| BREX in *E. coli* HS | 0.236 |

The benchmark sits in the gap with margin on both sides, and BREX is not flagged despite having
the broadest distribution of any real call — which was the thing to check, since BREX depletes
weakly with many escapers.

This is **independent of significance**. A shadow is highly significant (q ≈ 0) and bimodal; a
weak real site is significant and unimodal; a chance call is neither. The two together say more
than either alone, so both are reported.

In [46]:
#| export
def bimodality_coefficient(values):
    """Sarle's bimodality coefficient: (skew^2 + 1) / (kurtosis + 3(n-1)^2/((n-2)(n-3))).

    Above 5/9 the distribution is more bimodal than a uniform one. Here that means the motif's
    plasmids fall into two groups -- destroyed and untouched -- which is the signature of a
    motif that is really a diluted version of a different site, or of something wrong with the
    data. Returns NaN below four values, where it is not defined.
    """
    v = np.asarray(values, dtype=float)
    v = v[np.isfinite(v)]
    n = len(v)
    if n < 4 or np.allclose(v, v[0]):
        return float("nan")
    g = skew(v, bias=False)
    k = kurtosis(v, bias=False, fisher=True)
    denom = k + 3.0 * (n - 1) ** 2 / ((n - 2) * (n - 3))
    return float((g ** 2 + 1.0) / denom) if denom > 0 else float("nan")


BIMODALITY_BENCHMARK = 5.0 / 9.0


def annotate_significance(results_df, log2fc_series, left_context, right_context,
                          all_pvalues=None, log2fc_thr=-1, q_threshold=0.05, encoded=None):
    """Add p_value, q_value, called and bimodality to a result table.

    `all_pvalues` are the p-values of every motif the scan tested, which is what the
    Benjamini-Hochberg correction has to be computed over -- correcting only over the handful
    that survived filtering would be meaningless.

    Nothing is removed. `called` marks the rows that clear `q_threshold`; the rest stay in the
    table so that a weak result is visible as a weak claim rather than silently absent.
    """
    if results_df is None:
        return results_df
    if results_df.empty:
        # A strain with no active system is the first thing a new user runs, so the empty
        # table must have the same columns as a full one -- otherwise `flex[flex.called]`
        # works on every strain that finds something and raises on the ones that do not.
        out = results_df.copy()
        for _c, _dt in (("p_value", float), ("q_value", float),
                        ("called", bool), ("bimodality", float), ("bimodal", bool)):
            if _c not in out.columns:
                out[_c] = pd.Series(dtype=_dt)
        return out
    out = results_df.copy()
    # The null is this sample's own background depletion rate, and the correction runs over
    # every motif the scan tested, not just the survivors. Both are in `01_utils`.
    rate = background_depletion_rate(log2fc_series, log2fc_thr)

    p = motif_pvalues(out["num_sequences"].to_numpy(),
                      out["fraction_depleted"].to_numpy(), rate)
    out["p_value"] = p
    if all_pvalues is not None and len(all_pvalues):
        # The reported motifs were tested by the scan, so their p-values are already in
        # `all_pvalues`; appending them again counted those tests twice. Only a p-value the scan
        # never produced is a new test and joins the pool. Each motif's q is then read off the
        # adjusted pool at its own p-value -- BH q-values are a non-decreasing step function of
        # p, so tied p-values share one q.
        pool = np.asarray(all_pvalues, dtype=float)
        pool = np.sort(np.concatenate([pool, p[~np.isin(p, pool)]]))
        q_pool = benjamini_hochberg(pool)
        out["q_value"] = q_pool[np.searchsorted(pool, p, side="right") - 1]
    else:
        out["q_value"] = benjamini_hochberg(p)
    out["called"] = out["q_value"] < q_threshold

    # Presence comes from the window codes, not a regex per sequence -- the same vectorized
    # path the rest of the pipeline uses. Motifs the fast path cannot encode fall back.
    motifs = out["motif"].tolist()
    if "pattern" in out.columns:
        patterns = []
        for pat in out["pattern"]:
            try:
                patterns.append(tuple(ast.literal_eval(pat)) if isinstance(pat, str) else tuple(pat))
            except (ValueError, SyntaxError):
                patterns.append(None)
    else:
        patterns = [None] * len(motifs)

    if encoded is None:
        encoded = encode_library(
            get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
    presence, handled = motif_presence_matrix(encoded, motifs, patterns)
    for j in np.flatnonzero(~handled):
        presence[:, j] = _get_filter_for_motif(
            log2fc_series, motifs[j], left_context, right_context).to_numpy()

    values = log2fc_series.to_numpy()
    out["bimodality"] = [bimodality_coefficient(values[presence[:, j]])
                         for j in range(len(motifs))]
    out["bimodal"] = out["bimodality"] > BIMODALITY_BENCHMARK

    return out.sort_values(["called", "q_value"], ascending=[False, True])

In [47]:
#| hide
# destroyed-or-untouched, the signature of a borrowed score
_two = np.concatenate([np.zeros(20), np.full(20, -5.0)])
assert bimodality_coefficient(_two) > BIMODALITY_BENCHMARK
# one shifted population, the signature of a real site
_one = np.random.default_rng(0).normal(-3, 0.5, 40)
assert bimodality_coefficient(_one) < BIMODALITY_BENCHMARK
assert np.isnan(bimodality_coefficient([1.0, 2.0, 3.0]))   # undefined below four values
assert np.isnan(bimodality_coefficient([1.0] * 10))        # and with no spread at all
_L, _R = "AAAA", "TTTT"
_seqs = ["GGTCTCGGGGGG", "GGTCTCAAAAAA", "CCCCCCAAAAAA", "CCCCCCTTTTTT"]
_fc = pd.Series([-5.0, -5.0, -0.1, -0.1], index=_seqs)
_res = pd.DataFrame({"motif": ["GGTCTC"], "pattern": ["(6, 0, 0)"],
                     "fraction_depleted": [1.0], "num_sequences": [2], "avg_log2fc": [-5.0]})
_out = annotate_significance(_res, _fc, _L, _R, log2fc_thr=-1)
for _c in ("p_value", "q_value", "called", "bimodality", "bimodal"):
    assert _c in _out.columns
# nothing is removed: a weak row stays, flagged, rather than disappearing
test_eq(len(_out), 1)
# an empty table must carry the SAME columns, so `flex[flex.called]` works on every strain
_empty = annotate_significance(_res.iloc[:0], _fc, _L, _R, log2fc_thr=-1)
for _c in ("p_value", "q_value", "called", "bimodality", "bimodal"):
    assert _c in _empty.columns

## When the pipeline should refuse to answer

A strain with no real motif is the **hard** case, not the easy one: with nothing to find, many
near-threshold candidates survive into a step that compares them pairwise. That is exactly what
a new user runs first, as a negative control.

`max_candidates` is the guard, and it **raises**. The tempting alternative — warn, and return the
unfiltered candidate list — is unsafe: that list has the same columns as a real result and is easy
to mistake for one, so a single pathological strain can contribute hundreds of rows that are not
calls at all, and anything downstream that merges motifs will happily consume them.

The candidates are still attached to the exception for inspection, and a caller processing many
strains should catch it, record that strain as "no confident call", and carry on rather than
losing the run.

In [48]:
#| export
class TooManyCandidatesError(RuntimeError):
    """Raised when the flexible-motif search produces more candidates than it will score.

    The candidate table is available as `.candidates` for inspection. A count this large
    usually means the thresholds are too loose for the sample, not that the strain has hundreds
    of sites.
    """

    def __init__(self, n_candidates, max_candidates, log2fc_thr, score_thr, min_support, candidates):
        self.n_candidates = n_candidates
        self.max_candidates = max_candidates
        self.candidates = candidates
        super().__init__(
            f"Too many candidate motifs: {n_candidates} > max_candidates={max_candidates}. "
            f"The unique-hit scoring step is O(N^2) and would not finish. This usually means the "
            f"thresholds are too permissive for this data. Try a stricter "
            f"flexible_motif_log2fc_thr (currently {log2fc_thr}, e.g. -0.8 or -1.0), "
            f"flexible_motif_score_thr (currently {score_thr}, e.g. 0.7 or 0.85), or "
            f"flexible_motif_min_support (currently {min_support}, e.g. 5 or 10). "
            f"Raise max_candidates only if you know why this strain has so many candidates. "
            f"The unfiltered candidates are on this exception as `.candidates`."
        )

In [49]:
#| hide
_e = TooManyCandidatesError(200, 150, -1, 0.5, 3, pd.DataFrame({"motif": ["GGTCTC"]}))
test_eq(_e.n_candidates, 200)
test_eq(len(_e.candidates), 1)            # the candidates ride on the exception for inspection
assert "max_candidates=150" in str(_e)
assert "flexible_motif_score_thr (currently 0.5" in str(_e)

In [50]:
#| export
def _canonicalise_flexible_motifs(df):
    """Put every motif in a flexible-motif result table on its canonical strand.

    A motif and its reverse complement have identical statistics, so rewriting the label loses
    nothing.
    """
    if df is None or df.empty or 'motif' not in df.columns:
        return df
    df = df.copy()
    flipped = df['motif'] != df['motif'].map(canonical_motif)
    df['motif'] = df['motif'].map(canonical_motif)
    # The pattern has to follow the motif. Reverse-complementing a (d1, spacer, d2) site gives
    # a (d2, spacer, d1) site, so a relabelled row whose pattern was left alone would describe
    # a string it does not hold -- and every consumer that pairs motif with pattern, such as
    # motif_presence_matrix, would silently decline to handle it.
    if 'pattern' in df.columns:
        def _mirror(p):
            try:
                d1, sp, d2 = ast.literal_eval(p) if isinstance(p, str) else tuple(p)
            except (ValueError, SyntaxError, TypeError):
                return p
            # With no spacer the site is contiguous and (k, 0, 0) is the spelling the
            # pattern list uses, so mirroring must not turn (6, 0, 0) into (0, 0, 6).
            m = (d1 + d2, 0, 0) if sp == 0 else (d2, sp, d1)
            return str(m) if isinstance(p, str) else m
        df.loc[flipped, 'pattern'] = df.loc[flipped, 'pattern'].map(_mirror)
    return df

In [51]:
#| hide
import pandas as pd

# Rewrites to the canonical strand and leaves everything else alone.
_t = pd.DataFrame({'motif': ['GAGACC', 'AACNNNNCTTT'], 'pattern': [(6, 0, 0), (3, 4, 4)],
                   'num_sequences': [6, 54], 'avg_log2fc': [-3.75, -5.02]})
_out = _canonicalise_flexible_motifs(_t)
assert list(_out.motif) == ['GGTCTC', 'AAAGNNNNGTT']
assert list(_out.num_sequences) == [6, 54]

# An empty table is returned untouched rather than exploding.
assert _canonicalise_flexible_motifs(pd.DataFrame()).empty

print('ok')

ok

## Sites that straddle the vector junction

Every plasmid reads `left_flank + insert + right_flank`, and only the insert varies. A site can
therefore fall in one of three places:

| where | consequence |
|---|---|
| **inside the insert** | random position, random subset of plasmids — the ordinary case |
| **across a junction** | the flank spells out part of the site; what is left is pinned to a fixed offset |
| **inside a flank** | present in every plasmid, no baseline to deplete against — see `03_design` |

The middle case is not a special kind of site. It is an ordinary site that the vector happens to
half spell out, and because step 2 scans the flanks along with the insert, it usually needs no
special treatment at all. B156 is the example: its site `AAACNNNNGTC` is junction-formed, with
`AAAC` supplied by the vector and only `GTC` falling in the insert.

The chain below is steps 2–5 composed by hand, with nothing else in it:

In [52]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_panel, right_panel = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_panel = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20)

def flexible_only(series, patterns, left=left_panel, right=right_panel,
                  thr=-1, score_thr=0.5, min_support=5):
    "Steps 2 and 3 composed, with no fixed-position scan anywhere."
    enc = encode_library(get_lib_seq_context(series.index.tolist(), left, right))
    hits, tested = [], []
    for p in patterns:
        kept, pv, _ = process_single_flexible_pattern(p, enc, series.tolist(),
                                                      thr, score_thr, min_support)
        tested.append(pv)
        if not kept.empty:
            hits.append(kept)
    cands = filter_redundant_patterns(pd.concat(hits, ignore_index=True), series, left, right,
                                      log2fc_thr=thr, score_thr=score_thr,
                                      min_support=min_support)
    out = annotate_significance(_canonicalise_flexible_motifs(cands), series, left, right,
                                all_pvalues=np.concatenate(tested), log2fc_thr=thr)
    return sorted(out[out.called].motif) if len(out) else []

b156 = log2fc_panel["B156_R1"]
print("every shape scanned :", flexible_only(b156, get_patterns()))

every shape scanned : ['AAACNNNNGTC', 'ACANNNNNATGG', 'ACANNNNNGTGG', 'GAACNNNNGTC']

`AAACNNNNGTC` is recovered with no help: the vector supplies `AAAC`, the scan sees it because the
flanks are part of the scanned sequence, and the site is scored like any other motif of its
pattern. **This is the normal outcome, and nothing in the first part of this notebook had to know
about junctions at all.**

Now take away the one pattern that can express it. `AAACNNNNGTC` is found as `(3, 4, 4)`; drop
that shape and the site becomes inexpressible, while remaining just as real and just as
depleting:

In [53]:
print("without (3, 4, 4)   :", flexible_only(b156, [p for p in get_patterns() if p != (3, 4, 4)]))
at_offset_4 = b156.index.str[4:7] == "GTC"
print(f"\nplasmids with GTC at offset 4: {at_offset_4.sum()}, "
      f"{(b156[at_offset_4] < -1).mean():.0%} of them depleted")

without (3, 4, 4)   : ['AAACNNNAGTC', 'AAACNNNCGTC', 'AAACNNNGGTC', 'AAACNNNNGTCA', 'AAACNNNNGTCC', 'AAACNNNNGTCG', 'AAACNNNNGTCT', 'AAACNNNTGTC', 'ACANNNNNATGG', 'ACANNNNNGTGG', 'AGACNNNNGTTC', 'CGACNNNNGTTC', 'GAACNNNAGTC', 'GAACNNNCGTC', 'GAACNNNGGTC', 'GAACNNNNGTCA', 'GAACNNNNGTCC', 'GAACNNNTGTC']

plasmids with GTC at offset 4: 385, 95% of them depleted

The two unrelated motifs are still called. The junction-formed site is simply gone — and nothing
in the output says so, even though 385 plasmids sharing the same three bases at the same offset
are 95% depleted. A real restriction system reads as absent.

That is the failure the rest of this part addresses. It is not exotic: it happens whenever a
site's architecture is outside `flexible_motif_patterns`, which is a search-space choice the user
makes and can easily get wrong.

The signature is distinctive, though — depletion locked to a **constant offset**, which an
ordinary site never produces, because an ordinary site falls wherever it falls.

## Detecting position-locked depletion

So scan for it directly: for every short motif at every offset near each end, what fraction of the
plasmids carrying it are depleted? A site inside the insert will not concentrate at one offset; a
junction-formed one can only appear at one offset, because the flank that completes it never
moves.

In [54]:
#| export
def identify_depleted_motifs_scanning_ends(log2fc_series,
                                           scan_depth_k=6,
                                           max_motif_length=4,
                                           depletion_threshold=-1,
                                           score_thr=0.85,
                                           min_sequence_support=5):
    """Motifs whose depletion is locked to a constant offset from one end of the insert.

    For every motif length up to `max_motif_length` and every offset up to `scan_depth_k` from
    each end, score the sequences carrying that exact substring at that exact offset.

    An offset is measured **from the anchoring end**, and the `anchor` column says which:
    `left` counts from the start of the insert, `right` from its end. That distinction is what
    makes the scan work on a library of ragged inserts -- an absolute index means a different
    thing in a long insert and a short one, so a right-hand motif keyed by absolute index is
    split across every length present and mostly lost below `min_sequence_support`.

    Only ACGT counts: a window containing any other character is skipped, as in the flexible
    scan. The forward strand only, because an offset is not meaningful on the other one.

    Returns one row per (motif, anchor, offset) with 'motif', 'anchor', 'position', 'length',
    'num_sequences', 'avg_log2fc' and 'fraction_depleted', keeping those with more than
    `min_sequence_support` sequences and `fraction_depleted >= score_thr`.
    """
    cols = ['motif', 'anchor', 'position', 'length', 'num_sequences',
            'avg_log2fc', 'fraction_depleted']
    if not isinstance(log2fc_series, pd.Series) or log2fc_series.empty:
        return pd.DataFrame(columns=cols)

    values = pd.to_numeric(log2fc_series, errors='coerce').to_numpy(dtype=float)
    seqs = list(log2fc_series.index)
    usable = np.array([isinstance(s, str) for s in seqs]) & np.isfinite(values)
    seqs = [s for s, ok in zip(seqs, usable) if ok]
    fc = values[usable]
    if not seqs:
        return pd.DataFrame(columns=cols)

    name = log2fc_series.name if log2fc_series.name else "input Series"
    print(f"Scanning motifs of length 1 to {max_motif_length} at offsets 0 to {scan_depth_k} "
          f"from each end, for {name}.")
    print(f"Minimum sequence support for a motif: > {min_sequence_support} "
          f"(i.e., {min_sequence_support + 1} or more)")

    width = max(len(s) for s in seqs)
    # Left-aligned, and right-aligned by padding on the LEFT with 'N'. Padding encodes to the
    # same out-of-alphabet code a non-ACGT base does, so a window that runs off a short
    # sequence is rejected by the very test that rejects an N -- no length bookkeeping.
    encodings = {'left': encode_library(seqs)[0],
                 'right': encode_library([s.rjust(width, 'N') for s in seqs])[0]}
    is_depleted = fc < depletion_threshold

    rows = []
    for length in range(1, max_motif_length + 1):
        n_codes = 4 ** length
        for anchor, arr in encodings.items():
            for offset in range(scan_depth_k + 1):
                start = offset if anchor == 'left' else arr.shape[1] - offset - length
                if start < 0 or start + length > arr.shape[1]:
                    continue
                window = arr[:, start:start + length]
                good = ~(window == 4).any(axis=1)
                if not good.any():
                    continue
                codes = np.zeros(window.shape[0], dtype=np.int64)
                for j in range(length):          # the window as a base-4 numeral
                    codes = codes * 4 + window[:, j]
                codes, kept_fc, kept_dep = codes[good], fc[good], is_depleted[good]
                n = np.bincount(codes, minlength=n_codes)
                n_dep = np.bincount(codes, weights=kept_dep, minlength=n_codes)
                fc_sum = np.bincount(codes, weights=kept_fc, minlength=n_codes)
                enough = np.flatnonzero(n > min_sequence_support)
                if not len(enough):
                    continue
                selected = enough[(n_dep[enough] / n[enough]) >= score_thr]
                if not len(selected):
                    continue
                for motif, cnt, dep, total in zip(decode_motif_codes(selected, (length, 0, 0)),
                                                  n[selected], n_dep[selected], fc_sum[selected]):
                    rows.append({'motif': motif, 'anchor': anchor, 'position': offset,
                                 'length': length, 'num_sequences': int(cnt),
                                 'avg_log2fc': float(total / cnt),
                                 'fraction_depleted': float(dep / cnt)})
    if not rows:
        print("No motifs met the support and score thresholds.")
        return pd.DataFrame(columns=cols)
    return (pd.DataFrame(rows, columns=cols)
            .sort_values(['fraction_depleted', 'avg_log2fc', 'num_sequences'],
                         ascending=[False, True, False])
            .reset_index(drop=True))

In [55]:
depleted_motifs_df=identify_depleted_motifs_scanning_ends(log2fc_df["JJ1886_T0"])
depleted_motifs_df.head(10)

Scanning motifs of length 1 to 4 at offsets 0 to 6 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)

  motif anchor  position  length  num_sequences  avg_log2fc  fraction_depleted
0  AAAG  right         4       4             42   -5.076919                1.0
1  GTGC   left         0       4             42   -4.808616                1.0
2  GTGG   left         0       4             53   -4.775047                1.0
3   GTG   left         0       3            187   -4.764500                1.0
4  GTGT   left         0       4             40   -4.751248                1.0
5  GTGA   left         0       4             52   -4.728312                1.0

### Trimming to the core motif

Having found `GTG` at offset 0, the scan will also find `GTGA`, `CGTGA` and so on at the same
offset. Only one of them is worth keeping.

The rule: **keep the longer motif only if the extra base earns its place**, i.e. raises the
depletion fraction by more than a margin. Otherwise the shorter core stands.

In practice, on a real fixed-position call, the core is already at or near 1.0 — the step's own
`score_thr` of 0.85 guarantees it is high — so no extension can beat it by the margin, and the
rule reduces to *prefer the shortest description that clears the threshold*. **That is the
behaviour these motifs want**: a fixed motif's job is to name a set of plasmids for step 4 to
explain with, and the shortest description names the most of them. A longer, more specific motif
would explain fewer candidates and let more shadows through.

The hidden cell below checks all four cases on hand-made tables where the right answer is
obvious, including the one that is easiest to get backwards: a longer motif that scores *worse*
than the core it contains — `GTG` at 0.90 against `GTGA` at 0.40 — must leave the core standing.

In [56]:
#| export
def _contains_at(core, candidate):
    """Where `core` sits inside `candidate`, or None -- both given as (motif, anchor, offset).

    Containment is only meaningful within one anchor, and the arithmetic differs between them:
    a left-anchored motif grows rightwards from its offset, a right-anchored one grows
    leftwards, so the same core sits at a different index in the longer string.
    """
    (c_motif, c_anchor, c_pos), (k_motif, k_anchor, k_pos) = core, candidate
    if c_anchor != k_anchor or len(c_motif) >= len(k_motif):
        return None
    if c_anchor == 'left':
        expected = c_pos - k_pos
    else:
        expected = len(k_motif) + k_pos - len(c_motif) - c_pos
    if 0 <= expected <= len(k_motif) - len(c_motif) and \
            k_motif[expected:expected + len(c_motif)] == c_motif:
        return expected
    return None


def filter_to_core_motifs(depleted_motifs_df, score_improvement_margin=0.05):
    """Reduce each family of nested fixed-position motifs to its core.

    Having found `GTG` at an offset, the scan also finds `GTGA` and `CGTGA` at the same place.
    A longer motif is kept only if the extra base **earns its place** -- raises the depletion
    fraction by more than `score_improvement_margin`. On a real call the core is already at or
    near 1.0, so in practice this prefers the shortest description that clears the threshold,
    which is what an explainer wants: the shortest one names the most plasmids.
    """
    if depleted_motifs_df.empty:
        return pd.DataFrame(columns=depleted_motifs_df.columns)

    sorted_df = depleted_motifs_df.sort_values(
        by=['length', 'fraction_depleted', 'motif'],
        ascending=[True, False, True]).reset_index(drop=True)
    if 'anchor' not in sorted_df.columns:
        sorted_df = sorted_df.assign(anchor='left')

    cores = []
    for _, candidate in sorted_df.iterrows():
        key = (candidate['motif'], candidate.get('anchor', 'left'), int(candidate['position']))
        subsumed = False
        for core in cores:
            if _contains_at((core['motif'], core.get('anchor', 'left'),
                             int(core['position'])), key) is None:
                continue
            if not candidate['fraction_depleted'] > core['fraction_depleted'] + score_improvement_margin:
                subsumed = True
                break
        if not subsumed:
            cores.append(candidate.to_dict())
    return pd.DataFrame(cores) if cores else pd.DataFrame(columns=depleted_motifs_df.columns)

In [57]:
#| hide
# filter_to_core_motifs on hand-made tables, where the right answer is obvious.
def _row(motif, pos, frac, anchor="left"):
    return dict(motif=motif, anchor=anchor, position=pos, length=len(motif),
                fraction_depleted=frac, num_sequences=100, avg_log2fc=-2.0)

# The extra base adds nothing (0.90 -> 0.91, margin 0.05): the core is the real motif.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 0, 0.91)])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG"])

# The extra base matters (0.50 -> 0.95): keep both.
_t = pd.DataFrame([_row("GTG", 0, 0.50), _row("GTGA", 0, 0.95)])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG", "GTGA"])

# The longer motif is WORSE (0.90 -> 0.40): the extra base cannot earn its place by making
# things worse, so the core stands.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 0, 0.40)])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG"])

# Same sequence, different offset: not nested, so both stand.
_t = pd.DataFrame([_row("GTG", 0, 0.90), _row("GTGA", 5, 0.91)])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG", "GTGA"])

# A right-anchored motif grows LEFTWARDS from its offset, so AGTC@R0 contains GTC@R0 -- the
# nesting arithmetic is not the same as on the left, and getting it wrong would keep both.
_t = pd.DataFrame([_row("GTC", 0, 0.90, "right"), _row("AGTC", 0, 0.91, "right")])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTC"])

# Containment is only meaningful within one anchor: these two are unrelated.
_t = pd.DataFrame([_row("GTG", 0, 0.90, "left"), _row("GTGA", 0, 0.91, "right")])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG", "GTGA"])

# A table with no anchor column is read as left-anchored rather than refused.
_t = pd.DataFrame([dict(motif="GTG", position=0, length=3, fraction_depleted=0.90,
                        num_sequences=100, avg_log2fc=-2.0),
                   dict(motif="GTGA", position=0, length=4, fraction_depleted=0.91,
                        num_sequences=100, avg_log2fc=-2.0)])
test_eq(sorted(filter_to_core_motifs(_t, score_improvement_margin=0.05).motif), ["GTG"])
print("ok")

ok

In [58]:
depleted_motifs_df=filter_to_core_motifs(depleted_motifs_df)
depleted_motifs_df.head(10)

  motif anchor  position  length  num_sequences  avg_log2fc  fraction_depleted
0   GTG   left         0       3            187   -4.764500                1.0
1  AAAG  right         4       4             42   -5.076919                1.0

### Why these plasmids are not set aside

The plasmids whose insert completes a junction-formed site are **kept** in this scan. That is worth justifying, because the opposite is tempting: those
plasmids all share a constant flank, so they look like a special population that ought to be
handled separately before the scan ever sees them.

They should not be, for three reasons.

**They are the site's evidence.** On B156, whose site `AAACNNNNGTC` is junction-formed, the
junction-formed carriers are 43% of the true site's total support. Holding them back asks the
scan to find a site with nearly half its evidence removed.

**Removing them is undirected.** They deplete at 95%, so taking them out deflates the score of
every candidate that overlaps them — real and spurious alike. On B156 it pushes 26 candidates
below threshold and at the same time creates two that would not otherwise appear at all.

**What it would remove, step 4 removes properly.** Every one of those 26 candidates is explained
away by step 4 in any case. They are not many descriptions of one set of plasmids — their
pairwise Jaccard overlap is a median of 0.00 — but ordinary borrowed-score shadows: `AACTNNTGTC`,
`AACGNNTGTC`, `AACANNTGTC`, mis-spaced versions of the real site. That is exactly what step 4 is
for, and it works directionally, so the real site survives.

### The case this leaves open, and how it is covered

If a junction-formed site's architecture is **not in `get_patterns()`** — a spacer longer than
eight, say — then no flexible candidate can describe it. Nothing in the candidate set accounts
for the junction plasmids, and every candidate overlapping them borrows depletion that has no
owner.

The failure this produces is quiet rather than loud: the plasmids are depleted, nothing explains
them, and nothing is reported. The fixed-position motifs close the gap as step 4 explainers — a
candidate whose depletion is fully accounted for by the fixed motif is dropped — and because the
fixed motif then has no owner of its own, the pipeline **says so** instead of leaving strong
position-locked depletion unmentioned.

This is demonstrated on real data at the end of the notebook, once the pipeline is assembled:
B156's site is junction-formed, so dropping the single pattern that can express it reproduces the
case exactly.

## Putting it to work

A fixed-position motif is a string at a known offset, so asking which plasmids carry it is a slice
comparison — no search, no pattern. The pipeline uses that to raise a **warning**: a
fixed-position motif that nothing reported explains is the case demonstrated above, and the
pipeline says so rather than staying quiet.

It never removes a sequence.

**These motifs are deliberately not canonicalised**, unlike the reported ones. This table records
a motif *at an offset*, and an offset is only meaningful on one strand: `GTG` at position 0 is not
interchangeable with `CAC` at position 0. The two tables therefore use different conventions,
which is worth knowing when reading them side by side.

## When a fixed-position motif has no owner

A fixed-position motif names a set of plasmids that something destroyed. The question worth
asking at the end of a run is whether **anything reported explains it**.

If a site is junction-formed and its architecture *is* in the scanned pattern space, the
flexible scan finds it, and that motif accounts for the fixed motif's plasmids — the two are
descriptions of the same thing. So a fixed motif with no owner means one of:

- the site's shape was never tested — a spacer or half-site length outside `get_patterns()`
- the depletion at that offset is real but is not a recognition site at all

Either way it is something the user has to know, because the pipeline has just seen strong,
position-locked depletion and reported nothing for it. Silently dropping it is the failure mode
this check exists to prevent, and the evidence is printed so the call can be judged.

In [59]:
#| export
def unexplained_fixed_motifs(fixed_motifs_df, reported_motifs_df, log2fc_series,
                             left_context, right_context, log2fc_thr=-1,
                             score_thr=0.7, min_support=3, encoded=None):
    """Fixed-position motifs whose depletion no reported flexible motif accounts for.

    A fixed motif `F` is explained by a reported motif `M` when the plasmids carrying `F`
    but not `M` no longer deplete. One that survives every reported motif has no owner.

    Returns a DataFrame with the fixed motif's own evidence, empty when everything is
    accounted for.
    """
    empty = pd.DataFrame(columns=['motif', 'anchor', 'position', 'length',
                                  'num_sequences', 'fraction_depleted', 'avg_log2fc'])
    if fixed_motifs_df is None or len(fixed_motifs_df) == 0:
        return empty

    fixed_pres = fixed_motif_presence(log2fc_series, fixed_motifs_df)
    fc = log2fc_series.to_numpy()

    if reported_motifs_df is None or len(reported_motifs_df) == 0:
        rep = np.zeros((len(fc), 0), dtype=bool)
    else:
        patterns = []
        for p in reported_motifs_df.get('pattern', [None] * len(reported_motifs_df)):
            try:
                patterns.append(tuple(ast.literal_eval(p)) if isinstance(p, str) else tuple(p))
            except (ValueError, SyntaxError, TypeError):
                patterns.append(None)
        if encoded is None:
            encoded = encode_library(
                get_lib_seq_context(log2fc_series.index.tolist(), left_context, right_context))
        rep, handled = motif_presence_matrix(
            encoded, reported_motifs_df['motif'].tolist(), patterns)
        for j in np.flatnonzero(~handled):
            rep[:, j] = _get_filter_for_motif(
                log2fc_series, reported_motifs_df['motif'].iloc[j],
                left_context, right_context).to_numpy()

    rows = []
    for j, row in enumerate(fixed_motifs_df.itertuples()):
        owned = False
        for k in range(rep.shape[1]):
            alone = fixed_pres[:, j] & ~rep[:, k]
            n = int(alone.sum())
            still = float((fc[alone] < log2fc_thr).mean()) if n else 0.0
            if n < min_support or still < score_thr:
                owned = True
                break
        if not owned:
            carriers = fc[fixed_pres[:, j]]
            rows.append(dict(motif=row.motif, anchor=getattr(row, 'anchor', 'left'),
                             position=int(row.position),
                             length=int(row.length), num_sequences=len(carriers),
                             fraction_depleted=float((carriers < log2fc_thr).mean())
                             if len(carriers) else 0.0,
                             avg_log2fc=float(carriers.mean()) if len(carriers) else float('nan')))
    return pd.DataFrame(rows) if rows else empty


def _warn_unexplained_fixed(fixed_motifs_df, reported_motifs_df, log2fc_series,
                            left_context, right_context, log2fc_thr, score_thr, min_support,
                            encoded=None):
    """Warn, with evidence, about position-locked depletion that nothing reported explains."""
    orphans = unexplained_fixed_motifs(fixed_motifs_df, reported_motifs_df, log2fc_series,
                                       left_context, right_context, log2fc_thr=log2fc_thr,
                                       score_thr=score_thr, min_support=min_support,
                                       encoded=encoded)
    if len(orphans) == 0:
        return orphans
    lines = [f"    {r.motif} at offset {r.position} from the "
             f"{getattr(r, 'anchor', 'left')}: n={r.num_sequences}, "
             f"score={r.fraction_depleted:.2f}, mean log2FC={r.avg_log2fc:.2f}"
             for r in orphans.itertuples()]
    warnings.warn(
        "Position-locked depletion that no reported motif explains:\n" + "\n".join(lines) +
        "\nA junction-formed site whose shape IS in the scanned pattern space is normally "
        "found by the flexible scan, which then accounts for these plasmids. Consider widening "
        "flexible_motif_patterns (a longer spacer or a different half-site length), or check "
        "whether something other than a recognition site depletes at this offset.",
        stacklevel=3)
    return orphans

In [60]:
#| hide
_L, _R = "AAAA", "TTTT"
_seqs = ["GGTCTCGGGGGG", "GGTCTCAAAAAA", "CCCCCCAAAAAA", "CCCCCCTTTTTT"]
_fc = pd.Series([-5.0, -5.0, -0.1, -0.1], index=_seqs)
_fx = pd.DataFrame([dict(motif="GGT", position=0, length=3, fraction_depleted=1.0,
                         num_sequences=2, avg_log2fc=-5.0)])
# the reported motif accounts for every plasmid carrying the fixed one -> nothing to flag
_rep = pd.DataFrame({"motif": ["GGTCTC"], "pattern": ["(6, 0, 0)"]})
test_eq(len(unexplained_fixed_motifs(_fx, _rep, _fc, _L, _R, log2fc_thr=-1,
                                     score_thr=0.5, min_support=1)), 0)
# with nothing reported, the same fixed motif has no owner and is flagged, with its evidence
_orphan = unexplained_fixed_motifs(_fx, pd.DataFrame(), _fc, _L, _R, log2fc_thr=-1,
                                   score_thr=0.5, min_support=1)
test_eq(len(_orphan), 1)
test_eq(_orphan.motif.iloc[0], "GGT")
test_eq(int(_orphan.num_sequences.iloc[0]), 2)
test_eq(float(_orphan.fraction_depleted.iloc[0]), 1.0)

In [61]:
#| export

def find_restricted_motifs(log2fc_series,
                           left_context_str,
                           right_context_str,
                           n_jobs=1,
                           fixed_motif_scan_depth_k=6,
                           fixed_motif_max_length=4,
                           fixed_motif_depletion_thr=None,
                           fixed_motif_score_thr=0.85,
                           fixed_motif_min_support=5,
                           core_motif_score_margin=0.05,
                           flexible_motif_patterns=None,
                           flexible_motif_log2fc_thr=-1,
                           flexible_motif_min_support=5,
                           flexible_motif_score_thr=0.5,
                           max_candidates=150,
                           q_threshold=0.05,
                           encoded_library=None
                           ):
    """
    Full pipeline to identify fixed-position core motifs and then
    position-independent motifs in the remaining sequences.

    The fixed-position scan runs first; it does not remove any sequence. Every flexible
    pattern is then scanned over the whole library with its flanking context, the two-way
    filter_redundant_patterns is applied once over all candidates, step 4 drops candidates
    whose depletion a stronger motif -- flexible or fixed-position -- already accounts for, and
    the survivors are rescored on unique hits.

    A fixed motif at a sequence end is usually a flexible motif straddling the library context
    (JJ1886's GTG at position 0 is ATACNNNNGTG, with ATAC in the left context), so the flexible
    scan finds it directly. One that no reported motif explains is raised as a warning, because
    it means the site's shape was probably never tested.

    Args:
        n_jobs (int): processes used to scan the flexible patterns. 1 (default) runs in this
            process. With the vectorized scan a pattern takes about a second on a 30k-sequence
            library, so more is rarely worth the startup cost.
        flexible_motif_min_support (int): minimum plasmids for a motif to be considered. The
            default of 5 is set by a permutation test rather than by taste: on the smaller
            example library, motifs with 3-4 supporting plasmids arise by chance about once per
            scan (0.8 measured over 20 permutations, 0.60 expected analytically), and none at
            all arise at 5 or above. It cannot go higher than about 6 without deleting a real
            call -- BsaI on JJ1886 has only 6 supporting plasmids there.
        fixed_motif_depletion_thr (float): log2FC below which a sequence counts as depleted in
            the fixed-position scan. Defaults to `flexible_motif_log2fc_thr`, so the two scans
            agree on what depletion means; pass a value to decouple them.
        q_threshold (float): a motif is marked `called` when its Benjamini-Hochberg q-value,
            computed against this sample's own background depletion rate and over every motif
            the scan tested, falls below this. Motifs that do not clear it are still returned,
            flagged, rather than dropped.
        flexible_motif_patterns (list): the architectures to search, as `(d1, spacer, d2)`.
            Defaults to `get_patterns()`. Each is rewritten to its `canonical_pattern` and
            duplicates dropped, so `(4, 4, 3)` is searched as `(3, 4, 4)` and never twice.
        flexible_motif_score_thr (float): a candidate needs at least this fraction of its
            plasmids depleted. Default 0.5, the value used in the paper.
        encoded_library (tuple): `encode_library(get_lib_seq_context(log2fc_series.index,
            left_context_str, right_context_str))`, if the caller already has it. Strains
            screened with the same library and flanks share it, so a panel encodes it once.
            It must describe exactly `log2fc_series.index`, in order.
        max_candidates (int): Safety limit on the number of candidate flexible
            motifs before entering the O(N²) update_motif_scores_from_unique_hits
            step.  If more candidates are found the function aborts that step,
            prints guidance on tightening thresholds, and returns the raw
            (unfiltered) candidates so the caller can inspect them.
            Default: 150.
    """
    # The fixed scan's threshold tracks the flexible one unless the caller sets it, so both
    # scans agree on what "depleted" means. Pinned independently, it would go blind whenever a
    # caller lowers flexible_motif_log2fc_thr for a weakly-interfering system -- and step 4
    # would lose its explainer in exactly the permissive regime where borrowed scores are most
    # common.
    if fixed_motif_depletion_thr is None:
        fixed_motif_depletion_thr = flexible_motif_log2fc_thr

    print("--- Starting Fixed-Position Motif Analysis (on original short sequences) ---")
    depleted_fixed_motifs_df = identify_depleted_motifs_scanning_ends(
        log2fc_series,
        scan_depth_k=fixed_motif_scan_depth_k,
        max_motif_length=fixed_motif_max_length,
        depletion_threshold=fixed_motif_depletion_thr,
        score_thr=fixed_motif_score_thr,
        min_sequence_support=fixed_motif_min_support
    )
    core_fixed_motifs_df = filter_to_core_motifs(
        depleted_fixed_motifs_df,
        score_improvement_margin=core_motif_score_margin
    )
    del depleted_fixed_motifs_df

    if core_fixed_motifs_df.empty:
        print("No core motifs found at fixed positions.")
    else:
        print(f"Found {len(core_fixed_motifs_df)} core motifs at fixed positions:")
        for _, row in core_fixed_motifs_df.iterrows():
            print(f"  - Fixed Motif: {row['motif']}, Pos: {row['position']}, Len: {row['length']}, FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    print("\n--- Starting Position-Independent Motif Analysis (with context) ---")
    # This scan does NOT consume the fixed-position result: it runs on the full library, from
    # the same log2FC table the fixed scan read. The two are independent branches and meet
    # only at step 4, where a fixed-position motif may explain a flexible candidate away.
    if log2fc_series.empty:
        print("The input series is empty; there is nothing to scan.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
        # No pattern was scanned, so no test was performed: an empty p-value set, not the
        # not-yet-assigned tested_pvalues from the scan below.
        _final = annotate_significance(
            _canonicalise_flexible_motifs(flexible_motifs_results_df),
            log2fc_series, left_context_str, right_context_str,
            all_pvalues=np.array([]), log2fc_thr=flexible_motif_log2fc_thr,
            q_threshold=q_threshold)
        _warn_unexplained_fixed(core_fixed_motifs_df, _final, log2fc_series,
                                left_context_str, right_context_str,
                                flexible_motif_log2fc_thr, flexible_motif_score_thr,
                                flexible_motif_min_support)
        return core_fixed_motifs_df, _final

    # The library is encoded once and every step below reads it.
    if encoded_library is None:
        encoded_library = encode_library(get_lib_seq_context(
            log2fc_series.index.tolist(), left_context_str, right_context_str))
    elif encoded_library[0].shape[0] != len(log2fc_series):
        raise ValueError(
            f"encoded_library holds {encoded_library[0].shape[0]} sequences but log2fc_series "
            f"has {len(log2fc_series)}; it must encode exactly this series' index, in order, "
            f"with these flanks.")
    fc_values_for_flexible_analysis = log2fc_series.to_numpy(dtype=float)

    cumulative_flexible_motifs_df = pd.DataFrame()

    if flexible_motif_patterns is None:
        flexible_motif_patterns = get_patterns()
    if not isinstance(flexible_motif_patterns, list):
        print("Warning: flexible_motif_patterns should be a list. Wrapping it in a list.")
        flexible_motif_patterns = [flexible_motif_patterns]

    # A pattern and its mirror find the same sites (the scan reads both strands), and a gapless
    # pattern is one run however it is split, so each is searched once, in canonical form.
    rewritten = sorted({(tuple(p), canonical_pattern(p)) for p in flexible_motif_patterns
                        if tuple(p) != canonical_pattern(p)})
    for p, c in rewritten:
        print(f"Pattern {p} is searched as {c}: the same sites, read on the other strand.")
    flexible_motif_patterns = sorted({canonical_pattern(p) for p in flexible_motif_patterns},
                                     key=lambda x: (x[0] + x[2], x[1], x))

    if n_jobs == 1:
        per_pattern = [
            process_single_flexible_pattern(
                p, encoded_library, fc_values_for_flexible_analysis,
                flexible_motif_log2fc_thr, flexible_motif_score_thr,
                flexible_motif_min_support)
            for p in tqdm(flexible_motif_patterns, desc="Scanning patterns")
        ]
    else:
        worker = functools.partial(
            process_single_flexible_pattern,
            encoded_library=encoded_library,
            fc_values_for_flexible_analysis=fc_values_for_flexible_analysis,
            flexible_motif_log2fc_thr=flexible_motif_log2fc_thr,
            flexible_motif_score_thr=flexible_motif_score_thr,
            flexible_motif_min_support=flexible_motif_min_support,
            # Each worker scans single-threaded: n_jobs processes each starting numba's
            # thread pool would ask for n_jobs x cores at once, and a forked child never has
            # to touch a thread pool its parent may have started.
            parallel=False)
        with Pool(processes=n_jobs) as pool:
            # imap preserves pattern order, so the result does not depend on which worker
            # finishes first.
            per_pattern = list(tqdm(pool.imap(worker, flexible_motif_patterns),
                                    total=len(flexible_motif_patterns),
                                    desc="Scanning patterns"))

    tested_pvalues = (np.concatenate([pv for _, pv, _ in per_pattern]) if per_pattern
                      else np.array([]))
    hits = [df for df, _, _ in per_pattern if not df.empty]
    # Step 3 scores variants from the same counts; a pattern step 2 scanned is never rescanned.
    totals = {p: t for p, (_, _, t) in zip(flexible_motif_patterns, per_pattern)}
    if hits:
        # Every pattern is scanned first and the redundancy filter runs once over all
        # candidates, rather than after each pattern. Filtering incrementally made the
        # outcome depend on the order patterns were scanned in; with the filter now
        # order-independent the two agree, and doing it once is simpler and faster.
        cumulative_flexible_motifs_df = filter_redundant_patterns(
            pd.concat(hits, ignore_index=True), log2fc_series,
            left_context_str, right_context_str,
            log2fc_thr=flexible_motif_log2fc_thr,
            score_thr=flexible_motif_score_thr,
            min_support=flexible_motif_min_support,
            encoded=encoded_library, totals=totals,
        )
        print(f"{sum(len(h) for h in hits)} candidate(s) across all patterns; "
              f"{len(cumulative_flexible_motifs_df)} remain after redundancy filtering.")

    if cumulative_flexible_motifs_df.empty:
        print(f"\nNo flexible motifs found with support >= {flexible_motif_min_support} and score >= {flexible_motif_score_thr} for any provided pattern.")
        flexible_motifs_results_df = pd.DataFrame(columns=['motif', 'pattern', 'fraction_depleted', 'num_sequences', 'avg_log2fc'])
    else:
        cumulative_flexible_motifs_df, _explained = filter_explained_candidates(
            cumulative_flexible_motifs_df, log2fc_series, left_context_str, right_context_str,
            log2fc_thr=flexible_motif_log2fc_thr, score_thr=flexible_motif_score_thr,
            min_support=flexible_motif_min_support,
            fixed_motifs_df=core_fixed_motifs_df, encoded=encoded_library)
        if _explained:
            print(f"{len(_explained)} candidate(s) whose score was borrowed:")
            for _m, (_by, _n, _s) in sorted(_explained.items()):
                print(f"    {_m} <- {_by} (without them: n={_n}, score={_s:.2f})")

        n_candidates = len(cumulative_flexible_motifs_df)

        if n_candidates > max_candidates:
            raise TooManyCandidatesError(
                n_candidates,
                max_candidates,
                flexible_motif_log2fc_thr,
                flexible_motif_score_thr,
                flexible_motif_min_support,
                cumulative_flexible_motifs_df,
            )

        flexible_motifs_results_df = cumulative_flexible_motifs_df

        # Canonicalise before reporting, so the names printed here are the names in the
        # returned table. A motif and its reverse complement are the same site, and the scan
        # may have found either; a user who reads GAGACC in the log and then looks for it in
        # the results would not find it, because the result says GGTCTC.
        flexible_motifs_results_df = _canonicalise_flexible_motifs(flexible_motifs_results_df)

        print(f"\n{len(flexible_motifs_results_df)} motifs remaining:")
        if flexible_motifs_results_df.empty:
            print("No core flexible motifs remained after filtering.")
        else:
            for _, row in flexible_motifs_results_df.iterrows():
                print(f"{row['motif']} (from pattern {row['pattern']}), FracDep: {row['fraction_depleted']:.2f}, AvgFC: {row['avg_log2fc']:.2f}, N: {row['num_sequences']}")

    final_table = annotate_significance(
            flexible_motifs_results_df,
            log2fc_series, left_context_str, right_context_str,
            all_pvalues=tested_pvalues, log2fc_thr=flexible_motif_log2fc_thr,
            q_threshold=q_threshold, encoded=encoded_library)
    _warn_unexplained_fixed(core_fixed_motifs_df, final_table, log2fc_series,
                            left_context_str, right_context_str,
                            flexible_motif_log2fc_thr, flexible_motif_score_thr,
                            flexible_motif_min_support, encoded=encoded_library)
    return core_fixed_motifs_df, final_table

In [62]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)

patterns = get_patterns()
core_fixed_motifs_df, flexible_motifs_df = find_restricted_motifs(log2fc_df["JJ1886_T0"], 
                        left,
                        right, 
                        fixed_motif_scan_depth_k=6,
                        fixed_motif_max_length=4,
                        fixed_motif_depletion_thr=-1,
                        fixed_motif_score_thr=0.85,
                        fixed_motif_min_support=5,
                        core_motif_score_margin=0.05,
                        flexible_motif_patterns=[(6,0,0),(7,0,0),(4,2,4),(3,4,4),(4,3,4),(4,4,4)],
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_min_support=3,
                        flexible_motif_score_thr=0.7
                        )

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Scanning motifs of length 1 to 4 at offsets 0 to 6 from each end, for JJ1886_T0.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 2 core motifs at fixed positions:
  - Fixed Motif: GTG, Pos: 0, Len: 3, FracDep: 1.00, AvgFC: -4.76, N: 187
  - Fixed Motif: AAAG, Pos: 4, Len: 4, FracDep: 1.00, AvgFC: -5.08, N: 42

--- Starting Position-Independent Motif Analysis (with context) ---
92 candidate(s) across all patterns; 57 remain after redundancy filtering.
47 candidate(s) whose score was borrowed:
    AAAGNNCCGT <- AACNNNNCTTT + 3 more (without them: n=1, score=0.00)
    AAAGNNCTGT <- AACNNNNCTTT + 1 more (without them: n=3, score=0.33)
    AAAGNNGGGT <- AACNNNNCTTT + 1 more (without them: n=0, score=0.00)
    AAAGNNGTGT <- AACNNNNCTTT + 1 more (without them: n=2, score=0.50)
    AAAGNNTTGT <- AACNNNNCTTT + 1 more (without them: n=3, score=0.33)
    AAGGNNNGTTC <- AACNNNNCTTT (without them: n=2, score=0.50)
    AAGTNNNGTTA <- AACNNNNCTTT + 2 more (without them: n=1, score=0.00)
    AAGTNNNGTTC <- AACNNNNCTTT + 3 more (without them: n=1, score=0.00)
    AAGTNNNNTTAA <- AACNNNNCTTT (without them: n=3, score=0.67)
    AATANNNNTGTG <- CACNNNNGTAT + 5 more (without them: n=2, score=0.00)
    ACACNNNAGTA <- CACNNNNGTAT + 1 more (without them: n=2, score=0.00)
    ACACNNNCGTA <- CACNNNNGTAC (without them: n=1, score=0.00)
    ACACNNTAGT <- CACNNNNGTAT + 1 more (without them: n=0, score=0.00)
    ACCCNNACCT <- AGGTNNNGGTC + 2 more (without them: n=1, score=0.00)
    ACTANNGTGA <- CACNNNNGTAT + 1 more (without them: n=0, score=0.00)
    ACTANNGTGC <- CACNNNNGTAT + 3 more (without them: n=1, score=0.00)
    ACTANNGTGG <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    AGAGNNCTCA <- GAGACC + 1 more (without them: n=0, score=0.00)
    CACANNAGTA <- CACNNNNGTAT + 6 more (without them: n=2, score=0.00)
    CACCNNCGTA <- CACNNNNGTAC + 1 more (without them: n=1, score=0.00)
    CACGNNNNTACC <- CACNNNNGTAT + 4 more (without them: n=3, score=0.67)
    CAGANNNCTCA <- GAGACC + 1 more (without them: n=1, score=0.00)
    CAGANNTCTC <- GAGACC + 1 more (without them: n=0, score=0.00)
    CCGANNNCACA <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    CCTCNNCCTC <- GAGACC + 1 more (without them: n=1, score=0.00)
    CCTGAGA <- GAGACC + 1 more (without them: n=2, score=0.50)
    CCTGNNNCCTC <- GAGACC + 2 more (without them: n=1, score=0.00)
    CCTTNNNACAC <- CACNNNNGTAT + 1 more (without them: n=0, score=0.00)
    CGCCNNNNCACA <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    CTGANNCCTC <- GAGACC + 1 more (without them: n=1, score=0.00)
    CTGGNNNNCACA <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    GAAGNNNACAC <- CACNNNNGTAT + 1 more (without them: n=2, score=0.50)
    GACCNNGACC <- AGGTNNNGGTC + 1 more (without them: n=0, score=0.00)
    GACTNNNACAC <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    GCAGNNNNCTCA <- GAGACC + 1 more (without them: n=0, score=0.00)
    GCGGNNNNCACA <- CACNNNNGTAT + 3 more (without them: n=0, score=0.00)
    GGCANNNNCACA <- CACNNNNGTAT + 2 more (without them: n=0, score=0.00)
    GTACNNACGA <- CACNNNNGTAC (without them: n=3, score=0.67)
    GTGTNNCCAA <- CACNNNNGTAT + 1 more (without them: n=1, score=0.00)
    GTGTNNNNATAA <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    GTGTNNNNCGGA <- CACNNNNGTAT + 2 more (without them: n=3, score=0.67)
    TACGNNNGTGA <- CACNNNNGTAC + 1 more (without them: n=2, score=0.00)
    TACNNNNGTGC <- CACNNNNGTAT + 4 more (without them: n=1, score=0.00)
    TGCTNNNCACA <- CACNNNNGTAT + 1 more (without them: n=1, score=0.00)
    TGGCNNNCACA <- CACNNNNGTAT + 2 more (without them: n=2, score=0.00)
    TGTGNNNATAA <- CACNNNNGTAT + 2 more (without them: n=1, score=0.00)
    TGTGNNNNTAAA <- CACNNNNGTAT + 2 more (without them: n=0, score=0.00)

10 motifs remaining:
GGTCTC (from pattern (6, 0, 0)), FracDep: 1.00, AvgFC: -4.31, N: 9
AAAGNNNNGTT (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -5.16, N: 63
ATACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -4.76, N: 192
CACNNNNGTAC (from pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -5.24, N: 20
CCACNNNTGTA (from pattern (4, 3, 4)), FracDep: 1.00, AvgFC: -4.08, N: 3
CCACNNNAGTA (from pattern (4, 3, 4)), FracDep: 1.00, AvgFC: -4.85, N: 55
AGGTNNNGGTC (from pattern (4, 3, 4)), FracDep: 1.00, AvgFC: -1.08, N: 3
AGAGNNNNCACG (from pattern (4, 4, 4)), FracDep: 1.00, AvgFC: -3.60, N: 3
GACCNNNNCCTC (from pattern (4, 4, 4)), FracDep: 1.00, AvgFC: -4.36, N: 4
GAACNNNNGCCC (from pattern (4, 4, 4)), FracDep: 1.00, AvgFC: -3.17, N: 3

Scanning patterns: 100%|##########| 6/6 [00:00<00:00, 37.84it/s]

In [63]:
core_fixed_motifs_df

  motif anchor  position  length  num_sequences  avg_log2fc  fraction_depleted
0   GTG   left         0       3            187   -4.764500                1.0
1  AAAG  right         4       4             42   -5.076919                1.0

In [64]:
flexible_motifs_df

           motif  fraction_depleted  num_sequences  ...  called  bimodality bimodal
13   ATACNNNNGTG                1.0            192  ...    True    0.405340   False
11   AAAGNNNNGTT                1.0             63  ...    True    0.402660   False
51   CCACNNNAGTA                1.0             55  ...    True    0.568442    True
16   CACNNNNGTAC                1.0             20  ...    True    0.653875    True
1         GGTCTC                1.0              9  ...    True    0.391853   False
82  GACCNNNNCCTC                1.0              4  ...    True    0.243037   False
49   CCACNNNTGTA                1.0              3  ...    True         NaN   False
52   AGGTNNNGGTC                1.0              3  ...    True         NaN   False
81  AGAGNNNNCACG                1.0              3  ...    True         NaN   False
84  GAACNNNNGCCC                1.0              3  ...    True         NaN   False

[10 rows x 10 columns]

### What the warning is for, on a real strain

B156's site `AAACNNNNGTC` is junction-formed: the vector supplies `AAAC`, leaving `GTC` pinned at
offset 4. It is found as pattern `(3, 4, 4)`. Dropping that one shape from the search puts the
pipeline in the case described above — the site is real, strongly depleting, and no longer
expressible by anything the scan looks for.

In [65]:
import io, contextlib

b156 = log2fc_panel["B156_R1"]
without_its_shape = [p for p in get_patterns() if p != (3, 4, 4)]

for keep_fixed_scan in (True, False):
    # starving min_support means the fixed scan can never find anything: the step is inert
    kw = {} if keep_fixed_scan else {"fixed_motif_min_support": 10 ** 9}
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        # the pipeline is chatty and this cell is about its conclusion, not its log
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            _fx, _flex = find_restricted_motifs(
                b156, left_panel, right_panel, flexible_motif_patterns=without_its_shape,
                flexible_motif_log2fc_thr=-1, flexible_motif_score_thr=0.5, **kw)
    _said = [str(w.message) for w in caught if "Position-locked" in str(w.message)]
    print(f"fixed-position scan {'on ' if keep_fixed_scan else 'off'}: "
          f"calls={sorted(_flex[_flex.called].motif)}")
    print(f"    {_said[0].splitlines()[1].strip() if _said else '(nothing reported about it)'}")

fixed-position scan on : calls=['AAACNNNCGTC', 'AAACNNNNGTCA', 'AAACNNNNGTCC', 'AAACNNNNGTCG', 'AAACNNNNGTCT', 'AAACNNNTGTC', 'ACANNNNNATGG', 'ACANNNNNGTGG', 'CGACNNNNGTTC', 'GAACNNNAGTC', 'GAACNNNCGTC', 'GAACNNNGGTC', 'GAACNNNNGTCA', 'GAACNNNNGTCC', 'GAACNNNTGTC']
    GTC at offset 4 from the left: n=385, score=0.95, mean log2FC=-2.58
fixed-position scan off: calls=['AAACNNNCGTC', 'AAACNNNNGTCA', 'AAACNNNNGTCC', 'AAACNNNNGTCG', 'AAACNNNNGTCT', 'AAACNNNTGTC', 'ACANNNNNATGG', 'ACANNNNNGTGG', 'CGACNNNNGTTC', 'GAACNNNAGTC', 'GAACNNNCGTC', 'GAACNNNGGTC', 'GAACNNNNGTCA', 'GAACNNNNGTCC', 'GAACNNNTGTC']
    (nothing reported about it)

With the fixed-position scan on, the two unrelated motifs are still called and the user is told
that 385 plasmids sharing `GTC` at offset 4 are 95% depleted with nothing accounting for them —
which is the signal to widen `flexible_motif_patterns`. With it off, the output is identical
except that nothing is said at all, and a real restriction system reads as absent.

Note what this is *not*: the warning does not recover the motif, and it is not evidence that one
exists. It reports position-locked depletion that the reported motifs do not explain, which is a
question for the user rather than an answer.

In [66]:
#| export
def find_restricted_motifs_mp(*args, cpu_count=1, **kwargs):
    """Deprecated alias for `find_restricted_motifs`; pass `n_jobs` instead of `cpu_count`.

    Provided so that scripts written against the older two-function API keep working; it
    forwards every argument unchanged. New code should call
    `find_restricted_motifs(..., n_jobs=...)`.
    """
    warnings.warn(
        "find_restricted_motifs_mp is deprecated; call find_restricted_motifs(..., "
        "n_jobs=...) instead. cpu_count is forwarded to n_jobs.",
        DeprecationWarning, stacklevel=2)
    return find_restricted_motifs(*args, n_jobs=cpu_count, **kwargs)

## A helper the pipeline does not use

`filter_sequences_without_core_motifs` selects the sequences that do **not** carry a given
fixed-position motif. The pipeline has no use for it — it scans the whole library rather than
setting any of it aside — but the operation is a reasonable one to want by hand when inspecting
a strain, so it is exported.

In [67]:
#| export
def filter_sequences_without_core_motifs(log2fc_series, core_motifs_df):
    """
    Filters an original log2fc Series to remove sequences that contain 
    any of the specified core motifs.

    Not part of the pipeline, which scans the whole library rather than setting any of it
    aside. Provided because selecting the sequences that do *not* carry a given fixed motif is
    a reasonable thing to want by hand.

    Args:
        log2fc_series (pd.Series): Series with sequences as its index and log2FC values.
        core_motifs_df (pd.DataFrame): DataFrame of core motifs, must include
                                       'motif', 'position', and 'length' columns.

    Returns:
        pd.Series: A new Series containing only sequences (and their log2FC values)
                   from log2fc_series that do not carry any of the core motifs.
    """
    if not isinstance(log2fc_series, pd.Series) or log2fc_series.empty:
        # print("Info: log2fc_series is empty or not a Series. Returning a copy.")
        return log2fc_series.copy() 
    
    expected_core_motif_cols = ['motif', 'position', 'length']
    if not isinstance(core_motifs_df, pd.DataFrame) or core_motifs_df.empty or \
       not all(col in core_motifs_df.columns for col in expected_core_motif_cols):
        print("Info: core_motifs_df is empty or invalid for filtering. Returning original log2fc_series.")
        return log2fc_series.copy()

    # Create a boolean mask, True for sequences to keep
    sequences_to_keep_mask = pd.Series(True, index=log2fc_series.index)

    # Iterate through each unique sequence string in the original Series' index
    # Using .loc for assignment to the mask handles duplicate indices in the original Series correctly
    for seq_str_to_check in log2fc_series.index.unique(): 
        if not isinstance(seq_str_to_check, str): 
            continue # Skip if index label is not a string
        
        # Check this sequence against all core motifs
        for _, motif_row in core_motifs_df.iterrows():
            motif_str = motif_row['motif']
            try:
                position = int(motif_row['position'])
                motif_len = int(motif_row['length'])
            except (ValueError, TypeError):
                # print(f"Warning: Invalid position/length for motif {motif_str} in core_motifs_df. Skipping this motif.")
                continue 

            if not isinstance(motif_str, str) or not motif_str: 
                continue

            anchor = motif_row['anchor'] if 'anchor' in core_motifs_df.columns else 'left'
            if len(seq_str_to_check) >= position + motif_len:
                here = (seq_str_to_check[position:position + motif_len] if anchor == 'left'
                        else seq_str_to_check[len(seq_str_to_check) - position - motif_len:
                                              len(seq_str_to_check) - position])
                if here == motif_str:
                    # If a motif is found, mark all occurrences of this sequence string for removal
                    sequences_to_keep_mask.loc[log2fc_series.index == seq_str_to_check] = False 
                    break # Move to the next unique sequence_str_to_check

    return log2fc_series[sequences_to_keep_mask]

In [68]:
#| hide
# Sequences carrying the motif AT ITS OFFSET go; the same bases elsewhere do not count.
_s = pd.Series([-5.0, -0.1, -5.0, -0.2], index=["GTGACGT", "AAACGTA", "GTGTTTT", "AAGTGCC"])
_fx = pd.DataFrame([dict(motif="GTG", position=0, length=3)])
test_eq(list(filter_sequences_without_core_motifs(_s, _fx).index), ["AAACGTA", "AAGTGCC"])
# AAGTGCC contains GTG, but at offset 2, so it is kept -- position is part of the identity.
test_eq(len(filter_sequences_without_core_motifs(_s, pd.DataFrame())), 4)   # no motifs: no-op

Info: core_motifs_df is empty or invalid for filtering. Returning original log2fc_series.

### Example: strain JJ1886 in the shipped panel

`counts_panel.csv.gz` holds UMI counts for strain JJ1886 (replicate R1) and the `Control` input library, flanked by the `left_panel` / `right_panel` contexts below. Thresholds used throughout: a sequence counts as depleted at log2FC ≤ -1, and a motif is kept when ≥ 50% of the sequences carrying it are depleted (score ≥ 0.5).

In [69]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_panel, right_panel = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_panel = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20, pseudocount=1)
log2fc_panel.describe()

         Control_R2     JJ1886_R1  ...  EDL933_dRM_R1  EDL933_dRM_R2
count  30108.000000  30108.000000  ...   30108.000000   30108.000000
mean      -0.095335     -0.145983  ...      -0.051041      -0.264967
std        0.662484      0.925720  ...       0.477549       0.946920
min       -4.604587     -7.545017  ...      -8.050974      -7.464945
25%       -0.158043     -0.189782  ...      -0.303039      -0.651040
50%       -0.002551      0.046866  ...      -0.067980      -0.180923
75%        0.151623      0.261892  ...       0.181672       0.259139
max        1.402258      2.155107  ...       2.393285       3.121144

[8 rows x 17 columns]

In [70]:
core_fixed_12049, flexible_jj1886 = find_restricted_motifs_mp(log2fc_panel["JJ1886_R1"],
                        left_panel,
                        right_panel,
                        fixed_motif_depletion_thr=-1,
                        flexible_motif_patterns=get_patterns(),
                        flexible_motif_log2fc_thr=-1,
                        flexible_motif_score_thr=0.5,
                        cpu_count=1)

--- Starting Fixed-Position Motif Analysis (on original short sequences) ---
Scanning motifs of length 1 to 4 at offsets 0 to 6 from each end, for JJ1886_R1.
Minimum sequence support for a motif: > 5 (i.e., 6 or more)
Found 1 core motifs at fixed positions:
  - Fixed Motif: CTTT, Pos: 4, Len: 4, FracDep: 0.99, AvgFC: -3.31, N: 242

--- Starting Position-Independent Motif Analysis (with context) ---
75 candidate(s) across all patterns; 4 remain after redundancy filtering.

4 motifs remaining:
GGTCTC (from pattern (6, 0, 0)), FracDep: 0.95, AvgFC: -2.80, N: 55
ATACNNNNGTG (from pattern (4, 4, 3)), FracDep: 1.00, AvgFC: -3.22, N: 504
CACNNNNGTAC (from pattern (3, 4, 4)), FracDep: 1.00, AvgFC: -3.27, N: 468
AAAGNNNNGTT (from pattern (4, 4, 3)), FracDep: 0.99, AvgFC: -3.38, N: 913

<ipython-input-70-072dcded3e58>:1: DeprecationWarning: find_restricted_motifs_mp is deprecated; call find_restricted_motifs(..., n_jobs=...) instead. cpu_count is forwarded to n_jobs.
  core_fixed_12049, flexible_jj1886 = find_restricted_motifs_mp(log2fc_panel["JJ1886_R1"],
Scanning patterns: 100%|##########| 43/43 [00:00<00:00, 58.24it/s]

In [71]:
core_fixed_12049

  motif anchor  position  length  num_sequences  avg_log2fc  fraction_depleted
0  CTTT   left         4       4            242   -3.311566           0.987603

In [72]:
flexible_jj1886

          motif  fraction_depleted  num_sequences  ...  called  bimodality bimodal
19  ATACNNNNGTG           0.996032            504  ...    True    0.273289   False
22  CACNNNNGTAC           1.000000            468  ...    True    0.274410   False
23  AAAGNNNNGTT           0.994524            913  ...    True    0.249124   False
0        GGTCTC           0.945455             55  ...    True    0.363638   False

[4 rows x 10 columns]

In [73]:
#| hide
import nbdev; nbdev.nbdev_export()