In [1]:
%load_ext autoreload
%autoreload 2

# Utils

> useful basic functions

In [2]:
#| default_exp utils

In [3]:
#| hide
from nbdev.showdoc import *
from fastcore.test import test_eq, test_fail

In [4]:
#| export
import pandas as pd
import re
import numpy as np
from scipy.stats import binom
import os
import itertools
from random import choice
from itertools import combinations
from collections import deque

In [5]:
#| hide
from randseq.example_data import get_example_data_dir

In [6]:
#| export
# IUPAC DNA codes mapping for sequence generation
IUPAC_DNA_TO_BASES = {
    'A': ['A'], 'C': ['C'], 'G': ['G'], 'T': ['T'], 'R': ['A', 'G'],
    'Y': ['C', 'T'], 'S': ['G', 'C'], 'W': ['A', 'T'], 'K': ['G', 'T'],
    'M': ['A', 'C'], 'B': ['C', 'G', 'T'], 'D': ['A', 'G', 'T'],
    'H': ['A', 'C', 'T'], 'V': ['A', 'C', 'G'], 'N': ['A', 'C', 'G', 'T']
}

# IUPAC DNA codes mapping for regex conversion
IUPAC_DNA_TO_REGEX = {
    'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T', 'R': '[AG]', 'Y': '[CT]',
    'S': '[GC]', 'W': '[AT]', 'K': '[GT]', 'M': '[AC]', 'B': '[CGT]',
    'D': '[AGT]', 'H': '[ACT]', 'V': '[ACG]', 'N': '[ATGC]'
}

# IUPAC DNA codes for reverse complement
IUPAC_COMPLEMENT = {
    'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C',
    'R': 'Y', 'Y': 'R', 'S': 'S', 'W': 'W',
    'K': 'M', 'M': 'K', 'B': 'V', 'V': 'B',
    'D': 'H', 'H': 'D', 'N': 'N'
}

## Counts to log2 fold change

Each plasmid's depletion is the log2 ratio of its abundance in the recipient to its abundance in
the donor library. Three details matter, and two of them differ from what the manuscript's
Methods currently say — the code is right in both cases and the text needs fixing.

**The pseudocount is added before normalisation, not after.** The Methods describe
`(normalised count + 1) / (normalised count + 1)`. Normalised counts are far below 1, so adding
1 to them would swamp the signal entirely. What the code does — `(n+1)/Σ(n+1)`, then the ratio —
is the sensible reading.

**Normalisation is over the plasmids that survive the count filter, not over the whole sample.**
The Methods say "normalised to the total number of molecules per sample". Since the filter keeps
a few percent of observed inserts, the denominator here is a different quantity. It is a
per-sample constant, so it shifts every plasmid in a sample by the same amount and cannot change
which motifs are called — but it is not what the text claims.

**`count_threshold` is a power choice, not a correctness one.** It filters on *donor* abundance,
and depletion is independent of abundance (the paper measures pooled Pearson r = 0.135), so
raising it costs statistical power but cannot bias which motifs are called. The consequence
matters downstream: `num_sequences` is set by this threshold, so it is **not comparable between
experiments** unless the threshold is quoted with it. `median_log2fc` and escaper rate are.

In [7]:
#| export
def calculate_log2fc(df, reference_column='MFDpir', count_threshold=20, pseudocount=1):
    """
    Filters a DataFrame, normalizes columns by sum, calculates log2 fold change
    relative to a reference column, and drops the reference column.

    Args:
        df (pd.DataFrame): Input DataFrame (rows=features, columns=samples).
        reference_column (str): Name of the reference sample column.
        count_threshold (int): Minimum count in reference column to keep a feature.
        pseudocount (float): Value added to normalized counts before log2FC.

    Returns:
        pd.DataFrame: DataFrame with log2 fold change values. None if reference
                      column is missing. Empty DataFrame if all rows are filtered out.
    """
    
    df = df.replace(np.nan,0)
    if reference_column not in df.columns:
        print(f"Error: Reference column '{reference_column}' not found in DataFrame.")
        return None

    # 1. Filter rows
    df_filtered = df[df[reference_column] > count_threshold].copy()
    if df_filtered.empty:
        print("DataFrame is empty after filtering.")
        return pd.DataFrame()

    # 2. Add pseudocount
    # The pseudocount is added here, before normalization.
    df_with_pseudocount = df_filtered + pseudocount

    # 3. Normalize each column by its sum
    # Normalization is now performed on the data that includes the pseudocount.
    # df.sum(axis=0) calculates sum for each column.
    # .div performs element-wise division, axis=1 aligns column_sums with columns.
    column_sums = df_with_pseudocount.sum(axis=0)
    
    # Handle cases where column_sums might be zero (e.g., if all values were -pseudocount after filtering, though unlikely with positive counts)
    # If a column sum is 0 after adding pseudocount, it implies an issue or very specific data.
    # Division by zero will result in NaN or inf.
    df_processed = df_with_pseudocount.div(column_sums, axis=1)

    # Check if reference column still exists (it should)
    if reference_column not in df_processed.columns:
        # This check is crucial as operations might alter columns if not handled carefully.
        print(f"Error: Reference column '{reference_column}' lost during processing.")
        return None
        
    reference_values = df_processed[reference_column]

    # 4. Calculate log2FC
    # .div performs element-wise division, axis=0 aligns reference_values (a Series) with rows of df_processed.
    log2fc_df = np.log2(df_processed.div(reference_values, axis=0))
    
    # Columns are already named correctly from df_processed.

    # 5. Drop the reference column's own log2FC (which will be ~zeros)
    if reference_column in log2fc_df.columns:
        log2fc_df = log2fc_df.drop(columns=[reference_column])
    else:
        print(f"Warning: Reference column '{reference_column}' not found in log2fc_df for dropping.")
        
    return log2fc_df

In [8]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['__init__.py',
 '__pycache__',
 'countsTable.csv.gz',
 'counts_panel.csv.gz',
 'counts_panel_key.csv',
 'pMin_backbone.fasta']

In [9]:
counts_file="countsTable.csv.gz"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]

log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df.min(axis=0)

K12_T0       -2.844874
HS_T0        -3.320280
E1114_T0     -4.544421
E1167_T0     -3.645600
H120_T0      -3.572726
TA054_T0     -3.319211
TA447_T0     -3.566876
E101_T0      -8.108167
41-1Ti9_T0   -4.255918
TA280_T0     -4.800802
M114_T0      -4.143357
TA249_T0     -4.973009
ROAR8_T0     -4.621302
JJ1886_T0    -9.188692
CFT073_T0    -3.868714
APECO1_T0    -6.525634
UTI89_T0     -8.571068
S88_T0       -8.601767
MG1655_T0    -4.777041
dtype: float64

## The depletion score

Of the plasmids carrying a motif, what fraction fell below a log2FC threshold. One number per
motif, and the one the whole method reduces to.

In [10]:
#| export
def score(FCs, thr=-1):
    """Fraction of a motif's plasmids that are depleted below `thr`.

    The depletion score, written out plainly. The pipeline computes this quantity inline over
    whole arrays rather than calling this on a list, so nothing in `randseq.core` calls it; it
    is here to be read, and to score a motif's fold changes by hand.

    Args:
        FCs (list): log2 fold changes of the plasmids carrying the motif.
        thr (float): a plasmid is depleted when its log2FC is strictly below this.

    Returns:
        float: the fraction depleted, or 0.0 when no plasmid carries the motif.
    """
    if len(FCs) == 0:
        return 0.0
    return sum([x < thr for x in FCs]) / len(FCs)

In [11]:
test_eq(score([-2, -0.5, -0.1, -5], thr=-1), 0.5)
test_eq(score([-1.0, -1.0], thr=-1), 0.0)   # strict: exactly at the threshold is not depleted
test_eq(score([], thr=-1), 0.0)             # no plasmids carry the motif -> no evidence, not NaN

In [12]:
#| export
def revcomp(seq:str):
    '''Computes the reverse complement of a sequence'''
    trns=str.maketrans("ATGCN","TACGN")
    return seq.upper().translate(trns)[::-1]

In [13]:
assert revcomp("ATGC")=="GCAT"
assert revcomp("ATGCN")=="NGCAT"
assert revcomp("atgNN")=="NNCAT"

## Choosing which strand to report a motif on

A recognition site and its reverse complement are the same site. The library is scanned on both
strands, so a motif and its reverse complement always get **identical** statistics — same number
of supporting sequences, same depletion score, same average log2FC. They are one answer.

That makes the choice between them a tie, and a tie has to be broken by *something*. Left to the
order the candidates happen to arrive in, the same site comes back as `GAGACC` from one run and
`GGTCTC` from the next — two spellings of one answer, which makes two result tables impossible to
compare.

`canonical_motif` breaks the tie the same way every time: report the strand REBASE uses, so that
results line up with the literature and with the enzyme names people recognise (`GGTCTC` is
BsaI/Eco31I). For motifs REBASE does not know — which includes most of what a discovery screen
finds — fall back to the alphabetically first strand. That choice is arbitrary, but it is stable
across runs, machines and Python versions, which is the property that matters.

In [14]:
#| export
_REBASE_MOTIFS = None

def get_rebase_motifs():
    """The REBASE Gold Standard recognition motifs shipped with the package.

    Returns a `set` of IUPAC motif strings (n=983, downloaded 2025-12-03). Used by
    `canonical_motif` to decide which strand to report a motif on. Read once and cached.
    """
    global _REBASE_MOTIFS
    if _REBASE_MOTIFS is None:
        from randseq.data import get_data_dir
        path = os.path.join(get_data_dir(), 'rebase_gold_standard_motifs.txt')
        with open(path) as fh:
            _REBASE_MOTIFS = {line.strip().upper() for line in fh if line.strip()}
    return _REBASE_MOTIFS

In [15]:
#| export
def canonical_motif(motif, rebase_motifs=None):
    """Return the strand `motif` should be reported on.

    A motif and its reverse complement describe the same recognition site and always carry the
    same statistics, so exactly one of them should appear in the results. Prefer the strand that
    REBASE uses; if REBASE knows neither (or both), fall back to the alphabetically first strand,
    which is arbitrary but identical on every run.

    Args:
        motif (str): An IUPAC motif, e.g. `'GAGACC'` or `'CACNNNNGTAT'`.
        rebase_motifs (set, optional): Motif set to match against. Defaults to
            `get_rebase_motifs()`. Pass an explicit set to test or to use a different reference.

    Returns:
        str: `motif` or its reverse complement.
    """
    if rebase_motifs is None:
        rebase_motifs = get_rebase_motifs()
    motif = motif.upper()
    rc = revcomp(motif)
    in_fwd, in_rev = motif in rebase_motifs, rc in rebase_motifs
    if in_fwd and not in_rev:
        return motif
    if in_rev and not in_fwd:
        return rc
    return min(motif, rc)

In [16]:
# REBASE spells the BsaI / Eco31I site GGTCTC, so that is the strand we report.
assert canonical_motif('GAGACC') == 'GGTCTC'
assert canonical_motif('GGTCTC') == 'GGTCTC'

# Idempotent, and agrees with itself on both inputs of a pair.
for m in ['GAGACC', 'AACNNNNCTTT', 'CACNNNNGTAT', 'GCGGCCA', 'CCGCGG']:
    c = canonical_motif(m)
    assert canonical_motif(c) == c, m
    assert canonical_motif(revcomp(m)) == c, m

# A palindrome is its own reverse complement, so there is nothing to choose.
assert canonical_motif('CCGCGG') == 'CCGCGG'

# Unknown to REBASE -> alphabetically first, regardless of which strand was passed in.
assert canonical_motif('TGGCCGC', rebase_motifs=set()) == 'GCGGCCA'
assert canonical_motif('GCGGCCA', rebase_motifs=set()) == 'GCGGCCA'

# The real list resolves the motifs that matter and leaves novel ones to the fallback.
rb = get_rebase_motifs()
assert len(rb) == 983
assert canonical_motif('AACNNNNCTTT') == 'AAAGNNNNGTT'  # in REBASE on the other strand
print('ok')

ok

In [17]:
#| export
def get_lib_seq_context(seqs,left,right):
    """
    Generates a list of sequences by combining a left and right sequence with each sequence in the input list.
    
    Args:
        seqs (list): List of sequences to be combined.
        left (str): Left sequence to prepend.
        right (str): Right sequence to append.

    Returns:
        list: List of combined sequences.
    """
    left=left.upper()
    right=right.upper()
    lib=[left+r+right for r in seqs]
    return lib

In [18]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib=get_lib_seq_context(log2fc_df.index,left,right)
lib[:5]

['GTCCTAGGTATAATACTAGTCGGAGGTACTGGGTACATTTGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTTGGCGATAATGCCGGCTATCGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTTTCCAGTTCACTGGTCTTCGGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTAATTTCAGTGCCGTTCAGATGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTCTGCGGTAATAATTCCCGCCGTTTTAGAGCTAGAAATAGC']

In [19]:
#| export

def _generate_sequences_from_iupac(iupac_pattern_str):
    """Generates concrete DNA sequences from an IUPAC pattern."""
    if not iupac_pattern_str:
        return ['']
    possible_bases = [IUPAC_DNA_TO_BASES[c] for c in iupac_pattern_str.upper()]
    return ["".join(combo) for combo in itertools.product(*possible_bases)]

def _convert_iupac_to_regex(iupac_pattern_str):
    """Converts an IUPAC pattern to a regex string."""
    if not iupac_pattern_str:
        return ''
    return "".join([IUPAC_DNA_TO_REGEX[c] for c in iupac_pattern_str.upper()])

def _get_reverse_complement_iupac(iupac_pattern_str):
    """Computes the reverse complement of a DNA sequence in IUPAC format."""
    reversed_pattern = iupac_pattern_str.upper()[::-1]
    return "".join([IUPAC_COMPLEMENT[c] for c in reversed_pattern])

### Is one motif a version of another?

The redundancy filter needs to know when two candidates describe the same thing. These functions
answer it by IUPAC generality: `CACNNNNGTAY` is a *specific* version of `CACNNNNGTAN`, because
every sequence the first matches the second also matches.

**What this cannot see, and why it matters.** Generality is a comparison of *strings*. Two
candidates can describe the same site and be unrelated as strings — a different length, a
different pattern, or the opposite strand. On LMR_503 the real site is `CACNNNNGTAY` and the
candidate set contains `TACNNNNGTGG`, `CACTNNAGTA`, `ACACNNNAGTA` and fifteen more, all of which
decompose to `CAC-NNNN-GTA` with an extra base pinned somewhere irrelevant. None is an IUPAC
version of another, so none is removed here.

They are caught later instead, by comparing **plasmid sets** rather than strings — see
`filter_explained_candidates` in `core`. This function is doing its job correctly; it is simply
answering a narrower question than the one that needs answering.

In [20]:
#| export
def check_specific_matches_broad(specific, broad):
  """
  Checks if a 'specific' string matches a 'broad' string with a wildcard rule.

  This function compares two strings of the same length. The character 'N' in 
  the 'broad' string acts as a wildcard that can match any single character 
  in the 'specific' string at the same position. An 'N' in the 'specific' 
  string does not have any special meaning and is treated as a literal 'N'.

  Args:
    specific: The string that is being checked.
    broad: The string that contains the pattern, where 'N' is a wildcard.

  Returns:
    True if the 'specific' string matches the 'broad' pattern, False otherwise.
  """
  if len(specific) != len(broad):
    return False

  for spec_char, broad_char in zip(specific, broad):
    if spec_char == broad_char or broad_char == 'N':
      continue
    return False
  return True

def find_broad_in_specific(specific, broad):
  """
  Finds if a 'broad' DNA motif exists within a 'specific' DNA sequence, checking
  both forward and reverse complement orientations of the motif.

  If len(specific) < len(broad), it's impossible to find the motif, so it
  returns False. It first checks for the motif in the forward direction. If no match
  is found, it checks for the reverse complement of the motif.

  Args:
    specific: The DNA sequence to be searched within.
    broad: The DNA motif (pattern with 'N' wildcards) to search for.

  Returns:
    True if 'broad' or its reverse complement is found in 'specific', False otherwise.
  """
  if len(specific) < len(broad):
    return False
  
  broad_len = len(broad)
  if broad_len == 0:
      return True

  # 1. Check the forward orientation
  is_forward_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad) 
                         for i in range(len(specific) - broad_len + 1))
  
  if is_forward_match:
    return True

  # 2. If no forward match, check the reverse complement orientation
  broad_rev_comp = revcomp(broad)
  is_reverse_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad_rev_comp) 
                         for i in range(len(specific) - broad_len + 1))

  return is_reverse_match

In [21]:
assert find_broad_in_specific("AACNNNTT","AACGNNTT") == False 
assert find_broad_in_specific("AACGNNTT","AACNNNTT") == True
assert find_broad_in_specific("ATGCC","ATG") == True
assert find_broad_in_specific("GGATGCC","ATG") == True
assert find_broad_in_specific("GGATG","ATG") == True
assert find_broad_in_specific("ATG","GATGC") == False
assert find_broad_in_specific("ATG","ATGCC") == False
assert find_broad_in_specific("GTACNNNTGTG","CACNNNNGTAC") == True
assert find_broad_in_specific("GGCTT","AAGCC") == True

In [22]:
#| export
def get_motif_filter_with_context(df, left_context, right_context, motif):
    """Boolean filter selecting sequences that contain `motif`, on either strand.

    The motif is matched against the sequence *with its flanking vector context restored*,
    because a recognition site can straddle the junction between the random insert and the
    backbone — several of the motifs recovered from real data do exactly that.

    Both orientations are searched, since a site and its reverse complement are the same site.
    That is also why a motif and its reverse complement always carry identical statistics, and
    therefore why only one of them should ever be reported (see `canonical_motif`).

    Args:
        df: DataFrame or Series whose **index** holds the DNA sequences.
        left_context, right_context: the vector sequence flanking the insert.
        motif: an IUPAC motif, e.g. `'GGTCTC'` or `'CACNNNNGTAC'`.

    Returns:
        pd.Series: boolean, indexed like `df`.
    """
    try:
        fwd = re.compile(_convert_iupac_to_regex(motif), re.IGNORECASE)
        rev = re.compile(_convert_iupac_to_regex(_get_reverse_complement_iupac(motif)),
                         re.IGNORECASE)
    except (KeyError, ValueError, re.error):
        # An unparseable motif matches nothing rather than raising, so one bad candidate
        # cannot abort a whole strain panel.
        return pd.Series(False, index=df.index)

    def present(seq):
        full = f"{left_context}{seq}{right_context}"
        return bool(fwd.search(full) or rev.search(full))

    return df.index.to_series().apply(present)

In [23]:
motif_filter = get_motif_filter_with_context(counts, left, right, "GAGACC")
filtered_df = counts[motif_filter]
filtered_df

                      K12_T0  HS_T0  E1114_T0  ...  S88_T0  MG1655_T0  MFDpir
seq                                            ...
GGCGCTAAGGAGACCTTAAA     140    141        17  ...     137        150      63
CCTGAGACCTCTGCCTCCGG     361    341        38  ...     456        292     173
CTGAGACCTCTGCCTCCGGA     347    355        30  ...     401        282     167
GAACCTGAGACCTCTGCCTC     770    852        78  ...    1009        676     379
CAGAGACCAGGTGGGAATAG     299    329        23  ...     336        193     161
CTATACTGCCGCCAGGTCTC     289    330        34  ...     400        318     164
CCCAACCACCGAGACCCGAC     406    416        44  ...     392        543     179
CGAGACCGTTTATGCTGAAC     239    263        20  ...     327        256     113
TGGAATGAGACCACCCAGGC     240    273        20  ...     283        348     140

[9 rows x 20 columns]

In [24]:
#| export
def _get_filter_for_motif(series, motif, left_context, right_context):
    """`get_motif_filter_with_context` with the argument order used inside the pipeline.

    Kept as a separate name because `get_motif_filter_with_context` is public API that
    external scripts call; this one exists only so internal call sites read naturally.
    """
    return get_motif_filter_with_context(series, left_context, right_context, motif)

In [25]:
motif_filter = _get_filter_for_motif(counts, "GAGACC", left, right)
filtered_df = counts[motif_filter]
filtered_df

                      K12_T0  HS_T0  E1114_T0  ...  S88_T0  MG1655_T0  MFDpir
seq                                            ...
GGCGCTAAGGAGACCTTAAA     140    141        17  ...     137        150      63
CCTGAGACCTCTGCCTCCGG     361    341        38  ...     456        292     173
CTGAGACCTCTGCCTCCGGA     347    355        30  ...     401        282     167
GAACCTGAGACCTCTGCCTC     770    852        78  ...    1009        676     379
CAGAGACCAGGTGGGAATAG     299    329        23  ...     336        193     161
CTATACTGCCGCCAGGTCTC     289    330        34  ...     400        318     164
CCCAACCACCGAGACCCGAC     406    416        44  ...     392        543     179
CGAGACCGTTTATGCTGAAC     239    263        20  ...     327        256     113
TGGAATGAGACCACCCAGGC     240    273        20  ...     283        348     140

[9 rows x 20 columns]

In [26]:
#| export
def generate_tuple_combinations(a1, a2, b1, b2, c1, c2):
  """
  Generates a list of tuples with all possible number combinations within given ranges.

  Args:
    a1: The starting number for the first position.
    a2: The ending number for the first position (inclusive).
    b1: The starting number for the second position.
    b2: The ending number for the second position (inclusive).
    c1: The starting number for the third position.
    c2: The ending number for the third position (inclusive).

  Returns:
    A list of tuples, where each tuple contains three numbers representing
    a unique combination from the specified ranges.
  """
  range_a = range(a1, a2 + 1)
  range_b = range(b1, b2 + 1)
  range_c = range(c1, c2 + 1)
  
  # Using itertools.product is more efficient for generating Cartesian products
  combinations = list(itertools.product(range_a, range_b, range_c))
  
  return combinations

In [27]:
generate_tuple_combinations(5,7,0,0,0,0)

[(5, 0, 0), (6, 0, 0), (7, 0, 0)]

In [28]:
patterns = generate_tuple_combinations(2,4,1,8,2,4)
patterns[:5], patterns[-5:]

([(2, 1, 2), (2, 1, 3), (2, 1, 4), (2, 2, 2), (2, 2, 3)],
 [(4, 7, 3), (4, 7, 4), (4, 8, 2), (4, 8, 3), (4, 8, 4)])

In [29]:
#| export
def filter_symmetric_tuples(list_of_tuples):
    """
    Filters a list of 3-integer tuples, removing specific symmetric pairs.

    This function removes a tuple if another tuple exists in the list that is
    its mirror image by swapping the first and third elements. For example, 
    (1, 2, 3) is considered a symmetric pair with (3, 2, 1). When such a pair 
    is found, only the first one encountered in the original list is kept.

    Args:
        list_of_tuples: A list of tuples, where each tuple contains three integers.

    Returns:
        A new list of tuples with the symmetric pairs removed.
    """
    # This set will store the canonical representation of tuples we have 
    # already encountered. The canonical form is the smaller of a tuple and
    # its symmetric version, ensuring we can identify pairs efficiently.
    seen_canonical_forms = set()
    
    # This list will hold the final, filtered tuples.
    filtered_list = []

    # Iterate through each tuple in the input list.
    for tup in list_of_tuples:
        # Create the specific symmetric counterpart by swapping the first and last elements.
        symmetric_tup = (tup[2], tup[1], tup[0])

        # Determine the canonical form by picking the lexicographically smaller
        # of the original tuple and its symmetric version. This makes the
        # representation consistent for any pair.
        canonical_form = min(tup, symmetric_tup)

        # If the canonical form is already in our 'seen' set, it means we have
        # already processed this tuple or its symmetric pair, so we skip it.
        if canonical_form in seen_canonical_forms:
            continue

        # If the canonical form has not been seen, we add the original tuple
        # to our result list.
        filtered_list.append(tup)
        
        # Add the canonical form to the 'seen' set. This ensures that the
        # other member of the symmetric pair will be skipped if encountered later.
        seen_canonical_forms.add(canonical_form)
        
    return filtered_list

In [30]:
patterns = generate_tuple_combinations(2,4,1,8,2,4)
print(len(patterns))
print(len(filter_symmetric_tuples(patterns)))

72
48

In [31]:
#| export
def canonical_pattern(pattern):
    """The single form of `pattern` the scan uses.

    Two kinds of spelling describe the same search. A contiguous motif has no gap, so
    `(d1, 0, d2)` is just a run of `d1 + d2` bases: `(3, 0, 3)` and `(0, 0, 6)` are `(6, 0, 0)`.
    And a gapped pattern finds the same sites as its mirror `(d2, spacer, d1)`, because the scan
    reads both strands -- a site of one is the reverse complement of a site of the other. Of a
    mirror pair the one with the shorter first half is kept, `(3, 4, 4)` rather than `(4, 4, 3)`.
    """
    d1, spacer, d2 = (int(x) for x in pattern)
    if spacer == 0:
        return (d1 + d2, 0, 0)
    return min((d1, spacer, d2), (d2, spacer, d1))


def get_patterns(contiguous=(5, 7), halves=(2, 4), max_spacer=8, min_defined=5, max_defined=8):
    """The search space: every motif architecture the scan looks for by default.

    A pattern is `(d1, spacer, d2)` -- defined bases, undefined gap, defined bases. The default
    is the 43-pattern set used in the paper: contiguous sites of 5-7 bases, and gapped sites
    whose halves are 2-4 bases, with at least 5 defined bases in all and a gap of 1-8. It fits
    837 of the 983 distinct motifs in the REBASE Gold Standard set shipped with the package
    (`get_rebase_motifs`).

    The arguments widen it. `get_patterns(contiguous=(4, 8), halves=(2, 5), max_spacer=9)`
    (68 patterns) fits 902; adding `max_defined=9` (77) fits 911, at 2.4x the motifs scanned. A
    wider search is not free at the default thresholds: on the 21-strain panel the 68-pattern
    set adds 11 calls the published Fig 3 does not have -- one-base-longer descriptions of weak
    or degenerate sites, which steps 3 and 4 do not yet catch -- and loses one. It is kept as a
    test case for improving those steps, not as the default.

    Every pattern is returned in its `canonical_pattern` form.
    """
    patterns = {(k, 0, 0) for k in range(contiguous[0], contiguous[1] + 1)}
    for a in range(halves[0], halves[1] + 1):
        for b in range(halves[0], halves[1] + 1):
            if min_defined <= a + b <= max_defined:
                patterns.update(canonical_pattern((a, s, b)) for s in range(1, max_spacer + 1))
    return sorted(patterns, key=lambda p: (p[0] + p[2], p[1], p))

In [32]:
#| hide
test_eq(canonical_pattern((4, 4, 3)), (3, 4, 4))          # mirror -> shorter first half
test_eq(canonical_pattern((3, 4, 4)), (3, 4, 4))
test_eq(canonical_pattern((3, 0, 3)), (6, 0, 0))          # no gap -> one run
test_eq(canonical_pattern((0, 0, 6)), (6, 0, 0))
# every default pattern is already canonical, and the paper's 43 are reproducible
test_eq(all(canonical_pattern(p) == p for p in get_patterns()), True)
_paper = get_patterns()                                   # the default is the paper's set
test_eq(len(_paper), 43)
test_eq(set(_paper), set(filter_symmetric_tuples(generate_tuple_combinations(5, 7, 0, 0, 0, 0)
                                                 + generate_tuple_combinations(2, 4, 1, 8, 3, 4))))

In [33]:
patterns = get_patterns()
sorted(patterns, key=lambda x: (x[0]+x[2], x[1]))

[(5, 0, 0),
 (2, 1, 3),
 (2, 2, 3),
 (2, 3, 3),
 (2, 4, 3),
 (2, 5, 3),
 (2, 6, 3),
 (2, 7, 3),
 (2, 8, 3),
 (6, 0, 0),
 (2, 1, 4),
 (3, 1, 3),
 (2, 2, 4),
 (3, 2, 3),
 (2, 3, 4),
 (3, 3, 3),
 (2, 4, 4),
 (3, 4, 3),
 (2, 5, 4),
 (3, 5, 3),
 (2, 6, 4),
 (3, 6, 3),
 (2, 7, 4),
 (3, 7, 3),
 (2, 8, 4),
 (3, 8, 3),
 (7, 0, 0),
 (3, 1, 4),
 (3, 2, 4),
 (3, 3, 4),
 (3, 4, 4),
 (3, 5, 4),
 (3, 6, 4),
 (3, 7, 4),
 (3, 8, 4),
 (4, 1, 4),
 (4, 2, 4),
 (4, 3, 4),
 (4, 4, 4),
 (4, 5, 4),
 (4, 6, 4),
 (4, 7, 4),
 (4, 8, 4)]

In [34]:
len(get_patterns())

43

In [35]:
get_patterns()[5::5]

[(2, 5, 3),
 (2, 1, 4),
 (3, 3, 3),
 (2, 6, 4),
 (3, 8, 3),
 (3, 4, 4),
 (4, 1, 4),
 (4, 6, 4)]

In [36]:
def generate_random_sequence(length: int) -> str:
    """
    Generates a random DNA sequence of a given length.
    
    Args:
        length: The length of the sequence to generate.
        
    Returns:
        A string representing a random DNA sequence.
    """
    return ''.join(choice('ACGT') for _ in range(length))

### Custom motifs

Presence / log2FC helpers for a user-supplied list of candidate motifs (IUPAC-style, `N` = any base), independent of `find_restricted_motifs`.

In [37]:
#| export
def _custom_motif_to_regex(motif):
    """IUPAC letters -> regex character classes (e.g. R -> [AG], N -> [ATGC]);
    anything already inside [...] is kept as written, so '[AG]TAC' and 'RTAC' are equivalent."""
    out, in_class = [], False
    for ch in motif.upper():
        if ch == '[':
            in_class = True
        elif ch == ']':
            in_class = False
        out.append(ch if in_class or ch in '[]' else IUPAC_DNA_TO_REGEX.get(ch, ch))
    return ''.join(out)

In [38]:
assert _custom_motif_to_regex("RTACNNNNGTG") == "[AG]TAC[ATGC][ATGC][ATGC][ATGC]GTG"
assert _custom_motif_to_regex("[AG]TACNNNNGTG") == "[AG]TAC[ATGC][ATGC][ATGC][ATGC]GTG"
assert _custom_motif_to_regex("GGTCTC") == "GGTCTC"

In [39]:
#| export
def get_custom_motif_presence_in_library(short_sequences_list, left_context, right_context, motif_list):
    """
    Creates a DataFrame indicating the presence of flexible motifs in sequences (with context).

    Args:
        short_sequences_list (list): List of original short DNA sequences.
        left_context (str): Left context string to prepend.
        right_context (str): Right context string to append.
        motif_list (list): Motif strings using IUPAC codes (e.g. 'AACNNNNCTTT', 'RTACNNNNGTG')
                           and/or regex character classes (e.g. '[AG]TACNNNNGTG').

    Returns:
        pd.DataFrame: DataFrame with full sequences (with context) as index,
                      flexible motif strings as columns, and boolean values indicating presence.
    """
    full_sequences_with_context = get_lib_seq_context(short_sequences_list, left_context, right_context)

    # Filter out None entries from full_sequences_with_context which may arise from non-string inputs to get_lib_seq_context
    # and keep track of original indices to align with short_sequences_list if needed for other purposes,
    # though for this function, we just use the valid full sequences.
    valid_full_sequences = [seq for seq in full_sequences_with_context if isinstance(seq, str)]
    if not valid_full_sequences:
        print("No valid full sequences to process after adding context.")
        return pd.DataFrame()
    presence_data = []

    for full_seq_str in valid_full_sequences:
        row_data = {'full_sequence': full_seq_str}
        for flex_motif_str in motif_list:
            if not isinstance(flex_motif_str, str) or not flex_motif_str:
                row_data[flex_motif_str] = False # Or handle as error/skip
                continue
            regex_pattern = _custom_motif_to_regex(flex_motif_str)
            try:
                if re.search(regex_pattern, full_seq_str):
                    row_data[flex_motif_str] = True
                elif re.search(regex_pattern, revcomp(full_seq_str)):
                    row_data[flex_motif_str] = True
                else:
                    row_data[flex_motif_str] = False
            except re.error:
                # print(f"Warning: Regex error for motif '{flex_motif_str}' (pattern: '{regex_pattern}'). Marking as False.")
                row_data[flex_motif_str] = False
        presence_data.append(row_data)

    if not presence_data:
        return pd.DataFrame(index=valid_full_sequences, columns=motif_list)

    presence_df = pd.DataFrame(presence_data)
    if 'full_sequence' in presence_df.columns:
        presence_df = presence_df.set_index('full_sequence')
        
    return presence_df

In [40]:
#| export
def get_log2fc_distribution_by_motif(log2fc_df, left_context, right_context, motif_list, sample_columns=None):
    """
    Categorizes each sequence in log2fc_df by which motif (if any) it contains,
    and reshapes to long format for distribution comparison/plotting.

    Args:
        log2fc_df (pd.DataFrame): DataFrame of log2 fold change values, indexed by short
                                   sequence (rows=features, columns=samples).
        left_context (str): Left context string to prepend before motif search.
        right_context (str): Right context string to append before motif search.
        motif_list (list): List of motif strings (e.g. ['CAAGNNNNNGGT']), using 'N' as wildcard.
                            If a sequence matches multiple motifs, the LAST matching motif
                            in motif_list wins (same precedence as plot_motif_ggplot).
        sample_columns (list, optional): Subset of columns (samples) from log2fc_df to include.
                                          Defaults to all columns.

    Returns:
        pd.DataFrame: Long-format DataFrame with columns ['sequence', 'Motif_Category',
                      'sample', 'log2fc']. 'Motif_Category' is one of motif_list or 'Other'.
                      None if motif presence could not be computed.
    """
    if sample_columns is None:
        sample_columns = log2fc_df.columns.tolist()

    # Positionally aligned with log2fc_df.index (order preserved by get_lib_seq_context),
    # same approach as plot_motif_ggplot.
    presence_df = get_custom_motif_presence_in_library(
        log2fc_df.index.tolist(), left_context, right_context, motif_list
    )

    if presence_df.empty:
        print("Error: could not compute motif presence.")
        return None

    df = log2fc_df[sample_columns].copy()
    df['Motif_Category'] = 'Other'

    for motif in motif_list:
        df.loc[presence_df[motif].values, 'Motif_Category'] = motif

    index_name = df.index.name or 'index'
    long_df = (
        df.reset_index()
          .melt(id_vars=[index_name, 'Motif_Category'], value_vars=sample_columns,
                var_name='sample', value_name='log2fc')
          .rename(columns={index_name: 'sequence'})
    )

    return long_df

### Where this sits in the pipeline

`find_iupac_equivalent_motifs` collapses `CACNNNNGTAC` and `CACNNNNGTAT` into `CACNNNNGTAY` —
recovering the degenerate site from the two halves the scan reports separately.

It runs **after** `find_restricted_motifs`, on the results, which is worth being aware of: for
most of this package's history that meant the two halves competed against each other during
scoring before ever being merged. `filter_explained_candidates` now handles that inside the
pipeline, by asking whether one candidate still depletes the plasmids the other does not cover —
so `CACNNNNGTAC` survives `CACNNNNGTAT`, correctly, because it does.

## Is a motif's depletion more than the sample's own noise?

The scan in `00_core` tests an enormous number of motifs — 183,000 on the smaller example library, 750,000 on
the larger — so some will look perfect by luck alone. How many supporting plasmids a call needs
before that stops being a plausible explanation depends on the sample, not on a constant.

Under the null, a motif's depleted count is `Binomial(n, p)` where **`p` is that sample's own
background depletion rate**: the fraction of plasmids depleted when no site is involved. A noisy
sample has a higher `p` and therefore needs more evidence for the same claim, automatically.

This was checked against a permutation test that removes the plasmids carrying the confident
calls and reshuffles the rest, so that nothing real remains:

| | binomial expectation | permutation, 20 runs |
|---|---|---|
| JJ1886, n=3–4 (p=0.0178) | 0.60 spurious calls | 0.8 (max 4) |
| JJ1886, n≥5 | 0.01 | 0 |
| the panel sample, all n (p=0.0124) | 0.00 | 0 |

The two agree, so the analytic form can be computed for every candidate at no cost, where the
permutation takes minutes per sample. `work/permutation_fdr.py` is kept as an occasional
calibration check rather than part of the analysis.

It also explains something a fixed `min_support` cannot. The panel sample is safe at n=3 not
because it is a cleaner sample but because its larger library leaves far fewer motifs sitting at
tiny n.

**What this does not model.** The binomial treats a motif's plasmids as independent draws. They
are not: motifs co-occur, which is the whole subject of step 4 of the core pipeline. So the p-value is a screen
against chance, not a complete model of how a spurious call arises — a shadow of a real site is
highly significant by this test and still needs explaining away.

In [41]:
#| export
def background_depletion_rate(log2fc_series, log2fc_thr=-1):
    """The null depletion rate a motif's p-value is taken against: the fraction of all plasmids
    in this sample whose log2FC is below `log2fc_thr`.

    It is the raw sample-wide rate, so it includes the plasmids destroyed by the strain's real
    sites -- the null is inflated, and the p-values err on the conservative side. By how much
    depends on how much of the library the real sites cover: little for most strains, a lot for
    a strain like 381A, a third of whose library is depleted. Using it needs no knowledge of which
    motifs are real, which is the point.
    """
    v = np.asarray(log2fc_series, dtype=float)
    return float((v < log2fc_thr).mean()) if len(v) else 0.0


def benjamini_hochberg(pvalues):
    """BH-adjusted q-values. The scan tests every motif of every pattern, so the number of
    tests is large and sample-specific; correcting for it is not optional."""
    p = np.asarray(pvalues, dtype=float)
    n = len(p)
    if n == 0:
        return p
    order = np.argsort(p)
    ranked = p[order] * n / np.arange(1, n + 1)
    ranked = np.minimum.accumulate(ranked[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.clip(ranked, 0, 1)
    return out

In [42]:
#| export
def motif_pvalues(num_sequences, fraction_depleted, background_rate):
    """P(at least this many of n plasmids depleted | null), per motif.

    Vectorized over a whole score table; the cost is negligible beside the scan itself.
    """
    n = np.asarray(num_sequences, dtype=np.int64)
    k = np.rint(np.asarray(fraction_depleted, dtype=float) * n).astype(np.int64)
    if background_rate <= 0:
        return np.where(k > 0, 0.0, 1.0)
    return binom.sf(k - 1, n, background_rate)

In [43]:
#| hide
_q = benjamini_hochberg([0.01, 0.02, 0.03, 0.04])
assert np.allclose(_q, 0.04)          # p*n/rank is 0.04 for all four here
test_eq(len(benjamini_hochberg([])), 0)
_p = np.array([0.001, 0.5, 0.9])
_q = benjamini_hochberg(_p)
assert (_q >= _p).all() and (_q <= 1).all()      # never smaller than p, never above 1
assert (np.diff(_q[np.argsort(_p)]) >= 0).all()  # monotone in p

test_eq(background_depletion_rate(pd.Series([-2.0, -0.5, 0.1, -3.0]), log2fc_thr=-1), 0.5)
test_eq(background_depletion_rate(pd.Series([], dtype=float)), 0.0)
# strict in log2FC, like `score`: exactly -1 is not depleted
test_eq(background_depletion_rate(pd.Series([-1.0, -1.0]), log2fc_thr=-1), 0.0)

In [44]:
#| hide
# 10 of 10 depleted where the background rate is 0.5 is exactly 0.5**10
assert abs(float(motif_pvalues([10], [1.0], 0.5)[0]) - 0.5 ** 10) < 1e-12
# none depleted is not surprising at all
test_eq(round(float(motif_pvalues([10], [0.0], 0.5)[0]), 10), 1.0)
# the same perfect score is more surprising with more plasmids behind it
_p = motif_pvalues([3, 30], [1.0, 1.0], 0.1)
assert _p[1] < _p[0]
# and a noisier sample (higher background) makes the same observation less surprising
assert motif_pvalues([10], [1.0], 0.5)[0] > motif_pvalues([10], [1.0], 0.05)[0]

### Collapsing near-identical motifs into IUPAC codes

`find_restricted_motifs` often reports the same recognition site as several motifs that differ at one or two positions (e.g. `CACNNNNGTAT` and `CACNNNNGTAC`). `find_iupac_equivalent_motifs` groups same-length motifs that differ at ≤ `max_mismatches` positions (N positions skipped; reverse complements considered, since RM sites are strand-independent) and merges each group into one IUPAC motif (union of bases per position).

In [45]:
#| export
IUPAC_EXPAND = {k: frozenset(v) for k, v in IUPAC_DNA_TO_BASES.items()}
IUPAC_COLLAPSE = {v: k for k, v in IUPAC_EXPAND.items()}
_N_SET = frozenset('ACGT')


def _raw_distance(m1: str, m2: str) -> int:
    """
    Positional mismatch count between two same-length motifs.
    Positions where either motif is N (fully ambiguous) are skipped.
    Returns -1 for different lengths.
    """
    if len(m1) != len(m2):
        return -1
    dist = 0
    for a, b in zip(m1, m2):
        sa = IUPAC_EXPAND.get(a, frozenset())
        sb = IUPAC_EXPAND.get(b, frozenset())
        if sa == _N_SET or sb == _N_SET:
            continue
        if sa != sb:
            dist += 1
    return dist


def motif_distance(m1: str, m2: str, consider_rc: bool = True) -> tuple[int, bool]:
    """
    Minimum mismatch distance between m1 and m2, optionally also comparing m1
    to the reverse complement of m2 (because RM sites are strand-independent).

    Returns (distance, used_rc): distance is -1 if lengths differ; used_rc is
    True if the reverse complement of m2 gave the shorter distance.
    """
    d_fwd = _raw_distance(m1, m2)
    if not consider_rc or d_fwd == -1:
        return d_fwd, False

    d_rc = _raw_distance(m1, _get_reverse_complement_iupac(m2))

    if d_rc < d_fwd:
        return d_rc, True
    return d_fwd, False


def merge_motifs(motifs: list[str]) -> str:
    """
    Merge a list of same-length motifs (already in a consistent orientation)
    into a single IUPAC string by taking the union of nucleotide sets per position.
    """
    out = []
    for i in range(len(motifs[0])):
        union = frozenset()
        for m in motifs:
            union = union | IUPAC_EXPAND.get(m[i], frozenset())
        out.append(IUPAC_COLLAPSE.get(union, 'N'))
    return ''.join(out)

In [46]:
assert merge_motifs(["CACNNNNGTAT", "CACNNNNGTAC"]) == "CACNNNNGTAY"
assert motif_distance("CACNNNNGTAT", "CACNNNNGTAC") == (1, False)
assert motif_distance("GAGACC", "GGTCTC") == (0, True)
assert motif_distance("GAGACC", "GAGAC") == (-1, False)

In [47]:
#| export
def _connected_components(n_nodes: int,
                          edges: list[tuple[int, int]]) -> list[list[int]]:
    """Union-find connected components over integer node indices 0..n_nodes-1."""
    parent = list(range(n_nodes))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for u, v in edges:
        pu, pv = find(u), find(v)
        if pu != pv:
            parent[pu] = pv

    comps = {}
    for i in range(n_nodes):
        comps.setdefault(find(i), []).append(i)
    return list(comps.values())


def _assign_orientations(comp: list[int],
                         adj: dict[int, list[tuple[int, bool]]]) -> dict[int, bool]:
    """
    BFS from the first node of a component to assign a consistent orientation
    (forward / RC) to every other node, propagating along edges.

    adj[u] = [(v, used_rc), ...]  - used_rc=True means rc(m_v) was closer to m_u.
    Orientation logic for edge (u -> v, used_rc=r): orient[v] = orient[u] XOR r,
    i.e. if m_v must be flipped to align to m_u and m_u is already flipped,
    m_v ends up back in forward orientation.
    """
    orientation = {comp[0]: False}
    queue = deque([comp[0]])
    while queue:
        u = queue.popleft()
        for v, used_rc in adj.get(u, []):
            if v not in orientation:
                orientation[v] = orientation[u] ^ used_rc
                queue.append(v)
    # Safety net for nodes not reached from comp[0] (shouldn't happen)
    for node in comp:
        orientation.setdefault(node, False)
    return orientation

In [48]:
#| export
def find_iupac_equivalent_motifs(
    df: pd.DataFrame,
    max_mismatches: int = 2,
    motif_col: str = 'motif',
    sample_col: str = None,
    consider_rc: bool = True,
) -> pd.DataFrame:
    """
    Find motifs that differ by at most *max_mismatches* nucleotides and collapse
    them with IUPAC ambiguity codes (within each sample if *sample_col* is given).

    Rules:
    - Only motifs of the same length are compared.
    - N positions are skipped when counting mismatches.
    - When consider_rc=True (default), dist(A, B) = min(dist(A,B), dist(A,rc(B))).
      If rc(B) was closer, B is flipped before merging so all motifs in a group
      share a consistent strand orientation.
    - Groups are found via connected components (transitivity: A~B and B~C
      -> all three merged even if A and C are > max_mismatches apart).

    Args:
        df: DataFrame with at least *motif_col*, e.g. the flexible motifs returned by
            find_restricted_motifs. Optional num_sequences / avg_log2fc /
            fraction_depleted columns are aggregated per group.
        max_mismatches: 1 or 2 recommended.
        motif_col: column containing motif sequences.
        sample_col: column with the sample / strain identifier; None treats the
            whole df as one sample.
        consider_rc: whether to also compare against the reverse complement.

    Returns:
        DataFrame with one row per merged group (including singletons, n_merged == 1):
        [sample_col,] merged_motif, original_motifs, original_motifs_oriented,
        n_merged, max_pairwise_mismatches, rc_used, and when available
        total_sequences, avg_log2fc_weighted, avg_fraction_depleted.
    """
    records = []
    groups = df.groupby(sample_col, sort=False) if sample_col else [(None, df)]

    for sample, grp in groups:
        grp = grp.reset_index(drop=True)
        motifs = grp[motif_col].str.upper().tolist()

        # Group row indices by motif length
        by_len = {}
        for i, m in enumerate(motifs):
            by_len.setdefault(len(m), []).append(i)

        for row_idxs in by_len.values():
            sub_motifs = [motifs[i] for i in row_idxs]
            n = len(sub_motifs)

            # Build edge list; track RC usage and build adjacency for BFS
            edges = []
            pairwise_dist = {}
            adj = {k: [] for k in range(n)}  # adj[u] = [(v, used_rc), ...], bidirectional

            for i, j in combinations(range(n), 2):
                d, used_rc = motif_distance(sub_motifs[i], sub_motifs[j], consider_rc=consider_rc)
                if d != -1 and 0 < d <= max_mismatches:
                    edges.append((i, j))
                    pairwise_dist[(i, j)] = d
                    adj[i].append((j, used_rc))
                    adj[j].append((i, used_rc))  # symmetric: rc(rc(m)) = m

            for comp in _connected_components(n, edges):
                # Put all motifs of the component on the same strand before merging
                orientations = _assign_orientations(comp, adj)
                oriented_motifs = [_get_reverse_complement_iupac(sub_motifs[k]) if orientations[k] else sub_motifs[k]
                                   for k in comp]
                raw_mots = [sub_motifs[k] for k in comp]

                max_d = 0
                for a, b in combinations(sorted(comp), 2):
                    max_d = max(max_d, pairwise_dist.get((a, b), 0))

                comp_rows = grp.iloc[[row_idxs[k] for k in comp]]

                rec = {sample_col: sample} if sample_col else {}
                rec.update({
                    'merged_motif':             merge_motifs(oriented_motifs),
                    'original_motifs':          ' | '.join(sorted(set(raw_mots))),
                    'original_motifs_oriented': ' | '.join(sorted(set(oriented_motifs))),
                    'n_merged':                 len(set(raw_mots)),
                    'max_pairwise_mismatches':  max_d,
                    'rc_used':                  any(orientations[k] for k in comp),
                })

                if 'num_sequences' in grp.columns:
                    weights = comp_rows['num_sequences'].to_numpy(dtype=float)
                    rec['total_sequences'] = int(weights.sum())
                else:
                    weights = np.ones(len(comp_rows))

                if 'avg_log2fc' in grp.columns:
                    rec['avg_log2fc_weighted'] = float(
                        np.average(comp_rows['avg_log2fc'].to_numpy(dtype=float), weights=weights))

                if 'fraction_depleted' in grp.columns:
                    rec['avg_fraction_depleted'] = float(comp_rows['fraction_depleted'].mean())

                records.append(rec)

    return pd.DataFrame(records)

### Example: strain JJ1886 in the shipped panel

`counts_panel.csv.gz` holds UMI counts for strain JJ1886 (replicate R1) and the `Control` input library, flanked by the `left_panel` / `right_panel` contexts below. Candidate motifs here are JJ1886's three cognate RM motifs (IUPAC codes, e.g. `N` = any base, `R` = A/G; regex classes such as `[AG]` also work).

In [49]:
counts_panel = pd.read_csv(os.path.join(data_path, "counts_panel.csv.gz"), index_col=0)
left_panel, right_panel = "GTCTAGGGCGGCGGTAAAAC", "ACTAGAGCACCAGAAGTCTA"
log2fc_panel = calculate_log2fc(counts_panel, reference_column="Control_R1", count_threshold=20, pseudocount=1)
log2fc_panel.describe()

         Control_R2     JJ1886_R1  ...  EDL933_dRM_R1  EDL933_dRM_R2
count  30108.000000  30108.000000  ...   30108.000000   30108.000000
mean      -0.095335     -0.145983  ...      -0.051041      -0.264967
std        0.662484      0.925720  ...       0.477549       0.946920
min       -4.604587     -7.545017  ...      -8.050974      -7.464945
25%       -0.158043     -0.189782  ...      -0.303039      -0.651040
50%       -0.002551      0.046866  ...      -0.067980      -0.180923
75%        0.151623      0.261892  ...       0.181672       0.259139
max        1.402258      2.155107  ...       2.393285       3.121144

[8 rows x 17 columns]

In [50]:
jj1886_motifs = ["AAAGNNNNGTT", "[AG]TACNNNNGTG", "GGTCTC"]  # JJ1886 cognate RM motifs
presence_jj1886 = get_custom_motif_presence_in_library(counts_panel.index.tolist(), left_panel, right_panel, jj1886_motifs)
presence_jj1886.sum()

AAAGNNNNGTT       1027
[AG]TACNNNNGTG    1094
GGTCTC              65
dtype: int64

Fraction of sequences depleted (log2FC ≤ -1) per motif category, i.e. the score used by the motif search:

In [51]:
dist_jj1886 = get_log2fc_distribution_by_motif(log2fc_panel, left_panel, right_panel, jj1886_motifs, sample_columns=["JJ1886_R1"])
dist_jj1886.dropna(subset="log2fc").groupby("Motif_Category")["log2fc"].agg(n="size", median="median", frac_depleted=lambda x: (x <= -1).mean())

                    n    median  frac_depleted
Motif_Category
AAAGNNNNGTT       882 -3.355284       0.994331
GGTCTC             55 -2.936208       0.945455
Other           28209  0.071611       0.012372
[AG]TACNNNNGTG    962 -3.264534       0.997921

IUPAC codes and regex classes are interchangeable in the candidate list: `RTACNNNNGTG` (R = A/G) matches exactly the same sequences as `[AG]TACNNNNGTG`.

In [52]:
iupac_check = get_custom_motif_presence_in_library(counts_panel.index.tolist(), left_panel, right_panel,
                                                    ["[AG]TACNNNNGTG", "RTACNNNNGTG"])
assert (iupac_check["[AG]TACNNNNGTG"] == iupac_check["RTACNNNNGTG"]).all()
iupac_check.sum()

[AG]TACNNNNGTG    1094
RTACNNNNGTG       1094
dtype: int64

Collapsing the flexible motifs found for JJ1886 by `core.find_restricted_motifs` (log2FC ≤ -1, score ≥ 0.5; see the `core` notebook). `CACNNNNGTAT` and `CACNNNNGTAC` differ at one position and merge into `CACNNNNGTAY`, the reverse complement of JJ1886's `RTACNNNNGTG` Type I motif:

In [53]:
flexible_jj1886 = pd.DataFrame({
    "motif":             ["GAGACC", "CACNNNNGTAT", "CACNNNNGTAC", "AACNNNNCTTT"],
    "fraction_depleted": [0.938776, 1.000000, 1.000000, 0.994233],
    "num_sequences":     [49, 97, 78, 867],
    "avg_log2fc":        [-2.768577, -3.220028, -3.258632, -3.372092],
})
merged_12049 = find_iupac_equivalent_motifs(flexible_jj1886, max_mismatches=2)
merged_12049

  merged_motif  ... avg_fraction_depleted
0       GAGACC  ...              0.938776
1  CACNNNNGTAY  ...              1.000000
2  AACNNNNCTTT  ...              0.994233

[3 rows x 9 columns]

In [54]:
assert "CACNNNNGTAY" in merged_12049["merged_motif"].values
assert _get_reverse_complement_iupac("CACNNNNGTAY") == "RTACNNNNGTG"

In [54]:
#| hide
import nbdev; nbdev.nbdev_export()