In [ ]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Utils

> useful basic functions

In [ ]:
#| default_exp utils

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| export
import pandas as pd
import re
import numpy as np
import os
import itertools
from random import choice

In [ ]:
#| hide
from randseq.example_data import get_example_data_dir

In [ ]:
#| export
# IUPAC DNA codes mapping for sequence generation
IUPAC_DNA_TO_BASES = {
    'A': ['A'], 'C': ['C'], 'G': ['G'], 'T': ['T'], 'R': ['A', 'G'],
    'Y': ['C', 'T'], 'S': ['G', 'C'], 'W': ['A', 'T'], 'K': ['G', 'T'],
    'M': ['A', 'C'], 'B': ['C', 'G', 'T'], 'D': ['A', 'G', 'T'],
    'H': ['A', 'C', 'T'], 'V': ['A', 'C', 'G'], 'N': ['A', 'C', 'G', 'T']
}

# IUPAC DNA codes mapping for regex conversion
IUPAC_DNA_TO_REGEX = {
    'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T', 'R': '[AG]', 'Y': '[CT]',
    'S': '[GC]', 'W': '[AT]', 'K': '[GT]', 'M': '[AC]', 'B': '[CGT]',
    'D': '[AGT]', 'H': '[ACT]', 'V': '[ACG]', 'N': '[ATGC]'
}

# IUPAC DNA codes for reverse complement
IUPAC_COMPLEMENT = {
    'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C',
    'R': 'Y', 'Y': 'R', 'S': 'S', 'W': 'W',
    'K': 'M', 'M': 'K', 'B': 'V', 'V': 'B',
    'D': 'H', 'H': 'D', 'N': 'N'
}

In [ ]:
#| export
def calculate_log2fc(df, reference_column='MFDpir', count_threshold=20, pseudocount=1):
    """
    Filters a DataFrame, normalizes columns by sum, calculates log2 fold change
    relative to a reference column, and drops the reference column.

    Args:
        df (pd.DataFrame): Input DataFrame (rows=features, columns=samples).
        reference_column (str): Name of the reference sample column.
        count_threshold (int): Minimum count in reference column to keep a feature.
        pseudocount (float): Value added to normalized counts before log2FC.

    Returns:
        pd.DataFrame: DataFrame with log2 fold change values. None if reference
                      column is missing. Empty DataFrame if all rows are filtered out.
    """
    
    df = df.replace(np.nan,0)
    if reference_column not in df.columns:
        print(f"Error: Reference column '{reference_column}' not found in DataFrame.")
        return None

    # 1. Filter rows
    df_filtered = df[df[reference_column] > count_threshold].copy()
    if df_filtered.empty:
        print("DataFrame is empty after filtering.")
        return pd.DataFrame()

    # 2. Add pseudocount
    # The pseudocount is added here, before normalization.
    df_with_pseudocount = df_filtered + pseudocount

    # 3. Normalize each column by its sum
    # Normalization is now performed on the data that includes the pseudocount.
    # df.sum(axis=0) calculates sum for each column.
    # .div performs element-wise division, axis=1 aligns column_sums with columns.
    column_sums = df_with_pseudocount.sum(axis=0)
    
    # Handle cases where column_sums might be zero (e.g., if all values were -pseudocount after filtering, though unlikely with positive counts)
    # If a column sum is 0 after adding pseudocount, it implies an issue or very specific data.
    # Division by zero will result in NaN or inf.
    df_processed = df_with_pseudocount.div(column_sums, axis=1)

    # Check if reference column still exists (it should)
    if reference_column not in df_processed.columns:
        # This check is crucial as operations might alter columns if not handled carefully.
        print(f"Error: Reference column '{reference_column}' lost during processing.")
        return None
        
    reference_values = df_processed[reference_column]

    # 4. Calculate log2FC
    # .div performs element-wise division, axis=0 aligns reference_values (a Series) with rows of df_processed.
    log2fc_df = np.log2(df_processed.div(reference_values, axis=0))
    
    # Columns are already named correctly from df_processed.

    # 5. Drop the reference column's own log2FC (which will be ~zeros)
    if reference_column in log2fc_df.columns:
        log2fc_df = log2fc_df.drop(columns=[reference_column])
    else:
        print(f"Warning: Reference column '{reference_column}' not found in log2fc_df for dropping.")
        
    return log2fc_df

In [ ]:
#| hide
data_path=get_example_data_dir()
os.listdir(data_path)

['counts_long.csv',
 '__init__.py',
 'counts_long_clean.csv',
 'countsTable.csv',
 '__pycache__']

In [ ]:
counts_file="countsTable.csv"
file_path=os.path.join(data_path,counts_file)
counts=pd.read_csv(file_path, index_col=0)
counts = counts[[col for col in counts.columns if ("_T0" in col) or ("MFDpir" in col)]]

log2fc_df = calculate_log2fc(counts, reference_column='MFDpir', count_threshold=20, pseudocount=1)
log2fc_df.min(axis=0)

K12_T0       -2.844874
HS_T0        -3.320280
E1114_T0     -4.544421
E1167_T0     -3.645600
H120_T0      -3.572726
TA054_T0     -3.319211
TA447_T0     -3.566876
E101_T0      -8.108167
41-1Ti9_T0   -4.255918
TA280_T0     -4.800802
M114_T0      -4.143357
TA249_T0     -4.973009
ROAR8_T0     -4.621302
JJ1886_T0    -9.188692
CFT073_T0    -3.868714
APECO1_T0    -6.525634
UTI89_T0     -8.571068
S88_T0       -8.601767
MG1655_T0    -4.777041
dtype: float64

In [ ]:
#| export
def revcomp(seq:str):
    '''Computes the reverse complement of a sequence'''
    trns=str.maketrans("ATGCN","TACGN")
    return seq.upper().translate(trns)[::-1]

In [ ]:
assert revcomp("ATGC")=="GCAT"
assert revcomp("ATGCN")=="NGCAT"
assert revcomp("atgNN")=="NNCAT"

In [ ]:
#| export

bases=list("ATGC")
def allseqs(n,seqs=[""]):
    '''Recursive function that generates all possible sequences of length n
    seqs is a list of sequences to which we will add bases
    '''
    seqs=[s+b for s in seqs for b in bases]
    if len(seqs[0])<n:
        return allseqs(n,seqs)
    else:
        return seqs

In [ ]:
",".join(allseqs(2))

'AA,AT,AG,AC,TA,TT,TG,TC,GA,GT,GG,GC,CA,CT,CG,CC'

In [ ]:
#| export
flatten = lambda l: [item for sublist in l for item in sublist]

In [ ]:
assert flatten([[1,2],[3,4],[5,6]])==[1, 2, 3, 4, 5, 6]

In [ ]:
#| export
def get_all_sites(pattern):
    #generates a list of all sites that match the pattern
    return [s[:pattern[0]]+"N"*pattern[1]+s[pattern[0]:] for s in allseqs(pattern[0]+pattern[2])]

In [ ]:
get_all_sites((3,6,4))[:5]

['AAANNNNNNAAAA',
 'AAANNNNNNAAAT',
 'AAANNNNNNAAAG',
 'AAANNNNNNAAAC',
 'AAANNNNNNAATA']

In [ ]:
#| export
def get_lib_seq_context(seqs,left,right):
    """
    Generates a list of sequences by combining a left and right sequence with each sequence in the input list.
    
    Args:
        seqs (list): List of sequences to be combined.
        left (str): Left sequence to prepend.
        right (str): Right sequence to append.

    Returns:
        list: List of combined sequences.
    """
    left=left.upper()
    right=right.upper()
    lib=[left+r+right for r in seqs]
    return lib

In [ ]:
left, right = "GTCCTAGGTATAATACTAGT", "GTTTTAGAGCTAGAAATAGC"
lib=get_lib_seq_context(log2fc_df.index,left,right)
lib[:5]

['GTCCTAGGTATAATACTAGTCGGAGGTACTGGGTACATTTGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTTGGCGATAATGCCGGCTATCGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTTTCCAGTTCACTGGTCTTCGGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTAATTTCAGTGCCGTTCAGATGTTTTAGAGCTAGAAATAGC',
 'GTCCTAGGTATAATACTAGTCTGCGGTAATAATTCCCGCCGTTTTAGAGCTAGAAATAGC']

In [ ]:
#| export

def _generate_sequences_from_iupac(iupac_pattern_str):
    """Generates concrete DNA sequences from an IUPAC pattern."""
    if not iupac_pattern_str:
        return ['']
    possible_bases = [IUPAC_DNA_TO_BASES[c] for c in iupac_pattern_str.upper()]
    return ["".join(combo) for combo in itertools.product(*possible_bases)]

def _convert_iupac_to_regex(iupac_pattern_str):
    """Converts an IUPAC pattern to a regex string."""
    if not iupac_pattern_str:
        return ''
    return "".join([IUPAC_DNA_TO_REGEX[c] for c in iupac_pattern_str.upper()])

def _get_reverse_complement_iupac(iupac_pattern_str):
    """Computes the reverse complement of a DNA sequence in IUPAC format."""
    reversed_pattern = iupac_pattern_str.upper()[::-1]
    return "".join([IUPAC_COMPLEMENT[c] for c in reversed_pattern])

def check_specific_matches_broad_iupac(specific_iupac_pattern, broad_iupac_pattern):
    """
    Checks if all sequences from a specific IUPAC pattern contain a subsequence
    match for the broader IUPAC pattern in either forward or reverse 
    complementary orientation.
    """
    try:
        # No more padding. We check for subsequence matches directly.
        concrete_sequences = _generate_sequences_from_iupac(specific_iupac_pattern)
        
        broad_rc_pattern = _get_reverse_complement_iupac(broad_iupac_pattern)

        # Compile regex for the broad pattern and its reverse complement.
        broad_regex_fwd = re.compile(_convert_iupac_to_regex(broad_iupac_pattern))
        broad_regex_rc = re.compile(_convert_iupac_to_regex(broad_rc_pattern))

        for seq in concrete_sequences:
            # Use re.search() to find a match anywhere in the sequence.
            fwd_match = broad_regex_fwd.search(seq)
            rc_match = broad_regex_rc.search(seq)
            if not (fwd_match or rc_match):
                return False # This specific sequence does not contain the broad pattern.
        
        return True # All specific sequences contained the broad pattern.

    except (KeyError, ValueError, re.error):
        return False

In [ ]:
assert check_specific_matches_broad_iupac("AACNNNTT","AACGNNTT") == False 
assert check_specific_matches_broad_iupac("AACGNNTT","AACNNNTT") == True
assert check_specific_matches_broad_iupac("ATGCC","ATG") == True
assert check_specific_matches_broad_iupac("GGATGCC","ATG") == True
assert check_specific_matches_broad_iupac("GGATG","ATG") == True
assert check_specific_matches_broad_iupac("ATG","GATGC") == False
assert check_specific_matches_broad_iupac("ATG","ATGCC") == False
assert check_specific_matches_broad_iupac("GTACNNNTGTG","CACNNNNGTAC") == True
assert check_specific_matches_broad_iupac("GGCTT","AAGCC") == True

In [ ]:
#| export
def check_specific_matches_broad(specific, broad):
  """
  Checks if a 'specific' string matches a 'broad' string with a wildcard rule.

  This function compares two strings of the same length. The character 'N' in 
  the 'broad' string acts as a wildcard that can match any single character 
  in the 'specific' string at the same position. An 'N' in the 'specific' 
  string does not have any special meaning and is treated as a literal 'N'.

  Args:
    specific: The string that is being checked.
    broad: The string that contains the pattern, where 'N' is a wildcard.

  Returns:
    True if the 'specific' string matches the 'broad' pattern, False otherwise.
  """
  if len(specific) != len(broad):
    return False

  for spec_char, broad_char in zip(specific, broad):
    if spec_char == broad_char or broad_char == 'N':
      continue
    return False
  return True

def find_broad_in_specific(specific, broad):
  """
  Finds if a 'broad' DNA motif exists within a 'specific' DNA sequence, checking
  both forward and reverse complement orientations of the motif.

  If len(specific) < len(broad), it's impossible to find the motif, so it
  returns False. It first checks for the motif in the forward direction. If no match
  is found, it checks for the reverse complement of the motif.

  Args:
    specific: The DNA sequence to be searched within.
    broad: The DNA motif (pattern with 'N' wildcards) to search for.

  Returns:
    True if 'broad' or its reverse complement is found in 'specific', False otherwise.
  """
  if len(specific) < len(broad):
    return False
  
  broad_len = len(broad)
  if broad_len == 0:
      return True

  # 1. Check the forward orientation
  is_forward_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad) 
                         for i in range(len(specific) - broad_len + 1))
  
  if is_forward_match:
    return True

  # 2. If no forward match, check the reverse complement orientation
  broad_rev_comp = revcomp(broad)
  is_reverse_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad_rev_comp) 
                         for i in range(len(specific) - broad_len + 1))

  return is_reverse_match

In [ ]:
assert find_broad_in_specific("AACNNNTT","AACGNNTT") == False 
assert find_broad_in_specific("AACGNNTT","AACNNNTT") == True
assert find_broad_in_specific("ATGCC","ATG") == True
assert find_broad_in_specific("GGATGCC","ATG") == True
assert find_broad_in_specific("GGATG","ATG") == True
assert find_broad_in_specific("ATG","GATGC") == False
assert find_broad_in_specific("ATG","ATGCC") == False
assert find_broad_in_specific("GTACNNNTGTG","CACNNNNGTAC") == True
assert find_broad_in_specific("GGCTT","AAGCC") == True

In [ ]:
#| export
def get_motif_filter_with_context(df, left_context, right_context, motif):
    """
    Returns a boolean filter for the DataFrame to select rows whose index (sequence)
    contains the motif (with ambiguity codes), when flanked by the provided left and right context,
    searching both the forward and reverse complement orientations.

    Args:
        df (pd.DataFrame): DataFrame with DNA sequences as index.
        left_context (str): DNA string to prepend to each sequence.
        right_context (str): DNA string to append to each sequence.
        motif (str): DNA motif (may include IUPAC ambiguous bases).

    Returns:
        pd.Series: Boolean filter for df, True where the motif is present (with context, any orientation).
    """

    # IUPAC ambiguity codes to regex
    iupac_dict = {
        'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T',
        'R': '[AG]', 'Y': '[CT]', 'S': '[GC]', 'W': '[AT]',
        'K': '[GT]', 'M': '[AC]', 'B': '[CGT]', 'D': '[AGT]',
        'H': '[ACT]', 'V': '[ACG]', 'N': '[ACGT]'
    }
    # Build regex pattern from motif
    motif_regex = ''.join(iupac_dict.get(base.upper(), base) for base in motif)
    compiled = re.compile(motif_regex, re.IGNORECASE)

    def contains_motif(seq):
        seq_with_context = f"{left_context}{seq}{right_context}"
        seq_with_context_rc = revcomp(seq_with_context)
        return bool(compiled.search(seq_with_context) or compiled.search(seq_with_context_rc))

    return df.index.to_series().apply(contains_motif)

In [ ]:
motif_filter = get_motif_filter_with_context(counts, left, right, "GAGACC")
filtered_df = counts[motif_filter]
filtered_df

,K12_T0,HS_T0,E1114_T0,E1167_T0,H120_T0,TA054_T0,TA447_T0,E101_T0,41-1Ti9_T0,TA280_T0,M114_T0,TA249_T0,ROAR8_T0,JJ1886_T0,CFT073_T0,APECO1_T0,UTI89_T0,S88_T0,MG1655_T0,MFDpir
GGCGCTAAGGAGACCTTAAA,140,141,17,159,26,137,131,126,181,188,142,188,195,11,128,157,151,137,150,63
CCTGAGACCTCTGCCTCCGG,361,341,38,332,80,381,263,337,382,422,380,376,398,13,414,432,348,456,292,173
CTGAGACCTCTGCCTCCGGA,347,355,30,425,79,360,264,339,355,454,391,358,461,8,385,388,348,401,282,167
GAACCTGAGACCTCTGCCTC,770,852,78,1219,182,925,745,801,911,1069,944,985,1151,13,908,1045,535,1009,676,379
CAGAGACCAGGTGGGAATAG,299,329,23,330,62,349,281,288,388,367,312,232,387,33,344,375,152,336,193,161
CTATACTGCCGCCAGGTCTC,289,330,34,287,61,341,224,318,295,421,387,469,518,156,437,334,219,400,318,164
CCCAACCACCGAGACCCGAC,406,416,44,465,110,364,300,401,467,466,459,541,554,16,457,471,234,392,543,179
CGAGACCGTTTATGCTGAAC,239,263,20,395,74,301,209,225,320,336,288,259,385,12,311,291,187,327,256,113
TGGAATGAGACCACCCAGGC,240,273,20,328,60,300,237,267,280,349,328,315,328,9,259,324,423,283,348,140

In [ ]:
#| export
def _get_filter_for_motif(series, motif, left_context, right_context):
    """
    Returns a boolean filter for a Series to select rows whose index (sequence)
    contains the motif within the full context, searching both forward and
    reverse complement orientations of the motif.
    """
    try:
        fwd_regex = re.compile(_convert_iupac_to_regex(motif), re.IGNORECASE)
        rc_motif = _get_reverse_complement_iupac(motif)
        rc_regex = re.compile(_convert_iupac_to_regex(rc_motif), re.IGNORECASE)

        def check_sequence_with_context(seq):
            full_seq = f"{left_context}{seq}{right_context}"
            if fwd_regex.search(full_seq) or rc_regex.search(full_seq):
                return True
            return False

        return series.index.to_series().apply(check_sequence_with_context)

    except (KeyError, ValueError, re.error):
        return pd.Series(False, index=series.index)

In [ ]:
motif_filter = _get_filter_for_motif(counts, "GAGACC", left, right)
filtered_df = counts[motif_filter]
filtered_df

,K12_T0,HS_T0,E1114_T0,E1167_T0,H120_T0,TA054_T0,TA447_T0,E101_T0,41-1Ti9_T0,TA280_T0,M114_T0,TA249_T0,ROAR8_T0,JJ1886_T0,CFT073_T0,APECO1_T0,UTI89_T0,S88_T0,MG1655_T0,MFDpir
GGCGCTAAGGAGACCTTAAA,140,141,17,159,26,137,131,126,181,188,142,188,195,11,128,157,151,137,150,63
CCTGAGACCTCTGCCTCCGG,361,341,38,332,80,381,263,337,382,422,380,376,398,13,414,432,348,456,292,173
CTGAGACCTCTGCCTCCGGA,347,355,30,425,79,360,264,339,355,454,391,358,461,8,385,388,348,401,282,167
GAACCTGAGACCTCTGCCTC,770,852,78,1219,182,925,745,801,911,1069,944,985,1151,13,908,1045,535,1009,676,379
CAGAGACCAGGTGGGAATAG,299,329,23,330,62,349,281,288,388,367,312,232,387,33,344,375,152,336,193,161
CTATACTGCCGCCAGGTCTC,289,330,34,287,61,341,224,318,295,421,387,469,518,156,437,334,219,400,318,164
CCCAACCACCGAGACCCGAC,406,416,44,465,110,364,300,401,467,466,459,541,554,16,457,471,234,392,543,179
CGAGACCGTTTATGCTGAAC,239,263,20,395,74,301,209,225,320,336,288,259,385,12,311,291,187,327,256,113
TGGAATGAGACCACCCAGGC,240,273,20,328,60,300,237,267,280,349,328,315,328,9,259,324,423,283,348,140

In [ ]:
#| export
def generate_tuple_combinations(a1, a2, b1, b2, c1, c2):
  """
  Generates a list of tuples with all possible number combinations within given ranges.

  Args:
    a1: The starting number for the first position.
    a2: The ending number for the first position (inclusive).
    b1: The starting number for the second position.
    b2: The ending number for the second position (inclusive).
    c1: The starting number for the third position.
    c2: The ending number for the third position (inclusive).

  Returns:
    A list of tuples, where each tuple contains three numbers representing
    a unique combination from the specified ranges.
  """
  range_a = range(a1, a2 + 1)
  range_b = range(b1, b2 + 1)
  range_c = range(c1, c2 + 1)
  
  # Using itertools.product is more efficient for generating Cartesian products
  combinations = list(itertools.product(range_a, range_b, range_c))
  
  return combinations

In [ ]:
generate_tuple_combinations(5,7,0,0,0,0)

[(5, 0, 0), (6, 0, 0), (7, 0, 0)]

In [ ]:
patterns = generate_tuple_combinations(2,4,1,8,2,4)
patterns[:5], patterns[-5:]

([(2, 1, 2), (2, 1, 3), (2, 1, 4), (2, 2, 2), (2, 2, 3)],
 [(4, 7, 3), (4, 7, 4), (4, 8, 2), (4, 8, 3), (4, 8, 4)])

In [ ]:
#| export
def filter_symmetric_tuples(list_of_tuples):
    """
    Filters a list of 3-integer tuples, removing specific symmetric pairs.

    This function removes a tuple if another tuple exists in the list that is
    its mirror image by swapping the first and third elements. For example, 
    (1, 2, 3) is considered a symmetric pair with (3, 2, 1). When such a pair 
    is found, only the first one encountered in the original list is kept.

    Args:
        list_of_tuples: A list of tuples, where each tuple contains three integers.

    Returns:
        A new list of tuples with the symmetric pairs removed.
    """
    # This set will store the canonical representation of tuples we have 
    # already encountered. The canonical form is the smaller of a tuple and
    # its symmetric version, ensuring we can identify pairs efficiently.
    seen_canonical_forms = set()
    
    # This list will hold the final, filtered tuples.
    filtered_list = []

    # Iterate through each tuple in the input list.
    for tup in list_of_tuples:
        # Create the specific symmetric counterpart by swapping the first and last elements.
        symmetric_tup = (tup[2], tup[1], tup[0])

        # Determine the canonical form by picking the lexicographically smaller
        # of the original tuple and its symmetric version. This makes the
        # representation consistent for any pair.
        canonical_form = min(tup, symmetric_tup)

        # If the canonical form is already in our 'seen' set, it means we have
        # already processed this tuple or its symmetric pair, so we skip it.
        if canonical_form in seen_canonical_forms:
            continue

        # If the canonical form has not been seen, we add the original tuple
        # to our result list.
        filtered_list.append(tup)
        
        # Add the canonical form to the 'seen' set. This ensures that the
        # other member of the symmetric pair will be skipped if encountered later.
        seen_canonical_forms.add(canonical_form)
        
    return filtered_list

In [ ]:
patterns = generate_tuple_combinations(2,4,1,8,2,4)
print(len(patterns))
print(len(filter_symmetric_tuples(patterns)))

72
48

In [ ]:
#| export
def get_patterns():
    patterns = generate_tuple_combinations(5,7,0,0,0,0) + generate_tuple_combinations(2,4,1,8,3,4)
    patterns = filter_symmetric_tuples(patterns)
    patterns = sorted(patterns, key=lambda x: (x[0]+x[2], x[1])) 
    return patterns

In [ ]:
patterns = get_patterns()
sorted(patterns, key=lambda x: (x[0]+x[2], x[1]))

[(5, 0, 0),
 (2, 1, 3),
 (2, 2, 3),
 (2, 3, 3),
 (2, 4, 3),
 (2, 5, 3),
 (2, 6, 3),
 (2, 7, 3),
 (2, 8, 3),
 (6, 0, 0),
 (2, 1, 4),
 (3, 1, 3),
 (2, 2, 4),
 (3, 2, 3),
 (2, 3, 4),
 (3, 3, 3),
 (2, 4, 4),
 (3, 4, 3),
 (2, 5, 4),
 (3, 5, 3),
 (2, 6, 4),
 (3, 6, 3),
 (2, 7, 4),
 (3, 7, 3),
 (2, 8, 4),
 (3, 8, 3),
 (7, 0, 0),
 (3, 1, 4),
 (3, 2, 4),
 (3, 3, 4),
 (3, 4, 4),
 (3, 5, 4),
 (3, 6, 4),
 (3, 7, 4),
 (3, 8, 4),
 (4, 1, 4),
 (4, 2, 4),
 (4, 3, 4),
 (4, 4, 4),
 (4, 5, 4),
 (4, 6, 4),
 (4, 7, 4),
 (4, 8, 4)]

In [ ]:
len(get_patterns())

43

In [ ]:
get_patterns()[5::5]

[(2, 5, 3),
 (2, 1, 4),
 (3, 3, 3),
 (2, 6, 4),
 (3, 8, 3),
 (3, 4, 4),
 (4, 1, 4),
 (4, 6, 4)]

In [ ]:
#| export
def create_motif_presence_matrix(
    sequences,
    motif_sets
) -> pd.DataFrame:
    """
    Efficiently creates a presence/absence matrix from lists of sequences and their motifs.

    This function is optimized for performance and memory, making it suitable
    for very large datasets.

    Args:
        sequences: A list of sequence strings. An empty list is handled.
        motif_sets: A list of sets, where each set contains the motifs
                    found in the corresponding sequence.

    Returns:
        A pandas DataFrame with sequences as the index, unique motifs as
        columns, and boolean values indicating presence (True) or
        absence (False) of a motif in a sequence.

    Raises:
        ValueError: If the 'sequences' and 'motif_sets' lists are not the
                    same length.
    """
    # --- 1. Input Validation ---
    if len(sequences) != len(motif_sets):
        raise ValueError(
            "The 'sequences' and 'motif_sets' lists must be of the same length."
        )

    if not sequences:
        return pd.DataFrame() # Return an empty DataFrame if input is empty

    # --- 2. Flatten Data into Long Format ---
    # Create a generator of (sequence, motif) pairs for memory efficiency.
    # This processes only the motifs that are actually present.
    long_format_generator = (
        (sequence, motif)
        for sequence, motifs in zip(sequences, motif_sets)
        for motif in motifs
    )

    # Create an intermediate DataFrame from the generator
    df_long = pd.DataFrame(long_format_generator, columns=['sequence', 'motif'])

    # --- 3. Handle Edge Case: No Motifs Found ---
    # If df_long is empty, it means no motifs exist in any set.
    # We return a DataFrame of all False values.
    if df_long.empty:
        # Create an empty index with the correct name to match the non-empty case
        idx = pd.Index(sequences, name='sequence')
        return pd.DataFrame(False, index=idx, columns=[])

    # --- 4. Pivot to Create the Matrix ---
    df_long['present'] = True
    presence_matrix = df_long.pivot_table(
        index='sequence',
        columns='motif',
        values='present',
        fill_value=False
    )

    # --- 5. Ensure All Sequences are Included ---
    # Reindex ensures that sequences with no motifs are still included as rows
    # of all False values. This is crucial for correctness.
    final_df = presence_matrix.reindex(sequences, fill_value=False)

    return final_df

In [ ]:
# --- Example Usage ---

# Input data
my_sequences = ['AGCTAGCT', 'GATTACA', 'TGCATGC', 'AGCT', 'TTTTT']
my_motifs = [
    {'AGC', 'GCT'},      # Motifs for AGCTAGCT
    {'GAT', 'TACA', 'CA'}, # Motifs for GATTACA
    {'TGC', 'ATG', 'CA'},  # Motifs for TGCATGC
    {'AGCT', 'AGC'},       # Motifs for AGCT
    set()                  # No motifs for TTTTT
]

# Generate the DataFrame by calling the function
motif_df = create_motif_presence_matrix(my_sequences, my_motifs)

print(motif_df)

motif       AGC   AGCT    ATG     CA    GAT    GCT   TACA    TGC
sequence
AGCTAGCT    1.0  False  False  False  False    1.0  False  False
GATTACA   False  False  False    1.0    1.0  False    1.0  False
TGCATGC   False  False    1.0    1.0  False  False  False    1.0
AGCT        1.0    1.0  False  False  False  False  False  False
TTTTT     False  False  False  False  False  False  False  False

In [ ]:
def generate_random_sequence(length: int) -> str:
    """
    Generates a random DNA sequence of a given length.
    
    Args:
        length: The length of the sequence to generate.
        
    Returns:
        A string representing a random DNA sequence.
    """
    return ''.join(choice('ACGT') for _ in range(length))

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()